location_ids = {
    "Lake Hylia - Riverside Cave": 0x01,
    "Lake Hylia - Riverbank Rock Circle": 0x02,
    "Lake Hylia - Riverbank House Backyard": 0x03,
    "Lake Hylia - Riverbank Floating Item": 0x04,
    "Lake Hylia - Riverbank Underwater Item": 0x05,
    "Lake Hylia - Riverbank Cave Chest": 0x06,
    "Lake Hylia - Waterfall Lower Cave Floating Item": 0x07,
    "Lake Hylia - Waterfall Lower Cave Chest": 0x08,
    "Lake Hylia - Waterfall Upper Cave Floating Item": 0x09,
    "Lake Hylia - Waterfall Upper Cave Pedestal": 0x0A,
    "Lake Hylia - Waterfall Waterfall Item": 0x0B,
    "Lake Hylia - Three Caves Left Chest": 0x0C,
    "Lake Hylia - Three Caves Right Chest": 0x0D,
    "Lake Hylia - Three Caves Under Waterfall": 0x0E,
    "Lake Hylia - Waterfall Base Underwater": 0x0F,
    "Lake Hylia - Pit Cave Floating Item": 0x10,
    "Lake Hylia - N-Shaped Cave Left Chest": 0x11,
    "Lake Hylia - N-Shaped Cave Right Chest": 0x12,
    "Lake Hylia - Waterfall Base Cave Chest": 0x13,
    "Lake Hylia - Waterfall Base Cave Pedestal": 0x14,
    "Lake Hylia - Bridge Left Chest": 0x15,
    "Lake Hylia - Bridge Right Chest": 0x16
}
