global_trophy_table =["Mario (Trophy)", "Mario (Smash Trophy)", "Mario (Smash Alt Trophy)", "Donkey Kong (Trophy)", "Donkey Kong (Smash Trophy)",
                        "Donkey Kong (Smash Alt Trophy)", "Link (Trophy)", "Link (Smash Trophy)", "Link (Smash Alt Trophy)", "Samus Aran (Trophy)",
                        "Samus Aran (Smash Trophy)", "Samus Aran (Smash Alt Trophy)", "Yoshi (Trophy)", "Yoshi (Smash Trophy)", "Yoshi (Smash Alt Trophy)",
                        "Kirby (Trophy)", "Kirby (Smash Trophy)", "Kirby (Smash Alt Trophy)", "Fox McCloud (Trophy)", "Fox McCloud (Smash Trophy)", "Fox McCloud (Smash Alt Trophy)",
                        "Pikachu (Trophy)", "Pikachu (Smash Trophy)", "Pikachu (Smash Alt Trophy)", "Ness (Trophy)", "Ness (Smash Trophy)", "Ness (Smash Alt Trophy)",
                        "Captain Falcon (Trophy)", "Captain Falcon (Smash Trophy)", "Captain Falcon (Smash Alt Trophy)","Bowser (Trophy)", "Bowser (Smash Trophy)", "Bowser (Smash Alt Trophy)",
                        "Peach (Trophy)", "Peach (Smash Trophy)", "Peach (Smash Alt Trophy)", "Ice Climbers (Trophy)", "Ice Climbers (Smash Trophy)", "Ice Climbers (Smash Alt Trophy)",
                        "Zelda (Trophy)", "Zelda (Smash Trophy)", "Zelda (Smash Alt Trophy)", "Sheik (Trophy)", "Sheik (Smash Trophy)", "Sheik (Smash Alt Trophy)",
                        "Luigi (Trophy)", "Luigi (Smash Trophy)", "Luigi (Smash Alt Trophy)", "Jigglypuff (Trophy)", "Jigglypuff (Smash Trophy)", "Jigglypuff (Smash Alt Trophy)",
                        "Mewtwo (Trophy)", "Mewtwo (Smash Trophy)", "Mewtwo (Smash Alt Trophy)", "Marth (Trophy)", "Marth (Smash Trophy)", "Marth (Smash Alt Trophy)",
                        "Mr. Game & Watch (Trophy)", "Mr. Game & Watch (Smash Trophy)", "Mr. Game & Watch (Smash Alt Trophy)", "Dr. Mario (Trophy)", "Dr. Mario (Smash Trophy)", "Dr. Mario (Smash Alt Trophy)",
                        "Ganondorf (Trophy)", "Ganondorf (Smash Trophy)", "Ganondorf (Smash Alt Trophy)", "Falco Lombardi (Trophy)", "Falco Lombardi (Smash Trophy)", "Falco Lombardi (Smash Alt Trophy)",
                        "Young Link (Trophy)", "Young Link (Smash Trophy)", "Young Link (Smash Alt Trophy)", "Pichu (Trophy)", "Pichu (Smash Trophy)", "Pichu (Smash Alt Trophy)",
                        "Roy (Trophy)", "Roy (Smash Trophy)", "Roy (Smash Alt Trophy)",
                        "Male Wire Frame (Trophy)", "Female Wire Frame (Trophy)", "Fighting Wire Frame (Trophy)", "Giga Bowser (Trophy)", "Master Hand (Trophy)", "Crazy Hand (Trophy)",
                        "Food (Trophy)", "Maxim Tomato (Trophy)", "Heart Container (Trophy)", "Warp Star (Trophy)", "Ray Gun (Trophy)", "Super Scope (Trophy)",
                        "Fire Flower (Trophy)", "Lip's Stick (Trophy)", "Star Rod (Trophy)", "Beam Sword (Trophy)", "Home-Run Bat (Trophy)", "Fan (Trophy)",
                        "Hammer (Trophy)", "Green Shell (Trophy)", "Red Shell (Trophy)", "Flipper (Trophy)", "Freezie (Trophy)", "Mr. Saturn (Trophy)",
                        "Bob-omb (Trophy)", "Motion-Sensor Bomb (Trophy)", "Super Mushroom (Trophy)", "Poison Mushroom (Trophy)", "Starman (Trophy)", "Parasol (Trophy)",
                        "Screw Attack (Trophy)", "Metal Box (Trophy)", "Bunny Hood (Trophy)", "Cloaking Device (Trophy)", "Barrel Cannon (Trophy)", "Party Ball (Trophy)",
                        "Crate (Trophy)", "Barrel (Trophy)", "Capsule (Trophy)", "Egg (Trophy)", "Smash Coins (Trophy)", "Poké Ball (Trophy)",
                        "Venusaur (Trophy)", "Charizard (Trophy)", "Squirtle (Trophy)", "Blastoise (Trophy)", "Clefairy (Trophy)", "Electrode (Trophy)",
                        "Weezing (Trophy)", "Chansey (Trophy)", "Goldeen (Trophy)", "Staryu (Trophy)", "Snorlax (Trophy)", "Articuno (Trophy)",
                        "Zapdos (Trophy)", "Moltres (Trophy)", "Mew (Trophy)", "Chikorita (Trophy)", "Cyndaquil (Trophy)", "Togepi (Trophy)",
                        "Bellossom (Trophy)", "Marill (Trophy)", "Sudowoodo (Trophy)", "Unown (Trophy)", "Wobbuffet (Trophy)", "Scizor (Trophy)",
                        "Porygon2 (Trophy)", "Raikou (Trophy)", "Entei (Trophy)", "Suicune (Trophy)", "Lugia (Trophy)", "Ho-oh (Trophy)",
                        "Celebi (Trophy)", "Toad (Trophy)", "Coin (Trophy)", "Vegetable (Trophy)", "Megavitamins (Trophy)", "Lon Lon Milk (Trophy)",
                        "Kirby Hat 1 (Trophy)", "Kirby Hat 2 (Trophy)", "Kirby Hat 3 (Trophy)", "Kirby Hat 4 (Trophy)", "Kirby Hat 5 (Trophy)", "Princess Peach's Castle (Trophy)",
                        "Banzai Bill (Trophy)", "Lakitu (Trophy)", "Pidgit (Trophy)", "Birdo (Trophy)", "Klap Trap (Trophy)", "Shy Guys (Trophy)",
                        "Pak E. Derm (Trophy)", "Tingle (Trophy)", "Moon (Trophy)", "Turtle (Trophy)", "Four Giants (Trophy)", "Master Sword (Trophy)",
                        "Falcon Flyer (Trophy)", "F-Zero Racers (Trophy)", "Mute City (Trophy)", "Arwing (Trophy)", "Great Fox (Trophy)", "Peppy Hare (Trophy)",
                        "Slippy Toad (Trophy)", "Kraid (Trophy)", "Chozo Statue (Trophy)", "Whispy Woods (Trophy)", "Fountain of Dreams (Trophy)", "UFO (Trophy)",
                        "Pokémon Stadium (Trophy)", "Game & Watch (Trophy)", "Target (Trophy)", "Sandbag (Trophy)", "Battlefield (Trophy)", "Final Destination (Trophy)",
                        "Goomba (Trophy)", "Koopa Troopa (Trophy)", "Koopa Paratroopa (Trophy)", "ReDead (Trophy)", "Octorok (Trophy)", "Like Like (Trophy)",
                        "Topi (Trophy)", "Polar Bear (Trophy)", "Raccoon Mario (Trophy)", "Mario & Yoshi (Trophy)", "Metal Mario (Trophy)", "Paper Mario (Trophy)",
                        "Wario (Trophy)", "Plum (Trophy)", "Daisy (Trophy)", "Waluigi (Trophy)", "Thwomp (Trophy)", "Boo (Trophy)",
                        "Koopa Clown Car (Trophy)", "Viruses (Trophy)", "Bucket (Trophy)", "Racing Kart (Trophy)", "Baby Mario (Trophy)", "Baby Bowser (Trophy)",
                        "Raphael Raven (Trophy)", "Dixie Kong (Trophy)", "King K. Rool (Trophy)", "Goron (Trophy)", "Marin (Trophy)", "Majora's Mask (Trophy)",
                        "Ocarina of Time (Trophy)", "Samurai Goroh (Trophy)", "Dr. Stewart (Trophy)", "Jody Summer (Trophy)", "Landmaster Tank (Trophy)", "Wolfen (Trophy)",
                        "Andross (Trophy)", "Andross (64) (Trophy)", "Samus Unmasked (Trophy)", "Samus's Starship (Trophy)", "Metroid (Trophy)", "Ridley (Trophy)",
                        "Fire Kirby (Trophy)", "Fighter Kirby (Trophy)", "Ball Kirby (Trophy)", "Waddle Dee (Trophy)", "King Dedede (Trophy)", "Rick (Trophy)",
                        "Gooey (Trophy)", "Meta-Knight (Trophy)", "Paula (Trophy)", "Jeff (Trophy)", "Poo (Trophy)", "Starman (EarthBound) (Trophy)",
                        "Bulbasaur (Trophy)", "Poliwhirl (Trophy)", "Ditto (Trophy)", "Eevee (Trophy)", "Totodile (Trophy)", "Crobat (Trophy)",
                        "Cleffa (Trophy)", "Igglybuff (Trophy)", "Steelix (Trophy)", "Heracross (Trophy)", "Meowth (Trophy)", "Professor Oak (Trophy)",
                        "Misty (Trophy)", "ZERO-ONE (Trophy)", "Maruo Maruhige (Trophy)", "Ryota Hayami (Trophy)", "Kensuke Kimachi (Trophy)", "Love Giant (Trophy)",
                        "Hate Giant (Trophy)", "Ray Mk II (Trophy)", "Bayonette (Trophy)", "Annie (Trophy)", "Tom Nook (Trophy)", "Totakeke (Trophy)",
                        "Mr. Resetti (Trophy)", "Heririn (Trophy)", "Alpha (Trophy)", "Vacuum Luigi (Trophy)", "Pikmin (Trophy)", "Captain Olimar (Trophy)",
                        "Excite Bike (Trophy)", "Tamagon (Trophy)", "Donkey Kong Junior (Trophy)", "Ducks (Trophy)", "Bubbles (Trophy)", "Eggplant Man (Trophy)",
                        "Mach Rider (Trophy)", "Balloon Fighter (Trophy)", "Stanley (Trophy)", "Pit (Trophy)", "Dr. Wright (Trophy)", "Donbe & Hikari (Trophy)",
                        "Ayumi Tachibana (Trophy)", "Monster (Trophy)", "Sheriff (Trophy)", "Diskun (Trophy)", "GCN (Trophy)"
                        ]

bonus_checks = {
    0x01: [0, 0x1],
    0x02: [0, 0x2],
    0x03: [0, 0x4],
    0x04: [0, 0x8],
    0x05: [0, 0x10],
    0x06: [0, 0x20],
    0x07: [0, 0x40],
    0x08: [0, 0x80],

    0x09: [1, 0x1],
    0x0A: [1, 0x2],
    0x0B: [1, 0x4],
    0x0C: [1, 0x8],
    0x0D: [1, 0x10],
    0x0E: [1, 0x20],
    0x0F: [1, 0x40],
    0x10: [1, 0x80],

    0x11: [2, 0x1],
    0x13: [2, 0x4],
    0x14: [2, 0x8],
    0x15: [2, 0x10],
    0x16: [2, 0x20],
    0x17: [2, 0x40],
    0x18: [2, 0x80],

    0x19: [3, 0x1],
    0x1A: [3, 0x2],
    0x1B: [3, 0x4],
    0x1C: [3, 0x8],
    0x1D: [3, 0x10],
    0x1E: [3, 0x20],
    0x1F: [3, 0x40],
    0x20: [3, 0x80],

    0x21: [4, 0x1],
    0x22: [4, 0x2],
    0x23: [4, 0x4],
    0x24: [4, 0x8],
    0x25: [4, 0x10],
    0x26: [4, 0x20],
    0x27: [4, 0x40],
    0x28: [4, 0x80],

    0x29: [5, 0x1],
    0x2A: [5, 0x2],
    0x2B: [5, 0x4],
    0x2C: [5, 0x8],
    0x2D: [5, 0x10],
    0x2E: [5, 0x20],
    0x2F: [5, 0x40],
    0x30: [5, 0x80],

    0x31: [6, 0x1],
    0x32: [6, 0x4],
    0x33: [6, 0x8],
    0x34: [6, 0x10],
    0x35: [6, 0x20],
    0x36: [6, 0x40],
    0x37: [6, 0x80],

    0x38: [7, 0x1],
    0x39: [7, 0x2],
    0x3A: [7, 0x4],
    0x3B: [7, 0x8],
    0x3C: [7, 0x10],
    0x3D: [7, 0x20],
    0x3E: [7, 0x40],
    0x3F: [7, 0x80],

    0x40: [8, 0x1],
    0x41: [8, 0x1],
    0x42: [8, 0x4],
    0x43: [8, 0x8],
    0x44: [8, 0x10],
    0x45: [8, 0x20],
    0x46: [8, 0x40],
    0x47: [8, 0x80],

    0x48: [9, 0x1],
    0x49: [9, 0x2],
    0x4A: [9, 0x4],
    0x4B: [9, 0x8],
    0x4C: [9, 0x10],
    0x4D: [9, 0x20],
    0x4E: [9, 0x40],
    0x4F: [9, 0x80],

    0x50: [10, 0x1],
    0x51: [10, 0x1],
    0x52: [10, 0x4],
    0x53: [10, 0x8],
    0x54: [10, 0x10],
    0x55: [10, 0x20],
    0x56: [10, 0x40],
    0x57: [10, 0x80],

    0x58: [11, 0x1],
    0x59: [11, 0x2],
    0x5A: [11, 0x10],
    0x5B: [11, 0x20],
    0x5C: [11, 0x40],
    0x5D: [11, 0x80],

    0x5E: [12, 0x1],
    0x5F: [12, 0x1],
    0x60: [12, 0x4],
    0x61: [12, 0x8],
    0x62: [12, 0x10],
    0x63: [12, 0x20],
    0x64: [12, 0x40],
    0x65: [12, 0x80],

    0x66: [13, 0x1],
    0x67: [13, 0x2],
    0x68: [13, 0x4],
    0x69: [13, 0x8],
    0x6A: [13, 0x10],
    0x6B: [13, 0x20],
    0x6C: [13, 0x40],
    0x6D: [13, 0x80],

    0x6E: [14, 0x1],
    0x6F: [14, 0x1],
    0x70: [14, 0x4],
    0x71: [14, 0x8],
    0x72: [14, 0x10],
    0x73: [14, 0x20],
    0x74: [14, 0x40],
    0x75: [14, 0x80],

    0x76: [15, 0x1],
    0x77: [15, 0x2],
    0x78: [15, 0x4],
    0x79: [15, 0x8],
    0x7A: [15, 0x10],
    0x7B: [15, 0x20],
    0x7C: [15, 0x40],
    0x7D: [15, 0x80],

    0x7E: [16, 0x1],
    0x7F: [16, 0x1],
    0x80: [16, 0x4],
    0x81: [16, 0x8],
    0x82: [16, 0x10],
    0x83: [16, 0x20],
    0x84: [16, 0x40],
    0x85: [16, 0x80],

    0x86: [17, 0x1],
    0x87: [17, 0x2],
    0x12: [17, 0x4],
    0x88: [17, 0x8],
    0x89: [17, 0x10],
    0x8A: [17, 0x20],
    0x8B: [17, 0x40],
    0x8C: [17, 0x80],

    0x8D: [18, 0x1],
    0x8E: [18, 0x1],
    0x8F: [18, 0x4],
    0x90: [18, 0x8],
    0x91: [18, 0x10],
    0x92: [18, 0x20],
    0x93: [18, 0x40],
    0x94: [18, 0x80],

    0x95: [19, 0x1],
    0x96: [19, 0x2],
    0x97: [19, 0x4],
    0x98: [19, 0x8],
    0x99: [19, 0x10],
    0x9A: [19, 0x20],
    0x9B: [19, 0x40],
    0x9C: [19, 0x80],

    0x9D: [20, 0x1],
    0x9E: [20, 0x4],
    0x9F: [20, 0x8],
    0xA0: [20, 0x10],
    0xA1: [20, 0x20],
    0xA2: [20, 0x40],
    0xA3: [20, 0x80],

    0xA4: [21, 0x1],
    0xA5: [21, 0x2],
    0xA6: [21, 0x4],
    0xA7: [21, 0x8],
    0xA8: [21, 0x10],
    0xA9: [21, 0x20],
    0xAA: [21, 0x40],
    0xAB: [21, 0x80],

    0xAC: [22, 0x1],
    0xAD: [22, 0x2],
    0xAE: [22, 0x4],
    0xAF: [22, 0x8],
    0xB0: [22, 0x10],
    0xB1: [22, 0x20],
    0xB2: [22, 0x40],
    0xB3: [22, 0x80],

    0xB4: [23, 0x1],
    0xB5: [23, 0x2],
    0xB6: [23, 0x4],
    0xB7: [23, 0x8],
    0xB8: [23, 0x10],
    0xB9: [23, 0x20],
    0xBA: [23, 0x40],
    0xBB: [23, 0x80],

    0xBC: [24, 0x1],
    0xBD: [24, 0x2],
    0xBE: [24, 0x4],
    0xBF: [24, 0x8],
    0xC0: [24, 0x10],
    0xC1: [24, 0x20],
    0xC2: [24, 0x40],
    0xC3: [24, 0x80],

    0xC4: [25, 0x1],
    0xC5: [25, 0x2],
    0xC6: [25, 0x4],
    0xC7: [25, 0x8],
    0xC8: [25, 0x10],
    0xC9: [25, 0x20],
    0xCA: [25, 0x40],
    0xCB: [25, 0x80],

    0xCC: [26, 0x1],
    0xCD: [26, 0x8],
    0xCE: [26, 0x10],
    0xCF: [26, 0x20],
    0xD0: [26, 0x40],
    0xD1: [26, 0x80],

    0xD2: [27, 0x1],
    0xD3: [27, 0x2],
    0xD4: [27, 0x4],
    0xD5: [27, 0x8],
    0xD6: [27, 0x10],
    0xD7: [27, 0x20],
    0xD8: [27, 0x40],
    0xD9: [27, 0x80],

    0xDA: [28, 0x2],
    0xDB: [28, 0x4],
    0xDC: [28, 0x8],
    0xDD: [28, 0x10],
    0xDE: [28, 0x20],
    0xDF: [28, 0x40],
    0xE0: [28, 0x80],
    0xE1: [28, 0x01],

    0xE2: [29, 0x40],
    0xE3: [29, 0x80],
    0xE4: [29, 0x01],
    0xE5: [29, 0x02],
    0xE6: [29, 0x04],
    0xE7: [29, 0x08],
    0xE8: [29, 0x10],
    0xE9: [29, 0x20],

    0xEA: [30, 0x1],
    0xEB: [30, 0x2],
    0xEC: [30, 0x4],
    0xED: [30, 0x8],
    0xEE: [30, 0x10],
    0xEF: [30, 0x20],
    0xF0: [30, 0x40],
    0xF1: [30, 0x80],

    0xF2: [31, 0x1],
    0xF3: [31, 0x2],
    0xF4: [31, 0x4],
    0xF5: [31, 0x40],
    0xF6: [31, 0x80]
}

trophy_checks = [
        "Mario - Adventure Trophy Unlock",
        "Mario - Classic Trophy Unlock",
        "Mario - All-Star Trophy Unlock",
        "Donkey Kong - Adventure Trophy Unlock",
        "Donkey Kong - Classic Trophy Unlock",
        "Donkey Kong - All-Star Trophy Unlock",
        "Link - Adventure Trophy Unlock",
        "Link - Classic Trophy Unlock",
        "Link - All-Star Trophy Unlock",
        "Samus - Adventure Trophy Unlock",
        "Samus - Classic Trophy Unlock",
        "Samus - All-Star Trophy Unlock",
        "Yoshi - Adventure Trophy Unlock",
        "Yoshi - Classic Trophy Unlock",
        "Yoshi - All-Star Trophy Unlock",
        "Kirby - Adventure Trophy Unlock",
        "Kirby - Classic Trophy Unlock",
        "Kirby - All-Star Trophy Unlock",
        "Fox - Adventure Trophy Unlock",
        "Fox - Classic Trophy Unlock",
        "Fox - All-Star Trophy Unlock",
        "Pikachu - Adventure Trophy Unlock",
        "Pikachu - Classic Trophy Unlock",
        "Pikachu - All-Star Trophy Unlock",
        "Ness - Adventure Trophy Unlock",
        "Ness - Classic Trophy Unlock",
        "Ness - All-Star Trophy Unlock",
        "Captain Falcon - Adventure Trophy Unlock",
        "Captain Falcon - Classic Trophy Unlock",
        "Captain Falcon - All-Star Trophy Unlock",
        "Bowser - Adventure Trophy Unlock",
        "Bowser - Classic Trophy Unlock",
        "Bowser - All-Star Trophy Unlock",
        "Peach - Adventure Trophy Unlock",
        "Peach - Classic Trophy Unlock",
        "Peach - All-Star Trophy Unlock",
        "Ice Climbers - Adventure Trophy Unlock",
        "Ice Climbers - Classic Trophy Unlock",
        "Ice Climbers - All-Star Trophy Unlock",
        "Zelda - Adventure Trophy Unlock",
        "Zelda - Classic Trophy Unlock",
        "Zelda - All-Star Trophy Unlock",
        "Sheik - Adventure Trophy Unlock",
        "Sheik - Classic Trophy Unlock",
        "Sheik - All-Star Trophy Unlock",
        "Luigi - Adventure Trophy Unlock",
        "Luigi - Classic Trophy Unlock",
        "Luigi - All-Star Trophy Unlock",
        "Jigglypuff - Adventure Trophy Unlock",
        "Jigglypuff - Classic Trophy Unlock",
        "Jigglypuff - All-Star Trophy Unlock",
        "Mewtwo - Adventure Trophy Unlock",
        "Mewtwo - Classic Trophy Unlock",
        "Mewtwo - All-Star Trophy Unlock",
        "Marth - Adventure Trophy Unlock",
        "Marth - Classic Trophy Unlock",
        "Marth - All-Star Trophy Unlock",
        "Mr. Game & Watch - Adventure Trophy Unlock",
        "Mr. Game & Watch - Classic Trophy Unlock",
        "Mr. Game & Watch - All-Star Trophy Unlock",
        "Dr. Mario - Adventure Trophy Unlock",
        "Dr. Mario - Classic Trophy Unlock",
        "Dr. Mario - All-Star Trophy Unlock",
        "Ganondorf - Adventure Trophy Unlock",
        "Ganondorf - Classic Trophy Unlock",
        "Ganondorf - All-Star Trophy Unlock",
        "Falco - Adventure Trophy Unlock",
        "Falco - Classic Trophy Unlock",
        "Falco - All-Star Trophy Unlock",
        "Young Link - Adventure Trophy Unlock",
        "Young Link - Classic Trophy Unlock",
        "Young Link - All-Star Trophy Unlock",
        "Pichu - Adventure Trophy Unlock",
        "Pichu - Classic Trophy Unlock",
        "Pichu - All-Star Trophy Unlock",

        "Roy - Adventure Trophy Unlock",
        "Roy - Classic Trophy Unlock",
        "Roy - All-Star Trophy Unlock",
]


#Crash/Burn, byte 0
#Poolshark, byte 6
#deflector, byte 11
#ricochet rifler, byte 11
#barrel blast, byte 20
#Green And red shell, byte 26