global_trophy_table =["Mario (Trophy)", "Mario (Smash Trophy)", "Mario (Smash Alt Trophy)", "Donkey Kong (Trophy)", "Donkey Kong (Smash Trophy)",
                        "Donkey Kong (Smash Alt Trophy)", "Link (Trophy)", "Link (Smash Trophy)", "Link (Smash Alt Trophy)", "Samus (Trophy)",
                        "Samus (Smash Trophy)", "Samus (Smash Alt Trophy)", "Yoshi (Trophy)", "Yoshi (Smash Trophy)", "Yoshi (Smash Alt Trophy)",
                        "Kirby (Trophy)", "Kirby (Smash Trophy)", "Kirby (Smash Alt Trophy)", "Fox McCloud (Trophy)", "Fox McCloud (Smash Trophy)", "Fox McCloud (Smash Alt Trophy)",
                        "Pikachu (Trophy)", "Pikachu (Smash Trophy)", "Pikachu (Smash Alt Trophy)", "Ness (Trophy)", "Ness (Smash Trophy)", "Ness (Smash Alt Trophy)",
                        "Captain Falcon (Trophy)", "Captain Falcon (Smash Trophy)", "Captain Falcon (Smash Alt Trophy)","Bowser (Trophy)", "Bowser (Smash Trophy)", "Bowser (Smash Alt Trophy)",
                        "Peach (Trophy)", "Peach (Smash Trophy)", "Peach (Smash Alt Trophy)", "Ice Climbers (Trophy)", "Ice Climbers (Smash Trophy)", "Ice Climbers (Smash Alt Trophy)",
                        "Zelda (Trophy)", "Zelda (Smash Trophy)", "Zelda (Smash Alt Trophy)", "Sheik (Trophy)", "Sheik (Smash Trophy)", "Sheik (Smash Alt Trophy)",
                        "Luigi (Trophy)", "Luigi (Smash Trophy)", "Luigi (Smash Alt Trophy)", "Jigglypuff (Trophy)", "Jigglypuff (Smash Trophy)", "Jigglypuff (Smash Alt Trophy)",
                        "Mewtwo (Trophy)", "Mewtwo (Smash Trophy)", "Mewtwo (Smash Alt Trophy)", "Marth (Trophy)", "Marth (Smash Trophy)", "Marth (Smash Alt Trophy)",
                        "Mr. Game & Watch (Trophy)", "Mr. Game & Watch (Smash Trophy)", "Mr. Game & Watch (Smash Alt Trophy)", "Dr. Mario (Trophy)", "Dr. Mario (Smash Trophy)", "Dr. Mario (Smash Alt Trophy)",
                        "Ganondorf (Trophy)", "Ganondorf (Smash Trophy)", "Ganondorf (Smash Alt Trophy)", "Falco Lombardi (Trophy)", "Falco Lombardi (Smash Trophy)", "Falco Lombardi (Smash Alt Trophy)",
                        "Young Link (Trophy)", "Young Link (Smash Trophy)", "Young Link (Smash Alt Trophy)", "Pichu (Trophy)", "Pichu (Smash Trophy)", "Pichu (Smash Alt Trophy)",
                        "Roy (Trophy)", "Roy (Smash Trophy)", "Roy (Smash Alt Trophy)",
                        "Male Wire Frame (Trophy)", "Female Wire Frame (Trophy)", "Fighting Wire Frame (Trophy)", "Giga Bowser (Trophy)", "Master Hand (Trophy)", "Crazy Hand (Trophy)",
                        "Food (Trophy)", "Maxim Tomato (Trophy)", "Heart Container (Trophy)", "Warp Star (Trophy)", "Ray Gun (Trophy)", "Super Scope (Trophy)",
                        "Fire Flower (Trophy)", "Lip's Stick (Trophy)", "Star Rod (Trophy)", "Beam Sword (Trophy)", "Home-Run Bat (Trophy)", "Fan (Trophy)",
                        "Hammer (Trophy)", "Green Shell (Trophy)", "Red Shell (Trophy)", "Flipper (Trophy)", "Freezie (Trophy)", "Mr. Saturn (Trophy)",
                        "Bob-omb (Trophy)", "Motion-Sensor Bomb (Trophy)", "Super Mushroom (Trophy)", "Poison Mushroom (Trophy)", "Starman (Trophy)", "Parasol (Trophy)",
                        "Screw Attack (Trophy)", "Metal Box (Trophy)", "Bunny Hood (Trophy)", "Cloaking Device (Trophy)", "Barrel Cannon (Trophy)", "Party Ball (Trophy)",
                        "Crate (Trophy)", "Barrel (Trophy)", "Capsule (Trophy)", "Egg (Trophy)", "Smash Coins (Trophy)", "Poké Ball (Trophy)",
                        "Venusaur (Trophy)", "Charizard (Trophy)", "Squirtle (Trophy)", "Blastoise (Trophy)", "Clefairy (Trophy)", "Electrode (Trophy)",
                        "Weezing (Trophy)", "Chansey (Trophy)", "Goldeen (Trophy)", "Staryu (Trophy)", "Snorlax (Trophy)", "Articuno (Trophy)",
                        "Zapdos (Trophy)", "Moltres (Trophy)", "Mew (Trophy)", "Chikorita (Trophy)", "Cyndaquil (Trophy)", "Togepi (Trophy)",
                        "Bellossom (Trophy)", "Marill (Trophy)", "Sudowoodo (Trophy)", "Unown (Trophy)", "Wobbuffet (Trophy)", "Scizor (Trophy)",
                        "Porygon2 (Trophy)", "Raikou (Trophy)", "Entei (Trophy)", "Suicune (Trophy)", "Lugia (Trophy)", "Ho-oh (Trophy)",
                        "Celebi (Trophy)", "Toad (Trophy)", "Coin (Trophy)", "Vegetable (Trophy)", "Megavitamins (Trophy)", "Lon Lon Milk (Trophy)",
                        "Kirby Hat 1 (Trophy)", "Kirby Hat 2 (Trophy)", "Kirby Hat 3 (Trophy)", "Kirby Hat 4 (Trophy)", "Kirby Hat 5 (Trophy)", "Princess Peach's Castle (Trophy)",
                        "Banzai Bill (Trophy)", "Lakitu (Trophy)", "Pidgit (Trophy)", "Birdo (Trophy)", "Klap Trap (Trophy)", "Shy Guys (Trophy)",
                        "Pak E. Derm (Trophy)", "Tingle (Trophy)", "Moon (Trophy)", "Turtle (Trophy)", "Four Giants (Trophy)", "Master Sword (Trophy)",
                        "Falcon Flyer (Trophy)", "F-Zero Racers (Trophy)", "Mute City (Trophy)", "Arwing (Trophy)", "Great Fox (Trophy)", "Peppy Hare (Trophy)",
                        "Slippy Toad (Trophy)", "Kraid (Trophy)", "Chozo Statue (Trophy)", "Whispy Woods (Trophy)", "Fountain of Dreams (Trophy)", "UFO (Trophy)",
                        "Pokémon Stadium (Trophy)", "Game & Watch (Trophy)", "Target (Trophy)", "Sandbag (Trophy)", "Battlefield (Trophy)", "Final Destination (Trophy)",
                        "Goomba (Trophy)", "Koopa Troopa (Trophy)", "Koopa Paratroopa (Trophy)", "ReDead (Trophy)", "Octorok (Trophy)", "Like Like (Trophy)",
                        "Topi (Trophy)", "Polar Bear (Trophy)", "Raccoon Mario (Trophy)", "Mario & Yoshi (Trophy)", "Metal Mario (Trophy)", "Paper Mario (Trophy)",
                        "Wario (Trophy)", "Plum (Trophy)", "Daisy (Trophy)", "Waluigi (Trophy)", "Thwomp (Trophy)", "Boo (Trophy)",
                        "Koopa Clown Car (Trophy)", "Viruses (Trophy)", "Bucket (Trophy)", "Racing Kart (Trophy)", "Baby Mario (Trophy)", "Baby Bowser (Trophy)",
                        "Raphael Raven (Trophy)", "Dixie Kong (Trophy)", "King K. Rool (Trophy)", "Goron (Trophy)", "Marin (Trophy)", "Majora's Mask (Trophy)",
                        "Ocarina of Time (Trophy)", "Samurai Goroh (Trophy)", "Dr. Stewart (Trophy)", "Jody Summer (Trophy)", "Landmaster Tank (Trophy)", "Wolfen (Trophy)",
                        "Andross (Trophy)", "Andross (64) (Trophy)", "Samus Unmasked (Trophy)", "Samus's Starship (Trophy)", "Metroid (Trophy)", "Ridley (Trophy)",
                        "Fire Kirby (Trophy)", "Fighter Kirby (Trophy)", "Ball Kirby (Trophy)", "Waddle Dee (Trophy)", "King Dedede (Trophy)", "Rick (Trophy)",
                        "Gooey (Trophy)", "Meta-Knight (Trophy)", "Paula (Trophy)", "Jeff (Trophy)", "Poo (Trophy)", "Starman (EarthBound) (Trophy)",
                        "Bulbasaur (Trophy)", "Poliwhirl (Trophy)", "Ditto (Trophy)", "Eevee (Trophy)", "Totodile (Trophy)", "Crobat (Trophy)",
                        "Cleffa (Trophy)", "Igglybuff (Trophy)", "Steelix (Trophy)", "Heracross (Trophy)", "Meowth (Trophy)", "Professor Oak (Trophy)",
                        "Misty (Trophy)", "ZERO-ONE (Trophy)", "Maruo Maruhige (Trophy)", "Ryota Hayami (Trophy)", "Kensuke Kimachi (Trophy)", "Love Giant (Trophy)",
                        "Hate Giant (Trophy)", "Ray Mk II (Trophy)", "Bayonette (Trophy)", "Annie (Trophy)", "Tom Nook (Trophy)", "Totakeke (Trophy)",
                        "Mr. Resetti (Trophy)", "Heririn (Trophy)", "Alpha (Trophy)", "Vacuum Luigi (Trophy)", "Pikmin (Trophy)", "Captain Olimar (Trophy)",
                        "Excite Bike (Trophy)", "Tamagon (Trophy)", "Donkey Kong Junior (Trophy)", "Ducks (Trophy)", "Bubbles (Trophy)", "Eggplant Man (Trophy)",
                        "Mach Rider (Trophy)", "Balloon Fighter (Trophy)", "Stanley (Trophy)", "Pit (Trophy)", "Dr. Wright (Trophy)", "Donbe & Hikari (Trophy)",
                        "Ayumi Tachibana (Trophy)", "Monster (Trophy)", "Sheriff (Trophy)", "Diskun (Trophy)", "GCN (Trophy)"
                        ]

bonus_checks = {
    0x01: [0, 0x1]
}