base_glyphs = [  # Base-level Arm glyphs
    "Confodere",
    "Secare",
    "Hasta",
    "Macir",
    "Arcus",
    "Falcis",
    "Culter",
    "Lapiste",
    "Pneuma",
    "Ignis",
    "Grando",
    "Fulgur",
    "Umbra",
    "Luminatio",
    "Morbus",
    "Nitesco",
    "Acerbatus",
    "Globus"
]

starting_glyph_pool = [  # All glyphs that are able to be randomly started with
    "Confodere",  # Some of them are difficult or awkward to use, so we don't
    "Vol Confodere",  # want those to get forced on randomly
    "Melio Confodere",
    "Secare",
    "Vol Secare",
    "Melio Secare",
    "Hasta",
    "Vol Hasta",
    "Melio Hasta",
    "Macir",
    "Vol Macir",
    "Melio Macir",
    "Arcus",
    "Vol Arcus",
    "Melio Arcus",
    # "Ascia", Small and akward angle
    "Vol Ascia",
    "Melio Ascia",
    "Falcis",
    "Vol Falcis",
    "Melio Falcis",
    "Culter",
    "Vol Culter",
    "Melio Culter",
    # "Redire", Overpowered
    # "Cubus", Awkward
    "Lapiste",
    "Pneuma",
    "Ignis",
    "Vol Ignis",
    "Grando",
    "Vol Grando",
    "Fulgur",
    "Vol Fulgur",
    "Luminatio",
    "Vol Luminatio",
    "Umbra",
    "Vol Umbra",
    "Morbus",
    "Nitesco",
    "Acerbatus",
    "Globus"
]

valid_starting_glyphs = [  # All valid starting glyphs.
    "Confodere",
    "Vol Confodere",
    "Melio Confodere",
    "Secare",
    "Vol Secare",
    "Melio Secare",
    "Hasta",
    "Vol Hasta",
    "Melio Hasta",
    "Macir",
    "Vol Macir",
    "Melio Macir",
    "Arcus",
    "Vol Arcus",
    "Melio Arcus",
    "Ascia",
    "Vol Ascia",
    "Melio Ascia",
    "Falcis",
    "Vol Falcis",
    "Melio Falcis",
    "Culter",
    "Vol Culter",
    "Melio Culter",
    "Redire",
    "Cubus",
    "Lapiste",
    "Pneuma",
    "Ignis",
    "Vol Ignis",
    "Grando",
    "Vol Grando",
    "Fulgur",
    "Vol Fulgur",
    "Luminatio",
    "Vol Luminatio",
    "Umbra",
    "Vol Umbra",
    "Morbus",
    "Nitesco",
    "Acerbatus",
    "Globus"
]
