base_glyphs = [  # Base-level Arm glyphs
    "Confodere",
    "Secare",
    "Hasta",
    "Macir",
    "Arcus",
    "Falcis",
    # "Culter",
    "Lapiste",
    "Pneuma",
    "Ignis",
    "Grando",
    "Fulgur",
    "Umbra",
    "Luminatio",
    "Morbus",
    "Nitesco",
    "Acerbatus",
    "Globus"
]

melee_glyphs = [  # Base-level Weapon glyphs
    "Confodere",
    "Secare",
    "Hasta",
    "Macir",
    "Falcis"
    # "Culter",
]

starting_glyph_pool = [  # All glyphs that are able to be randomly started with
    "Confodere",  # Some of them are difficult or awkward to use, so we don't
    "Vol Confodere",  # want those to get forced on randomly
    "Melio Confodere",
    "Secare",
    "Vol Secare",
    "Melio Secare",
    "Hasta",
    "Vol Hasta",
    "Melio Hasta",
    "Macir",
    "Vol Macir",
    "Melio Macir",
    "Arcus",
    "Vol Arcus",
    "Melio Arcus",
    # "Ascia", Small and akward angle
    "Vol Ascia",
    "Melio Ascia",
    "Falcis",
    "Vol Falcis",
    "Melio Falcis",
    # "Culter",
    # "Vol Culter",
    # "Melio Culter",
    # "Redire", Overpowered
    # "Cubus", Awkward
    "Lapiste",
    "Pneuma",
    "Ignis",
    "Vol Ignis",
    "Grando",
    "Vol Grando",
    "Fulgur",
    "Vol Fulgur",
    "Luminatio",
    "Vol Luminatio",
    "Umbra",
    "Vol Umbra",
    "Morbus",
    "Nitesco",
    "Acerbatus",
    "Globus"
]

valid_starting_glyphs = [  # All valid starting glyphs.
    "Confodere",
    "Vol Confodere",
    "Melio Confodere",
    "Secare",
    "Vol Secare",
    "Melio Secare",
    "Hasta",
    "Vol Hasta",
    "Melio Hasta",
    "Macir",
    "Vol Macir",
    "Melio Macir",
    "Arcus",
    "Vol Arcus",
    "Melio Arcus",
    "Ascia",
    "Vol Ascia",
    "Melio Ascia",
    "Falcis",
    "Vol Falcis",
    "Melio Falcis",
    "Culter",
    "Vol Culter",
    "Melio Culter",
    "Redire",
    "Cubus",
    "Lapiste",
    "Pneuma",
    "Ignis",
    "Vol Ignis",
    "Grando",
    "Vol Grando",
    "Fulgur",
    "Vol Fulgur",
    "Luminatio",
    "Vol Luminatio",
    "Umbra",
    "Vol Umbra",
    "Morbus",
    "Nitesco",
    "Acerbatus",
    "Globus"
]

area_list = [
    "Dracula's Castle",
    "Wygol Village",
    "Ecclesia",
    "Training Hall",
    "Ruvas Forest",
    "Argila Swamp",
    "Kalidus Channel",
    "Somnus Reef",
    "Minera Prison Island",
    "Lighthouse",
    "Tymeo Mountains",
    "Tristis Pass",
    "Large Cavern",
    "Giant's Dwelling",
    "Mystery Manor",
    "Misty Forest Road",
    "Oblivion Ridge",
    "Skeleton Cave",
    "Monastery"]

villager_list = [
    "Nikolai",
    "Jacob",
    "Abram",
    "Laura",
    "Eugen",
    "Aeon",
    "Marcel",
    "George",
    "Serge",
    "Anna",
    "Monica",
    "Irina",
    "Daniela"]

villager_flags = {
    "Nikolai": 0x08,
    "George": 0x0D,
    "Jacob": 0x2A,
    "Abram": 0x2D,
    "Laura": 0x32,
    "Eugen": 0x38,
    "Aeon": 0x3C,
    "Marcel": 0x40,
    "Serge": 0x47,
    "Anna": 0x4B,
    "Monica": 0x4F,
    "Irina": 0x53,
    "Daniela": 0x57
}

enemy_table = [
    "Bat",
    "Zombie",
    "Skeleton",
    "Ghost",
    "Banshee",
    "Bone Scimitar",
    "Sea Stinger",
    "Nominon",
    "Axe Knight",
    "Une",
    "Merman",
    "Necromancer",
    "Bone Archer",
    "Spear Guard",
    "Invisible Man",
    "Gelso",
    "Needles",
    "Demon",
    "Fishhead",
    "Dark Octopus",
    "Killer Fish",
    "Forneus",
    "The Creature",
    "Black Crow",
    "Skull Spider",
    "Scarecrow",
    "Sea Demon",
    "Winged Guard",
    "Nightmare",
    "Rock Knight",
    "Fire Demon",
    "Bitterfly",
    "Specter",
    "Grave Digger",
    "Werebat",
    "Black Fomor",
    "Enkidu",
    "Bone Pillar",
    "Skeleton Frisky",
    "Skeleton Hero",
    "Dullahan",
    "Skeleton Rex",
    "White Dragon",
    "Saint Elmo",
    "Lorelai",
    "Edimmu",
    "Decarabia",
    "Merman",
    "Ladycat",
    "Ectoplasm",
    "Curse Diva",
    "Miss Murder",
    "Automaton ZX26",
    "Skeleton Beast",
    "Balloon",
    "Arachne",
    "Lizardman",
    "Armored Beast",
    "Yeti",
    "Thunder Demon",
    "Owl",
    "Werewolf",
    "Altair",
    "Mandragora",
    "Jersey Devil",
    "Owl Knight",
    "Chosen Une",
    "Stone Rose",
    "Mad Butcher",
    "White Fomor",
    "Evil Force",
    "Flea Man",
    "Ghoul",
    "Peeping Eye",
    "Gargoyle",
    "Blood Skeleton",
    "Black Panther",
    "Mimic",
    "Draculina",
    "Tin Man",
    "Polkir",
    "Nova Skeleton",
    "Gashida",
    "Devil",
    "Gurkha Master",
    "Red Smasher",
    "Cave Troll",
    "Blade Master",
    "Lilith",
    "Lizardman Blade",
    "Hammer Shaker",
    "Rebuild",
    "Imp",
    "Bugbear",
    "Spectral Sword",
    "Automaton ZX27",
    "Medusa Head",
    "Gorgon Head",
    "Mad Snatcher",
    "Great Knight",
    "King Skeleton",
    "Winged Skeleton",
    "Final Knight",
    "Jiang Shi",
    "Demon Lord",
    "Double Hammer",
    "Weapon Master",
    "Giant Skeleton",
    "Arthroverta",
    "Brachyura",
    "Maneater",
    "Rusalka",
    "Goliath",
    "Gravedorcus",
    "Albus",
    "Barlowe",
    "Wallman",
    "Blackmore",
    "Eligor",
    "Death",
    "Dracula"
]
