from typing import Dict, Set, NamedTuple, Optional
from BaseClasses import ItemClassification


class ItemData(NamedTuple):
    category: str
    code: Optional[int]
    classification: ItemClassification
    default_count: Optional[int] = 1


item_table: Dict[str, ItemData] = {
    "Confodere": ItemData("Arm Glyphs", 0x02, ItemClassification.useful),
    "Vol Confodere": ItemData("Arm Glyphs", 0x03, ItemClassification.filler, 0),
    "Melio Confodere": ItemData("Arm Glyphs", 0x04, ItemClassification.useful),
    "Secare": ItemData("Arm Glyphs", 0x05, ItemClassification.filler, 0),
    "Vol Secare": ItemData("Arm Glyphs", 0x06, ItemClassification.useful),
    "Melio Secare": ItemData("Arm Glyphs", 0x07, ItemClassification.filler, 0),
    "Hasta": ItemData("Arm Glyphs", 0x08, ItemClassification.filler, 0),
    "Vol Hasta": ItemData("Arm Glyphs", 0x09, ItemClassification.useful),
    "Melio Hasta": ItemData("Arm Glyphs", 0x0A, ItemClassification.useful),
    "Macir": ItemData("Arm Glyphs", 0x0B, ItemClassification.useful),
    "Vol Macir": ItemData("Arm Glyphs", 0x0C, ItemClassification.useful),
    "Melio Macir": ItemData("Arm Glyphs", 0x0D, ItemClassification.filler, 0),
    "Arcus": ItemData("Arm Glyphs", 0x0E, ItemClassification.filler, 0),
    "Vol Arcus": ItemData("Arm Glyphs", 0x0F, ItemClassification.useful),
    "Melio Arcus": ItemData("Arm Glyphs", 0x10, ItemClassification.useful),
    "Ascia": ItemData("Arm Glyphs", 0x11, ItemClassification.filler, 0),
    "Vol Ascia": ItemData("Arm Glyphs", 0x12, ItemClassification.useful),
    "Melio Ascia": ItemData("Arm Glyphs", 0x13, ItemClassification.filler, 0),
    "Falcis": ItemData("Arm Glyphs", 0x14, ItemClassification.useful),
    "Vol Falcis": ItemData("Arm Glyphs", 0x15, ItemClassification.filler, 0),
    "Melio Falcis": ItemData("Arm Glyphs", 0x16, ItemClassification.useful),
    "Culter": ItemData("Arm Glyphs", 0x17, ItemClassification.useful),
    "Vol Culter": ItemData("Arm Glyphs", 0x18, ItemClassification.filler, 0),
    "Melio Culter": ItemData("Arm Glyphs", 0x19, ItemClassification.useful),
    "Scutum": ItemData("Arm Glyphs", 0x1A, ItemClassification.useful),
    "Vol Scutum": ItemData("Arm Glyphs", 0x1B, ItemClassification.filler, 0),
    "Melio Scutum": ItemData("Arm Glyphs", 0x1C, ItemClassification.useful),
    "Redire": ItemData("Arm Glyphs", 0x1D, ItemClassification.useful),
    "Cubus": ItemData("Arm Glyphs", 0x1E, ItemClassification.useful),
    "Torpor": ItemData("Arm Glyphs", 0x1F, ItemClassification.filler, 0),
    "Lapiste": ItemData("Arm Glyphs", 0x20, ItemClassification.useful),
    "Pneuma": ItemData("Arm Glyphs", 0x21, ItemClassification.useful),
    "Ignis": ItemData("Arm Glyphs", 0x22, ItemClassification.filler, 0),
    "Vol Ignis": ItemData("Arm Glyphs", 0x23, ItemClassification.useful),
    "Grando": ItemData("Arm Glyphs", 0x24, ItemClassification.filler, 0),
    "Vol Grando": ItemData("Arm Glyphs", 0x25, ItemClassification.useful),
    "Fulgur": ItemData("Arm Glyphs", 0x26, ItemClassification.filler, 0),
    "Vol Fulgur": ItemData("Arm Glyphs", 0x27, ItemClassification.useful),
    "Luminatio": ItemData("Arm Glyphs", 0x28, ItemClassification.useful),
    "Vol Luminatio": ItemData("Arm Glyphs", 0x29, ItemClassification.filler, 0),
    "Umbra": ItemData("Arm Glyphs", 0x2A, ItemClassification.filler, 0),
    "Vol Umbra": ItemData("Arm Glyphs", 0x2B, ItemClassification.useful),
    "Morbus": ItemData("Arm Glyphs", 0x2C, ItemClassification.useful),
    "Nitesco": ItemData("Arm Glyphs", 0x2D, ItemClassification.filler, 0),
    "Acerbatus": ItemData("Arm Glyphs", 0x2E, ItemClassification.filler, 0),
    "Globus": ItemData("Arm Glyphs", 0x2F, ItemClassification.filler, 0),
    "Dextro Custos": ItemData("Arm Glyphs", 0x30, ItemClassification.progression),
    "Sinestro Custos": ItemData("Arm Glyphs", 0x31, ItemClassification.progression),
    "Dominus Hatred": ItemData("Arm Glyphs", 0x32, ItemClassification.progression),
    "Dominus Anger": ItemData("Arm Glyphs", 0x33, ItemClassification.progression),

    "Magnes": ItemData("Back Glyphs", 0x39, ItemClassification.progression),
    "Paries": ItemData("Back Glyphs", 0x3A, ItemClassification.progression),
    "Volaticus": ItemData("Back Glyphs", 0x3B, ItemClassification.progression),
    "Rapidus Fio": ItemData("Back Glyphs", 0x3C, ItemClassification.progression),
    "Vis Fio": ItemData("Back Glyphs", 0x3D, ItemClassification.useful),
    "Fortis Fio": ItemData("Back Glyphs", 0x3E, ItemClassification.useful),
    "Sapiens Fio": ItemData("Back Glyphs", 0x3F, ItemClassification.useful),
    "Fides Fio": ItemData("Back Glyphs", 0x40, ItemClassification.useful),
    "Felicem Fio": ItemData("Back Glyphs", 0x41, ItemClassification.useful),
    "Inire Pecunia": ItemData("Back Glyphs", 0x42, ItemClassification.useful),
    "Arma Felix": ItemData("Back Glyphs", 0x43, ItemClassification.filler, 0),
    "Arma Chiroptera": ItemData("Back Glyphs", 0x44, ItemClassification.filler, 0),
    "Arma Machina": ItemData("Back Glyphs", 0x45, ItemClassification.progression),
    "Refectio": ItemData("Back Glyphs", 0x46, ItemClassification.useful),
    "Arma Custos": ItemData("Back Glyphs", 0x47, ItemClassification.progression),
    "Fidelis Caries": ItemData("Back Glyphs", 0x48, ItemClassification.filler, 0),
    "Fidelis Alate": ItemData("Back Glyphs", 0x49, ItemClassification.filler, 0),
    "Fidelis Polkir": ItemData("Back Glyphs", 0x4A, ItemClassification.filler, 0),
    "Fidelis Noctua": ItemData("Back Glyphs", 0x4B, ItemClassification.filler, 0),
    "Fidelis Medusa": ItemData("Back Glyphs", 0x4C, ItemClassification.filler, 0),
    "Fidelis Aranea": ItemData("Back Glyphs", 0x4D, ItemClassification.filler, 0),
    "Fidelis Mortus": ItemData("Back Glyphs", 0x4E, ItemClassification.filler, 0),
    "Dominus Agony": ItemData("Back Glyphs", 0x4F, ItemClassification.progression),
    "Agartha": ItemData("Back Glyphs", 0x50, ItemClassification.useful),

    "Lizard Tail": ItemData("Relics", 0x70, ItemClassification.progression),
    "Ordinary Rock": ItemData("Relics", 0x71, ItemClassification.progression),
    "Serpent Scale": ItemData("Relics", 0x72, ItemClassification.progression),
    "Glyph Union": ItemData("Relics", 0x73, ItemClassification.progression),
    "Glyph Sleeve": ItemData("Relics", 0x74, ItemClassification.useful),
    "Book of Spirits": ItemData("Relics", 0x75, ItemClassification.useful),

    "Potion": ItemData("Consumables", 0x76, ItemClassification.filler, 0),
    "High Potion": ItemData("Consumables", 0x77, ItemClassification.filler, 0),
    "Super Potion": ItemData("Consumables", 0x78, ItemClassification.filler, 0),
    "Tonic": ItemData("Consumables", 0x79, ItemClassification.filler, 0),
    "High Tonic": ItemData("Consumables", 0x7A, ItemClassification.filler, 0),
    "Super Tonic": ItemData("Consumables", 0x7B, ItemClassification.filler, 0),
    "Heart Repair": ItemData("Consumables", 0x7C, ItemClassification.filler, 0),
    # "Magical Ticket": ItemData("Consumables", 0x7D, ItemClassification.useful),
    "Anti-Venom": ItemData("Consumables", 0x7E, ItemClassification.filler, 0),
    "Uncurse Potion": ItemData("Consumables", 0x7F, ItemClassification.filler, 0),
    "HP Max up": ItemData("Max Up", 0x80, ItemClassification.useful, 13),
    "MP Max up": ItemData("Max Up", 0x81, ItemClassification.useful, 15),
    "HEART Max up": ItemData("Max Up", 0x82, ItemClassification.useful, 14),
    "Meat": ItemData("Consumables", 0x83, ItemClassification.filler, 0),
    "Tasty Meat": ItemData("Consumables", 0x84, ItemClassification.filler, 0),
    "Thick Steak": ItemData("Consumables", 0x85, ItemClassification.filler, 0),
    "Raw Killer Fish": ItemData("Consumables", 0x86, ItemClassification.filler, 0),
    "Rice Ball": ItemData("Consumables", 0x87, ItemClassification.filler, 0),
    "Mushroom": ItemData("Consumables", 0x88, ItemClassification.filler, 0),
    "Corn Soup": ItemData("Consumables", 0x89, ItemClassification.filler, 0),
    "Minestrone": ItemData("Consumables", 0x8A, ItemClassification.filler, 0),
    "Curry": ItemData("Consumables", 0x8B, ItemClassification.filler, 0),
    "Ramen Noodles": ItemData("Consumables", 0x8C, ItemClassification.filler, 0),
    "Cream Puff": ItemData("Consumables", 0x8D, ItemClassification.filler, 0),
    "Pudding": ItemData("Consumables", 0x8E, ItemClassification.filler, 0),
    "Mocha Eclair": ItemData("Consumables", 0x8F, ItemClassification.filler, 0),
    "Tart Tatin": ItemData("Consumables", 0x90, ItemClassification.filler, 0),
    "Choco Souffle": ItemData("Consumables", 0x91, ItemClassification.filler, 0),
    "Crepes Suzette": ItemData("Consumables", 0x92, ItemClassification.filler, 0),
    "Croque Monsieur": ItemData("Consumables", 0x93, ItemClassification.filler, 0),
    "Schnitzel": ItemData("Consumables", 0x94, ItemClassification.filler, 0),
    "Eisbein": ItemData("Consumables", 0x95, ItemClassification.filler, 0),
    "Killer Fish BBQ": ItemData("Consumables", 0x96, ItemClassification.filler, 0),
    "Salt": ItemData("Consumables", 0x97, ItemClassification.filler, 0),
    "Mint Sundae": ItemData("Consumables", 0x98, ItemClassification.filler, 0),
    "Milk": ItemData("Consumables", 0x99, ItemClassification.filler, 0),
    "Coffee": ItemData("Consumables", 0x9A, ItemClassification.filler, 0),
    "Earl Grey": ItemData("Consumables", 0x9B, ItemClassification.filler, 0),
    "Darjeeling Tea": ItemData("Consumables", 0x9C, ItemClassification.filler, 0),
    "Red Drops": ItemData("Consumables", 0x9D, ItemClassification.useful, 0),
    "Blue Drops": ItemData("Consumables", 0x9E, ItemClassification.useful, 0),
    "Green Drops": ItemData("Consumables", 0x9F, ItemClassification.useful, 0),
    "White Drops": ItemData("Consumables", 0xA0, ItemClassification.useful, 0),
    "Black Drops": ItemData("Consumables", 0xA1, ItemClassification.useful, 0),
    "Amanita": ItemData("Consumables", 0xA2, ItemClassification.trap, 0),
    "Rotten Meat": ItemData("Consumables", 0xA3, ItemClassification.trap, 0),
    "Spoiled Milk": ItemData("Consumables", 0xA4, ItemClassification.trap, 0),
    "Record 1": ItemData("Key Items", 0xA5, ItemClassification.useful),
    "Record 2": ItemData("Key Items", 0xA6, ItemClassification.filler, 0),
    "Record 3": ItemData("Key Items", 0xA7, ItemClassification.filler, 0),
    "Record 4": ItemData("Key Items", 0xA8, ItemClassification.filler, 0),
    "Record 5": ItemData("Key Items", 0xA9, ItemClassification.useful),
    "Record 6": ItemData("Key Items", 0xAA, ItemClassification.filler, 0),
    "Record 7": ItemData("Key Items", 0xAB, ItemClassification.filler, 0),
    "Record 8": ItemData("Key Items", 0xAC, ItemClassification.filler, 0),
    "Mouse": ItemData("Key Items", 0xAD, ItemClassification.progression, 0),
    "Cat Collar": ItemData("Key Items", 0xAE, ItemClassification.progression, 0),  # Quest progress
    "Camera": ItemData("Key Items", 0xAF, ItemClassification.progression, 0),
    "Photo 1": ItemData("Key Items", 0xB0, ItemClassification.progression, 0),
    "Photo 2": ItemData("Key Items", 0xB1, ItemClassification.progression, 0),
    "Photo 3": ItemData("Key Items", 0xB2, ItemClassification.progression, 0),
    "Poor Photo": ItemData("Key Items", 0xB3, ItemClassification.filler, 0),
    '"Frontier" Issue 1': ItemData("Key Items", 0xB4, ItemClassification.filler, 0),
    '"Frontier" Issue 2"': ItemData("Key Items", 0xB5, ItemClassification.filler, 0),
    '"Frontier" Final"': ItemData("Key Items", 0xB6, ItemClassification.filler, 0),
    "Sketch Book": ItemData("Key Items", 0xB7, ItemClassification.progression, 0),
    "Lighthouse Art": ItemData("Key Items", 0xB8, ItemClassification.progression, 0),
    "Waterfall Art": ItemData("Key Items", 0xB9, ItemClassification.progression, 0),
    "Church Art": ItemData("Key Items", 0xBA, ItemClassification.progression, 0),
    "Horse Hair": ItemData("Material", 0xBB, ItemClassification.filler, 0),
    "Eagle Feather": ItemData("Material", 0xBC, ItemClassification.filler, 0),
    "Black Ink": ItemData("Material", 0xBD, ItemClassification.filler, 0),
    "Cotton Thread": ItemData("Material", 0xBE, ItemClassification.filler, 0),
    "Silk Thread": ItemData("Material", 0xBF, ItemClassification.filler, 0),
    "Cashmere Thread": ItemData("Material", 0xC0, ItemClassification.filler, 0),
    "Sage": ItemData("Material", 0xC1, ItemClassification.filler, 0),
    "Chamomile": ItemData("Material", 0xC2, ItemClassification.filler, 0),
    "Rue": ItemData("Material", 0xC3, ItemClassification.filler, 0),
    "Mandrake Root": ItemData("Material", 0xC4, ItemClassification.filler, 0),
    "Merman Meat": ItemData("Material", 0xC5, ItemClassification.filler, 0),
    "Zircon": ItemData("Material", 0xC6, ItemClassification.filler, 0),
    "Lapis Lazuli": ItemData("Material", 0xC7, ItemClassification.filler, 0),
    "Chrysoberyl": ItemData("Material", 0xC8, ItemClassification.filler, 0),
    "Ruby": ItemData("Consumables", 0xC9, ItemClassification.filler, 0),
    "Sapphire": ItemData("Consumables", 0xCA, ItemClassification.filler, 0),
    "Emerald": ItemData("Consumables", 0xCB, ItemClassification.filler, 0),
    "Onyx": ItemData("Consumables", 0xCC, ItemClassification.filler, 0),
    "Diamond": ItemData("Consumables", 0xCD, ItemClassification.filler, 0),
    "Alexandrite": ItemData("Consumables", 0xCE, ItemClassification.filler, 0),
    "Copper Ore": ItemData("Consumables", 0xCF, ItemClassification.filler, 0),
    "Iron Ore": ItemData("Consumables", 0xD0, ItemClassification.filler, 0),
    "Silver Ore": ItemData("Consumables", 0xD1, ItemClassification.filler, 0),
    "Gold Ore": ItemData("Consumables", 0xD2, ItemClassification.filler, 0),
    "VIP Card": ItemData("Consumables", 0xD3, ItemClassification.useful, 0),
    # "AP Item": ItemData("Key Items", 0xD4, ItemClassification.progression, 0), reserved
    # "AP Item": ItemData("Key Items", 0xD5, ItemClassification.progression, 0),
    # "AP Item": ItemData("Key Items", 0xD6, ItemClassification.progression, 0),
    "Phonograph": ItemData("Key Items", 0xD7, ItemClassification.progression, 0),
    "Arthro Medal": ItemData("Medals", 0xD8, ItemClassification.useful, 0),
    "Skeleton Medal": ItemData("Medals", 0xD9, ItemClassification.useful, 0),
    "Brachyura Medal": ItemData("Medals", 0xDA, ItemClassification.useful, 0),
    "Maneater Medal": ItemData("Medals", 0xDB, ItemClassification.useful, 0),
    "Rusalka Medal": ItemData("Medals", 0xDC, ItemClassification.useful, 0),
    "Goliath Medal": ItemData("Medals", 0xDD, ItemClassification.useful, 0),
    "Gravedo Medal": ItemData("Medals", 0xDE, ItemClassification.useful, 0),
    "Albus Medal": ItemData("Medals", 0xDF, ItemClassification.useful, 0),
    "Barlowe Medal": ItemData("Medals", 0xE0, ItemClassification.useful, 0),
    "Wallman Medal": ItemData("Medals", 0xE1, ItemClassification.useful, 0),
    "Blackmore Medal": ItemData("Medals", 0xE2, ItemClassification.useful, 0),
    "Eligor Medal": ItemData("Medals", 0xE3, ItemClassification.useful, 0),
    "Death Medal": ItemData("Medals", 0xE4, ItemClassification.useful, 0),
    "Dracula Medal": ItemData("Medals", 0xE5, ItemClassification.useful, 0),

    "Casual Clothes": ItemData("Body Armor", 0xE7, ItemClassification.filler, 0),
    "Military Wear": ItemData("Body Armor", 0xE8, ItemClassification.filler, 0),
    "Rubber Suit": ItemData("Body Armor", 0xE9, ItemClassification.filler, 0),
    "Reinforced Suit": ItemData("Body Armor", 0xEA, ItemClassification.useful),
    "Body Suit": ItemData("Body Armor", 0xEB, ItemClassification.useful),
    "Leather Cuirass": ItemData("Body Armor", 0xEC, ItemClassification.filler, 0),
    "Copper Plate": ItemData("Body Armor", 0xED, ItemClassification.filler, 0),
    "Iron Plate": ItemData("Body Armor", 0xEE, ItemClassification.filler, 0),
    "Silver Plate": ItemData("Body Armor", 0xEF, ItemClassification.filler, 0),
    "Gold Plate": ItemData("Body Armor", 0xF0, ItemClassification.filler, 0),
    "Platinum Plate": ItemData("Body Armor", 0xF1, ItemClassification.filler, 0),
    "Mirror Cuirass": ItemData("Body Armor", 0xF2, ItemClassification.filler, 0),
    "Heart Cuirass": ItemData("Body Armor", 0xF3, ItemClassification.useful),
    "Barbarian Belt": ItemData("Body Armor", 0xF4, ItemClassification.filler, 0),
    "Knight Cuirass": ItemData("Body Armor", 0xF5, ItemClassification.filler, 0),
    "Crimson Mail": ItemData("Body Armor", 0xF6, ItemClassification.filler, 0),
    "Valkyrie Mail": ItemData("Body Armor", 0xF7, ItemClassification.useful),
    "Minerva Mail": ItemData("Body Armor", 0xF8, ItemClassification.filler, 0),
    "Cotton Dress": ItemData("Body Armor", 0xF9, ItemClassification.filler, 0),
    "Silk Dress": ItemData("Body Armor", 0xFA, ItemClassification.filler, 0),
    "Sequined Dress": ItemData("Body Armor", 0xFB, ItemClassification.filler, 0),
    "Empire Dress": ItemData("Body Armor", 0xFC, ItemClassification.filler, 0),
    "Corset Dress": ItemData("Body Armor", 0xFD, ItemClassification.filler, 0),
    "Party Dress": ItemData("Body Armor", 0xFE, ItemClassification.filler, 0),
    "Wedding Dress": ItemData("Body Armor", 0xFF, ItemClassification.filler, 0),
    "Robe Decollete": ItemData("Body Armor", 0x100, ItemClassification.filler, 0),

    "Eye for Decay": ItemData("Headgear", 0x102, ItemClassification.filler, 0),
    "L. Eye of God": ItemData("Headgear", 0x103, ItemClassification.filler, 0),
    "R. Eye of Devil": ItemData("Headgear", 0x104, ItemClassification.filler, 0),
    "Cotton Hat": ItemData("Headgear", 0x105, ItemClassification.useful),
    "Garbo Hat": ItemData("Headgear", 0x106, ItemClassification.filler, 0),
    "Treasure Hat": ItemData("Headgear", 0x107, ItemClassification.filler, 0),
    "Dowsing Hat": ItemData("Headgear", 0x108, ItemClassification.filler, 0),
    "Traveler's Hat": ItemData("Headgear", 0x109, ItemClassification.filler, 0),
    "Ribbon": ItemData("Headgear", 0x10A, ItemClassification.filler, 0),
    "Cabriolet": ItemData("Headgear", 0x10B, ItemClassification.useful),
    "Babushka": ItemData("Headgear", 0x10C, ItemClassification.filler, 0),
    "Caprine": ItemData("Headgear", 0x10D, ItemClassification.useful),
    "Crochet": ItemData("Headgear", 0x10E, ItemClassification.filler, 0),
    "Barbarian Helm": ItemData("Headgear", 0x10F, ItemClassification.filler, 0),
    "Knight Helm": ItemData("Headgear", 0x110, ItemClassification.filler, 0),
    "Crimson Mask": ItemData("Headgear", 0x111, ItemClassification.useful),
    "Valkyrie Mask": ItemData("Headgear", 0x112, ItemClassification.useful),
    "Minerva Mask": ItemData("Headgear", 0x113, ItemClassification.filler, 0),
    "Ruby Pins": ItemData("Headgear", 0x114, ItemClassification.filler, 0),
    "Sapphire Pins": ItemData("Headgear", 0x115, ItemClassification.filler, 0),
    "Emerald Pins": ItemData("Headgear", 0x116, ItemClassification.filler, 0),
    "Diamond Pins": ItemData("Headgear", 0x117, ItemClassification.filler, 0),
    "Onyx Pins": ItemData("Headgear", 0x118, ItemClassification.filler, 0),
    "Stephanie": ItemData("Headgear", 0x119, ItemClassification.filler, 0),
    "Royal Crown": ItemData("Headgear", 0x11A, ItemClassification.filler, 0),
    "Sword Helm": ItemData("Headgear", 0x11B, ItemClassification.useful),
    "Rapier Helm": ItemData("Headgear", 0x11C, ItemClassification.useful),
    "Lance Helm": ItemData("Headgear", 0x11D, ItemClassification.useful),
    "Hammer Helm": ItemData("Headgear", 0x11E, ItemClassification.useful),
    "Arrow Helm": ItemData("Headgear", 0x11F, ItemClassification.useful),
    "Axe Helm": ItemData("Headgear", 0x120, ItemClassification.useful),
    "Sickle Helm": ItemData("Headgear", 0x121, ItemClassification.useful),
    "Knife Helm": ItemData("Headgear", 0x122, ItemClassification.useful),
    "Shield Helm": ItemData("Headgear", 0x123, ItemClassification.useful),
    "Queen of Hearts": ItemData("Headgear", 0x124, ItemClassification.useful, 0),

    "Moonwalkers": ItemData("Boots", 0x126, ItemClassification.useful),
    "Mercury Boots": ItemData("Boots", 0x127, ItemClassification.useful),
    "Winged Boots": ItemData("Boots", 0x128, ItemClassification.filler, 0),
    "Combo Boots": ItemData("Boots", 0x129, ItemClassification.filler, 0),
    "Sandals": ItemData("Boots", 0x12A, ItemClassification.useful),
    "Sabrina Shoes": ItemData("Boots", 0x12B, ItemClassification.filler, 0),
    "Cossack Boots": ItemData("Boots", 0x12C, ItemClassification.filler, 0),
    "Baggy Boots": ItemData("Boots", 0x12D, ItemClassification.filler, 0),
    "Battle Boots": ItemData("Boots", 0x12E, ItemClassification.filler, 0),
    "Ghillie Boots": ItemData("Boots", 0x12F, ItemClassification.filler, 0),
    "Cavalier Boots": ItemData("Boots", 0x130, ItemClassification.filler, 0),
    "Iron Leggings": ItemData("Boots", 0x131, ItemClassification.filler, 0),
    "Silver Leggings": ItemData("Boots", 0x132, ItemClassification.filler, 0),
    "Gold Leggings": ItemData("Boots", 0x133, ItemClassification.filler, 0),
    "Plat Leggings": ItemData("Boots", 0x134, ItemClassification.filler, 0),
    "Barbarian Shoes": ItemData("Boots", 0x135, ItemClassification.filler, 0),
    "Knight Leggings": ItemData("Boots", 0x136, ItemClassification.filler, 0),
    "Crimson Greaves": ItemData("Boots", 0x137, ItemClassification.filler, 0),
    "Valkyrie Greaves": ItemData("Boots", 0x138, ItemClassification.useful),
    "Minerva Greaves": ItemData("Boots", 0x139, ItemClassification.filler, 0),

    "Protect Ring": ItemData("Accessories", 0x13B, ItemClassification.filler, 0),
    "Resist Ring": ItemData("Accessories", 0x13C, ItemClassification.filler, 0),
    "Fool Ring": ItemData("Accessories", 0x13D, ItemClassification.useful),
    "Magician Ring": ItemData("Accessories", 0x13E, ItemClassification.useful),
    "Priestess Ring": ItemData("Accessories", 0x13F, ItemClassification.useful),
    "Empress Ring": ItemData("Accessories", 0x140, ItemClassification.useful),
    "Emperor Ring": ItemData("Accessories", 0x141, ItemClassification.useful),
    "Hierophant Ring": ItemData("Accessories", 0x142, ItemClassification.useful),
    "Lovers Ring": ItemData("Accessories", 0x143, ItemClassification.useful),
    "Chariot Ring": ItemData("Accessories", 0x144, ItemClassification.useful),
    "Justice Ring": ItemData("Accessories", 0x145, ItemClassification.useful),
    "Hermit Ring": ItemData("Accessories", 0x146, ItemClassification.useful),
    "Fortune Ring": ItemData("Accessories", 0x147, ItemClassification.useful),
    "Strength Ring": ItemData("Accessories", 0x148, ItemClassification.useful),
    "Hanged Man Ring": ItemData("Accessories", 0x149, ItemClassification.useful),
    "Death Ring": ItemData("Accessories", 0x14A, ItemClassification.useful),
    "Temperance Ring": ItemData("Accessories", 0x14B, ItemClassification.useful),
    "Devil Ring": ItemData("Accessories", 0x14C, ItemClassification.useful),
    "Tower Ring": ItemData("Accessories", 0x14D, ItemClassification.useful),
    "Star Ring": ItemData("Accessories", 0x14E, ItemClassification.useful),
    "Moon Ring": ItemData("Accessories", 0x14F, ItemClassification.useful),
    "Sun Ring": ItemData("Accessories", 0x150, ItemClassification.useful),
    "Judgement Ring": ItemData("Accessories", 0x151, ItemClassification.useful),
    "World Ring": ItemData("Accessories", 0x152, ItemClassification.useful),
    "Archer Ring": ItemData("Accessories", 0x153, ItemClassification.filler, 0),
    "Blow Ring": ItemData("Accessories", 0x154, ItemClassification.filler, 0),
    "Wind Ring": ItemData("Accessories", 0x155, ItemClassification.filler, 0),
    "Ruby Ring": ItemData("Accessories", 0x156, ItemClassification.filler, 0),
    "Sapphire Ring": ItemData("Accessories", 0x157, ItemClassification.filler, 0),
    "Emerald Ring": ItemData("Accessories", 0x158, ItemClassification.filler, 0),
    "Diamond Ring": ItemData("Accessories", 0x159, ItemClassification.filler, 0),
    "Onyx Ring": ItemData("Accessories", 0x15A, ItemClassification.filler, 0),
    "Heart Earrings": ItemData("Accessories", 0x15B, ItemClassification.filler, 0),
    "Gold Ring": ItemData("Accessories", 0x15C, ItemClassification.filler, 0),
    "Miser Ring": ItemData("Accessories", 0x15D, ItemClassification.filler, 0),
    "Lucky Clover": ItemData("Accessories", 0x15E, ItemClassification.filler, 0),
    "Thief Ring": ItemData("Accessories", 0x15F, ItemClassification.filler, 0),
    "Master Ring": ItemData("Accessories", 0x160, ItemClassification.useful, 0),

    "1G": ItemData("Money", 0x161, ItemClassification.filler, 0),
    "10G": ItemData("Money", 0x162, ItemClassification.filler, 0),
    "50G": ItemData("Money", 0x163, ItemClassification.filler, 0),
    "100G": ItemData("Money", 0x164, ItemClassification.filler, 0),
    "500G": ItemData("Money", 0x165, ItemClassification.filler, 0),
    "1000G": ItemData("Money", 0x166, ItemClassification.filler, 0),
    "2000G": ItemData("Money", 0x167, ItemClassification.filler, 0),

    "Nikolai": ItemData("Villagers", 0x168, ItemClassification.progression),
    "Jacob": ItemData("Villagers", 0x169, ItemClassification.progression),
    "Abram": ItemData("Villagers", 0x16A, ItemClassification.progression),
    "Laura": ItemData("Villagers", 0x16B, ItemClassification.progression),
    "Eugen": ItemData("Villagers", 0x16C, ItemClassification.progression),
    "Aeon": ItemData("Villagers", 0x16D, ItemClassification.progression),
    "Marcel": ItemData("Villagers", 0x16E, ItemClassification.progression),
    "George": ItemData("Villagers", 0x16F, ItemClassification.progression),
    "Serge": ItemData("Villagers", 0x170, ItemClassification.progression),
    "Anna": ItemData("Villagers", 0x171, ItemClassification.progression),
    "Monica": ItemData("Villagers", 0x172, ItemClassification.progression),
    "Irina": ItemData("Villagers", 0x173, ItemClassification.progression),
    "Daniela": ItemData("Villagers", 0x174, ItemClassification.progression),

    "Map: Training Hall": ItemData("Area Maps", 0x179, ItemClassification.progression),
    "Map: Ruvas Forest": ItemData("Area Maps", 0x17A, ItemClassification.progression),
    "Map: Argila Swamp": ItemData("Area Maps", 0x17B, ItemClassification.progression),
    "Map: Kalidus Channel": ItemData("Area Maps", 0x17C, ItemClassification.progression, 2),
    "Map: Somnus Reef": ItemData("Area Maps", 0x17D, ItemClassification.progression),
    "Map: Minera Prison Island": ItemData("Area Maps", 0x17E, ItemClassification.progression),
    "Map: Lighthouse": ItemData("Area Maps", 0x17F, ItemClassification.progression),
    "Map: Tymeo Mountains": ItemData("Area Maps", 0x180, ItemClassification.progression),
    "Map: Tristis Pass": ItemData("Area Maps", 0x181, ItemClassification.progression),
    "Map: Large Cavern": ItemData("Area Maps", 0x182, ItemClassification.progression),
    "Map: Giant's Dwelling": ItemData("Area Maps", 0x183, ItemClassification.progression),
    "Map: Mystery Manor": ItemData("Area Maps", 0x184, ItemClassification.progression),
    "Map: Misty Forest Road": ItemData("Area Maps", 0x185, ItemClassification.progression),
    "Map: Oblivion Ridge": ItemData("Area Maps", 0x186, ItemClassification.progression),
    "Map: Skeleton Cave": ItemData("Area Maps", 0x187, ItemClassification.progression),
    "Map: Monastery": ItemData("Area Maps", 0x188, ItemClassification.progression)}


def get_item_names_per_category() -> Dict[str, Set[str]]:
    categories: Dict[str, Set[str]] = {}

    for name, data in item_table.items():
        if data.category != "Events":
            categories.setdefault(data.category, set()).add(name)

    return categories
