from typing import TYPE_CHECKING, Optional, NamedTuple, List
from .static_location_data import location_data_table
from .Options import AddBrownChests

if TYPE_CHECKING:
    from . import OoEWorld


class LocationData(NamedTuple):
    region: str
    name: str
    is_event: Optional[bool] = False


def get_locations(world: "OoEWorld") -> List[LocationData]:
    location_table: List[LocationData] = [
        LocationData("Ecclesia", "Ecclesia: Center Chest"),
        LocationData("Ecclesia", "Ecclesia: Hidden Chest"),
        LocationData("Ecclesia", "Ecclesia: Training Hall Chest"),
        LocationData("Ecclesia", "Ecclesia: Barlowe Fight", True),

        LocationData("Wygol Village", "Wygol Village: Chest In Right House"),
        LocationData("Wygol Village", "Wygol Village: Left Chest"),
        LocationData("Wygol Village", "Wygol Village: Right Chest"),
        LocationData("Wygol Village", "Wygol Village: Grounded Chest"),

        LocationData("Ruvas Forest", "Ruvas Forest: First Room Freestanding"),
        LocationData("Ruvas Forest", "Ruvas Forest: Area Exit"),
        LocationData("Ruvas Forest", "Ruvas Forest: Left Chest"),
        LocationData("Ruvas Forest", "Ruvas Forest: Right Chest"),

        LocationData("Argila Swamp", "Argila Swamp: Chest"),
        LocationData("Argila Swamp", "Argila Swamp: Area Exit"),

        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Left Small Vertical Freestanding"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Left Tall Room Freestanding"),
        LocationData("Kalidus Channel", "Kalidus Channel: Upper Exit"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Left Tall Room Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Left Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Central"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Right Shaft Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Right Center Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Lower Exit"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Lower Left Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Lower Center Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Lower Right Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Deepest Room"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Right Depths Dead End Chest"),
        LocationData("Kalidus Channel", "Kalidus Channel: Right Exit Underwater Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Center Left Chest"),
        LocationData("Kalidus Channel", "Kalidus Channel: Right Side Underwater Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Secret Room Left Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Right Left Chest"),
        LocationData("Kalidus Channel", "Kalidus Channel: First Room Underwater"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Secret Room Right Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Hidden Chest"),
        LocationData("Kalidus Channel", "Kalidus Channel: Right Side Hidden Item"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths First Room Chest"),
        LocationData("Kalidus Channel", "Kalidus Channel: Hallway Item 1"),
        LocationData("Kalidus Channel", "Kalidus Channel: Third Room Underwater"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Secret Room Center Chest"),
        LocationData("Kalidus Channel", "Kalidus Channel: Hallway Item 2"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Right Right Chest"),
        LocationData("Kalidus Channel", "Kalidus Channel: Second Room Underwater"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Rightmost Shaft Freestanding"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Center Right Chest"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Depths Lower Left"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Upper Left"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Upper Right"),
        LocationData("Kalidus Channel Depths", "Kalidus Channel: Ship Room Center Freestanding"),

        LocationData("Somnus Reef Main", "Somnus Reef: Left Big Room Freestanding"),
        LocationData("Somnus Reef Main", "Somnus Reef: East Entrance Item"),
        LocationData("Somnus Reef Main", "Somnus Reef: Right Side Isolated Room"),
        LocationData("Somnus Reef Main", "Somnus Reef: Left Open Room Lower Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Lower Left Right Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Right Side Cave Hidden Item"),
        LocationData("Somnus Reef Main", "Somnus Reef: Left Big Room Right Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: First Shaft Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: First Big Room Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Hidden Room"),
        LocationData("Somnus Reef Main", "Somnus Reef: Left Big Room Left Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Left Big Room Center Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Left Big Room Upper Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Right Side Cave Item"),
        LocationData("Somnus Reef Main", "Somnus Reef: Right Shaft"),
        LocationData("Somnus Reef Main", "Somnus Reef: Area Exit"),
        LocationData("Somnus Reef Main", "Somnus Reef: Lower Left Left Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Lower Right Left Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Lower Right Right Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: Exit Shaft Chest"),
        LocationData("Somnus Reef Main", "Somnus Reef: First Shaft Freestanding"),

        LocationData("Minera Prison Island Main", "Minera Prison Island: Albus 1"),
        LocationData("Minera Prison Island Final Segment", "Minera Prison Island: Shaft Near Exit"),
        LocationData("Minera Prison Island Final Segment", "Minera Prison Island: Electric Room"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Entrance Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Upper Spear Hall"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Lower Spear Hall Later Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Right Entry Shaft Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Top Room"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Lowest Room"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Lower Right Hall"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Right Central Room"),
        LocationData("Minera Prison Island Final Segment", "Minera Prison Island: Right Spear Hall Chest"),
        LocationData("Minera Prison Island Final Segment", "Minera Prison Island: Exit Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Left Lower Hall"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Lower Spear Hall Ending Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Right Vertical Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Hidden Room"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Top Room Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Right Vertical Hidden Item"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Shaft Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Lower Spear Hall First Chest"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Entrance Pickup"),
        LocationData("Minera Prison Island Main", "Minera Prison Island: Room Past Albus"),
        LocationData("Minera Prison Island Final Segment", "Minera Prison Island: Area Exit"),

        LocationData("Lighthouse Post-Boss", "Lighthouse: Searchlight Glyph"),
        LocationData("Lighthouse Post-Boss", "Lighthouse: Exit Chest"),
        LocationData("Lighthouse Post-Boss", "Lighthouse: Right Hall"),
        LocationData("Lighthouse Post-Boss", "Lighthouse: Area Exit"),

        LocationData("Tymeo Mountains East", "Tymeo Mountains: Wind Glyph"),
        LocationData("Tymeo Mountains Past Spikes Room", "Tymeo Mountains: Left Hill Alcove Pickup"),
        LocationData("Tymeo Mountains Past Spikes Room", "Tymeo Mountains: Side Room"),
        LocationData("Tymeo Mountains Past Spikes Room", "Tymeo Mountains: Bridge Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Right Shaft Upper"),
        LocationData("Tymeo Mountains Past Spikes Room", "Tymeo Mountains: Left Hill Alcove Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Upper Hill Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Upper Mountain Hidden Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Lower Mountain Lower Paries Chest"),
        LocationData("Tymeo Mountains", "Tymeo Mountains: First Room Hidden Chest"),
        LocationData("Tymeo Mountains", "Tymeo Mountains: Cavern Near Breakable Wall"),
        LocationData("Tymeo Mountains Past Spikes Room", "Tymeo Mountains: Left Exit"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Right Hill Alcove Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Right Shaft Hidden Item"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Lower Mountain Upper Paries Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Lower Mountain Free Chest"),
        LocationData("Tymeo Mountains", "Tymeo Mountains: Hidden Room"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Upper Mountain Left Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Upper Mountain Right Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Right Exit"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Right Exit Item"),
        LocationData("Tymeo Mountains", "Tymeo Mountains: Cavern Chest"),
        LocationData("Tymeo Mountains East", "Tymeo Mountains: Right Shaft Lower"),

        LocationData("Tristis Pass Frozen Area", "Tristis Pass: Frozen Waterfall Glyph"),  # obj 47
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Final Hill Underground Pickup"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Ice Cave Chest"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Final Hill Alcove"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Waterfall Upper"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Waterfall Hidden Chest"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Second Hill Lowest Chest"),
        LocationData("Tristis Pass", "Tristis Pass: First Alcove"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Bridge Chest"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Lower Hill Left"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Lower Hill Right"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Second Hill Lower Left"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Second Hill Upper Chest"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Third Hill Left"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Third Hill Right"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Waterfall Center"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Ice Exit Hidden Item"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Final Hill Tree Chest"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Area Exit"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Final Hill Underground Chest"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Waterfall Lower"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Room Behind Waterfall"),
        LocationData("Tristis Pass Waterfall", "Tristis Pass: Second Hill Pickup"),

        LocationData("Giant's Dwelling Main", "Giant's Dwelling: Bottom Right Room Pickup"),
        LocationData("Giant's Dwelling Main", "Giant's Dwelling: Albus 2"),
        LocationData("Giant's Dwelling", "Giant's Dwelling: Entrance Item"),
        LocationData("Giant's Dwelling Main", "Giant's Dwelling: Above Entrance"),
        LocationData("Giant's Dwelling Main", "Giant's Dwelling: Area Exit"),
        LocationData("Giant's Dwelling Main", "Giant's Dwelling: First Corner"),
        LocationData("Giant's Dwelling Main", "Giant's Dwelling: First Main Room Top"),
        
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
    ]

    if not world.options.remove_training_hall:
        location_table.extend([
            LocationData("Training Hall", "Training Hall: Freestanding"),
            LocationData("Training Hall", "Training Hall: Top Chest"),
            LocationData("Training Hall", "Training Hall: First Way Down Chest"),
            LocationData("Training Hall", "Training Hall: Second Way Down Chest"),
            LocationData("Training Hall", "Training Hall: Third Way Down Chest"),
            LocationData("Training Hall", "Training Hall: Final Chest")])

    if not world.options.remove_large_cavern:
        location_table.extend([
            LocationData("Large Cavern", "Large Cavern: Rest Room 1"),
            LocationData("Large Cavern", "Large Cavern: Rest Room 2"),
            LocationData("Large Cavern", "Large Cavern: Rest Room 3"),
            LocationData("Large Cavern", "Large Cavern: Rest Room 4"),
            LocationData("Large Cavern", "Large Cavern: Final Reward 1"),
            LocationData("Large Cavern", "Large Cavern: Final Reward 2")
        ])

    if world.options.add_brown_chests != AddBrownChests.option_include:
        for location in location_table:
            name = location.name
            if location_data_table[name].location_type == "Wood Chest":
                location_table.remove(location)

    return location_table
