from typing import TYPE_CHECKING, Optional, NamedTuple, List
from .Options import AddBrownChests

if TYPE_CHECKING:
    from . import OoEWorld


class LocationData(NamedTuple):
    region: str
    name: str
    is_event: Optional[bool] = False


def get_locations(world: "OoEWorld") -> List[LocationData]:
    location_table: List[LocationData] = [
        LocationData("Ecclesia", "Ecclesia: Center Chest"),
        LocationData("Ecclesia", "Ecclesia: Hidden Chest"),
        LocationData("Ecclesia", "Ecclesia: Training Hall Chest"),
        LocationData("Ecclesia", "Ecclesia: Barlowe Fight", True),

        LocationData("Wygol Village", "Wygol Village: Chest In Right House"),
        LocationData("Wygol Village", "Wygol Village: Left Chest"),
        LocationData("Wygol Village", "Wygol Village: Right Chest"),
        LocationData("Wygol Village", "Wygol Village: Grounded Chest"),

        LocationData("Ruvas Forest", "Ruvas Forest: First Room Freestanding"),
        LocationData("Ruvas Forest", "Ruvas Forest: Area Exit"),
        LocationData("Ruvas Forest", "Ruvas Forest: Left Chest"),
        LocationData("Ruvas Forest", "Ruvas Forest: Right Chest"),
        
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
        LocationData("Dummy", "Dummy"),
    ]

    if not world.options.remove_training_hall:
        location_table.append(LocationData("Training Hall", "Training Hall: Freestanding"))  # Regular check

        if world.options.add_brown_chests == AddBrownChests.option_include:
            location_table.extend([
                LocationData("Training Hall", "Training Hall: Top Chest"),
                LocationData("Training Hall", "Training Hall: First Way Down Chest"),
                LocationData("Training Hall", "Training Hall: Second Way Down Chest"),
                LocationData("Training Hall", "Training Hall: Third Way Down Chest"),
                LocationData("Training Hall", "Training Hall: Final Chest")])

    return location_table
