from typing import NamedTuple
#  IDs are matched to which internal Flag number the location uses
#  Because of this, they are asynchronous and out of order from what is expected
#  They are listed here in numerical order for clarity


class LocationInformation(NamedTuple):  # In-game information used to define each Location in the ROM.
    pointer: int
    file: str
    location_type: str


location_ids = {
    "Library: Past Wallman": 0x05,

    "Giant's Dwelling: Bottom Right Room Pickup": 0x07,
    "Minera Prison Island: Albus 1": 0x09,
    "Tristis Pass: Second Hill Pickup": 0x0A,
    "Barracks: Basement Entrance Pickup": 0x0B,
    "Ruvas Forest: First Room Freestanding": 0x0C,
    "Misty Forest Road: Right Big Room Pickup": 0x0D,
    "Giant's Dwelling: Albus 2": 0x0F,
    "Somnus Reef: Left Big Room Freestanding": 0x10,
    "Misty Forest Road: Paries Room Pickup": 0x11,

    "Somnus Reef: East Entrance Item": 0x13,

    "Minera Prison Island: Shaft Near Exit": 0x15,
    "Mystery Manor: Albus 3": 0x16,
    "Arms Depot: Upper Hall Item": 0x17,
    "Monastery: Central Freestading": 0x18,

    "Kalidus Channel: Depths Left Small Vertical Freestanding": 0x1B,

    "Arms Depot: Near Dead End Pickup": 0x1D,
    "Training Hall: Freestanding": 0x1E,
    "Monastery: Blocks Glyph": 0x1F,
    # 0x20 reserved for villagers in Torpor
    "Underground Labyrinth: Boulder Room Glyph": 0x21,
    "Tymeo Mountains: Wind Glyph": 0x22,
    "Underground Labyrinth: Fire Room": 0x24,
    "Tristis Pass: Frozen Waterfall Glyph": 0x26,
    "Minera Prison Island: Electric Room": 0x28,
    "Lighthouse: Searchlight Glyph": 0x29,
    "Mystery Manor: Dark Room Glyph": 0x2C,
    "Mechanical Tower: Generator Puzzle": 0x2D,
    "Library: Final Room Item": 0x31,  # todo. Set this flag
    "Mechanical Tower: Post-Boss": 0x32, 
    "Monastery: Magnet Room Free": 0x3A,  # todo. Set this flag.
    "Final Approach: Central Room Pickup": 0x3C,
    "Underground Labyrinth: Exit Item": 0x3D,
    "Mechanical Tower: Outer Item": 0x3E,
    "Kalidus Channel: Depths Left Tall Room Freestanding": 0x3F,
    "Oblivion Ridge: Pre-Boss Ledge": 0x40,
    "Tymeo Mountains: Left Hill Alcove Pickup": 0x41,
    "Underground Labyrinth: Secret Passge Pickup": 0x42,
    "Tristis Pass: Final Hill Underground Pickup": 0x43,
    "Wygol Village: Chest In Right House": 0x44,
    "Wygol Village: Left Chest": 0x45,
    "Wygol Village: Right Chest": 0x46,
    "Library: Hidden Room Free": 0x47,
    "Arms Depot: Post-Boss Item": 0x48, 
    "Kalidus Channel: Upper Exit": 0x49,
    "Kalidus Channel: Depths Left Tall Room Chest": 0x4A,
    "Kalidus Channel: Depths Left Chest": 0x4B,
    "Kalidus Channel: Depths Central": 0x4C,
    "Kalidus Channel: Depths Right Shaft Chest": 0x4D,
    "Kalidus Channel: Depths Right Center Chest": 0x4E,
    "Kalidus Channel: Lower Exit": 0x4F,
    "Kalidus Channel: Ship Room Lower Left Chest": 0x50,
    "Kalidus Channel: Ship Room Lower Center Chest": 0x51,
    "Kalidus Channel: Ship Room Lower Right Chest": 0x52,
    "Argila Swamp: Chest": 0x53,
    "Kalidus Channel: Deepest Room": 0x54,
    "Wygol Village: Grounded Chest": 0x55,
    "Monastery: Final Dead End": 0x56,
    "Monastery: Long Hall Chest": 0x57,
    "Minera Prison Island: Entrance Chest": 0x59,
    "Minera Prison Island: Upper Spear Hall": 0x5A,
    "Minera Prison Island: Lower Spear Hall Later Chest": 0x5B,
    "Minera Prison Island: Right Entry Shaft Chest": 0x5C,
    "Minera Prison Island: Top Room": 0x5D,
    "Minera Prison Island: Lowest Room": 0x5F,
    "Minera Prison Island: Lower Right Hall": 0x60,
    "Minera Prison Island: Right Central Room": 0x61,
    "Minera Prison Island: Right Spear Hall Chest": 0x62,
    "Minera Prison Island: Area Exit": 0x64,
    "Lighthouse: Exit Chest": 0x65,
    "Skeleton Cave: Final Room Chest": 0x66,
    "Ecclesia: Center Chest": 0x67,
    "Minera Prison Island: Exit Chest": 0x68,
    "Monastery: Second Big Room Chest": 0x69,
    "Lighthouse: Right Hall": 0x6A,
    "Lighthouse: Area Exit": 0x6B,
    "Tymeo Mountains: Side Room": 0x6C,
    "Tymeo Mountains: Bridge Chest": 0x6D,
    "Monastery: Big Room Under Shelf": 0x6E,
    "Minera Prison Island: Left Lower Hall": 0x6F,
    "Kalidus Channel: Right Depths Dead End Chest": 0x70,
    "Kalidus Channel: Right Exit Underwater Chest": 0x71,
    "Tymeo Mountains: Right Shaft Upper": 0x72,
    "Skeleton Cave: Dead End Upper": 0x73,
    "Somnus Reef: Right Side Isolated Room": 0x74,
    "Tristis Pass: Ice Cave Chest": 0x75,
    "Castle Entrance: Paries Wall": 0x76,
    "Library: First Chest": 0x77,
    "Mechanical Tower: Upper Magnets Wall Item": 0x78,
    "Barracks: Left Secret Room": 0x79,
    "Arms Depot: Left Room Chest": 0x7A,
    "Final Approach: Throne Right Chest": 0x7B,
    "Monastery: Pre-Boss Chest": 0x82,
    "Minera Prison Island: Lower Spear Hall Ending Chest": 0x83,
    "Kalidus Channel: Ship Room Center Left Chest": 0x84,
    "Kalidus Channel: Right Side Underwater Chest": 0x85,
    "Tymeo Mountains: Left Hill Alcove Chest": 0x86,
    "Skeleton Cave: Bottom Corner Far Chest": 0x87,
    "Somnus Reef: Left Open Room Lower Chest": 0x88,
    "Tristis Pass: Final Hill Alcove": 0x89,
    "Library: Pre-Boss Chest": 0x8A,
    "Underground Labyrinth: Second Shadow Room": 0x8B,
    "Barracks: Lower Right Square Chest": 0x8C,
    "Final Approach: Treasure Room Second From Right": 0x8D,
    "Kalidus Channel: Depths Secret Room Left Chest": 0x8E,
    "Final Approach: Central Room Right Chest": 0x8F,
    "Monastery: Hidden Room": 0x96,
    "Minera Prison Island: Right Vertical Chest": 0x97,
    "Kalidus Channel: Depths Right Left Chest": 0x98,
    "Kalidus Channel: First Room Underwater": 0x99,
    "Tymeo Mountains: Upper Hill Chest": 0x9A,
    "Skeleton Cave: First Room": 0x9B,
    "Somnus Reef: Lower Left Right Chest": 0x9C,
    "Tristis Pass: Waterfall Upper": 0x9D,
    "Castle Entrance: Entry Chest": 0x9E,
    "Underground Labyrinth: Dead End Chest": 0x9F,
    "Barracks: Left Corner": 0xA0,
    "Final Approach: Treasure Room Far Right": 0xA1,
    "Kalidus Channel: Depths Secret Room Right Chest": 0xA2,
    "Final Approach: Upper Isolated Chest": 0xA3,
    "Monastery: Big Room Ledge": 0xAA,
    "Kalidus Channel: Ship Room Hidden Chest": 0xAB,
    "Minera Prison Island: Hidden Room": 0xAC,
    "Tymeo Mountains: Upper Mountain Hidden Chest": 0xAE,
    "Misty Forest Road: Paries Room Chest": 0xAF,
    "Tristis Pass: Waterfall Hidden Chest": 0xB0,
    "Tristis Pass: Second Hill Lowest Chest": 0xB1,
    "Monastery: Blocks Reward Chest": 0xB2,
    "Oblivion Ridge: Final Room In Wall": 0xB3,
    "Mystery Manor: Dark Room Chest": 0xB4,
    # B5 is reserved for the TinMan chest on island
    "Library: Hidden Room Chest": 0xB6,
    "Mechanical Tower: Hidden Room": 0xB7,
    "Giant's Dwelling: Entrance Item": 0xB8,
    "Tymeo Mountains: Lower Mountain Lower Paries Chest": 0xB9,
    "Minera Prison Island: Top Room Chest": 0xBA,
    "Underground Labyrinth: Boulder Room Hidden Chest": 0xBB,
    "Barracks: Right Secret Room": 0xBC,
    "Final Approach: Treasure Room Far Left": 0xBD,
    "Final Approach: Final Room Hidden Item": 0xBE,
    "Final Approach: Final Stash Far Right": 0xBF,
    "Minera Prison Island: Right Vertical Hidden Item": 0xC0,
    "Kalidus Channel: Right Side Hidden Item": 0xC1,
    "Somnus Reef: Right Side Cave Hidden Item": 0xC2,
    "Ecclesia: Hidden Chest": 0xC3,
    "Ecclesia: Training Hall Chest": 0xC4,
    "Monastery: Albus Event": 0xC5,
    "Tristis Pass: First Alcove": 0xC6,
    "Tristis Pass: Bridge Chest": 0xC7,
    "Tristis Pass: Lower Hill Left": 0xC8,
    "Kalidus Channel: Depths First Room Chest": 0xC9,
    "Kalidus Channel: Hallway Item 1": 0xCA,
    "Kalidus Channel: Third Room Underwater": 0xCB,
    "Final Approach: Central Room Left Chest": 0xCC,
    "Barracks: Right Connector Hidden Chest": 0xCD,
    "Tymeo Mountains: First Room Hidden Chest": 0xCE,
    "Barracks: Lower Ramparts Hidden Chest": 0xCF,
    "Giant's Dwelling: Above Entrance": 0xD0,
    "Castle Entrance: Second Big Hidden Chest": 0xD1,
    "Underground Labyrinth: Hidden Room Chest": 0xD2,
    "Final Approach: Throne Left Chest": 0xD3,
    "Kalidus Channel: Depths Secret Room Center Chest": 0xD4,
    "Kalidus Channel: Hallway Item 2": 0xD5,
    "Final Approach: Lower Big Room Chest": 0xD6,
    "Giant's Dwelling: Area Exit": 0xD7,
    "Skeleton Cave: Second Hall Ledge": 0xD8,
    "Skeleton Cave: Dead End Lower": 0xD9,
    "Skeleton Cave: Center Chest": 0xDA,
    "Skeleton Cave: Bottom Corner Near Chest": 0xDB,
    "Skeleton Cave: Final Room Pickup": 0xDC,
    "Minera Prison Island: Shaft Chest": 0xDD,
    "Kalidus Channel: Depths Right Right Chest": 0xDE,
    "Large Cavern: Rest Room 1": 0xDF,
    "Large Cavern: Rest Room 2": 0xE0,
    "Large Cavern: Rest Room 3": 0xE1,
    "Large Cavern: Rest Room 4": 0xE2,
    "Large Cavern: Final Reward 1": 0xE3,
    "Underground Labyrinth: Area Exit": 0xE4,
    "Misty Forest Road: Right Big Room Ledge": 0xE6,
    "Monastery: Second Big Room Upper Ledge": 0xE7,
    "Monastery: Final Shaft Chest": 0xE8,
    "Oblivion Ridge: Post-Boss Ledge Item": 0xE9,
    "Kalidus Channel: Second Room Underwater": 0xEA,
    "Barracks: Lower Barracks Chest": 0xEB,
    "Misty Forest Road: Ledge Item": 0xEC,
    "Barracks: Connector Chest": 0xED,
    "Monastery: First Shaft": 0xEF,
    #  "Monastery: Final Shaft Uppper Hidden Item": 0xF2, I dont think this can spawn?
    "Castle Entrance: First Shaft Hidden Item": 0xF2,  # Same flag? Check on
    "Large Cavern: Final Reward 2": 0xF4,
    "Giant's Dwelling: First Corner": 0xF5,
    "Castle Entrance: Second Big Lower": 0xF6,
    "Tymeo Mountains: Cavern Near Breakable Wall": 0xF7,
    "Tymeo Mountains: Left Exit": 0xF8,
    "Misty Forest Road: Left Big Room Chest": 0xF9,
    "Misty Forest Road: Right Big Room Chest": 0xFA,
    "Tymeo Mountains: Right Hill Alcove Chest": 0xFB,
    "Library: Near End Hidden Item": 0xFC,
    "Mystery Manor: Top Left Hidden Item": 0xFD,
    "Forsaken Cloister: Central Shaft Hidden Item": 0xFE,
    "Arms Depot: Before Boss": 0xFF,
    "Tristis Pass: Lower Hill Right": 0x100,
    "Tristis Pass: Second Hill Lower Left": 0x101,
    "Tristis Pass: Second Hill Upper Chest": 0x102,
    "Tristis Pass: Third Hill Left": 0x103,
    "Tristis Pass: Third Hill Right": 0x104,
    "Monastery: Final Shaft Lower Hidden Item": 0x105,
    "Final Approach: Treasure Room Second From Left": 0x106,
    "Barracks: Top Right Square Hidden Item": 0x107,
    "Skeleton Cave: Bottom Corner In Wall": 0x108,
    "Underground Labyrinth: Connector Shaft Bottom Hidden": 0x109,
    "Misty Forest Road: Paries Room Hidden Item": 0x10A,
    "Mechanical Tower: Low Shaft Chest": 0x10B,
    "Tristis Pass: Waterfall Center": 0x010E,
    "Tymeo Mountains: Right Shaft Hidden Item": 0x113,
    "Kalidus Channel: Depths Rightmost Shaft Freestanding": 0x115,
    "Kalidus Channel: Ship Room Center Right Chest": 0x117,
    "Tristis Pass: Ice Exit Hidden Item": 0x119,
    "Final Approach: Final Stash Second From Right": 0x11A,
    "Oblivion Ridge: Post-Boss Wall Item": 0x11B,
    "Final Approach: Final Stash Second From Left": 0x11C,
    "Mystery Manor: Dead End Chest": 0x11D,
    "Final Approach: Final Stash Far Left": 0x11E,
    "Kalidus Channel: Depths Lower Left": 0x11F,
    "Monastery: Lower Dead End": 0x122,
    "Tymeo Mountains: Lower Mountain Upper Paries Chest": 0x123,
    "Underground Labyrinth: Detour Chest": 0x124,
    "Somnus Reef: Left Big Room Right Chest": 0x125,
    "Tristis Pass: Final Hill Tree Chest": 0x126,
    "Mechanical Tower: Upper Magnets Chest": 0x127,
    "Barracks: Lowest Room": 0x128,
    "Monastery: Magnet Room Top Chest": 0x129,
    "Minera Prison Island: Lower Spear Hall First Chest": 0x12A,
    "Giant's Dwelling: First Main Room Top": 0x12B,
    "Tymeo Mountains: Lower Mountain Free Chest": 0x12C,
    "Mechanical Tower: Center Room Chest": 0x12D,
    "Castle Entrance: Near Basement Center": 0x12E,
    "Somnus Reef: First Shaft Chest": 0x12F,
    "Somnus Reef: First Big Room Chest": 0x130,
    "Somnus Reef: Hidden Room": 0x131,
    "Somnus Reef: Left Big Room Left Chest": 0x132,
    "Somnus Reef: Left Big Room Center Chest": 0x133,
    "Somnus Reef: Left Big Room Upper Chest": 0x134,
    "Somnus Reef: Right Side Cave Item": 0x135,
    "Somnus Reef: Right Shaft": 0x136,
    "Somnus Reef: Area Exit": 0x137,
    "Somnus Reef: Lower Left Left Chest": 0x138,
    "Somnus Reef: Lower Right Left Chest": 0x139,
    "Somnus Reef: Lower Right Right Chest": 0x13A,
    "Somnus Reef: Exit Shaft Chest": 0x13B,
    "Tristis Pass: Area Exit": 0x13D,
    "Tristis Pass: Final Hill Underground Chest": 0x13E,
    "Tymeo Mountains: Hidden Room": 0x140,
    "Training Hall: Top Chest": 0x141,
    "Training Hall: First Way Down Chest": 0x142,
    "Training Hall: Second Way Down Chest": 0x143,
    "Training Hall: Third Way Down Chest": 0x144,
    "Training Hall: Final Chest": 0x145,
    "Ruvas Forest: Area Exit": 0x146,
    "Ruvas Forest: Left Chest": 0x147,
    "Ruvas Forest: Right Chest": 0x148,
    "Argila Swamp: Area Exit": 0x149,
    "Monastery: Final Shaft Free Item": 0x14A,
    "Minera Prison Island: Entrance Pickup": 0x14B,
    "Kalidus Channel: Ship Room Upper Left": 0x14C,
    "Kalidus Channel: Ship Room Upper Right": 0x14D,
    "Kalidus Channel: Ship Room Center Freestanding": 0x014E,
    "Minera Prison Island: Room Past Albus": 0x14F,
    "Somnus Reef: First Shaft Freestanding": 0x150,
    "Mystery Manor: Top Left Free Item": 0x151,
    "Mystery Manor: Top Right Free Item": 0x152,
    "Barracks: Lower Ramparts Pickup": 0x154,
    "Barracks: Upper Ramparts Left": 0x155,
    "Barracks: Upper Ramparts Right": 0x156,
    "Misty Forest Road: Area Exit": 0x159,
    "Tymeo Mountains: Upper Mountain Left Chest": 0x15A,
    "Tymeo Mountains: Upper Mountain Right Chest": 0x15B,
    "Tymeo Mountains: Right Exit": 0x15C,
    "Tymeo Mountains: Right Exit Item": 0x15D,
    "Tymeo Mountains: Cavern Chest": 0x15E,
    "Tymeo Mountains: Right Shaft Lower": 0x15F,
    "Tristis Pass: Waterfall Lower": 0x190,
    "Tristis Pass: Room Behind Waterfall": 0x191,
    "Castle Entrance: Past Paries Big Room Chest": 0x192,
    "Castle Entrance: Before Switch Wall": 0x193,
    "Underground Labyrinth: First Shadow Room": 0x195,
    "Mechanical Tower: First Gears Room Chest": 0x197,
    "Arms Depot: Right Room Chest": 0x198,
    "Wallman Glyph": 0x274
    # Mechnical tower room 8 s 6 has an oob chest?

    # Tin man chest?
    }


#  Chests; VarA = Item ID, VarB = location ID
#  Wooden Chests; Same as normal chests, however, their Object Type needs to be set to 16, and we need to write in their VarB Location ID
#  Freestanding; has special behavior on the item. Freestanding pickups use VarA as the Item ID, Subtype as Item Type, and VarB as the Location ID. Free Glyphs need to place statues.
#  Area Exits; VarA Item ID, varB Location ID
#  Event Glyphs; treated as glyphs no matter what the item is. VarB on the Event Actor is used as the Item ID.
#  Freestanding Glyph; The same as Freestanding, but we want to create it as a Glyph instead of a statue.
#  Event Chest; Hardcoded chest spawns. VarA of the parent Event Actor is used for the Item ID
location_data_table = {
    "Ecclesia: Center Chest": LocationInformation(0x022D3094, "overlay_42", "Chest"),
    "Ecclesia: Hidden Chest": LocationInformation(0x022D307C, "overlay_42", "Chest"),
    "Ecclesia: Training Hall Chest": LocationInformation(0x022D2FB0, "overlay_42", "Chest"),

    "Wygol Village: Chest In Right House": LocationInformation(0x022CC6F0, "overlay_40", "Wood Chest"),
    "Wygol Village: Left Chest": LocationInformation(0x022C7BD8, "overlay_41", "Wood Chest"),
    "Wygol Village: Right Chest": LocationInformation(0x022C7BE4, "overlay_41", "Wood Chest"),
    "Wygol Village: Grounded Chest": LocationInformation(0x022C7C80, "overlay_41", "Chest"),

    "Training Hall: Freestanding": LocationInformation(0x022CF8FC, "overlay_43", "Freestanding"),
    "Training Hall: Top Chest": LocationInformation(0x022CF914, "overlay_43", "Wood Chest"),
    "Training Hall: First Way Down Chest": LocationInformation(0x022CF920, "overlay_43", "Wood Chest"),
    "Training Hall: Second Way Down Chest": LocationInformation(0x022CF92C, "overlay_43", "Wood Chest"),
    "Training Hall: Third Way Down Chest": LocationInformation(0x022CF938, "overlay_43", "Wood Chest"),
    "Training Hall: Final Chest": LocationInformation(0x022CF908, "overlay_43", "Wood Chest"),

    "Ruvas Forest: First Room Freestanding": LocationInformation(0x022CD204, "overlay_44", "Freestanding"),
    "Ruvas Forest: Area Exit": LocationInformation(0x022CD468, "overlay_44", "Area Exit"),
    "Ruvas Forest: Left Chest": LocationInformation(0x022CD480, "overlay_44", "Wood Chest"),
    "Ruvas Forest: Right Chest": LocationInformation(0x022CD48C, "overlay_44", "Wood Chest"),

    "Argila Swamp: Chest": LocationInformation(0x022CA3A8, "overlay_45", "Wood Chest"),
    "Argila Swamp: Area Exit": LocationInformation(0x022CA1E0, "overlay_45", "Area Exit"),
    
    "Kalidus Channel: Depths Left Small Vertical Freestanding": LocationInformation(0x022E4624, "overlay_46", "Freestanding"),
    "Kalidus Channel: Depths Left Tall Room Freestanding": LocationInformation(0x022E44E0, "overlay_46", "Freestanding"),
    "Kalidus Channel: Upper Exit": LocationInformation(0x022E4420, "overlay_46", "Area Exit"),
    "Kalidus Channel: Depths Left Tall Room Chest": LocationInformation(0x022E44D4, "overlay_46", "Wood Chest"),
    "Kalidus Channel: Depths Left Chest": LocationInformation(0x022E45A0, "overlay_46", "Wood Chest"),
    "Kalidus Channel: Depths Central": LocationInformation(0x022E469C, "overlay_46", "Wood Chest"),
    "Kalidus Channel: Depths Right Shaft Chest": LocationInformation(0x022E46FC, "overlay_46", "Wood Chest"),
    "Kalidus Channel: Depths Right Center Chest": LocationInformation(0x022E4930, "overlay_46", "Wood Chest"),
    "Kalidus Channel: Lower Exit": LocationInformation(0x022CF4C0, "overlay_47", "Area Exit"),
    "Kalidus Channel: Ship Room Lower Left Chest": LocationInformation(0x022CF670, "overlay_47", "Wood Chest"),
    "Kalidus Channel: Ship Room Lower Center Chest": LocationInformation(0x022CF604, "overlay_47", "Wood Chest"),
    "Kalidus Channel: Ship Room Lower Right Chest": LocationInformation(0x022CF61C, "overlay_47", "Wood Chest"),
    "Kalidus Channel: Deepest Room": LocationInformation(0x022CF6D0, "overlay_47", "Freestanding"),
    "Kalidus Channel: Right Depths Dead End Chest": LocationInformation(0x022E4888, "overlay_46", "Chest"),
    "Kalidus Channel: Right Exit Underwater Chest": LocationInformation(0x022E43A8, "overlay_46", "Chest"),
    "Kalidus Channel: Ship Room Center Left Chest": LocationInformation(0x022CF5D4, "overlay_47", "Chest"),
    "Kalidus Channel: Right Side Underwater Chest": LocationInformation(0x022E41EC, "overlay_46", "Chest"),
    "Kalidus Channel: Depths Secret Room Left Chest": LocationInformation(0x022E47B0, "overlay_46", "Chest"),
    "Kalidus Channel: Depths Right Left Chest": LocationInformation(0x022E4924, "overlay_46", "Chest"),
    "Kalidus Channel: First Room Underwater": LocationInformation(0x022E3E5C, "overlay_46", "Chest"),
    "Kalidus Channel: Depths Secret Room Right Chest": LocationInformation(0x022E47BC, "overlay_46", "Chest"),
    "Kalidus Channel: Ship Room Hidden Chest": LocationInformation(0x022CF5BC, "overlay_47", "Chest"),
    "Kalidus Channel: Right Side Hidden Item": LocationInformation(0x022E421C, "overlay_46", "Freestanding Glyph"),
    "Kalidus Channel: Depths First Room Chest": LocationInformation(0x022CF70C, "overlay_46", "Chest"),
    "Kalidus Channel: Hallway Item 1": LocationInformation(0x022E4174, "overlay_46", "Freestanding"),
    "Kalidus Channel: Third Room Underwater": LocationInformation(0x022E4048, "overlay_46", "Wood Chest"),
    "Kalidus Channel: Depths Secret Room Center Chest": LocationInformation(0x022E47A4, "overlay_46", "Chest"),
    "Kalidus Channel: Hallway Item 2": LocationInformation(0x022E4180, "overlay_46", "Freestanding"),
    "Kalidus Channel: Depths Right Right Chest": LocationInformation(0x022E493C, "overlay_46", "Chest"),
    "Kalidus Channel: Second Room Underwater": LocationInformation(0x022E3F10, "overlay_46", "Chest"),
    "Kalidus Channel: Depths Rightmost Shaft Freestanding": LocationInformation(0x022E4828, "overlay_46", "Freestanding"),
    "Kalidus Channel: Ship Room Center Right Chest": LocationInformation(0x022CF5C8, "overlay_47", "Chest"),
    "Kalidus Channel: Depths Lower Left": LocationInformation(0x022CF4E4, "overlay_47", "Chest"),
    "Kalidus Channel: Ship Room Upper Left": LocationInformation(0x022CF5E0, "overlay_47", "Freestanding"),
    "Kalidus Channel: Ship Room Upper Right": LocationInformation(0x022CF5EC, "overlay_47", "Freestanding"),
    "Kalidus Channel: Ship Room Center Freestanding": LocationInformation(0x022CF5F8, "overlay_47", "Freestanding"),

    "Somnus Reef: Left Big Room Freestanding": LocationInformation(0x022DD1FC, "overlay_48", "Freestanding"),
    "Somnus Reef: East Entrance Item": LocationInformation(0x022DD37C, "overlay_48", "Freestanding"),
    "Somnus Reef: Right Side Isolated Room": LocationInformation(0x022DD52C, "overlay_48", "Chest"),
    "Somnus Reef: Left Open Room Lower Chest": LocationInformation(0x022DD208, "overlay_48", "Chest"),
    "Somnus Reef: Lower Left Right Chest": LocationInformation(0x022DD49C, "overlay_48", "Chest"),
    "Somnus Reef: Right Side Cave Hidden Item": LocationInformation(0x022DD274, "overlay_48", "Freestanding Glyph"),
    "Somnus Reef: Left Big Room Right Chest": LocationInformation(0x022DD148, "overlay_48", "Chest"),
    "Somnus Reef: First Shaft Chest": LocationInformation(0x022DD07C, "overlay_48", "Wood Chest"),
    "Somnus Reef: First Big Room Chest": LocationInformation(0x022DD0D0, "overlay_48", "Wood Chest"),
    "Somnus Reef: Hidden Room": LocationInformation(0x022DD124, "overlay_48", "Freestanding"),
    "Somnus Reef: Left Big Room Left Chest": LocationInformation(0x022DD154, "overlay_48", "Wood Chest"),
    "Somnus Reef: Left Big Room Center Chest": LocationInformation(0x022DD160, "overlay_48", "Wood Chest"),
    "Somnus Reef: Left Big Room Upper Chest": LocationInformation(0x022DD214, "overlay_48", "Wood Chest"),
    "Somnus Reef: Right Side Cave Item": LocationInformation(0x022DD280, "overlay_48", "Freestanding"),
    "Somnus Reef: Right Shaft": LocationInformation(0x022DD580, "overlay_48", "Wood Chest"),
    "Somnus Reef: Area Exit": LocationInformation(0x022DD3E8, "overlay_48", "Area Exit"),
    "Somnus Reef: Lower Left Left Chest": LocationInformation(0x022DD490, "overlay_48", "Wood Chest"),
    "Somnus Reef: Lower Right Left Chest": LocationInformation(0x022DD4D8, "overlay_48", "Wood Chest"),
    "Somnus Reef: Lower Right Right Chest": LocationInformation(0x022DD4E4, "overlay_48", "Wood Chest"),
    "Somnus Reef: Exit Shaft Chest": LocationInformation(0x022DD334, "overlay_48", "Wood Chest"),
    "Somnus Reef: First Shaft Freestanding": LocationInformation(0x022DD088, "overlay_48", "Freestanding"),

    "Minera Prison Island: Albus 1": LocationInformation(0x022CF55C, "overlay_51", "Event Glyph"),
    "Minera Prison Island: Shaft Near Exit": LocationInformation(0x022CCD40, "overlay_52", "Freestanding"),
    "Minera Prison Island: Electric Room": LocationInformation(0x022CCD10, "overlay_52", "Event Glyph"),
    "Minera Prison Island: Entrance Chest": LocationInformation(0x022CE618, "overlay_50", "Wood Chest"),
    "Minera Prison Island: Upper Spear Hall": LocationInformation(0x022CE660, "overlay_50", "Wood Chest"),
    "Minera Prison Island: Lower Spear Hall Later Chest": LocationInformation(0x022CE708, "overlay_50", "Wood Chest"),
    "Minera Prison Island: Right Entry Shaft Chest": LocationInformation(0x022CE7F8, "overlay_50", "Wood Chest"),
    "Minera Prison Island: Top Room": LocationInformation(0x022CF3C4, "overlay_51", "Freestanding"),
    "Minera Prison Island: Lowest Room": LocationInformation(0x022CF5F8, "overlay_51", "Freestanding"),
    "Minera Prison Island: Lower Right Hall": LocationInformation(0x022CF628, "overlay_51", "Wood Chest"),
    "Minera Prison Island: Right Central Room": LocationInformation(0x022CF670, "overlay_51", "Wood Chest"),
    "Minera Prison Island: Right Spear Hall Chest": LocationInformation(0x022CCC20, "overlay_52", "Wood Chest"),
    "Minera Prison Island: Exit Chest": LocationInformation(0x022CCDD0, "overlay_52", "Chest"),
    "Minera Prison Island: Left Lower Hall": LocationInformation(0x022CF460, "overlay_51", "Chest"),
    "Minera Prison Island: Lower Spear Hall Ending Chest": LocationInformation(0x022CE6FC, "overlay_50", "Chest"),
    "Minera Prison Island: Right Vertical Chest": LocationInformation(0x022CCBC0, "overlay_52", "Chest"),
    "Minera Prison Island: Hidden Room": LocationInformation(0x022CE7C8, "overlay_50", "Chest"),
    "Minera Prison Island: Top Room Chest": LocationInformation(0x022CF3B8, "overlay_51", "Chest"),
    "Minera Prison Island: Right Vertical Hidden Item": LocationInformation(0x022CCBD8, "overlay_52", "Freestanding Glyph"),
    "Minera Prison Island: Shaft Chest": LocationInformation(0x022CF3E8, "overlay_51", "Chest"),
    "Minera Prison Island: Lower Spear Hall First Chest": LocationInformation(0x022CE714, "overlay_50", "Chest"),
    "Minera Prison Island: Entrance Pickup": LocationInformation(0x022CE624, "overlay_50", "Freestanding"),
    "Minera Prison Island: Room Past Albus": LocationInformation(0x022CF58C, "overlay_51", "Freestanding"),
    "Minera Prison Island: Area Exit": LocationInformation(0x022CCDB8, "overlay_52", "Area Exit"),

    "Lighthouse: Searchlight Glyph": LocationInformation(0x022CD790, "overlay_53", "Event Glyph"),
    "Lighthouse: Exit Chest": LocationInformation(0x022CD850, "overlay_53", "Chest"),
    "Lighthouse: Right Hall": LocationInformation(0x022CD82C, "overlay_53", "Freestanding"),
    "Lighthouse: Area Exit": LocationInformation(0x022CD844, "overlay_53", "Area Exit"),

    "Tymeo Mountains: Wind Glyph": LocationInformation(0x022CF928, "overlay_55", "Event Glyph"),
    "Tymeo Mountains: Left Hill Alcove Pickup": LocationInformation(0x022DAD74, "overlay_54", "Freestanding"),
    "Tymeo Mountains: Side Room": LocationInformation(0x022DAC3C, "overlay_54", "Freestanding"),
    "Tymeo Mountains: Bridge Chest": LocationInformation(0x022DAC6C, "overlay_54", "Wood Chest"),
    "Tymeo Mountains: Right Shaft Upper": LocationInformation(0x022CF8BC, "overlay_55", "Chest"),
    "Tymeo Mountains: Left Hill Alcove Chest": LocationInformation(0x022DAD80, "overlay_54", "Chest"),
    "Tymeo Mountains: Upper Hill Chest": LocationInformation(0x022DB110, "overlay_54", "Chest"),
    "Tymeo Mountains: Upper Mountain Hidden Chest": LocationInformation(0x022DB188, "overlay_54", "Chest"),
    "Tymeo Mountains: Lower Mountain Lower Paries Chest": LocationInformation(0x022DAF3C, "overlay_54", "Chest"),
    "Tymeo Mountains: First Room Hidden Chest": LocationInformation(0x022DAB58, "overlay_54", "Chest"),
    "Tymeo Mountains: Cavern Near Breakable Wall": LocationInformation(0x022CF640, "overlay_55", "Freestanding"),
    "Tymeo Mountains: Left Exit": LocationInformation(0x022DAE40, "overlay_54", "Area Exit"),
    "Tymeo Mountains: Right Hill Alcove Chest": LocationInformation(0x022DAE88, "overlay_54", "Wood Chest"),
    "Tymeo Mountains: Right Shaft Hidden Item": LocationInformation(0x022CF8E0, "overlay_55", "Freestanding Glyph"),
    "Tymeo Mountains: Lower Mountain Upper Paries Chest": LocationInformation(0x022DAF30, "overlay_54", "Chest"),
    "Tymeo Mountains: Lower Mountain Free Chest": LocationInformation(0x022DAF24, "overlay_54", "Chest"),
    "Tymeo Mountains: Hidden Room": LocationInformation(0x022CF73C, "overlay_55", "Chest"),
    "Tymeo Mountains: Upper Mountain Left Chest": LocationInformation(0x022DB194, "overlay_54", "Wood Chest"),
    "Tymeo Mountains: Upper Mountain Right Chest": LocationInformation(0x022DB1A0, "overlay_54", "Wood Chest"),
    "Tymeo Mountains: Right Exit": LocationInformation(0x022DB2A8, "overlay_54", "Area Exit"),
    "Tymeo Mountains: Right Exit Item": LocationInformation(0x022DB2B4, "overlay_54", "Freestanding"),
    "Tymeo Mountains: Cavern Chest": LocationInformation(0x022CF580, "overlay_55", "Wood Chest"),
    "Tymeo Mountains: Right Shaft Lower": LocationInformation(0x022CF8C8, "overlay_55", "Wood Chest"),

    "Tristis Pass: Frozen Waterfall Glyph": LocationInformation(0x022D0EB8, "overlay_57", "Event Glyph"),
    "Tristis Pass: Final Hill Underground Pickup": LocationInformation(0x022D60E8, "overlay_56", "Freestanding"),
    "Tristis Pass: Ice Cave Chest": LocationInformation(0x022D1020, "overlay_57", "Chest"),
    "Tristis Pass: Final Hill Alcove": LocationInformation(0x022D6100, "overlay_56", "Chest"),
    "Tristis Pass: Waterfall Upper": LocationInformation(0x022D0EE8, "overlay_57", "Chest"),
    "Tristis Pass: Waterfall Hidden Chest": LocationInformation(0x022D0EDC, "overlay_57", "Chest"),
    "Tristis Pass: Second Hill Lowest Chest": LocationInformation(0x022D5F98, "overlay_56", "Chest"),
    "Tristis Pass: First Alcove": LocationInformation(0x022D5C68, "overlay_56", "Wood Chest"),
    "Tristis Pass: Bridge Chest": LocationInformation(0x022D5DDC, "overlay_56", "Wood Chest"),
    "Tristis Pass: Lower Hill Left": LocationInformation(0x022D5EFC, "overlay_56", "Wood Chest"),
    "Tristis Pass: Lower Hill Right": LocationInformation(0x022D5EF0, "overlay_56", "Wood Chest"),
    "Tristis Pass: Second Hill Lower Left": LocationInformation(0x022D5FB0, "overlay_56", "Wood Chest"),
    "Tristis Pass: Second Hill Upper Chest": LocationInformation(0x022D5FA4, "overlay_56", "Wood Chest"),
    "Tristis Pass: Third Hill Left": LocationInformation(0x022D6070, "overlay_56", "Wood Chest"),
    "Tristis Pass: Third Hill Right": LocationInformation(0x022D6064, "overlay_56", "Wood Chest"),
    "Tristis Pass: Waterfall Center": LocationInformation(0x022D0F00, "overlay_57", "Freestanding"),  # You can probably absorb this from behind the frozen waterfall if it's a villager. Hmm...
    "Tristis Pass: Ice Exit Hidden Item": LocationInformation(0x022D10A4, "overlay_57", "Freestanding Glyph"),
    "Tristis Pass: Final Hill Tree Chest": LocationInformation(0x022D60F4, "overlay_56", "Chest"),
    "Tristis Pass: Area Exit": LocationInformation(0x022D61D8, "overlay_56", "Area Exit"),
    "Tristis Pass: Final Hill Underground Chest": LocationInformation(0x022D610C, "overlay_56", "Wood Chest"),
    "Tristis Pass: Waterfall Lower": LocationInformation(0x022D0EF4, "overlay_57", "Wood Chest"),
    "Tristis Pass: Room Behind Waterfall": LocationInformation(0x022D0F48, "overlay_57", "Freestanding"),
    "Tristis Pass: Second Hill Pickup": LocationInformation(0x022D5F8C, "overlay_56", "Freestanding"),

    "Large Cavern: Rest Room 1": LocationInformation(0x022CA554, "overlay_58", "Wood Chest"),
    "Large Cavern: Rest Room 2": LocationInformation(0x022CA5F0, "overlay_58", "Wood Chest"),
    "Large Cavern: Rest Room 3": LocationInformation(0x022CA6A4, "overlay_58", "Wood Chest"),
    "Large Cavern: Rest Room 4": LocationInformation(0x022CA794, "overlay_58", "Wood Chest"),
    "Large Cavern: Final Reward 1": LocationInformation(0x022CA800, "overlay_58", "Wood Chest"),
    "Large Cavern: Final Reward 2": LocationInformation(0x022CA7F4, "overlay_58", "Wood Chest"),

    "Giant's Dwelling: Bottom Right Room Pickup": LocationInformation(0x022D3510, "overlay_59", "Freestanding"),
    "Giant's Dwelling: Albus 2": LocationInformation(0x022D3564, "overlay_59", "Event Glyph"),
    "Giant's Dwelling: Entrance Item": LocationInformation(0x022D3450, "overlay_59", "Freestanding Glyph"),
    "Giant's Dwelling: Above Entrance": LocationInformation(0x022D3624, "overlay_59", "Chest"),
    "Giant's Dwelling: Area Exit": LocationInformation(0x022D3588, "overlay_59", "Area Exit"),
    "Giant's Dwelling: First Corner": LocationInformation(0x022D34F8, "overlay_59", "Freestanding"),
    "Giant's Dwelling: First Main Room Top": LocationInformation(0x022D3480, "overlay_59", "Chest"),

    "Mystery Manor: Albus 3": LocationInformation(0x022D2CF8, "overlay_60", "Event Glyph"),
    "Mystery Manor: Dark Room Glyph": LocationInformation(0x022D2920, "overlay_60", "Event Glyph"),
    "Mystery Manor: Dark Room Chest": LocationInformation(0x022D2920, "overlay_60", "Event Chest"),
    "Mystery Manor: Top Left Hidden Item": LocationInformation(0x022D2A88, "overlay_60", "Freestanding Glyph"),
    "Mystery Manor: Dead End Chest": LocationInformation(0x022D2C68, "overlay_60", "Chest"),
    "Mystery Manor: Top Left Free Item": LocationInformation(0x022D2A94, "overlay_60", "Freestanding"),
    "Mystery Manor: Top Right Free Item": LocationInformation(0x022D2C2C, "overlay_60", "Freestanding"),

    "Misty Forest Road: Right Big Room Pickup": LocationInformation(0x022D0B48, "overlay_61", "Freestanding"),
    "Misty Forest Road: Paries Room Pickup": LocationInformation(0x022D0AC4, "overlay_61", "Freestanding"),
    "Misty Forest Road: Paries Room Chest": LocationInformation(0x022D0AD0, "overlay_61", "Chest"),
    "Misty Forest Road: Right Big Room Ledge": LocationInformation(0x022D0B60, "overlay_61", "Freestanding"),
    "Misty Forest Road: Ledge Item": LocationInformation(0x022D0A64, "overlay_61", "Freestanding"),
    "Misty Forest Road: Left Big Room Chest": LocationInformation(0x022D0A58, "overlay_61", "Wood Chest"),
    "Misty Forest Road: Right Big Room Chest": LocationInformation(0x022D0B54, "overlay_61", "Wood Chest"),
    "Misty Forest Road: Paries Room Hidden Item": LocationInformation(0x022D0AE8, "overlay_61", "Freestanding Glyph"),
    "Misty Forest Road: Area Exit": LocationInformation(0x022D09E0, "overlay_61", "Area Exit"),
    
    "Oblivion Ridge: Final Room In Wall": LocationInformation(0x022C5F98, "overlay_62", "Freestanding Glyph"),
    "Oblivion Ridge: Post-Boss Ledge Item": LocationInformation(0x022D050C, "overlay_63", "Freestanding"),
    "Oblivion Ridge: Post-Boss Wall Item": LocationInformation(0x022D0500, "overlay_63", "Freestanding Glyph"),
    "Oblivion Ridge: Pre-Boss Ledge": LocationInformation(0x022D05A8, "overlay_63", "Freestanding"),
    
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
    "Dummy": LocationInformation(0x00000000, "dummy", "dummy"),
}


def get_location_groups():
    location_groups = {
        "Wygol Village": set(),
        "Ecclesia": set(),
        "Training Hall": set(),
        "Ruvas Forest": set(),
        "Argila Swamp": set(),
        "Kalidus Channel": set(),
        "Somnus Reef": set(),
        "Minera Prison Island": set(),
        "Lighthouse": set(),
        "Tymeo Mountains": set(),
        "Tristis Pass": set(),
        "Large Cavern": set(),
        "Giant's Dwelling": set(),
        "Mystery Manor": set(),
        "Misty Forest Road": set(),
        "Oblivion Ridge": set(),
        "Skeleton Cave": set(),
        "Monastery": set(),
        "Castle Entrance": set(),
        "Underground Labyrinth": set(),
        "Library": set(),
        "Barracks": set(),
        "Mechanical Tower": set(),
        "Arms Depot": set(),
        "Forsaken Cloister": set(),
        "Final Approach": set(),
        "Enemy Glyphs": set()
    }
    for location in location_ids:
        group = location.split(":")[0]
        if group not in location_groups:
            location_groups["Enemy Glyphs"].add(location)
        else:
            location_groups[group].add(location)
    return location_groups
