enemy_species = [
    "Cultist",
    "Spook",
    "Frog",
    "Buffalo",
    "Antoid",
    "Evil Mushroom",
    "Fungus",
    "Mobile Sprout",
    "Fire Plug",
    "Record",
    "Power Robot",
    "Reactor Robot",
    "Hieroglyph",
    "Asp Hieroglyph",
    "Swoosh",
    "Menace",
    "Spirit",
    "Elemental",
    "Party Man",
    "Reveler",
    "Local Guy",
    "Hippie",
    "Bear",
    "Bear Seven",
    "Moldyman",
    "Mite",
    "Lady",
    "Ant",
    "Coffee Cup",
    "Dice",
    "Little Pile",
    "Kraken",
    "Robo",
    "Cop",
    "Coil Snake",
    "Batty",
    "Roach",
    "Sign",
    "Shambler",
    "Punk",
    "Skater",
    "Musica",
    "Skelpion",
    "Starman",
    "Sphere",
    "Royal Guard",
    "General",
    "Zombie",
    "Possessor",
    "Dog",
    "Oak",
    "Octobot",
    "Duck",
    "Clock",
    "Wolf",
    "Musica",
    "Pile of Puke",
    "Kiss of Death",
    "Eel",
    "Tangoo",
    "Arachnid",
    "Demon",
    "Fobby",
    "Foppy",
    "Booka",
    "Mook",
    "Ghost",
    "Slug",
    "Mouse",
    "Bomb",
    "Tom",
    "Sam",
    "Fish",
    "Fish's Brother",
    "Kid",
    "Boy",
    "Art",
    "Shattered Man",
    "Orb",
    "Man Junior",
    "Li'l UFO",
    "UFO",
    "Guy",
    "Taxi",
    "Molecule",
    "Protoplasm",
    "Robot",
    "Psycho",
    "Goat",
    "Mole",
    "Flame",
    "Petunia",
    "Ranboob",
    "Noose",
    "Pump",
    "Crocodile",
    "Fly",
    "Crow",
    "Caterpillar",
    "Eye",
    "Worm",
    "Statue",
    "Rat of Doom",
    "Specter",
    "Chief",
    "Bot",
    "Gangster",
    "Storm",
    "Dino",
    "Painter",
    "Burglar"
]

enemy_adjectives = [
    "",
    "Insane ",
    "Dept. Store ",
    "Armored ",
    "Bad ",
    "Black ",
    "Red ",
    "Ramblin' ",
    "Struttin' ",
    "Tough ",
    "Enraged ",
    "Mystical ",
    "Atomic ",
    "Nuclear ",
    "Guardian ",
    "Lethal ",
    "Electro ",
    "Conducting ",
    "Evil ",
    "Annoying Old ",
    "Annoying ",
    "Unassuming ",
    "New Age Retro ",
    "Carbon ",
    "Mighty ",
    "Putrid ",
    "Thunder ",
    "Cranky ",
    "Extra Cranky ",
    "Titanic ",
    "Gigantic ",
    "Mondo ",
    "Scalding ",
    "Loaded ",
    "Slimy ",
    "Even Slimier ",
    "Bionic ",
    "Spinning ",
    "Whirling ",
    "Hyper Spinning ",
    "Coil ",
    "Thirsty ",
    "Mr. ",
    "Elder ",
    "Violent ",
    "Filthy Attack ",
    "Crazed ",
    "Wooly ",
    "Wild 'n Wooly ",
    "Skate ",
    "Dread ",
    "Super ",
    "Ghost of ",
    "Smilin' ",
    "Uncontrollable ",
    "Petrified ",
    "Urban ",
    "Zombie ",
    "Crooked ",
    "Over Zealous ",
    "Territorial ",
    "Hostile Elder ",
    "Diamond ",
    "Marauder ",
    "Military ",
    "Mechanical ",
    "Ultimate ",
    "Mad ",
    "Dali's ",
    "Trillionage ",
    "Desert ",
    "Big ",
    "French ",
    "Zap ",
    "Squatter ",
    "Crested ",
    "Great Crested ",
    "Lesser ",
    "Smelly ",
    "Stinky ",
    "Attack ",
    "Pit Bull ",
    "Rowdy ",
    "Deadly ",
    "Care Free ",
    "Electro ",
    "Handsome ",
    "Manly ",
    "Runaway ",
    "Trick or Trick ",
    "Cave ",
    "Abstract ",
    "Shattered ",
    "Fierce ",
    "Ego ",
    "Yes ",
    "Cute ",
    "Beautiful ",
    "Pogo ",
    "Tough ",
    "Worthless ",
    "Sentry ",
    "Heavily Armed ",
    "Psychic ",
    "Major Psychic ",
    "Gruff ",
    "Clumsy ",
    "Soul Consuming ",
    "Demonic ",
    "High-class ",
    "Robo-",
    "Plain ",
    "Strong ",
    "Hard ",
    "No Good ",
    "Mostly Bad ",
    "Spiteful ",
    "Farm ",
    "Criminal ",
    "Master Criminal ",
    "Final ",
    "Plague ",
    "Disingenuous ",
    "Disgusting ",
    "Inadequate ",
    "Dr. ",
    "Electronic ",
    "Jealous ",
    "Bald ",
    "Baked ",
    "Magic ",
    "Polar ",
    "Depressed ",
    "Clean ",
    "Elderly ",
    "Banned ",
    "Grumpy ",
    "Whelmed ",
    "Loud ",
    "Mushy ",
    "Randomized ",
    "Homesick ",
    "Mecha "
]

battle_sprites = {
    "Antoid": [0x01],
    "Dog": [0x02, 0x42],
    "Frog": [0x03],
    "Sphere": [0x04],
    "Evil Mushroom": [0x05],
    "Bomb": [0x06],
    "Octobot": [0x07],
    "Musica": [0x08],
    "Ranboob": [0x09],
    "Moldyman": [0x0A],
    "Fungus": [0x0B],
    "Booka": [0x0C],
    "Shambler": [0x0D],
    "Dino": [0x0E, 0x41],
    "Art": [0x0F],
    "Crow": [0x10],
    "Fobby": [0x11],
    "Foppy": [0x11],
    "Duck": [0x12],
    "Batty": [0x13],
    "Mouse": [0x14],
    "Kiss of Death": [0x15],
    "Swoosh": [0x16],
    "Petunia": [0x17],
    "Flame": [0x18],
    "Coil Snake": [0x19],
    "Sign": [0x1A],
    "Kid": [0x1B],
    "Sam": [0x1C],
    "Tom": [0x1C],
    "Psycho": [0x1D],
    "Mite": [0x1E],
    "Fish": [0x1F],
    "Fish's Brother": [0x1F],
    "Burglar": [0x20],
    "Painter": [0x21],
    "Party Man": [0x22],
    "Reveler": [0x22],
    "Local Guy": [0x23],
    "Menace": [0x24],
    "Spirit": [0x24],
    "Gangster": [0x25],
    "Guy": [0x26],
    "Storm": [0x27],
    #Carbon
    "Kraken": [0x29],
    #Pokey
    "Li'l UFO": [0x2B],
    "Coffee Cup": [0x2C],
    "Molecule": [0x2D],
    "Record": [0x2E],
    "Slug": [0x2F],
    "Elemental": [0x30],
    "UFO": [0x31],
    "Possessor": [0x32],
    "Cop": [0x33],
    "Robo": [0x34],
    "Ghost": [0x35],
    "Robot": [0x36],
    "Starman": [0x37, 0x6A],
    "Shattered Man": [0x38],
    "Specter": [0x39],
    "Dice": [0x3A],
    "Fire Plug": [0x3B],
    "Protoplasm": [0x3C],
    "Mook": [0x3D],
    "Spook": [0x3D],
    "Pump": [0x3E],
    "Cultist": [0x3F],
    "Man Junior": [0x40],
    "Asp Hieroglyph": [0x43],
    "Eel": [0x44],
    "Chief": [0x45],
    "Hieroglyph": [0x46],
    "Bot": [0x47],
    "Zombie": [0x48],
    "Ant": [0x49],
    "Buffalo": [0x4A],
    "Rat of Doom": [0x4B],
    #Diamond Dog
    "Arachnid": [0x4D],
    "Mole": [0x4E],
    "Statue": [0x4F],
    "Roach": [0x50],
    "Noose": [0x51],
    "Tangoo": [0x52],
    #MondoMole
    "Crocodile": [0x54],
    "Taxi": [0x55],
    "Demon": [0x56],
    "General": [0x57],
    "Royal Guard": [0x57],
    #Trillionage sprout
    "Fly": [0x59],
    "Mobile Sprout": [0x5A],
    "Little Pile": [0x5B],
    "Skelpion": [0x5C],
    "Clock": [0x5D],
    "Goat": [0x5E],
    "Oak": [0x5F],
    "Punk": [0x60],
    #Frankystein
    "Pile of Puke": [0x62],
    "Lady": [0x63],
    "Skater": [0x64],
    "Boy": [0x65],
    "Orb": [0x66],
    "Wolf": [0x67],
    "Bear": [0x68],
    "Bear Seven": [0x68],
    "Power Robot": [0x69],
    "Reactor Robot": [0x69],
    "Hippie": [0x6B],
    "Worm": [0x6D],
    "Caterpillar": [0x6D],
    "Eye": [0x6E]


}

field_sprites = {

}

excluded_enemies = [
    "Dept. Store Spook",
    "Frank",
    "Frankystein Mark II",
    "Titanic Ant",
    "Mondo Mole",
    "Mr. Carpainter",
    "Boogey Tent",
    "Mini Barf",
    "Master Belch",
    "Guardian Digger",
    "Evil Mani-Mani",
    "Shrooom!",
    "Kraken",
    "Plague Rat of Doom",
    "Thunder and Storm",
    "Guardian General",
    "Master Barf",
    "Starman Deluxe",
    "Carbon Dog",
    "Diamond Dog",
    "Ness's Nightmare",
    "Giygas (2)",
    "Giygas (3)",
    "Giygas (4)",
    "Giygas (5)",
    "Captain Strong",
    "Giygas (6)",
    "Clumsy Robot (3)",
    "Tiny Li'l Ghost",
    "Buzz Buzz",
    "Starman Junior",
    "Heavily Armed Pokey",
    "Dept. Store Spook (2)",
    "Ness's Nightmare (2)",
    "Mr. Carpainter (2)",
    "Carbon Dog (2)",
    "Titanic Ant (2)",
    "Master Belch (2)",
    "Master Barf (2)",
    "Starman Deluxe (2)",
    "Shrooom! (2)",
    "Plague Rat of Doom (2)",
    "Mondo Mole (2)",
    "Guardian Digger (2)",
    "Kraken (2)",
    "Clumsy Robot",
    "Trillionage Sprout",
    "Electro Specter",
    "Everdred"
]