from typing import Dict, Set, NamedTuple, Optional
from BaseClasses import ItemClassification

class ItemData(NamedTuple):
    category: str
    code: Optional[int]
    classification: ItemClassification
    amount: Optional[int] = 1

item_table: Dict[str, ItemData] = {
    "$1": ItemData("Money", 0x100, ItemClassification.filler, 0),
    "$10": ItemData("Money", 0x101, ItemClassification.filler, 0),
    "$50": ItemData("Money", 0x102, ItemClassification.filler, 0),
    "$100": ItemData("Money", 0x103, ItemClassification.filler, 0),
    "$500": ItemData("Money", 0x104, ItemClassification.filler, 0),
    "$1000": ItemData("Money", 0x105, ItemClassification.filler, 0),
    "$2000": ItemData("Money", 0x106, ItemClassification.filler, 0),

    "Potion": ItemData("Consumables", 0x0200, ItemClassification.filler, 0),
    "High Potion": ItemData("Consumables", 0x0201, ItemClassification.filler, 0),
    "Super Potion": ItemData("Consumables", 0x0202, ItemClassification.filler, 0),
    "Tonic": ItemData("Consumables", 0x0203, ItemClassification.filler, 0),
    "High Tonic": ItemData("Consumables", 0x0204, ItemClassification.filler, 0),
    "Super Tonic": ItemData("Consumables", 0x0205, ItemClassification.filler, 0),
    "Anti-Venom": ItemData("Consumables", 0x0206, ItemClassification.filler, 0),
    "Uncurse Potion": ItemData("Consumables", 0x0207, ItemClassification.filler, 0),
    "HP Max up": ItemData("Upgrades", 0x0208, ItemClassification.useful, ???),
    "MP Max up": ItemData("Upgrades", 0x0209, ItemClassification.useful, ???),
    "Beef Jerky": ItemData("Consumables", 0x020A, ItemClassification.filler, 0),
    "Tasty Meat": ItemData("Consumables", 0x020B, ItemClassification.filler, 0),
    "New York Steak": ItemData("Consumables", 0x020C, ItemClassification.filler, 0),
    "Rice Ball": ItemData("Consumables", 0x020D, ItemClassification.filler, 0),
    "Mushroom": ItemData("Consumables", 0x020E, ItemClassification.filler, 0),
    "Corn Soup": ItemData("Consumables", 0x020F, ItemClassification.filler, 0),
    "Curry": ItemData("Consumables", 0x0210, ItemClassification.filler, 0),
    "Ramen Noodles": ItemData("Consumables", 0x0211, ItemClassification.filler, 0),
    "Mint Sundae": ItemData("Consumables", 0x0212, ItemClassification.filler, 0),
    "Cream Puff": ItemData("Consumables", 0x0213, ItemClassification.filler, 0),
    "Milk": ItemData("Consumables", 0x0214, ItemClassification.filler, 0),
    "Coffee": ItemData("Consumables", 0x0215, ItemClassification.filler, 0),
    "Tea": ItemData("Consumables", 0x0216, ItemClassification.filler, 0),
    "Pudding": ItemData("Consumables", 0x0217, ItemClassification.filler, 0),
    "Strawberry": ItemData("Consumables", 0x0218, ItemClassification.filler, 0),
    "Melon": ItemData("Consumables", 0x0219, ItemClassification.filler, 0),
    "Grapes": ItemData("Consumables", 0x021A, ItemClassification.filler, 0),
    "Hamburger": ItemData("Consumables", 0x021B, ItemClassification.filler, 0),
    "Fried Chicken": ItemData("Consumables", 0x021C, ItemClassification.filler, 0),
    "Hot Dog": ItemData("Consumables", 0x021D, ItemClassification.filler, 0),
    "Pumpkin Pie": ItemData("Consumables", 0x021E, ItemClassification.filler, 0),
    "Pancake": ItemData("Consumables", 0x021F, ItemClassification.filler, 0),
    "Tinned Spinach": ItemData("Consumables", 0x0220, ItemClassification.filler, 0),
    "Foie Gras": ItemData("Consumables", 0x0221, ItemClassification.filler, 0),
    "Caviar": ItemData("Consumables", 0x0222, ItemClassification.filler, 0),
    "Truffle": ItemData("Consumables", 0x0223, ItemClassification.filler, 0),
    "Paella": ItemData("Consumables", 0x0224, ItemClassification.filler, 0),
    "Spaghetti": ItemData("Consumables", 0x0225, ItemClassification.filler, 0),
    "Ice Cream": ItemData("Consumables", 0x0226, ItemClassification.filler, 0),
    "Meuniere": ItemData("Consumables", 0x0227, ItemClassification.filler, 0),
    "Boiled Starfish": ItemData("Consumables", 0x0228, ItemClassification.filler, 0),
    "Wheat Roll": ItemData("Consumables", 0x0229, ItemClassification.filler, 0),
    "Sachertorte": ItemData("Consumables", 0x022A, ItemClassification.filler, 0),
    "NY Cheesecake": ItemData("Consumables", 0x022B, ItemClassification.filler, 0),
    "Mille-feuille": ItemData("Consumables", 0x022C, ItemClassification.filler, 0),
    "Tarte au Poire": ItemData("Consumables", 0x022D, ItemClassification.filler, 0),
    "Gateau Fraise": ItemData("Consumables", 0x022E, ItemClassification.filler, 0),
    "Kugelhopf": ItemData("Consumables", 0x022F, ItemClassification.filler, 0),
    "Green Tea Cake": ItemData("Consumables", 0x0230, ItemClassification.filler, 0),
    "Gateau Marron": ItemData("Consumables", 0x0231, ItemClassification.filler, 0),
    "Langues de Chat": ItemData("Consumables", 0x0232, ItemClassification.filler, 0),
    "Financier": ItemData("Consumables", 0x0233, ItemClassification.filler, 0),
    "Tropical Sundae": ItemData("Consumables", 0x0234, ItemClassification.filler, 0),
    "Pudding Bucket": ItemData("Consumables", 0x0235, ItemClassification.filler, 0),
    "Piyoko": ItemData("Consumables", 0x0236, ItemClassification.filler, 0),
    "1000 Year Egg": ItemData("Consumables", 0x0237, ItemClassification.filler, 0),
    "Jamon Iberico": ItemData("Consumables", 0x0238, ItemClassification.filler, 0),
    "Spicy Shrimp": ItemData("Consumables", 0x0239, ItemClassification.filler, 0),
    "Peking Duck": ItemData("Consumables", 0x023A, ItemClassification.filler, 0),
    "Pasta Carbonara": ItemData("Consumables", 0x023B, ItemClassification.filler, 0),
    "Penne Arrabiata": ItemData("Consumables", 0x023C, ItemClassification.filler, 0),
    "Powdered Milk": ItemData("Consumables", 0x023D, ItemClassification.filler, 0),
    "Rotten Durian": ItemData("Consumables", 0x023E, ItemClassification.trap, 0),
    "Ground Meat": ItemData("Consumables", 0x023F, ItemClassification.filler, 0),
    "Noodle Bun": ItemData("Consumables", 0x0240, ItemClassification.filler, 0),
    "Touch & Pop": ItemData("Consumables", 0x0241, ItemClassification.filler, 0),
    "Moldy Bread": ItemData("Consumables", 0x0242, ItemClassification.trap, 0),
    "Penters Natural": ItemData("Consumables", 0x0243, ItemClassification.filler, 0),
    "Birthday Cake": ItemData("Consumables", 0x0244, ItemClassification.filler, 0),
    # "Magical Ticket": ItemData("Consumables", 0x0245, ItemClassification.filler, 0), We have infinite of these, AP doesn't need them
    "Beehive": ItemData("Consumables", 0x0246, ItemClassification.filler, 0),
    "Amanita": ItemData("Consumables", 0x0247, ItemClassification.trap, 0),
    "Rotten Meat": ItemData("Consumables", 0x0248, ItemClassification.trap, 0),
    "Spoiled Milk": ItemData("Consumables", 0x0249, ItemClassification.trap, 0),
    "Rusty Food Tin": ItemData("Consumables", 0x024A, ItemClassification.trap, 0),
    "CASTLE MAP 1": ItemData("Key Items", 0x024B, ItemClassification.filler, 0),
    "CASTLE MAP 2": ItemData("Key Items", 0x024C, ItemClassification.filler, 0),
    "CASTLE MAP 3": ItemData("Key Items", 0x024D, ItemClassification.filler, 0),
    "Cog": ItemData("Key Items", 0x024E, ItemClassification.progression),
    # "AP Item": ItemData("Consumables", 0x024F, ItemClassification.filler, 0),
    # "AP Item": ItemData("Consumables", 0x0250, ItemClassification.filler, 0), These are reserved for offworld items
    # "Vic Viper": ItemData("Consumables", 0x0251, ItemClassification.filler, 0),
    "Tome of Arms p1": ItemData("Key Items", 0x0252, ItemClassification.useful),
    "Tome of Arms p2": ItemData("Key Items", 0x0253, ItemClassification.useful),
    "Spade": ItemData("Key Items", 0x0254, ItemClassification.filler, 0),
    "Diamond": ItemData("Key Items", 0x0255, ItemClassification.filler, 0),
    "Heart": ItemData("Key Items", 0x0256, ItemClassification.filler, 0),
    "Club": ItemData("Key Items", 0x0257, ItemClassification.filler, 0),
    "Joker": ItemData("Key Items", 0x0258, ItemClassification.filler, 0),
    "Statue's Tear": ItemData("Key Items", 0x0259, ItemClassification.useful, 0),
    "Record Player": ItemData("Key Items", 0x025A, ItemClassification.useful, 0),
    "Record 1": ItemData("Key Items", 0x025B, ItemClassification.filler, 0),
    "Record 2": ItemData("Key Items", 0x025C, ItemClassification.filler, 0),
    "Record 3": ItemData("Key Items", 0x025D, ItemClassification.filler, 0),
    "Record 4": ItemData("Key Items", 0x025E, ItemClassification.filler, 0),
    "Record 5": ItemData("Key Items", 0x025F, ItemClassification.filler, 0),

    "Vampire Killer": ItemData("Whips", 0x0301, ItemClassification.useful, 0),  # The starter copy
    "Leather Whip": ItemData("Whips", 0x0302, ItemClassification.filler, 0),
    "Steel Whip": ItemData("Whips", 0x0303, ItemClassification.filler, 0),
    "Rose Stem Whip": ItemData("Whips", 0x0304, ItemClassification.filler, 0),
    "Medusa Whip": ItemData("Whips", 0x0305, ItemClassification.filler, 0),
    "Nebula": ItemData("Whips", 0x0306, ItemClassification.filler, 0),
    "Flame Whip": ItemData("Whips", 0x0307, ItemClassification.filler, 0),
    "Jet Black Whip": ItemData("Whips", 0x0308, ItemClassification.filler, 0),
    "Undead Killer": ItemData("Whips", 0x0309, ItemClassification.filler, 0),
    "True Vampire Killer": ItemData("Whips", 0x030A, ItemClassification.useful, 0),
    "Richter Vampire Killer": ItemData("Whips", 0x030B, ItemClassification.filler, 0),  # Used for richter mode
    "Encyclopedia": ItemData("Books", 0x030C, ItemClassification.filler, 0),
    "Blank Book": ItemData("Books", 0x030D, ItemClassification.filler, 0),
    "Tristan&Isolde": ItemData("Books", 0x030E, ItemClassification.filler, 0),
    "Don Quixote": ItemData("Books", 0x030F, ItemClassification.filler, 0),
    "Book of Death": ItemData("Books", 0x0310, ItemClassification.filler, 0),
    "Tome of Arms 1": ItemData("Books", 0x0311, ItemClassification.filler, 0),
    "Tome of Arms 2": ItemData("Books", 0x0312, ItemClassification.filler, 0),
    "Tome of Arms 3": ItemData("Books", 0x0313, ItemClassification.filler, 0),
    "Tome of Arms X": ItemData("Books", 0x0314, ItemClassification.filler, 0),
    "Knife": ItemData("Knives", 0x0315, ItemClassification.filler, 0),
    "Combat Knife": ItemData("Knives", 0x0316, ItemClassification.filler, 0),
    "Baselard": ItemData("Knives", 0x0317, ItemClassification.filler, 0),
    "Katar": ItemData("Knives", 0x0318, ItemClassification.filler, 0),
    "Cinquedea": ItemData("Knives", 0x319, ItemClassification.filler, 0),
    "Short Sword": ItemData("Swords", 0x031A, ItemClassification.filler, 0),
    "Cutlass": ItemData("Swords", 0x031B, ItemClassification.filler, 0),
    "Long Sword": ItemData("Swords", 0x031C, ItemClassification.filler, 0),
    "Gladius": ItemData("Swords", 0x031D, ItemClassification.filler, 0),
    "Milican's Sword": ItemData("Swords", 0x031E, ItemClassification.filler, 0),
    "Rahab's Frost": ItemData("Swords", 0x031F, ItemClassification.filler, 0),
    "Agni's Flame": ItemData("Swords", 0x0320, ItemClassification.filler, 0),
    "Assassin Blade": ItemData("Swords", 0x0321, ItemClassification.filler, 0),
    "Heaven's Sword": ItemData("Swords", 0x0322, ItemClassification.filler, 0),
    "Bakatwa": ItemData("Swords", 0x0323, ItemClassification.filler, 0),
    "Jagdplaute": ItemData("Swords", 0x0324, ItemClassification.filler, 0),
    "Stellar Sword": ItemData("Swords", 0x0325, ItemClassification.filler, 0),
    "Damascus Sword": ItemData("Swords", 0x0326, ItemClassification.filler, 0),
    "Claymore": ItemData("Greatswords", 0x0327, ItemClassification.filler, 0),
    "Falchion": ItemData("Greatswords", 0x0328, ItemClassification.filler, 0),
    "Great Sword": ItemData("Greatswords", 0x0329, ItemClassification.filler, 0),
    "Zweihander": ItemData("Greatswords", 0x032A, ItemClassification.filler, 0),
    "Royal Sword": ItemData("Greatswords", 0x032B, ItemClassification.filler, 0),
    "Dragon Slayer": ItemData("Greatswords", 0x032C, ItemClassification.filler, 0),
    "Final Sword": ItemData("Greatswords", 0x032D, ItemClassification.filler, 0),
    "Holy Claymore": ItemData("Greatswords", 0x032E, ItemClassification.filler, 0),
    "Spear": ItemData("Spears", 0x032F, ItemClassification.filler, 0),
    "Partisan": ItemData("Spears", 0x0330, ItemClassification.filler, 0),
    "Halberd": ItemData("Spears", 0x0331, ItemClassification.filler, 0),
    "Lance": ItemData("Spears", 0x0332, ItemClassification.filler, 0),
    "Trident": ItemData("Spears", 0x0333, ItemClassification.filler, 0),
    "Long Spear": ItemData("Spears", 0x0334, ItemClassification.filler, 0),
    "Couse": ItemData("Spears", 0x0335, ItemClassification.filler, 0),
    "Sarissa": ItemData("Spears", 0x0336, ItemClassification.filler, 0),
    "Alucard's Spear": ItemData("Spears", 0x0337, ItemClassification.filler, 0),
    "Axe": ItemData("Axes", 0x0338, ItemClassification.filler, 0),
    "Mace": ItemData("Axes", 0x0339, ItemClassification.filler, 0),
    "Battle Axe": ItemData("Axes", 0x033A, ItemClassification.filler, 0),
    "Morning Star": ItemData("Axes", 0x033B, ItemClassification.filler, 0),
    "Bhuj": ItemData("Axes", 0x033C, ItemClassification.filler, 0),
    "Great Axe": ItemData("Axes", 0x033D, ItemClassification.filler, 0),
    "Voulge": ItemData("Axes", 0x033E, ItemClassification.filler, 0),
    "Bullova": ItemData("Axes", 0x033F, ItemClassification.filler, 0),
    "Golden Axe": ItemData("Axes", 0x0340, ItemClassification.filler, 0),
    "Brass Knuckles": ItemData("Fists", 0x0341, ItemClassification.filler, 0),
    "Cestus": ItemData("Fists", 0x0342, ItemClassification.filler, 0),
    "Whip Knuckles": ItemData("Fists", 0x0343, ItemClassification.filler, 0),
    "Bahg Nahk": ItemData("Fists", 0x0344, ItemClassification.filler, 0),
    "Bullet Punch": ItemData("Fists", 0x0345, ItemClassification.filler, 0),
    "Illusion Fist": ItemData("Fists", 0x0346, ItemClassification.filler, 0),
    "Kaiser Knuckles": ItemData("Fists", 0x0347, ItemClassification.filler, 0),
    "Tori": ItemData("Other Weapons", 0x0348, ItemClassification.filler, 0),




    "Dummy": ItemData("Dummy", 0x, ItemClassification.filler, 0),
