from typing import Dict, Set, NamedTuple, Optional
from BaseClasses import ItemClassification


class ItemData(NamedTuple):
    category: str
    code: Optional[int]
    classification: ItemClassification
    default_count: Optional[int] = 1


item_table: Dict[str, ItemData] = {
    "$1": ItemData("Money", 0x100, ItemClassification.filler, 0),
    "$10": ItemData("Money", 0x101, ItemClassification.filler, 0),
    "$50": ItemData("Money", 0x102, ItemClassification.filler, 0),
    "$100": ItemData("Money", 0x103, ItemClassification.filler, 0),
    "$500": ItemData("Money", 0x104, ItemClassification.filler, 0),
    "$1000": ItemData("Money", 0x105, ItemClassification.filler, 0),
    "$2000": ItemData("Money", 0x106, ItemClassification.filler, 0),

    "Potion": ItemData("Consumables", 0x0200, ItemClassification.filler, 0),
    "High Potion": ItemData("Consumables", 0x0201, ItemClassification.filler, 0),
    "Super Potion": ItemData("Consumables", 0x0202, ItemClassification.filler, 0),
    "Tonic": ItemData("Consumables", 0x0203, ItemClassification.filler, 0),
    "High Tonic": ItemData("Consumables", 0x0204, ItemClassification.filler, 0),
    "Super Tonic": ItemData("Consumables", 0x0205, ItemClassification.filler, 0),
    "Anti-Venom": ItemData("Consumables", 0x0206, ItemClassification.filler, 0),
    "Uncurse Potion": ItemData("Consumables", 0x0207, ItemClassification.filler, 0),
    "HP Max up": ItemData("Upgrades", 0x0208, ItemClassification.useful, 16),
    "MP Max up": ItemData("Upgrades", 0x0209, ItemClassification.useful, 16),
    "Beef Jerky": ItemData("Consumables", 0x020A, ItemClassification.filler, 0),
    "Tasty Meat": ItemData("Consumables", 0x020B, ItemClassification.filler, 0),
    "New York Steak": ItemData("Consumables", 0x020C, ItemClassification.filler, 0),
    "Rice Ball": ItemData("Consumables", 0x020D, ItemClassification.filler, 0),
    "Mushroom": ItemData("Consumables", 0x020E, ItemClassification.filler, 0),
    "Corn Soup": ItemData("Consumables", 0x020F, ItemClassification.filler, 0),
    "Curry": ItemData("Consumables", 0x0210, ItemClassification.filler, 0),
    "Ramen Noodles": ItemData("Consumables", 0x0211, ItemClassification.filler, 0),
    "Mint Sundae": ItemData("Consumables", 0x0212, ItemClassification.filler, 0),
    "Cream Puff": ItemData("Consumables", 0x0213, ItemClassification.filler, 0),
    "Milk": ItemData("Consumables", 0x0214, ItemClassification.filler, 0),
    "Coffee": ItemData("Consumables", 0x0215, ItemClassification.filler, 0),
    "Tea": ItemData("Consumables", 0x0216, ItemClassification.filler, 0),
    "Pudding": ItemData("Consumables", 0x0217, ItemClassification.filler, 0),
    "Strawberry": ItemData("Consumables", 0x0218, ItemClassification.filler, 0),
    "Melon": ItemData("Consumables", 0x0219, ItemClassification.filler, 0),
    "Grapes": ItemData("Consumables", 0x021A, ItemClassification.filler, 0),
    "Hamburger": ItemData("Consumables", 0x021B, ItemClassification.filler, 0),
    "Fried Chicken": ItemData("Consumables", 0x021C, ItemClassification.filler, 0),
    "Hot Dog": ItemData("Consumables", 0x021D, ItemClassification.filler, 0),
    "Pumpkin Pie": ItemData("Consumables", 0x021E, ItemClassification.filler, 0),
    "Pancake": ItemData("Consumables", 0x021F, ItemClassification.filler, 0),
    "Tinned Spinach": ItemData("Consumables", 0x0220, ItemClassification.filler, 0),
    "Foie Gras": ItemData("Consumables", 0x0221, ItemClassification.filler, 0),
    "Caviar": ItemData("Consumables", 0x0222, ItemClassification.filler, 0),
    "Truffle": ItemData("Consumables", 0x0223, ItemClassification.filler, 0),
    "Paella": ItemData("Consumables", 0x0224, ItemClassification.filler, 0),
    "Spaghetti": ItemData("Consumables", 0x0225, ItemClassification.filler, 0),
    "Ice Cream": ItemData("Consumables", 0x0226, ItemClassification.filler, 0),
    "Meuniere": ItemData("Consumables", 0x0227, ItemClassification.filler, 0),
    "Boiled Starfish": ItemData("Consumables", 0x0228, ItemClassification.filler, 0),
    "Wheat Roll": ItemData("Consumables", 0x0229, ItemClassification.filler, 0),
    "Sachertorte": ItemData("Consumables", 0x022A, ItemClassification.filler, 0),
    "NY Cheesecake": ItemData("Consumables", 0x022B, ItemClassification.filler, 0),
    "Mille-feuille": ItemData("Consumables", 0x022C, ItemClassification.filler, 0),
    "Tarte au Poire": ItemData("Consumables", 0x022D, ItemClassification.filler, 0),
    "Gateau Fraise": ItemData("Consumables", 0x022E, ItemClassification.filler, 0),
    "Kugelhopf": ItemData("Consumables", 0x022F, ItemClassification.filler, 0),
    "Green Tea Cake": ItemData("Consumables", 0x0230, ItemClassification.filler, 0),
    "Gateau Marron": ItemData("Consumables", 0x0231, ItemClassification.filler, 0),
    "Langues de Chat": ItemData("Consumables", 0x0232, ItemClassification.filler, 0),
    "Financier": ItemData("Consumables", 0x0233, ItemClassification.filler, 0),
    "Tropical Sundae": ItemData("Consumables", 0x0234, ItemClassification.filler, 0),
    "Pudding Bucket": ItemData("Consumables", 0x0235, ItemClassification.filler, 0),
    "Piyoko": ItemData("Consumables", 0x0236, ItemClassification.filler, 0),
    "1000 Year Egg": ItemData("Consumables", 0x0237, ItemClassification.filler, 0),
    "Jamon Iberico": ItemData("Consumables", 0x0238, ItemClassification.filler, 0),
    "Spicy Shrimp": ItemData("Consumables", 0x0239, ItemClassification.filler, 0),
    "Peking Duck": ItemData("Consumables", 0x023A, ItemClassification.filler, 0),
    "Pasta Carbonara": ItemData("Consumables", 0x023B, ItemClassification.filler, 0),
    "Penne Arrabiata": ItemData("Consumables", 0x023C, ItemClassification.filler, 0),
    "Powdered Milk": ItemData("Consumables", 0x023D, ItemClassification.filler, 0),
    "Rotten Durian": ItemData("Consumables", 0x023E, ItemClassification.trap, 0),
    "Ground Meat": ItemData("Consumables", 0x023F, ItemClassification.filler, 0),
    "Noodle Bun": ItemData("Consumables", 0x0240, ItemClassification.filler, 0),
    "Touch & Pop": ItemData("Consumables", 0x0241, ItemClassification.filler, 0),
    "Moldy Bread": ItemData("Consumables", 0x0242, ItemClassification.trap, 0),
    "Penters Natural": ItemData("Consumables", 0x0243, ItemClassification.filler, 0),
    "Birthday Cake": ItemData("Consumables", 0x0244, ItemClassification.filler, 0),
    # "Magical Ticket": ItemData("Consumables", 0x0245, ItemClassification.filler, 0), We have infinite of these, AP doesn't need them
    "Beehive": ItemData("Consumables", 0x0246, ItemClassification.filler, 0),
    "Amanita": ItemData("Consumables", 0x0247, ItemClassification.trap, 0),
    "Rotten Meat": ItemData("Consumables", 0x0248, ItemClassification.trap, 0),
    "Spoiled Milk": ItemData("Consumables", 0x0249, ItemClassification.trap, 0),
    "Rusty Food Tin": ItemData("Consumables", 0x024A, ItemClassification.trap, 0),
    "CASTLE MAP 1": ItemData("Key Items", 0x024B, ItemClassification.filler, 0),
    "CASTLE MAP 2": ItemData("Key Items", 0x024C, ItemClassification.filler, 0),
    "CASTLE MAP 3": ItemData("Key Items", 0x024D, ItemClassification.filler, 0),
    "Cog": ItemData("Key Items", 0x024E, ItemClassification.progression),
    # "AP Item": ItemData("Consumables", 0x024F, ItemClassification.filler, 0),
    # "AP Item": ItemData("Consumables", 0x0250, ItemClassification.filler, 0), These are reserved for offworld items
    # "Vic Viper": ItemData("Consumables", 0x0251, ItemClassification.filler, 0),
    "Tome of Arms p1": ItemData("Key Items", 0x0252, ItemClassification.useful),
    "Tome of Arms p2": ItemData("Key Items", 0x0253, ItemClassification.useful),
    "Spade": ItemData("Key Items", 0x0254, ItemClassification.filler, 0),
    "Diamond": ItemData("Key Items", 0x0255, ItemClassification.filler, 0),
    "Heart": ItemData("Key Items", 0x0256, ItemClassification.filler, 0),
    "Club": ItemData("Key Items", 0x0257, ItemClassification.filler, 0),
    "Joker": ItemData("Key Items", 0x0258, ItemClassification.filler, 0),
    "Statue's Tear": ItemData("Key Items", 0x0259, ItemClassification.useful, 0),
    "Record Player": ItemData("Key Items", 0x025A, ItemClassification.useful, 0),
    "Record 1": ItemData("Key Items", 0x025B, ItemClassification.filler, 0),
    "Record 2": ItemData("Key Items", 0x025C, ItemClassification.filler, 0),
    "Record 3": ItemData("Key Items", 0x025D, ItemClassification.filler, 0),
    "Record 4": ItemData("Key Items", 0x025E, ItemClassification.filler, 0),
    "Record 5": ItemData("Key Items", 0x025F, ItemClassification.filler, 0),

    "Vampire Killer": ItemData("Whips", 0x0301, ItemClassification.useful, 0),  # The starter copy
    "Leather Whip": ItemData("Whips", 0x0302, ItemClassification.filler, 0),
    "Steel Whip": ItemData("Whips", 0x0303, ItemClassification.filler, 0),
    "Rose Stem Whip": ItemData("Whips", 0x0304, ItemClassification.filler, 0),
    "Medusa Whip": ItemData("Whips", 0x0305, ItemClassification.filler, 0),
    "Nebula": ItemData("Whips", 0x0306, ItemClassification.useful),
    "Flame Whip": ItemData("Whips", 0x0307, ItemClassification.useful),
    "Jet Black Whip": ItemData("Whips", 0x0308, ItemClassification.useful),
    "Undead Killer": ItemData("Whips", 0x0309, ItemClassification.useful, 0),
    "True Vampire Killer": ItemData("Whips", 0x030A, ItemClassification.useful, 0),
    "Richter Vampire Killer": ItemData("Whips", 0x030B, ItemClassification.filler, 0),  # Used for richter mode
    "Encyclopedia": ItemData("Books", 0x030C, ItemClassification.filler, 0),
    "Blank Book": ItemData("Books", 0x030D, ItemClassification.filler, 0),
    "Tristan&Isolde": ItemData("Books", 0x030E, ItemClassification.useful),
    "Don Quixote": ItemData("Books", 0x030F, ItemClassification.useful),
    "Book of Death": ItemData("Books", 0x0310, ItemClassification.useful),
    "Tome of Arms 1": ItemData("Books", 0x0311, ItemClassification.useful),
    "Tome of Arms 2": ItemData("Books", 0x0312, ItemClassification.useful),
    "Tome of Arms 3": ItemData("Books", 0x0313, ItemClassification.useful),
    "Tome of Arms X": ItemData("Books", 0x0314, ItemClassification.useful, 0),
    "Knife": ItemData("Knives", 0x0315, ItemClassification.filler, 0),
    "Combat Knife": ItemData("Knives", 0x0316, ItemClassification.filler, 0),
    "Baselard": ItemData("Knives", 0x0317, ItemClassification.filler, 0),
    "Katar": ItemData("Knives", 0x0318, ItemClassification.filler, 0),
    "Cinquedea": ItemData("Knives", 0x319, ItemClassification.filler, 0),
    "Short Sword": ItemData("Swords", 0x031A, ItemClassification.filler, 0),
    "Cutlass": ItemData("Swords", 0x031B, ItemClassification.filler, 0),
    "Long Sword": ItemData("Swords", 0x031C, ItemClassification.useful),
    "Gladius": ItemData("Swords", 0x031D, ItemClassification.filler, 0),
    "Milican's Sword": ItemData("Swords", 0x031E, ItemClassification.useful),
    "Rahab's Frost": ItemData("Swords", 0x031F, ItemClassification.filler, 0),
    "Agni's Flame": ItemData("Swords", 0x0320, ItemClassification.filler, 0),
    "Assassin Blade": ItemData("Swords", 0x0321, ItemClassification.useful, 0),
    "Heaven's Sword": ItemData("Swords", 0x0322, ItemClassification.filler, 0),
    "Bakatwa": ItemData("Swords", 0x0323, ItemClassification.useful),
    "Jagdplaute": ItemData("Swords", 0x0324, ItemClassification.filler, 0),
    "Stellar Sword": ItemData("Swords", 0x0325, ItemClassification.useful, 0),
    "Damascus Sword": ItemData("Swords", 0x0326, ItemClassification.filler, 0),
    "Claymore": ItemData("Greatswords", 0x0327, ItemClassification.filler, 0),
    "Falchion": ItemData("Greatswords", 0x0328, ItemClassification.filler, 0),
    "Great Sword": ItemData("Greatswords", 0x0329, ItemClassification.filler, 0),
    "Zweihander": ItemData("Greatswords", 0x032A, ItemClassification.filler, 0),
    "Royal Sword": ItemData("Greatswords", 0x032B, ItemClassification.useful, 0),
    "Dragon Slayer": ItemData("Greatswords", 0x032C, ItemClassification.filler, 0),
    "Final Sword": ItemData("Greatswords", 0x032D, ItemClassification.filler, 0),
    "Holy Claymore": ItemData("Greatswords", 0x032E, ItemClassification.filler, 0),
    "Spear": ItemData("Spears", 0x032F, ItemClassification.filler, 0),
    "Partisan": ItemData("Spears", 0x0330, ItemClassification.filler, 0),
    "Halberd": ItemData("Spears", 0x0331, ItemClassification.useful),
    "Lance": ItemData("Spears", 0x0332, ItemClassification.filler, 0),
    "Trident": ItemData("Spears", 0x0333, ItemClassification.filler, 0),
    "Long Spear": ItemData("Spears", 0x0334, ItemClassification.filler, 0),
    "Couse": ItemData("Spears", 0x0335, ItemClassification.filler, 0),
    "Sarissa": ItemData("Spears", 0x0336, ItemClassification.filler, 0),
    "Alucard's Spear": ItemData("Spears", 0x0337, ItemClassification.useful, 0),
    "Axe": ItemData("Axes", 0x0338, ItemClassification.filler, 0),
    "Mace": ItemData("Axes", 0x0339, ItemClassification.filler, 0),
    "Battle Axe": ItemData("Axes", 0x033A, ItemClassification.filler, 0),
    "Morning Star": ItemData("Axes", 0x033B, ItemClassification.filler, 0),
    "Bhuj": ItemData("Axes", 0x033C, ItemClassification.filler, 0),
    "Great Axe": ItemData("Axes", 0x033D, ItemClassification.useful),
    "Voulge": ItemData("Axes", 0x033E, ItemClassification.filler, 0),
    "Bullova": ItemData("Axes", 0x033F, ItemClassification.filler, 0),
    "Golden Axe": ItemData("Axes", 0x0340, ItemClassification.filler, 0),
    "Brass Knuckles": ItemData("Fists", 0x0341, ItemClassification.filler, 0),
    "Cestus": ItemData("Fists", 0x0342, ItemClassification.filler, 0),
    "Whip Knuckles": ItemData("Fists", 0x0343, ItemClassification.useful),
    "Bahg Nahk": ItemData("Fists", 0x0344, ItemClassification.useful),
    "Bullet Punch": ItemData("Fists", 0x0345, ItemClassification.useful, 0),
    "Illusion Fist": ItemData("Fists", 0x0346, ItemClassification.filler, 0),
    "Kaiser Knuckles": ItemData("Fists", 0x0347, ItemClassification.useful),
    "Tori": ItemData("Other Weapons", 0x0348, ItemClassification.filler, 0),

    "Casual Clothes": ItemData("Body Armor", 0x0401, ItemClassification.filler, 0),
    "Hobo's Clothes": ItemData("Body Armor", 0x0402, ItemClassification.filler, 0),
    "Houppelande": ItemData("Body Armor", 0x0403, ItemClassification.filler, 0),
    "Poncho": ItemData("Body Armor", 0x0404, ItemClassification.filler, 0),
    "Combat Fatigues": ItemData("Body Armor", 0x0405, ItemClassification.filler, 0),
    "Adrenaline Gear": ItemData("Body Armor", 0x0406, ItemClassification.filler, 0),
    "Kalasiris": ItemData("Body Armor", 0x0407, ItemClassification.filler, 0),
    "Feather Gear": ItemData("Body Armor", 0x0408, ItemClassification.filler, 0),
    "Tailcoat": ItemData("Jonathan Armor", 0x0409, ItemClassification.filler, 0),
    "Biker's Jacket": ItemData("Jonathan Armor", 0x040A, ItemClassification.filler, 0),
    "Justaucorps": ItemData("Jonathan Armor", 0x040B, ItemClassification.filler, 0),
    "Tuxedo Coat": ItemData("Jonathan Armor", 0x040C, ItemClassification.filler, 0),
    "Battle Jacket": ItemData("Jonathan Armor", 0x040D, ItemClassification.filler, 0),
    "Surcoat": ItemData("Jonathan Armor", 0x040E, ItemClassification.filler, 0),
    "Leather Cuirass": ItemData("Jonathan Armor", 0x040F, ItemClassification.filler, 0),
    "Copper Plate": ItemData("Jonathan Armor", 0x0410, ItemClassification.filler, 0),
    "Iron Plate": ItemData("Jonathan Armor", 0x0411, ItemClassification.filler, 0),
    "Silver Plate": ItemData("Jonathan Armor", 0x0412, ItemClassification.filler, 0),
    "Gold Plate": ItemData("Jonathan Armor", 0x0413, ItemClassification.filler, 0),
    "Lorica": ItemData("Jonathan Armor", 0x0414, ItemClassification.filler, 0),
    "Platinum Plate": ItemData("Jonathan Armor", 0x0415, ItemClassification.filler, 0),
    "Samurai Plate": ItemData("Jonathan Armor", 0x0416, ItemClassification.filler, 0),
    "Holy Mail": ItemData("Jonathan Armor", 0x0417, ItemClassification.filler, 0),
    "Berserker Mail": ItemData("Jonathan Armor", 0x0418, ItemClassification.filler, 0),
    "Ancient Armor": ItemData("Jonathan Armor", 0x0419, ItemClassification.filler, 0),
    "Healing Mail": ItemData("Jonathan Armor", 0x041A, ItemClassification.useful),
    "Mirror Cuirass": ItemData("Jonathan Armor", 0x041B, ItemClassification.filler, 0),
    "Spiked Mail": ItemData("Jonathan Armor", 0x041C, ItemClassification.filler, 0),
    "Scout Armor": ItemData("Jonathan Armor", 0x041D, ItemClassification.filler, 0),
    "Heavy Armor": ItemData("Jonathan Armor", 0x041E, ItemClassification.filler, 0),
    "Impervious Mail": ItemData("Jonathan Armor", 0x041F, ItemClassification.filler, 0),
    "Leather Corset": ItemData("Charlotte Armor", 0x0420, ItemClassification.filler, 0),
    "Jade Corset": ItemData("Charlotte Armor", 0x0421, ItemClassification.filler, 0),
    "Amethyst Corset": ItemData("Charlotte Armor", 0x0422, ItemClassification.filler, 0),
    "Emerald Corset": ItemData("Charlotte Armor", 0x0423, ItemClassification.filler, 0),
    "Ruby Corset": ItemData("Charlotte Armor", 0x0424, ItemClassification.filler, 0),
    "Sapphire Corset": ItemData("Charlotte Armor", 0x0425, ItemClassification.filler, 0),
    "Lilith Corset": ItemData("Charlotte Armor", 0x0426, ItemClassification.filler, 0),
    "Platinum Corset": ItemData("Charlotte Armor", 0x0427, ItemClassification.useful),
    "Diamond Corset": ItemData("Charlotte Armor", 0x0428, ItemClassification.filler, 0),
    "Kirtle": ItemData("Charlotte Armor", 0x0429, ItemClassification.filler, 0),
    "Miko Dress": ItemData("Charlotte Armor", 0x042A, ItemClassification.filler, 0),
    "Cotton Apron": ItemData("Charlotte Armor", 0x042B, ItemClassification.filler, 0),
    "Silk Negligee": ItemData("Charlotte Armor", 0x042C, ItemClassification.filler, 0),
    "Bathrobe": ItemData("Charlotte Armor", 0x042D, ItemClassification.filler, 0),
    "Frilly Camisole": ItemData("Charlotte Armor", 0x042E, ItemClassification.filler, 0),
    "Sequined Dress": ItemData("Charlotte Armor", 0x042F, ItemClassification.filler, 0),
    "Clown Shirt": ItemData("Charlotte Armor", 0x0430, ItemClassification.filler, 0),
    "Nun's Robes": ItemData("Charlotte Armor", 0x0431, ItemClassification.useful),
    "Cocktail Dress": ItemData("Charlotte Armor", 0x0432, ItemClassification.filler, 0),
    "Dancer's Blouse": ItemData("Charlotte Armor", 0x0433, ItemClassification.filler, 0),
    "Cotehardie": ItemData("Charlotte Armor", 0x0434, ItemClassification.filler, 0),
    "Wedding Dress": ItemData("Charlotte Armor", 0x0435, ItemClassification.filler, 0),
    "Europa's Dress": ItemData("Charlotte Armor", 0x0436, ItemClassification.filler, 0),
    "Dalmatica": ItemData("Charlotte Armor", 0x0437, ItemClassification.filler, 0),
    "Princess Coat": ItemData("Charlotte Armor", 0x0438, ItemClassification.filler, 0),
    "Robe Decollete": ItemData("Charlotte Armor", 0x0439, ItemClassification.useful),

    "Eye for Decay": ItemData("Headgear", 0x0501, ItemClassification.filler, 0),
    "Gambler Glasses": ItemData("Headgear", 0x0502, ItemClassification.useful, 0),
    "Sunglasses": ItemData("Headgear", 0x0503, ItemClassification.filler, 0),
    "Thick Glasses": ItemData("Headgear", 0x0504, ItemClassification.filler, 0),
    "Glasses": ItemData("Headgear", 0x0505, ItemClassification.filler, 0),
    "Monocle": ItemData("Headgear", 0x0506, ItemClassification.filler, 0),
    "Goggles": ItemData("Headgear", 0x0507, ItemClassification.filler, 0),
    "Combat Beret": ItemData("Headgear", 0x0508, ItemClassification.useful),
    "Uraeus": ItemData("Headgear", 0x0509, ItemClassification.filler, 0),
    "Royal Crown": ItemData("Headgear", 0x050A, ItemClassification.filler, 0),
    "Headguard": ItemData("Jonathan Headgear", 0x050B, ItemClassification.filler, 0),
    "Bandana": ItemData("Jonathan Headgear", 0x050C, ItemClassification.useful),
    "Iron Helmet": ItemData("Jonathan Headgear", 0x050D, ItemClassification.filler, 0),
    "Stone Mask": ItemData("Jonathan Headgear", 0x050E, ItemClassification.filler, 0),
    "Viking Helmet": ItemData("Jonathan Headgear", 0x050F, ItemClassification.filler, 0),
    "Ballroom Masque": ItemData("Jonathan Headgear", 0x0510, ItemClassification.filler, 0),
    "Fedora": ItemData("Jonathan Headgear", 0x0511, ItemClassification.filler, 0),
    "Porkpie Hat": ItemData("Jonathan Headgear", 0x0512, ItemClassification.filler, 0),
    "Silk Hat": ItemData("Jonathan Headgear", 0x0513, ItemClassification.filler, 0),
    "Traveler's Hat": ItemData("Headgear", 0x0514, ItemClassification.filler, 0),
    "Attica Helmet": ItemData("Jonathan Headgear", 0x0515, ItemClassification.useful),
    "Samurai Helmet": ItemData("Jonathan Headgear", 0x0516, ItemClassification.filler, 0),
    "Shogun Helmet": ItemData("Jonathan Headgear", 0x0517, ItemClassification.useful),
    "Skull Mask": ItemData("Jonathan Headgear", 0x0518, ItemClassification.filler, 0),
    "Velvet Ribbon": ItemData("Charlotte Headgear", 0x0519, ItemClassification.useful),
    "Witch's Hat": ItemData("Charlotte Headgear", 0x051A, ItemClassification.filler, 0),
    "Mourning Veil": ItemData("Charlotte Headgear", 0x051B, ItemClassification.filler, 0),
    "Nun's Habit": ItemData("Charlotte Headgear", 0x051C, ItemClassification.useful),
    "Open Veil": ItemData("Charlotte Headgear", 0x051D, ItemClassification.filler, 0),
    "Holy Veil": ItemData("Charlotte Headgear", 0x051E, ItemClassification.filler, 0),
    "Clover Tiara": ItemData("Charlotte Headgear", 0x051F, ItemClassification.useful),
    "Pearl Tiara": ItemData("Charlotte Headgear", 0x0520, ItemClassification.filler, 0),
    "Diamond Tiara": ItemData("Charlotte Headgear", 0x0521, ItemClassification.filler, 0),
    "Princess Tiara": ItemData("Charlotte Headgear", 0x0522, ItemClassification.useful),
    "Muse's Tiara": ItemData("Charlotte Headgear", 0x0523, ItemClassification.filler, 0),
    "Midnight Tiara": ItemData("Charlotte Headgear", 0x0524, ItemClassification.filler, 0),
    "Arachne Hennin": ItemData("Charlotte Headgear", 0x0525, ItemClassification.filler, 0),

    "Sandals": ItemData("Boots", 0x0601, ItemClassification.filler, 0),
    "Engineer Boots": ItemData("Boots", 0x0602, ItemClassification.filler, 0),
    "Royal Sandals": ItemData("Boots", 0x0603, ItemClassification.filler, 0),
    "Combat Boots": ItemData("Boots", 0x0604, ItemClassification.filler, 0),
    "Moonwalkers": ItemData("Boots", 0x0605, ItemClassification.useful),
    "Slick Boots": ItemData("Boots", 0x0606, ItemClassification.filler, 0),
    "Spiked Boots": ItemData("Boots", 0x0607, ItemClassification.useful),
    "Mercury Boots": ItemData("Boots", 0x0608, ItemClassification.useful),
    "Winged Boots": ItemData("Boots", 0x0609, ItemClassification.useful),
    "Hiking Boots": ItemData("Jonathan Boots", 0x060A, ItemClassification.filler, 0),
    "Oxfords": ItemData("Jonathan Boots", 0x060B, ItemClassification.filler, 0),
    "Wingtips": ItemData("Jonathan Boots", 0x060C, ItemClassification.filler, 0),
    "Iron Leggings": ItemData("Jonathan Boots", 0x060D, ItemClassification.filler, 0),
    "Silver Leggings": ItemData("Jonathan Boots", 0x060E, ItemClassification.filler, 0),
    "Gold Leggings": ItemData("Jonathan Boots", 0x060F, ItemClassification.filler, 0),
    "Steel Greaves": ItemData("Jonathan Boots", 0x0610, ItemClassification.useful),
    "Platinum Lggngs": ItemData("Jonathan Boots", 0x0611, ItemClassification.filler, 0),
    "Samurai Leggngs": ItemData("Jonathan Boots", 0x0612, ItemClassification.useful),
    "Enamel Pinheels": ItemData("Charlotte Boots", 0x0613, ItemClassification.useful, 0),
    "Inuit Boots": ItemData("Charlotte Boots", 0x0614, ItemClassification.filler, 0),
    "Succubus Boots": ItemData("Charlotte Boots", 0x0615, ItemClassification.filler, 0),
    "Glamorous Pumps": ItemData("Charlotte Boots", 0x0616, ItemClassification.useful),
    "Silent Sandals": ItemData("Charlotte Boots", 0x0617, ItemClassification.filler, 0),
    "Artemis Shoes": ItemData("Charlotte Boots", 0x0618, ItemClassification.useful),
    "Nun's Shoes": ItemData("Charlotte Boots", 0x0619, ItemClassification.useful),
    "Glass Shoes": ItemData("Charlotte Boots", 0x061A, ItemClassification.filler, 0),
    "Prima Shoes": ItemData("Charlotte Boots", 0x061B, ItemClassification.filler, 0),
    "Diamond Shoes": ItemData("Charlotte Boots", 0x061C, ItemClassification.filler, 0),

    "Studded Choker": ItemData("Accessories", 0x0701, ItemClassification.filler, 0),
    "Charm Necklace": ItemData("Accessories", 0x0702, ItemClassification.useful),
    "Stella's Locket": ItemData("Key Items", 0x0703, ItemClassification.progression),
    "Astral Ring": ItemData("Accessories", 0x0704, ItemClassification.filler, 0),
    "Engagement Ring": ItemData("Accessories", 0x0705, ItemClassification.useful),
    "Magus Ring": ItemData("Accessories", 0x0706, ItemClassification.filler, 0),
    "Gold Ring": ItemData("Accessories", 0x0707, ItemClassification.filler, 0),
    "Shaman Ring": ItemData("Accessories", 0x0708, ItemClassification.useful),
    "Miser Ring": ItemData("Accessories", 0x0709, ItemClassification.useful, 0),
    "Sage Ring": ItemData("Accessories", 0x070A, ItemClassification.useful, 0),
    "Thief Ring": ItemData("Accessories", 0x070B, ItemClassification.useful, 0),
    "Pearl Ring": ItemData("Accessories", 0x070C, ItemClassification.filler, 0),
    "Tough Ring": ItemData("Accessories", 0x070D, ItemClassification.filler, 0),
    "Master Ring": ItemData("Accessories", 0x070E, ItemClassification.filler, 0),
    "Skull Ring": ItemData("Accessories", 0x070F, ItemClassification.filler, 0),
    "Immunity Ring": ItemData("Accessories", 0x0710, ItemClassification.useful, 0),
    "Blessed Ring": ItemData("Accessories", 0x0711, ItemClassification.useful, 0),
    "Hercules Ring": ItemData("Accessories", 0x0712, ItemClassification.filler, 0),
    "Cape": ItemData("Accessories", 0x0713, ItemClassification.filler, 0),
    "Hero's Cape": ItemData("Accessories", 0x0714, ItemClassification.filler, 0),
    "Blue Cape": ItemData("Accessories", 0x0715, ItemClassification.filler, 0),
    "Elven Cape": ItemData("Accessories", 0x0716, ItemClassification.filler, 0),
    "Assassin's Cape": ItemData("Accessories", 0x0717, ItemClassification.useful),
    "Invisible Cape": ItemData("Accessories", 0x0718, ItemClassification.filler, 0),
    "Holy Mantle": ItemData("Accessories", 0x0719, ItemClassification.filler, 0),
    "Paludamentum": ItemData("Accessories", 0x071A, ItemClassification.filler, 0),
    "Blessed Ankh": ItemData("Accessories", 0x071B, ItemClassification.filler, 0),
    "White Corsage": ItemData("Accessories", 0x071C, ItemClassification.useful),
    "Orchid Corsage": ItemData("Accessories", 0x071D, ItemClassification.filler, 0),
    "Rose Corsage": ItemData("Accessories", 0x071E, ItemClassification.filler, 0),
    "Sorceress Crest": ItemData("Accessories", 0x071F, ItemClassification.useful, 0),
    "Forget-Me-Not": ItemData("Accessories", 0x0720, ItemClassification.filler, 0),
    "Crystal Necklet": ItemData("Accessories", 0x0721, ItemClassification.useful),
    "Platinum Chain": ItemData("Accessories", 0x0722, ItemClassification.filler, 0),
    "Heart Brooch": ItemData("Accessories", 0x0723, ItemClassification.filler, 0),
    "Astral Brooch": ItemData("Accessories", 0x0724, ItemClassification.filler, 0),
    "Laurel Brooch": ItemData("Accessories", 0x0725, ItemClassification.useful),
    "Abalone Brooch": ItemData("Accessories", 0x0726, ItemClassification.filler, 0),
    "Diamond Brooch": ItemData("Accessories", 0x0727, ItemClassification.useful),
    "Moon Brooch": ItemData("Accessories", 0x0728, ItemClassification.filler, 0),
    "Venus Brooch": ItemData("Accessories", 0x0729, ItemClassification.useful),

    "Puppet Master": ItemData("Subweapons", 0x0801, ItemClassification.progression, 0),
    "R. Axe": ItemData("Subweapons", 0x0802, ItemClassification.filler, 0),
    "R. Cross": ItemData("Subweapons", 0x0803, ItemClassification.filler, 0),
    "R. Holy Water": ItemData("Subweapons", 0x0804, ItemClassification.filler, 0),
    "Julius Cross": ItemData("Subweapons", 0x0805, ItemClassification.filler, 0),
    "Seiryu": ItemData("Subweapons", 0x0806, ItemClassification.filler, 0),
    "Suzaku": ItemData("Subweapons", 0x0807, ItemClassification.filler, 0),
    "Byakko": ItemData("Subweapons", 0x0808, ItemClassification.filler, 0),
    "Gnebu": ItemData("Subweapons", 0x0809, ItemClassification.filler, 0),
    "Knife Subweapon": ItemData("Subweapons", 0x080A, ItemClassification.useful),
    "Axe Subweapon": ItemData("Subweapons", 0x080B, ItemClassification.filler, 0),
    "Cross": ItemData("Subweapons", 0x080C, ItemClassification.useful, 0),
    "Holy Water": ItemData("Subweapons", 0x080D, ItemClassification.useful, 0),
    "Bible": ItemData("Subweapons", 0x080E, ItemClassification.useful, 0),
    "Javelin": ItemData("Subweapons", 0x080F, ItemClassification.filler, 0),
    "Ricochet Rock": ItemData("Subweapons", 0x0810, ItemClassification.filler, 0),
    "Boomerang": ItemData("Subweapons", 0x0811, ItemClassification.filler, 0),
    "Bwaka Knife": ItemData("Subweapons", 0x0812, ItemClassification.useful),
    "Shuriken": ItemData("Subweapons", 0x0813, ItemClassification.filler, 0),
    "Yagyu Shuriken": ItemData("Subweapons", 0x0814, ItemClassification.filler, 0),
    "Discus": ItemData("Subweapons", 0x0815, ItemClassification.filler, 0),
    "Kunimitsu": ItemData("Subweapons", 0x0816, ItemClassification.filler, 0),
    "Kunai": ItemData("Subweapons", 0x0817, ItemClassification.filler, 0),
    "Paper Airplane": ItemData("Subweapons", 0x0818, ItemClassification.useful),
    "Cream Pie": ItemData("Subweapons", 0x0819, ItemClassification.useful),
    "Crossbow": ItemData("Subweapons", 0x081A, ItemClassification.filler, 0),
    "Dart": ItemData("Subweapons", 0x081B, ItemClassification.filler, 0),
    "Grenade": ItemData("Subweapons", 0x081C, ItemClassification.useful),
    "Steel Ball": ItemData("Subweapons", 0x081D, ItemClassification.useful),
    "Stonewall": ItemData("Subweapons", 0x081E, ItemClassification.useful),
    "Offensive Form": ItemData("Subweapons", 0x081F, ItemClassification.useful),
    "Defensive Form": ItemData("Subweapons", 0x0820, ItemClassification.filler, 0),
    "Taunt": ItemData("Subweapons", 0x0821, ItemClassification.useful),
    "Wrecking Ball": ItemData("Subweapons", 0x0822, ItemClassification.filler, 0),
    "Rampage": ItemData("Subweapons", 0x0823, ItemClassification.filler, 0),
    "Knee Strike": ItemData("Subweapons", 0x0824, ItemClassification.useful),
    "Aura Blast": ItemData("Subweapons", 0x0825, ItemClassification.useful),
    "Rocket Slash": ItemData("Subweapons", 0x0826, ItemClassification.useful, 0),

    "Toad Morph": ItemData("Spells", 0x0827, ItemClassification.progression),
    "Owl Morph": ItemData("Spells", 0x0828, ItemClassification.progression, 0),
    "Sanctuary": ItemData("Spells", 0x0829, ItemClassification.progression),
    "Speed Up": ItemData("Spells", 0x082A, ItemClassification.useful),
    "Berserker": ItemData("Spells", 0x082B, ItemClassification.filler, 0),
    "Eye for an Eye": ItemData("Spells", 0x082C, ItemClassification.useful),
    "Clear Skies": ItemData("Spells", 0x082D, ItemClassification.useful),
    "Time Stop": ItemData("Spells", 0x082E, ItemClassification.useful, 0),
    "Heal": ItemData("Spells", 0x082F, ItemClassification.useful, 0),
    "Cure Poison": ItemData("Spells", 0x0830, ItemClassification.useful),
    "Cure Curse": ItemData("Spells", 0x0831, ItemClassification.filler, 0),
    "STR Boost": ItemData("Spells", 0x0832, ItemClassification.useful),
    "CON Boost": ItemData("Spells", 0x0833, ItemClassification.useful),
    "INT Boost": ItemData("Spells", 0x0834, ItemClassification.useful),
    "MIND Boost": ItemData("Spells", 0x0835, ItemClassification.useful),
    "LUCK Boost": ItemData("Spells", 0x0836, ItemClassification.filler, 0),
    "ALL Boost": ItemData("Spells", 0x0837, ItemClassification.useful),
    "Gale Force": ItemData("Spells", 0x0838, ItemClassification.useful),
    "Rock Riot": ItemData("Spells", 0x0839, ItemClassification.filler, 0),
    "Raging Fire": ItemData("Spells", 0x083A, ItemClassification.useful),
    "Ice Fang": ItemData("Spells", 0x083B, ItemClassification.useful),
    "Thunderbolt": ItemData("Spells", 0x083C, ItemClassification.useful),
    "Spirit of Light": ItemData("Spells", 0x083D, ItemClassification.filler, 0),
    "Dark Rift": ItemData("Spells", 0x083E, ItemClassification.filler, 0),
    "Tempest": ItemData("Spells", 0x083F, ItemClassification.useful),
    "Stone Circle": ItemData("Spells", 0x0840, ItemClassification.filler, 0),
    "Ice Needle": ItemData("Spells", 0x0841, ItemClassification.filler, 0),
    "Explosion": ItemData("Spells", 0x0842, ItemClassification.filler, 0),
    "Chain Lightning": ItemData("Spells", 0x0843, ItemClassification.filler, 0),
    "Piercing Beam": ItemData("Spells", 0x0844, ItemClassification.useful),
    "Nightmare": ItemData("Spells", 0x0845, ItemClassification.filler, 0),
    "Summon Medusa": ItemData("Spells", 0x0846, ItemClassification.filler, 0),
    "Acidic Bubbles": ItemData("Spells", 0x0847, ItemClassification.filler, 0),
    "Hex": ItemData("Spells", 0x0848, ItemClassification.filler, 0),
    "Salamander": ItemData("Spells", 0x0849, ItemClassification.filler, 0),
    "Cocytus": ItemData("Spells", 0x084A, ItemClassification.useful, 0),
    "Thor's Bellow": ItemData("Spells", 0x084B, ItemClassification.filler, 0),
    "Summon Crow": ItemData("Spells", 0x084C, ItemClassification.filler, 0),
    "Summon Skeleton": ItemData("Spells", 0x084D, ItemClassification.filler, 0),
    "Summon Ghost": ItemData("Spells", 0x084E, ItemClassification.filler, 0),
    "Summon Gunman": ItemData("Spells", 0x084F, ItemClassification.filler, 0),
    "Summon Frog": ItemData("Spells", 0x0850, ItemClassification.filler, 0),

    "Rush": ItemData("Dual Crashes", 0x0852, ItemClassification.useful),
    "Holy Lightning": ItemData("Dual Crashes", 0x0853, ItemClassification.useful),
    "Axe Bomber": ItemData("Dual Crashes", 0x0854, ItemClassification.useful),
    "1,000 Blades": ItemData("Dual Crashes", 0x0855, ItemClassification.useful),
    "Volcano": ItemData("Dual Crashes", 0x0856, ItemClassification.useful),
    "Meteor": ItemData("Dual Crashes", 0x0857, ItemClassification.useful),
    "Grand Cruz": ItemData("Dual Crashes", 0x0858, ItemClassification.useful, 0),
    "Divine Storm": ItemData("Dual Crashes", 0x0859, ItemClassification.useful),
    "Dark Gate": ItemData("Dual Crashes", 0x085A, ItemClassification.useful),
    "Greatest Five": ItemData("Dual Crashes", 0x085B, ItemClassification.useful, 0),
    
    "Change Cube": ItemData("Relics", 0x085C, ItemClassification.progression),
    "Call Cube": ItemData("Relics", 0x085D, ItemClassification.progression),
    "Skill Cube": ItemData("Relics", 0x085E, ItemClassification.useful),
    "Wait Cube": ItemData("Relics", 0x085F, ItemClassification.progression),
    "Acrobat Cube": ItemData("Relics", 0x0860, ItemClassification.progression),
    "Push Cube": ItemData("Relics", 0x0861, ItemClassification.progression),
    "Lizard Tail": ItemData("Relics", 0x0862, ItemClassification.progression),
    "Stone of Flight": ItemData("Relics", 0x0863, ItemClassification.progression),
    "Griffon Wing": ItemData("Relics", 0x0864, ItemClassification.progression),
    "Strength Glove": ItemData("Relics", 0x0865, ItemClassification.progression),
    "Spinning Art": ItemData("Relics", 0x0866, ItemClassification.useful, 0),
    "Martial Art": ItemData("Relics", 0x0867, ItemClassification.useful, 0),
    "Critical Art": ItemData("Relics", 0x0868, ItemClassification.useful),
    "Whip Skill 1": ItemData("Relics", 0x0869, ItemClassification.useful),
    "Whip Skill 2": ItemData("Relics", 0x086A, ItemClassification.useful),
    "Book of Spirits": ItemData("Relics", 0x086B, ItemClassification.useful),

    "Portrait Clear": ItemData("Events", None, ItemClassification.progression, 0),
    "Tower Elevator Active": ItemData("Events", None, ItemClassification.progression, 0),
    "Dracula Defeated": ItemData("Events", None, ItemClassification.progression, 0),
    "Brauner Defeated": ItemData("Events", None, ItemClassification.progression, 0),
}


def get_item_names_per_category() -> Dict[str, Set[str]]:
    categories: Dict[str, Set[str]] = {}

    for name, data in item_table.items():
        if data.category != "Events":
            categories.setdefault(data.category, set()).add(name)

    return categories


money_table = [
 "$1",
 "$10",
 "$50",
 "$100",
 "$500",
 "$1000",
 "$2000"
]

consumable_table = [
    "Potion",
    "High Potion",
    "Tonic",
    "High Tonic",
    "Anti-Venom",
    "Uncurse Potion",
    "Beef Jerky",
    "Rice Ball",
    "Mushroom",
    "Corn Soup",
    "Mint Sundae",
    "Cream Puff",
    "Milk",
    "Coffee",
    "Tea",
    "Pudding",
    "Strawberry",
    "Grapes",
    "Hamburger",
    "Fried Chicken",
    "Hot Dog",
    "Pumpkin Pie",
    "Pancake",
    "Tinned Spinach",
    "Paella",
    "Spaghetti",
    "Ice Cream",
    "Meuniere",
    "Boiled Starfish",
    "Wheat Roll",
    "Sachertorte",
    "NY Cheesecake",
    "Mille-feuille",
    "Tarte au Poire",
    "Gateau Fraise",
    "Kugelhopf",
    "Green Tea Cake",
    "Gateau Marron",
    "Langues de Chat",
    "Financier",
    "Tropical Sundae",
    "Pudding Bucket",
    "Piyoko",
    "1000 Year Egg",
    "Jamon Iberico",
    "Spicy Shrimp",
    "Pasta Carbonara",
    "Penne Arrabiata",
    "Powdered Milk",
    "Rotten Durian",
    "Ground Meat",
    "Noodle Bun",
    "Touch & Pop",
    "Moldy Bread",
    "Penters Natural",
    "Beehive",
    "Amanita",
    "Rotten Meat",
    "Spoiled Milk",
    "Rusty Food Tin"
]

good_food_table = [
    "Super Potion",
    "Super Tonic",
    "Tasty Meat",
    "New York Steak",
    "Curry",
    "Ramen Noodles",
    "Melon",
    "Foie Gras",
    "Caviar",
    "Truffle",
    "Peking Duck",
    "Birthday Cake"
]
