from typing import List, Optional, NamedTuple, TYPE_CHECKING
from .Options import NestofEvil

if TYPE_CHECKING:
    from . import PoRWorld


class LocationData(NamedTuple):
    region: str
    name: str
    is_event: Optional[bool] = False


def get_locations(world: "PoRWorld") -> List[LocationData]:
    location_table: List[LocationData] = [
        LocationData("Entrance - Wind's Room", "Quest: Preparations"),

        LocationData("Entrance - Hub", "Entrance: Drawbridge Pit Item"),
        LocationData("Entrance - Hub", "Entrance: Drawbridge Switch Item"),
        LocationData("Entrance - Hub", "Entrance: Drawbridge Upper Item"),
        LocationData("Entrance - Hub", "Entrance: First Passage Upper Item"),
        LocationData("Entrance - Hub", "Entrance: First Passage Lower Item"),
        LocationData("Entrance - Hub", "Entrance: First Passage Hidden Wall"),
        LocationData("Entrance - Hub", "Entrance: Hub Room"),
        LocationData("Entrance - Hub", "Entrance: Above Hub"),
        LocationData("Entrance - Hub", "Entrance: Statue Room Upper"),
        LocationData("Entrance - Hub", "Entrance: Statue Room Above Statue"),
        LocationData("Entrance - Hub", "Entrance: Behemoth Chase Room"),
        LocationData("Entrance - Hub", "Entrance: Double Room Lower"),
        LocationData("Entrance - Behemoth Area", "Entrance: Double Room Upper"),
        LocationData("Entrance - Behemoth Area", "Entrance: Pre-Behemoth Boss Room"),
        LocationData("Entrance - Behemoth Area", "Entrance: Right Hidden Room"),
        LocationData("Entrance - Upper Area", "Entrance: Lilith Room"),
        LocationData("Entrance - Upper Area", "Entrance: Above Metal Block Room"),
        LocationData("Entrance - Upper Area", "Entrance: Center Hidden Room"),
        LocationData("Entrance - Upper Area", "Entrance: Beyond Great Armor Hallway"),

        LocationData("Buried Chamber", "Buried Chamber: Westmost Room"),
        LocationData("Buried Chamber", "Buried Chamber: Central Secret"),
        LocationData("Buried Chamber", "Buried Chamber: West Shaft"),
        LocationData("Buried Chamber", "Buried Chamber: Central Hall"),
        LocationData("Buried Chamber", "Buried Chamber: Hidden Wall Item"),
        LocationData("Buried Chamber", "Buried Chamber: Right Secret"),
        LocationData("Buried Chamber", "Buried Chamber: Right Shade Hall"),
        LocationData("Buried Chamber", "Buried Chamber: Final Shaft Item"),
        LocationData("Buried Chamber", "Buried Chamber: Right Shaft Top"),
        LocationData("Buried Chamber", "Buried Chamber: Eastmost Room"),

        LocationData("Great Stairway - Lower", "Great Stairway: After Keremet Lower"),
        LocationData("Great Stairway - Lower", "Great Stairway: Before Keremet Room"),
        LocationData("Great Stairway - Central Painting Area", "Great Stairway: Left Loft"),
        LocationData("Great Stairway - Central Painting Area", "Great Stairway: Left Loft Lower"),
        LocationData("Great Stairway - Entrance Connector", "Great Stairway: Central Nook"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Upper Grand Staircase Corner Nook"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Upper Grand Staircase Middle Alcove"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Upper Grand Staircase Lower Alcove"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Upper Grand Staircase Upper Alcove"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Lower Grand Staircase Corner Nook"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Lower Grand Staircase Lower Alcove"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Lower Grand Staircase Middle Alcove"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Lower Grand Staircase Upper Alcove"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Upper Underground Room"),
        LocationData("Great Stairway - Staircases", "Great Stairway: After Keremet Upper"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Big Underground Room Upper"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Big Underground Room Hidden Item"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Big Underground Room Lower"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Underground Hidden Room"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Underground East Room"),
        LocationData("Great Stairway - Upper", "Great Stairway: Connector Pipe Left"),
        LocationData("Great Stairway - Upper", "Great Stairway: Connector Pipe Right"),
        LocationData("Great Stairway - Staircases", "Great Stairway: Upper Grand Staircase Top Left Item"),
        LocationData("Great Stairway - Upper", "Great Stairway: Central Upper"),
        LocationData("Great Stairway - Upper", "Great Stairway: Right Loft"),

        LocationData("Tower of Death - Bottom", "Tower of Death: Lower Passage Hidden Item"),
        LocationData("Tower of Death - Bottom", "Tower of Death: Stella Item"),
        LocationData("Tower of Death - First Gear Room", "Tower of Death: Lower Gears Room Spike Shaft"),
        LocationData("Tower of Death - Motorcycles", "Tower of Death: Above Motorcycles"),
        LocationData("Tower of Death - Belt Area", "Tower of Death: Rampart Room"),
        LocationData("Tower of Death - Belt Area", "Tower of Death: Hidden Room"),
        LocationData("Tower of Death - Belt Area", "Tower of Death: Gear Belt Room"),
        LocationData("Tower of Death - Elevator Room", "Tower of Death: Secret Room"),
        LocationData("Tower of Death - Elevator Room", "Tower of Death: Elevator Room Lower"),
        LocationData("Tower of Death - Elevator Room", "Tower of Death: Elevator Room Middle"),
        LocationData("Tower of Death - Elevator Room", "Tower of Death: Elevator Room Top"),
        LocationData("Tower of Death - Second Gear Room", "Tower of Death: Second Gears Room Left"),
        LocationData("Tower of Death - Second Gear Room", "Tower of Death: Passage Hidden Item"),
        LocationData("Tower of Death - Second Gear Room", "Tower of Death: Second Gears Room Right"),
        LocationData("Tower of Death - Second Gear Room", "Tower of Death: Top Gears Room"),
        LocationData("Tower of Death - Second Gear Room", "Tower of Death: Third Gears Room"),
        LocationData("Tower of Death - Top of the Tower", "Tower of Death: Top of the Tower"),
        LocationData("Tower of Death - Top of the Tower", "Tower of Death: Elevator Switch", True),

        LocationData("Master's Keep - Lower", "Master's Keep: Entrance"),
        LocationData("Master's Keep - Main", "Master's Keep: Hidden Room"),
        LocationData("Master's Keep - Main", "Master's Keep: Right Square Room"),
        LocationData("Master's Keep - Portrait Room", "Master's Keep: Whip Trial"),
        LocationData("Master's Keep - Portrait Room", "Lost Gallery: Studio Portrait Fight", True),

        LocationData("City of Haze", "City of Haze: Meat Room"),
        LocationData("City of Haze", "City of Haze: First Passage"),
        LocationData("City of Haze", "City of Haze: First Big Room"),
        LocationData("City of Haze", "City of Haze: Corner Room"),
        LocationData("City of Haze", "City of Haze: Winding Rooms"),
        LocationData("City of Haze", "City of Haze: Chunky Room"),
        LocationData("City of Haze", "City of Haze: Right Corner Room"),
        LocationData("City of Haze", "City of Haze: Bar Left"),
        LocationData("City of Haze", "City of Haze: Bar Right"),
        LocationData("City of Haze", "City of Haze: Register Room"),
        LocationData("City of Haze", "City of Haze: Axe Armor Item"),
        LocationData("City of Haze", "City of Haze: Center Room Top"),
        LocationData("City of Haze", "City of Haze: Center Room Lower"),
        LocationData("City of Haze", "City of Haze: Bread Shelf"),
        LocationData("City of Haze", "City of Haze: Left Plaza"),
        LocationData("City of Haze", "City of Haze: Before Cart Room"),
        LocationData("City of Haze East", "City of Haze: Cart Secret Left"),
        LocationData("City of Haze East", "City of Haze: Cart Secret Right"),
        LocationData("City of Haze - East", "City of Haze: Church Hallway"),
        LocationData("City of Haze - East", "City of Haze: Central Hallway Stairs"),
        LocationData("City of Haze - East", "City of Haze: Heavy Cart Item"),
        LocationData("City of Haze - East", "City of Haze: Axe Courtyard"),
        LocationData("City of Haze - East", "City of Haze: Left Dance Hall Left Item"),
        LocationData("City of Haze - East", "City of Haze: Left Dance Hall Right Item"),
        LocationData("City of Haze - East", "City of Haze: Dance Halls Basement"),
        LocationData("City of Haze - East", "City of Haze: Right Dance Hall Item"),
        LocationData("City of Haze - East", "City of Haze: Right Dance Hall Secret Room"),
        LocationData("City of Haze - East", "City of Haze: Post-Boss Room"),
        LocationData("City of Haze - East", "City of Haze: Tunnel Room Right"),
        LocationData("City of Haze - East", "City of Haze: Tunnel Room Left"),
        LocationData("City of Haze - East", "City of Haze: Dance Halls Vertical Hallway"),
        LocationData("City of Haze - East", "City of Haze: Underground Square Right"),
        LocationData("City of Haze - East", "City of Haze: Underground Secret Room"),
        LocationData("City of Haze - East", "City of Haze: Underground Square Left"),
        LocationData("City of Haze - East", "City of Haze: Central Hallway Lower"),
        LocationData("City of Haze - East", "City of Haze: Boss Room", True),

        LocationData("13th Street - Main", "13th Street: Triple Moth Room"),
        LocationData("13th Street - Main", "13th Street: Behind Final Guard"),
        LocationData("13th Street - Main", "13th Street: Three Amalaric Snipers"),
        LocationData("13th Street - Main", "13th Street: Many Nyxes Room"),
        LocationData("13th Street - Main", "13th Street: Train Room Secret Right"),
        LocationData("13th Street - Main", "13th Street: Underground Secret Room"),
        LocationData("13th Street - Main", "13th Street: Underground Demon Room"),
        LocationData("13th Street - Main", "13th Street: Left Big Room"),
        LocationData("13th Street - Main", "13th Street: Secret Floor Room"),
        LocationData("13th Street - Main", "13th Street: East Courtyard"),
        LocationData("13th Street - Main", "13th Street: Near Big Room"),
        LocationData("13th Street - Main", "13th Street: Bakery Middle"),
        LocationData("13th Street - Main", "13th Street: Right Dance Hall Top Right"),
        LocationData("13th Street - Main", "13th Street: Bakery Left"),
        LocationData("13th Street - Main", "13th Street: Square Room"),
        LocationData("13th Street - Main", "13th Street: Bakery Right"),
        LocationData("13th Street - Main", "13th Street: Right Dance Hall Top Left"),
        LocationData("13th Street - Main", "13th Street: Train Room Secret Left"),
        LocationData("13th Street - Main", "13th Street: Boss Room", True),

        LocationData("Sandy Grave", "Sandy Grave: Sandworm Stomach"),
        LocationData("Sandy Grave", "Sandy Grave: On Statue"),
        LocationData("Sandy Grave", "Sandy Grave: Behind Bricks"),
        LocationData("Sandy Grave", "Sandy Grave: Left Trap"),
        LocationData("Sandy Grave", "Sandy Grave: Right Trap"),
        LocationData("Sandy Grave", "Sandy Grave: Bottom Right Room"),
        LocationData("Sandy Grave", "Sandy Grave: Lower Big Underground Room Bottom"),
        LocationData("Sandy Grave", "Sandy Grave: Lower Big Underground Room Top"),
        LocationData("Sandy Grave", "Sandy Grave: Lonely Mimic Alcove"),
        LocationData("Sandy Grave", "Sandy Grave: Boulder Room Corner Alcove"),
        LocationData("Sandy Grave", "Sandy Grave: Boulder Room Tunnel"),
        LocationData("Sandy Grave", "Sandy Grave: Upper Big Underground Top Right"),
        LocationData("Sandy Grave", "Sandy Grave: Upper Big Underground Top Left"),
        LocationData("Sandy Grave", "Sandy Grave: Eastmost Item"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Pyramid East 1F"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Giant Shaft Upper Item"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Giant Shaft Middle Item"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Giant Shaft Low Item"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Pyramid 3F Lower"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Pyramid 3F Upper"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Pyramid East 5F"),  # check if this is top
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Fleaman Pit"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Mega Ghost Room Upper"),
        LocationData("Sandy Grave - Upper Pyramid", "Sandy Grave: Mega Ghost Room Lower"),
        LocationData("Sandy Grave - Pyramid Top", "Sandy Grave: Pyramid 5F Nook"),
        LocationData("Sandy Grave - Pyramid Top", "Sandy Grave: Boss Room", True),

        LocationData("Forgotten City", "Forgotten City: Outside Left"),
        LocationData("Forgotten City", "Forgotten City: Pyramid East 5F"),
        LocationData("Forgotten City", "Forgotten City: Armored Fleaman Pit"),
        LocationData("Forgotten City", "Forgotten City: Pyramid East 3F"),
        LocationData("Forgotten City", "Forgotten City: Pyramid 5F"),
        LocationData("Forgotten City", "Forgotten City: Pyramid 1F Bricks"),
        LocationData("Forgotten City", "Forgotten City: Lower Boulder Room Tunnel Alcove"),
        LocationData("Forgotten City", "Forgotten City: Lower Boulder Room Upper Alcove"),
        LocationData("Forgotten City", "Forgotten City: Gorgon Room"),
        LocationData("Forgotten City", "Forgotten City: Bottom Chamber"),
        LocationData("Forgotten City - Inner", "Forgotten City: Lower Underground Square Lower Item"),
        LocationData("Forgotten City - Inner", "Forgotten City: Lower Underground Square Upper Item"),
        LocationData("Forgotten City - Inner", "Forgotten City: Upper Underground Square"),
        LocationData("Forgotten City - Inner Upper", "Forgotten City: Pyramid East 1F"),
        LocationData("Forgotten City - Inner Upper", "Forgotten City: Big Shaft Room Left"),
        LocationData("Forgotten City - Inner Upper", "Forgotten City: Big Shaft Room Right"),
        LocationData("Forgotten City - Inner Upper", "Forgotten City: Post-Boss Item"),
        LocationData("Forgotten City - Inner Upper", "Forgotten City: Boss Room", True),

        LocationData("Nation of Fools - Right Lower", "Nation of Fools: Bottom Corner Room"),
        LocationData("Nation of Fools - Right Lower", "Nation of Fools: Bottom-Right Room Left Building"),
        LocationData("Nation of Fools - Right Lower", "Nation of Fools: Bottom-Right Room Middle Building"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Central Top Shaft"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Legion Arena"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Mid-Right Corner Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Left Upper Corner Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Right Horizontal Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Right Bottom Corner Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Top Corner Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Bottom-Left Room Building"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Upper Upside Down"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Bottom Left Medium Square On Wall"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Crevice Item"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Top-Right Room Axe Item"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Left Bottom Corner Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Bottom Right Medium Square On Wall"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Right Vertical Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Top-Right Room Bottom Item"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Top-Left Room Right Building"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Top-Right Room Breakable Wall"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Right Center Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Left Center Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Upside Down Building"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Secret Room"),
        LocationData("Nation of Fools - Main", "Nation of Fools: Boss Room", True),

        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Left Lower Isolated Room"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Right Lower Isolated Room"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Left Upper Isolated Room"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Right Upper Isolated Room"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Left Upper Big Corner"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Upper Left Big Room Middle Building"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Upper Right Big Room Right Side"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Upper Left Big Room Left Building"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Upper Left Lower Corner Upright Building"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Right Upper Big Corner On Wall"),
        LocationData("Burnt Paradise - Entrance", "Burnt Paradise: Upper Right Big Room"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Left Big Corner"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Lower Left Big Room"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Lower Vertical Hall"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Bottom Corner"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Bottom Right Breakable Wall"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Bottom Right Big Room"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Bottom Right Corner Room"),
        LocationData("Burnt Paradise - Bottom", "Burnt Paradise: Boss Room", True),

        LocationData("Forest of Doom - Main", "Forest of Doom: Left Atrium Big Room"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Right Atrium East Square Room Right"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Left Atrium Top"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Right Atrium East Top Room"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Right Atrium East Square Room Left"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Right Atrium West Top Room"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Left Atrium Breakable Wall"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Left Atrium Middle Room"),
        LocationData("Forest of Doom - Main", "Forest of Doom: Left Atrium Upper Room"),
        LocationData("Forest of Doom - Cave", "Forest of Doom: Secret Cave Room"),
        LocationData("Forest of Doom - Cave", "Forest of Doom: Near Cave Save Breakable Wall"),
        LocationData("Forest of Doom - Cave", "Forest of Doom: Post-Boss Room"),
        LocationData("Forest of Doom - Cave", "Forest of Doom: Boss Room", True),

        LocationData("Dark Academy - Right Building", "Dark Academy: Right Building Center Room"),
        LocationData("Dark Academy - Right Building", "Dark Academy: Right Building Top Floor"),
        LocationData("Dark Academy - Main", "Dark Academy: Main Building Ghoul Room"),
        LocationData("Dark Academy - Main", "Dark Academy: Main Building Three Toads"),
        LocationData("Dark Academy - Main", "Dark Academy: Main Building Secret Ceiling"),
        LocationData("Dark Academy - Main", "Dark Academy: Main Building Entrance"),
        LocationData("Dark Academy - Main", "Dark Academy: Main Building Secret Malphas Room"),
        LocationData("Dark Academy - Main", "Dark Academy: West Building Breakable Wall"),
        LocationData("Dark Academy - Main", "Dark Academy: Main Building Square Room Breakable Wall"),
        LocationData("Dark Academy - Main", "Dark Academy: Main Building Minotaur Room"),
        LocationData("Dark Academy - Main", "Dark Academy: West Building Top Floor Right"),
        LocationData("Dark Academy - Main", "Dark Academy: West Building Top Floor Left"),
        LocationData("Dark Academy - Main", "Dark Academy: Boss Room", True)
    ]

    if world.options.goal:
        location_table += [
            LocationData("The Throne Room", "The Throne Room: Above Throne Left"),
            LocationData("The Throne Room", "The Throne Room: Great Stairs Under Stairs"),
            LocationData("The Throne Room", "The Throne Room: Great Stairs Center"),
            LocationData("The Throne Room", "The Throne Room: Above Throne Right"),
            LocationData("The Throne Room", "The Throne Room: Great Stairs Hidden"),
            LocationData("The Throne Room", "The Throne Room: Great Stairs Left"),
            LocationData("The Throne Room", "The Throne Room: Dracula", True),
        ]

    if world.options.nest_of_evil_state != NestofEvil.option_removed:
        location_table += [
         LocationData("Nest of Evil", "Nest of Evil: Doppelganger Reward"),
         LocationData("Nest of Evil", "Nest of Evil: First Item"),
         LocationData("Nest of Evil", "Nest of Evil: Second Item")]

    return location_table
    # LocationData("Dummy", "Dummy"),
