from typing import NamedTuple
#  IDs are matched to which internal Flag number the location uses
#  Because of this, they are asynchronous and out of order from what is expected
#  They are listed here in numerical order for clarity

class LocationInformation(NamedTuple):  # In-game information used to define each Location in the ROM.
    pointer: int
    file: str
    is_grounded: bool = False
    location_type: str = "Normal"

location_ids = {
    "Entrance: Drawbridge Pit Item": 0x01,
    "Entrance: Drawbridge Switch Item": 0x02,
    "City of Haze: Church Hallway": 0x03,
    "Entrance: Statue Room Above Statue": 0x04,
    "City of Haze: Post-Boss Room": 0x05,
    "City of Haze: Heavy Cart Item": 0x06,
    "Sandy Grave: Pyramid 5F Nook": 0x07,
    "Great Stairway: After Keremet Lower": 0x09,
    "Forgotten City: Pyramid 1F Bricks": 0x0A,
    "Nation of Fools: Central Top Shaft": 0x0D,
    "Entrance: Above Hub": 0x0E,
    "Entrance: Double Room Upper": 0x0F,
    "Nation of Fools: Legion Arena": 0x10,
    "Forest of Doom: Post-Boss Room": 0x11,
    "Dark Academy: Right Building Center Room": 0x12,
    "The Throne Room: Above Throne Left": 0x13,
    "Sandy Grave: Boulder Room Tunnel": 0x14,
    "City of Haze: Before Cart Room": 0x16,
    "City of Haze: Underground Square Right": 0x17,
    "Sandy Grave: Upper Big Underground Top Right": 0x18,
    "Nation of Fools: Bottom Corner Room": 0x19,
    "Nation of Fools: Mid-Right Corner Room": 0x1A,
    "Sandy Grave: Lower Big Underground Room Bottom": 0x1B,
    "Sandy Grave: Left Trap": 0x1C,
    "Buried Chamber: Central Secret": 0x20,
    "Sandy Grave: Sandworm Stomach": 0x21,
    "Tower of Death: Second Gears Room Left": 0x22,
    "Great Stairway: Lower Grand Staircase Corner Nook": 0x23,
    "Master's Keep: Entrance": 0x24,
    "Forest of Doom: Left Atrium Big Room": 0x25,
    "Forgotten City: Big Shaft Room Left": 0x26,
    "Nation of Fools: Left Upper Corner Room": 0x27,
    "Dark Academy: Main Building Ghoul Room": 0x28,
    "13th Street: Triple Moth Room": 0x29,
    "Tower of Death: Secret Room": 0x2A,
    "Nation of Fools: Right Horizontal Room": 0x2B,
    "Burnt Paradise: Left Lower Isolated Room": 0x2C,
    "Burnt Paradise: Right Lower Isolated Room": 0x2D,
    "The Throne Room: Great Stairs Under Stairs": 0x2E,
    "13th Street: Behind Final Guard": 0x2F,
    "Buried Chamber: Right Secret": 0x30,
    "Sandy Grave: Bottom Right Room": 0x31,
    "Tower of Death: Passage Hidden Item": 0x32,
    "Great Stairway: Left Loft Lower": 0x33,
    "Entrance: Center Hidden Room": 0x35,
    "Forgotten City: Big Shaft Room Right": 0x36,
    "Nation of Fools: Right Bottom Corner Room": 0x37,
    "Master's Keep: Hidden Room": 0x38,
    "13th Street: Three Amalaric Snipers": 0x39,
    "Dark Academy: Main Building Three Toads": 0x3A,
    "Nation of Fools: Top Corner Room": 0x3B,
    "Burnt Paradise: Left Upper Isolated Room": 0x3C,
    "Burnt Paradise: Right Upper Isolated Room": 0x3D,
    "The Throne Room: Great Stairs Center": 0x3E,
    "Forgotten City: Upper Underground Square": 0x3F,
    "Entrance: Double Room Lower": 0x40,
    "Buried Chamber: Westmost Room": 0x41,
    "Sandy Grave: Pyramid East 1F": 0x42,
    "City of Haze: Register Room": 0x46,
    "City of Haze: Bar Left": 0x47,
    "Nation of Fools: Bottom-Left Room Building": 0x48,
    "Sandy Grave: Pyramid 3F Lower": 0x49,
    "Tower of Death: Rampart Room": 0x4A,
    "Entrance: Beyond Great Armor Hallway": LocationInformation(0x02305020, "overlay_79"),
    "Tower of Death: Elevator Room Lower": 0x4C,
    "Forest of Doom: Right Atrium East Square Room Right": 0x4D,
    "Forgotten City: Outside Left": 0x4E,
    "Sandy Grave: Upper Big Underground Top Left": 0x4F,
    "Burnt Paradise: Left Upper Big Corner": 0x51,
    "Great Stairway: Upper Grand Staircase Top Left Item": 0x53,
    "City of Haze: Axe Courtyard": 0x54,
    "Tower of Death: Top of the Tower": 0x55,
    "Great Stairway: Upper Underground Room": 0x56,
    "Entrance: Drawbridge Upper Item": 0x57,
    "Entrance: Statue Room Upper": 0x58,
    "Tower of Death: Second Gears Room Right": 0x59,
    "Tower of Death: Lower Gears Room Spike Shaft": 0x5A,
    "Master's Keep: Right Square Room": 0x5D,
    "City of Haze: Central Hallway Stairs": 0x60,
    "Buried Chamber: Right Shade Hall": 0x61,
    "City of Haze: Right Corner Room": 0x64,
    "City of Haze: Left Plaza": 0x65,
    "Great Stairway: Underground Hidden Room": 0x66,
    "Sandy Grave: Lower Big Underground Room Top": 0x67,
    "Nation of Fools: Upper Upside Down": 0x68,
    "Forgotten City: Lower Boulder Room Tunnel Alcove": 0x69,
    "Dark Academy: Main Building Secret Ceiling": 0x6B,
    "Forest of Doom: Secret Cave Room": 0x6C,
    "Nest of Evil: Doppelganger Reward": 0x6D,
    "City of Haze: Center Room Lower": 0x6E,
    "Sandy Grave: On Statue": 0x6F,
    "Tower of Death: Third Gears Room": 0x70,
    "Entrance: Above Metal Block Room": 0x71,
    "Dark Academy: Main Building Entrance": 0x72,
    "Burnt Paradise: Bottom Corner": 0x73,
    "Forest of Doom: Left Atrium Top": 0x75,
    "Great Stairway: Before Keremet Room": 0x76,
    "Forgotten City: Lower Boulder Room Upper Alcove": 0x77,
    "Entrance: First Passage Upper Item": 0x78,
    "Great Stairway: Upper Grand Staircase Corner Nook": 0x79,
    "Burnt Paradise: Bottom Right Big Room": 0x7A,
    "Entrance: Right Hidden Room": 0x7B,
    "Entrance: First Passage Lower Item": 0x7C,
    "City of Haze: Left Dance Hall Right Item": 0x7E,
    "City of Haze: Tunnel Room Left": 0x7F,
    "Burnt Paradise: Upper Left Big Room Middle Building": 0x82,
    "City of Haze: Chunky Room": 0x84,
    "Entrance: Pre-Behemoth Boss Room": 0x88,
    "Great Stairway: After Keremet Upper": 0x89,
    "Tower of Death: Gear Belt Room": 0x8A,
    "City of Haze: Dance Halls Basement": 0x8B,
    "City of Haze: Central Hallway Lower": 0x8C,
    "Burnt Paradise: Upper Right Big Room Right Side": 0x8F,
    "Buried Chamber: Central Hall": 0x92,
    "Great Stairway: Central Nook": 0x93,
    "Sandy Grave: Eastmost Item": 0x94,
    "Sandy Grave: Behind Bricks": 0x95,
    "City of Haze: Underground Square Left": 0xA0,
    "Great Stairway: Upper Grand Staircase Upper Alcove": 0xA1,
    "City of Haze: Right Dance Hall Secret Room": 0xA7,
    "Nation of Fools: Bottom Left Medium Square On Wall": 0xA8,
    "City of Haze: First Big Room": 0xA9,
    "Buried Chamber: Final Shaft Item": 0xAA,
    "Great Stairway: Central Upper": 0xAB,
    "Forest of Doom: Right Atrium East Top Room": 0xAC,
    "Dark Academy: Right Building Top Floor": 0xAD,
    "Sandy Grave: Boulder Room Corner Alcove": 0xAE,
    "Forgotten City: Post-Boss Item": 0xAF,
    "City of Haze: Cart Secret Left": 0xB0,
    "City of Haze: Winding Rooms": 0xB3,
    "Great Stairway: Lower Grand Staircase Lower Alcove": 0xB4,
    "Forest of Doom: Right Atrium East Square Room Left": 0xB5,
    "Forgotten City: Bottom Chamber": 0xB9,
    "City of Haze: Meat Room": 0xBB,
    "Great Stairway: Big Underground Room Hidden Item": 0xBF,
    "Great Stairway: Right Loft": 0xC0,
    "Great Stairway: Left Loft": 0xC1,
    "Nation of Fools: Bottom-Right Room Left Building": 0xC2,
    "13th Street: Many Nyxes Room": 0xC4,
    "The Throne Room: Above Throne Right": 0xC5,
    "City of Haze: Tunnel Room Right": 0xC8,
    "Great Stairway: Lower Grand Staircase Upper Alcove": 0xCA,
    "Great Stairway: Underground East Room": 0xCB,
    "Tower of Death: Elevator Room Top": 0xCC,
    "Entrance: Hub Room": 0xCD,
    "Buried Chamber: Eastmost Room": 0xCE,
    "Tower of Death: Hidden Room": 0xD1,
    "Nation of Fools: Bottom-Right Room Middle Building": 0xD4,
    "Forgotten City: Pyramid 5F": 0xD5,
    "13th Street: Train Room Secret Right": 0xD6,
    "City of Haze: Left Dance Hall Left Item": 0xD8,
    "Great Stairway: Big Underground Room Lower": 0xDA,
    "Tower of Death: Elevator Room Middle": 0xDB,
    "Nation of Fools: Crevice Item": 0xDC,
    "City of Haze: First Passage": 0xDD,
    "Forgotten City: Gorgon Room": 0xDE,
    "City of Haze: Axe Armor Item": 0xE0,
    "Sandy Grave: Giant Shaft Upper Item": 0xE1,
    "City of Haze: Dance Halls Vertical Hallway": 0xE2,
    "Tower of Death: Above Motorcycles": 0xE3,
    "Nation of Fools: Top-Right Room Axe Item": 0xE4,
    "Dark Academy: Main Building Secret Malphas Room": 0xE5,
    "13th Street: Underground Secret Room": 0xE6,
    "Great Stairway: Big Underground Room Upper": 0xE7,
    "Forest of Doom: Right Atrium West Top Room": 0xE8,
    "Burnt Paradise: Upper Left Big Room Left Building": 0xE9,
    "13th Street: Underground Demon Room": 0xEA,
    "Sandy Grave: Mega Ghost Room Lower": 0xEB,
    "13th Street: Left Big Room": 0xEC,
    "City of Haze: Bread Shelf": 0xED,
    "Burnt Paradise: Upper Left Lower Corner Upright Building": 0xEE,
    "City of Haze: Underground Secret Room": 0xEF,
    "Sandy Grave: Mega Ghost Room Upper": 0xF0,
    "Burnt Paradise: Lower Left Big Room": 0xF1,
    "13th Street: Secret Floor Room": 0xF3,
    "City of Haze: Right Dance Hall Item": 0xF7,
    "Tower of Death: Top Gears Room": 0xF9,
    "13th Street: East Courtyard": 0xFA,
    "City of Haze: Corner Room": 0xFC,
    "Sandy Grave: Giant Shaft Middle Item": 0xFD,
    "Entrance: Lilith Room": 0x101,
    "Sandy Grave: Right Trap": 0x103,
    "Nation of Fools: Left Bottom Corner Room": 0x104,
    "Forgotten City: Lower Underground Square Upper Item": 0x105,
    "City of Haze: Center Room Top": 0x10E,
    "Great Stairway: Upper Grand Staircase Middle Alcove": 0x10F,
    "Buried Chamber: Right Shaft Top": 0x110,
    "Sandy Grave: Pyramid 3F Upper": 0x113,
    "Nation of Fools: Bottom Right Medium Square On Wall": 0x114,
    "Sandy Grave: Lonely Mimic Alcove": 0x116,
    "13th Street: Near Big Room": 0x118,
    "Forgotten City: Pyramid East 3F": 0x119,
    "Great Stairway: Upper Grand Staircase Lower Alcove": 0x11B,
    "Nation of Fools: Right Vertical Room": 0x11C,
    "Sandy Grave: Fleaman Pit": 0x11E,
    "Nation of Fools: Top-Right Room Bottom Item": 0x11F,
    "Forgotten City: Pyramid East 5F": 0x122,
    "Burnt Paradise: Lower Vertical Hall": 0x123,
    "Buried Chamber: West Shaft": 0x124,
    "Great Stairway: Lower Grand Staircase Middle Alcove": 0x127,
    "Entrance: Behemoth Chase Room": 0x12C,
    "Entrance: First Passage Hidden Wall": 0x12D,
    "Tower of Death: Lower Passage Hidden Item": 0x131,
    "Dark Academy: West Building Breakable Wall": 0x134,
    "Forgotten City: Armored Fleaman Pit": 0x137,
    "Nation of Fools: Top-Left Room Right Building": 0x13F,
    "Forest of Doom: Left Atrium Breakable Wall": 0x140,
    "Sandy Grave: Giant Shaft Low Item": 0x144,
    "The Throne Room: Great Stairs Hidden": 0x145,
    "Nation of Fools: Top-Right Room Breakable Wall": 0x146,
    "Burnt Paradise: Bottom Right Breakable Wall": 0x147,
    "Burnt Paradise: Right Upper Big Corner On Wall": 0x148,
    "Nation of Fools: Right Center Room": 0x149,
    "Burnt Paradise: Left Big Corner": 0x14A,
    "Buried Chamber: Hidden Wall Item": 0x014C,
    "13th Street: Bakery Middle": 0x14D,
    "City of Haze: Cart Secret Right": 0x14E,
    "13th Street: Right Dance Hall Top Right": 0x150,
    "13th Street: Bakery Left": 0x152,
    "13th Street: Train Room Secret Left": 0x153,
    "City of Haze: Bar Right": 0x154,
    "13th Street: Square Room": 0x155,
    "13th Street: Bakery Right": 0x156,
    "Burnt Paradise: Bottom Right Corner Room": 0x157,
    "Nation of Fools: Left Center Room": 0x15F,
    "Dark Academy: Main Building Square Room Breakable Wall": 0x160,
    "Nation of Fools: Upside Down Building": 0x161,
    "Dark Academy: Main Building Minotaur Room": 0x163,
    "Dark Academy: West Building Top Floor Right": 0x164,
    "Nation of Fools: Secret Room": 0x166,
    "Forest of Doom: Left Atrium Middle Room": 0x167,
    "Burnt Paradise: Upper Right Big Room": 0x16B,
    "Forest of Doom: Near Cave Save Breakable Wall": 0x16C,
    "Sandy Grave: Pyramid East 5F": 0x173,
    "Nest of Evil: First Item": 0x175,
    "Nest of Evil: Second Item": 0x176,
    "Forest of Doom: Left Atrium Upper Room": 0x177,
    "Great Stairway: Connector Pipe Left": 0x180,
    "Great Stairway: Connector Pipe Right": 0x181,
    "The Throne Room: Great Stairs Left": 0x182,
    "13th Street: Right Dance Hall Top Left": 0x183,
    "Dark Academy: West Building Top Floor Left": 0x184,
    "Forgotten City: Pyramid East 1F": 0x185,
    "Forgotten City: Lower Underground Square Lower Item": 0x186,
    "Tower of Death: Stella Item": 0x187,
    "Master's Keep: Whip Trial": 0x188,

    "Quest: Preparations": 0x0200,
    "Quest: Supersonic Punch": 0x0201,
    "Quest: Ghosts of the Desert": 0x0202,
    "Quest: Defender of the Stairs": 0x0203,
    "Quest: The Spinning Art": 0x0204,
    "Quest: Art of the Zephyr": 0x0205,
    "Quest: Find the King of Birds": 0x0206,
    "Quest: Overcome the Curse": 0x0207,
    "Quest: The Statue's Tear": 0x0208,
    "Quest: The Martial Art": 0x0209,
    "Quest: Holy Appearance": 0x020A,
    "Quest: Number of Fortune": 0x020B,
    "Quest: Mental Training 1": 0x020C,
    "Quest: Mental Training 2": 0x020D,
    "Quest: The Spear of Legend": 0x020E,
    "Quest: Mental Training 3": 0x020F,
    "Quest: Defeat the Ghoul King": 0x0211,
    "Quest: Abandon Greed": 0x0212,
    "Quest: A Rank Hunter": 0x0213,
    "Quest: Mental Training 4": 0x0214,
    "Quest: S Rank Hunter": 0x0215,
    "Quest: The Gambler": 0x0216,
    "Quest: Hands of the Clock": 0x0217,
    "Quest: Poison vs. Poison": 0x0218,
    "Quest: Build Your Strength 1": 0x0219,
    "Quest: Build Your Strength 2": 0x021A,
    "Quest: The Lonely Stage": 0x021B,
    "Quest: Build Your Strength 3": 0x021C,
    "Quest: Pray Before the Cross": 0x021D,
    "Quest: Build Your Strength 4": 0x021E,
    "Quest: Lost Page": 0x021F,
    "Quest: The Hundred Tasks": 0x0220,
    "Quest: Master the Holy Power": 0x0221,
    "Quest: Almighty": 0x0222,
    "Quest: The Great Sage": 0x0223,
    "Quest: Kill Gergoth": 0x0224
    }

location_data_table = {
    "Entrance: Drawbridge Pit Item": LocationInformation(0x022F9110, "overlay_78"),
    "Entrance: Drawbridge Switch Item": LocationInformation(0x022F911C, "overlay_78"),
    "City of Haze: Church Hallway": LocationInformation(0x022F6E7C, "overlay_94"),
    "Entrance: Statue Room Above Statue": LocationInformation(0x02304E64, "overlay_79"),
    "City of Haze: Post-Boss Room": LocationInformation(0x02302A18, "overlay_95"),
    
    "City of Haze: Heavy Cart Item": 0x06,
    "Sandy Grave: Pyramid 5F Nook": 0x07,
    "Great Stairway: After Keremet Lower": 0x09,
    "Forgotten City: Pyramid 1F Bricks": 0x0A,
    "Nation of Fools: Central Top Shaft": 0x0D,
    "Entrance: Above Hub": LocationInformation(0x02304A8C, "overlay_79"),
    "Entrance: Double Room Upper": LocationInformation(0x02309140, "overlay_119"),
    "Nation of Fools: Legion Arena": 0x10,
    "Forest of Doom: Post-Boss Room": 0x11,
    "Dark Academy: Right Building Center Room": 0x12,
    "The Throne Room: Above Throne Left": 0x13,
    "Sandy Grave: Boulder Room Tunnel": 0x14,
    "City of Haze: Before Cart Room": 0x16,
    "City of Haze: Underground Square Right": 0x17,
    "Sandy Grave: Upper Big Underground Top Right": 0x18,
    "Nation of Fools: Bottom Corner Room": 0x19,
    "Nation of Fools: Mid-Right Corner Room": 0x1A,
    "Sandy Grave: Lower Big Underground Room Bottom": 0x1B,
    "Sandy Grave: Left Trap": 0x1C,
    "Buried Chamber: Central Secret": 0x20,
    "Sandy Grave: Sandworm Stomach": 0x21,
    "Tower of Death: Second Gears Room Left": 0x22,
    "Great Stairway: Lower Grand Staircase Corner Nook": 0x23,
    "Master's Keep: Entrance": 0x24,
    "Forest of Doom: Left Atrium Big Room": 0x25,
    "Forgotten City: Big Shaft Room Left": 0x26,
    "Nation of Fools: Left Upper Corner Room": 0x27,
    "Dark Academy: Main Building Ghoul Room": 0x28,
    "13th Street: Triple Moth Room": 0x29,
    "Tower of Death: Secret Room": 0x2A,
    "Nation of Fools: Right Horizontal Room": 0x2B,
    "Burnt Paradise: Left Lower Isolated Room": 0x2C,
    "Burnt Paradise: Right Lower Isolated Room": 0x2D,
    "The Throne Room: Great Stairs Under Stairs": 0x2E,
    "13th Street: Behind Final Guard": 0x2F,
    "Buried Chamber: Right Secret": 0x30,
    "Sandy Grave: Bottom Right Room": 0x31,
    "Tower of Death: Passage Hidden Item": 0x32,
    "Great Stairway: Left Loft Lower": 0x33,
    "Entrance: Center Hidden Room": LocationInformation(0x02304F0C, "overlay_79"),
    "Forgotten City: Big Shaft Room Right": 0x36,
    "Nation of Fools: Right Bottom Corner Room": 0x37,
    "Master's Keep: Hidden Room": 0x38,
    "13th Street: Three Amalaric Snipers": 0x39,
    "Dark Academy: Main Building Three Toads": 0x3A,
    "Nation of Fools: Top Corner Room": 0x3B,
    "Burnt Paradise: Left Upper Isolated Room": 0x3C,
    "Burnt Paradise: Right Upper Isolated Room": 0x3D,
    "The Throne Room: Great Stairs Center": 0x3E,
    "Forgotten City: Upper Underground Square": 0x3F,
    "Entrance: Double Room Lower": LocationInformation(0x0230914C, "overlay_119"),
    "Buried Chamber: Westmost Room": 0x41,
    "Sandy Grave: Pyramid East 1F": 0x42,
    "City of Haze: Register Room": 0x46,
    "City of Haze: Bar Left": 0x47,
    "Nation of Fools: Bottom-Left Room Building": 0x48,
    "Sandy Grave: Pyramid 3F Lower": 0x49,
    "Tower of Death: Rampart Room": 0x4A,
    "Entrance: Beyond Great Armor Hallway": 0x4B,
    "Tower of Death: Elevator Room Lower": 0x4C,
    "Forest of Doom: Right Atrium East Square Room Right": 0x4D,
    "Forgotten City: Outside Left": 0x4E,
    "Sandy Grave: Upper Big Underground Top Left": 0x4F,
    "Burnt Paradise: Left Upper Big Corner": 0x51,
    "Great Stairway: Upper Grand Staircase Top Left Item": 0x53,
    "City of Haze: Axe Courtyard": 0x54,
    "Tower of Death: Top of the Tower": 0x55,
    "Great Stairway: Upper Underground Room": 0x56,
    "Entrance: Drawbridge Upper Item": LocationInformation(0x022F9128, "overlay_78"),
    "Entrance: Statue Room Upper": LocationInformation(0x02304E70, "overlay_79"),
    "Tower of Death: Second Gears Room Right": 0x59,
    "Tower of Death: Lower Gears Room Spike Shaft": 0x5A,
    "Master's Keep: Right Square Room": 0x5D,
    "City of Haze: Central Hallway Stairs": 0x60,
    "Buried Chamber: Right Shade Hall": 0x61,
    "City of Haze: Right Corner Room": 0x64,
    "City of Haze: Left Plaza": 0x65,
    "Great Stairway: Underground Hidden Room": 0x66,
    "Sandy Grave: Lower Big Underground Room Top": 0x67,
    "Nation of Fools: Upper Upside Down": 0x68,
    "Forgotten City: Lower Boulder Room Tunnel Alcove": 0x69,
    "Dark Academy: Main Building Secret Ceiling": 0x6B,
    "Forest of Doom: Secret Cave Room": 0x6C,
    "Nest of Evil: Doppelganger Reward": 0x6D,
    "City of Haze: Center Room Lower": 0x6E,
    "Sandy Grave: On Statue": 0x6F,
    "Tower of Death: Third Gears Room": 0x70,
    "Entrance: Above Metal Block Room": LocationInformation(0x02304F3C, "overlay_79"),
    "Dark Academy: Main Building Entrance": 0x72,
    "Burnt Paradise: Bottom Corner": 0x73,
    "Forest of Doom: Left Atrium Top": 0x75,
    "Great Stairway: Before Keremet Room": 0x76,
    "Forgotten City: Lower Boulder Room Upper Alcove": 0x77,
    "Entrance: First Passage Upper Item": LocationInformation(0x02304AEC, "overlay_79"),
    "Great Stairway: Upper Grand Staircase Corner Nook": 0x79,
    "Burnt Paradise: Bottom Right Big Room": 0x7A,
    "Entrance: Right Hidden Room": LocationInformation(0x022F92C0, "overlay_78"),
    "Entrance: First Passage Lower Item": LocationInformation(0x02304AE0, "overlay_79"),
    "City of Haze: Left Dance Hall Right Item": 0x7E,
    "City of Haze: Tunnel Room Left": 0x7F,
    "Burnt Paradise: Upper Left Big Room Middle Building": 0x82,
    "City of Haze: Chunky Room": 0x84,
    "Entrance: Pre-Behemoth Boss Room": LocationInformation(0x022F91E8, "overlay_78"),
    "Great Stairway: After Keremet Upper": 0x89,
    "Tower of Death: Gear Belt Room": 0x8A,
    "City of Haze: Dance Halls Basement": 0x8B,
    "City of Haze: Central Hallway Lower": 0x8C,
    "Burnt Paradise: Upper Right Big Room Right Side": 0x8F,
    "Buried Chamber: Central Hall": 0x92,
    "Great Stairway: Central Nook": 0x93,
    "Sandy Grave: Eastmost Item": 0x94,
    "Sandy Grave: Behind Bricks": 0x95,
    "City of Haze: Underground Square Left": 0xA0,
    "Great Stairway: Upper Grand Staircase Upper Alcove": 0xA1,
    "City of Haze: Right Dance Hall Secret Room": 0xA7,
    "Nation of Fools: Bottom Left Medium Square On Wall": 0xA8,
    "City of Haze: First Big Room": 0xA9,
    "Buried Chamber: Final Shaft Item": 0xAA,
    "Great Stairway: Central Upper": 0xAB,
    "Forest of Doom: Right Atrium East Top Room": 0xAC,
    "Dark Academy: Right Building Top Floor": 0xAD,
    "Sandy Grave: Boulder Room Corner Alcove": 0xAE,
    "Forgotten City: Post-Boss Item": 0xAF,
    "City of Haze: Cart Secret Left": 0xB0,
    "City of Haze: Winding Rooms": 0xB3,
    "Great Stairway: Lower Grand Staircase Lower Alcove": 0xB4,
    "Forest of Doom: Right Atrium East Square Room Left": 0xB5,
    "Forgotten City: Bottom Chamber": 0xB9,
    "City of Haze: Meat Room": 0xBB,
    "Great Stairway: Big Underground Room Hidden Item": 0xBF,
    "Great Stairway: Right Loft": 0xC0,
    "Great Stairway: Left Loft": 0xC1,
    "Nation of Fools: Bottom-Right Room Left Building": 0xC2,
    "13th Street: Many Nyxes Room": 0xC4,
    "The Throne Room: Above Throne Right": 0xC5,
    "City of Haze: Tunnel Room Right": 0xC8,
    "Great Stairway: Lower Grand Staircase Upper Alcove": 0xCA,
    "Great Stairway: Underground East Room": 0xCB,
    "Tower of Death: Elevator Room Top": 0xCC,
    "Entrance: Hub Room": LocationInformation(0x02304AB0, "overlay_79"),
    "Buried Chamber: Eastmost Room": 0xCE,
    "Tower of Death: Hidden Room": 0xD1,
    "Nation of Fools: Bottom-Right Room Middle Building": 0xD4,
    "Forgotten City: Pyramid 5F": 0xD5,
    "13th Street: Train Room Secret Right": 0xD6,
    "City of Haze: Left Dance Hall Left Item": 0xD8,
    "Great Stairway: Big Underground Room Lower": 0xDA,
    "Tower of Death: Elevator Room Middle": 0xDB,
    "Nation of Fools: Crevice Item": 0xDC,
    "City of Haze: First Passage": 0xDD,
    "Forgotten City: Gorgon Room": 0xDE,
    "City of Haze: Axe Armor Item": 0xE0,
    "Sandy Grave: Giant Shaft Upper Item": 0xE1,
    "City of Haze: Dance Halls Vertical Hallway": 0xE2,
    "Tower of Death: Above Motorcycles": 0xE3,
    "Nation of Fools: Top-Right Room Axe Item": 0xE4,
    "Dark Academy: Main Building Secret Malphas Room": 0xE5,
    "13th Street: Underground Secret Room": 0xE6,
    "Great Stairway: Big Underground Room Upper": 0xE7,
    "Forest of Doom: Right Atrium West Top Room": 0xE8,
    "Burnt Paradise: Upper Left Big Room Left Building": 0xE9,
    "13th Street: Underground Demon Room": 0xEA,
    "Sandy Grave: Mega Ghost Room Lower": 0xEB,
    "13th Street: Left Big Room": 0xEC,
    "City of Haze: Bread Shelf": 0xED,
    "Burnt Paradise: Upper Left Lower Corner Upright Building": 0xEE,
    "City of Haze: Underground Secret Room": 0xEF,
    "Sandy Grave: Mega Ghost Room Upper": 0xF0,
    "Burnt Paradise: Lower Left Big Room": 0xF1,
    "13th Street: Secret Floor Room": 0xF3,
    "City of Haze: Right Dance Hall Item": 0xF7,
    "Tower of Death: Top Gears Room": 0xF9,
    "13th Street: East Courtyard": 0xFA,
    "City of Haze: Corner Room": 0xFC,
    "Sandy Grave: Giant Shaft Middle Item": 0xFD,
    "Entrance: Lilith Room": LocationInformation(0x02304E28, "overlay_79"),
    "Sandy Grave: Right Trap": 0x103,
    "Nation of Fools: Left Bottom Corner Room": 0x104,
    "Forgotten City: Lower Underground Square Upper Item": 0x105,
    "City of Haze: Center Room Top": 0x10E,
    "Great Stairway: Upper Grand Staircase Middle Alcove": 0x10F,
    "Buried Chamber: Right Shaft Top": 0x110,
    "Sandy Grave: Pyramid 3F Upper": 0x113,
    "Nation of Fools: Bottom Right Medium Square On Wall": 0x114,
    "Sandy Grave: Lonely Mimic Alcove": 0x116,
    "13th Street: Near Big Room": 0x118,
    "Forgotten City: Pyramid East 3F": 0x119,
    "Great Stairway: Upper Grand Staircase Lower Alcove": 0x11B,
    "Nation of Fools: Right Vertical Room": 0x11C,
    "Sandy Grave: Fleaman Pit": 0x11E,
    "Nation of Fools: Top-Right Room Bottom Item": 0x11F,
    "Forgotten City: Pyramid East 5F": 0x122,
    "Burnt Paradise: Lower Vertical Hall": 0x123,
    "Buried Chamber: West Shaft": 0x124,
    "Great Stairway: Lower Grand Staircase Middle Alcove": 0x127,
    "Entrance: Behemoth Chase Room": LocationInformation(0x02304DA4, "overlay_79"),
    "Entrance: First Passage Hidden Wall": LocationInformation(0x02304B34, "overlay_79"),
    "Tower of Death: Lower Passage Hidden Item": 0x131,
    "Dark Academy: West Building Breakable Wall": 0x134,
    "Forgotten City: Armored Fleaman Pit": 0x137,
    "Nation of Fools: Top-Left Room Right Building": 0x13F,
    "Forest of Doom: Left Atrium Breakable Wall": 0x140,
    "Sandy Grave: Giant Shaft Low Item": 0x144,
    "The Throne Room: Great Stairs Hidden": 0x145,
    "Nation of Fools: Top-Right Room Breakable Wall": 0x146,
    "Burnt Paradise: Bottom Right Breakable Wall": 0x147,
    "Burnt Paradise: Right Upper Big Corner On Wall": 0x148,
    "Nation of Fools: Right Center Room": 0x149,
    "Burnt Paradise: Left Big Corner": 0x14A,
    "Buried Chamber: Hidden Wall Item": 0x014C,
    "13th Street: Bakery Middle": 0x14D,
    "City of Haze: Cart Secret Right": 0x14E,
    "13th Street: Right Dance Hall Top Right": 0x150,
    "13th Street: Bakery Left": 0x152,
    "13th Street: Train Room Secret Left": 0x153,
    "City of Haze: Bar Right": 0x154,
    "13th Street: Square Room": 0x155,
    "13th Street: Bakery Right": 0x156,
    "Burnt Paradise: Bottom Right Corner Room": 0x157,
    "Nation of Fools: Left Center Room": 0x15F,
    "Dark Academy: Main Building Square Room Breakable Wall": 0x160,
    "Nation of Fools: Upside Down Building": 0x161,
    "Dark Academy: Main Building Minotaur Room": 0x163,
    "Dark Academy: West Building Top Floor Right": 0x164,
    "Nation of Fools: Secret Room": 0x166,
    "Forest of Doom: Left Atrium Middle Room": 0x167,
    "Burnt Paradise: Upper Right Big Room": 0x16B,
    "Forest of Doom: Near Cave Save Breakable Wall": 0x16C,
    "Sandy Grave: Pyramid East 5F": 0x173,
    "Nest of Evil: First Item": 0x175,
    "Nest of Evil: Second Item": 0x176,
    "Forest of Doom: Left Atrium Upper Room": 0x177,
    "Great Stairway: Connector Pipe Left": 0x180,
    "Great Stairway: Connector Pipe Right": 0x181,
    "The Throne Room: Great Stairs Left": 0x182,
    "13th Street: Right Dance Hall Top Left": 0x183,
    "Dark Academy: West Building Top Floor Left": 0x184,
    "Forgotten City: Pyramid East 1F": 0x185,
    "Forgotten City: Lower Underground Square Lower Item": 0x186,
    "Tower of Death: Stella Item": 0x187,
    "Master's Keep: Whip Trial": 0x188,

    "Quest: Preparations": 0x0200
}

"Dummy": LocationInformation(0x022F9110, "overlay_78"),