from typing import NamedTuple
#  IDs are matched to which internal Flag number the location uses
#  Because of this, they are asynchronous and out of order from what is expected
#  They are listed here in numerical order for clarity


class LocationInformation(NamedTuple):  # In-game information used to define each Location in the ROM.
    pointer: int
    file: str
    is_grounded: bool = False
    location_type: str = "Normal"


location_ids = {
    "Entrance: Drawbridge Pit Item": 0x01,
    "Entrance: Drawbridge Switch Item": 0x02,
    "City of Haze: Church Hallway": 0x03,
    "Entrance: Statue Room Above Statue": 0x04,
    "City of Haze: Post-Boss Room": 0x05,
    "City of Haze: Heavy Cart Item": 0x06,
    "Sandy Grave: Pyramid 5F Nook": 0x07,
    "Great Stairway: After Keremet Lower": 0x09,
    "Forgotten City: Pyramid 1F Bricks": 0x0A,
    "Nation of Fools: Central Top Shaft": 0x0D,
    "Entrance: Above Hub": 0x0E,
    "Entrance: Double Room Upper": 0x0F,
    "Nation of Fools: Legion Arena": 0x10,
    "Forest of Doom: Post-Boss Room": 0x11,
    "Dark Academy: Right Building Center Room": 0x12,
    "The Throne Room: Above Throne Left": 0x13,
    "Sandy Grave: Boulder Room Tunnel": 0x14,
    "City of Haze: Before Cart Room": 0x16,
    "City of Haze: Underground Square Right": 0x17,
    "Sandy Grave: Upper Big Underground Top Right": 0x18,
    "Nation of Fools: Bottom Corner Room": 0x19,
    "Nation of Fools: Mid-Right Corner Room": 0x1A,
    "Sandy Grave: Lower Big Underground Room Bottom": 0x1B,
    "Sandy Grave: Left Trap": 0x1C,
    "Buried Chamber: Central Secret": 0x20,
    "Sandy Grave: Sandworm Stomach": 0x21,
    "Tower of Death: Second Gears Room Left": 0x22,
    "Great Stairway: Lower Grand Staircase Corner Nook": 0x23,
    "Master's Keep: Entrance": 0x24,
    "Forest of Doom: Left Atrium Big Room": 0x25,
    "Forgotten City: Big Shaft Room Left": 0x26,
    "Nation of Fools: Left Upper Corner Room": 0x27,
    "Dark Academy: Main Building Ghoul Room": 0x28,
    "13th Street: Triple Moth Room": 0x29,
    "Tower of Death: Secret Room": 0x2A,
    "Nation of Fools: Right Horizontal Room": 0x2B,
    "Burnt Paradise: Left Lower Isolated Room": 0x2C,
    "Burnt Paradise: Right Lower Isolated Room": 0x2D,
    "The Throne Room: Great Stairs Under Stairs": 0x2E,
    "13th Street: Behind Final Guard": 0x2F,
    "Buried Chamber: Right Secret": 0x30,
    "Sandy Grave: Bottom Right Room": 0x31,
    "Tower of Death: Passage Hidden Item": 0x32,
    "Great Stairway: Left Loft Lower": 0x33,
    "Entrance: Center Hidden Room": 0x35,
    "Forgotten City: Big Shaft Room Right": 0x36,
    "Nation of Fools: Right Bottom Corner Room": 0x37,
    "Master's Keep: Hidden Room": 0x38,
    "13th Street: Three Amalaric Snipers": 0x39,
    "Dark Academy: Main Building Three Toads": 0x3A,
    "Nation of Fools: Top Corner Room": 0x3B,
    "Burnt Paradise: Left Upper Isolated Room": 0x3C,
    "Burnt Paradise: Right Upper Isolated Room": 0x3D,
    "The Throne Room: Great Stairs Center": 0x3E,
    "Forgotten City: Upper Underground Square": 0x3F,
    "Entrance: Double Room Lower": 0x40,
    "Buried Chamber: Westmost Room": 0x41,
    "Sandy Grave: Pyramid East 1F": 0x42,
    "City of Haze: Register Room": 0x46,
    "City of Haze: Bar Left": 0x47,
    "Nation of Fools: Bottom-Left Room Building": 0x48,
    "Sandy Grave: Pyramid 3F Lower": 0x49,
    "Tower of Death: Rampart Room": 0x4A,
    "Entrance: Beyond Great Armor Hallway": 0x4B,
    "Tower of Death: Elevator Room Lower": 0x4C,
    "Forest of Doom: Right Atrium East Square Room Right": 0x4D,
    "Forgotten City: Outside Left": 0x4E,
    "Sandy Grave: Upper Big Underground Top Left": 0x4F,
    "Burnt Paradise: Left Upper Big Corner": 0x51,
    "Great Stairway: Upper Grand Staircase Top Left Item": 0x53,
    "City of Haze: Axe Courtyard": 0x54,
    "Tower of Death: Top of the Tower": 0x55,
    "Great Stairway: Upper Underground Room": 0x56,
    "Entrance: Drawbridge Upper Item": 0x57,
    "Entrance: Statue Room Upper": 0x58,
    "Tower of Death: Second Gears Room Right": 0x59,
    "Tower of Death: Lower Gears Room Spike Shaft": 0x5A,
    "Master's Keep: Right Square Room": 0x5D,
    "City of Haze: Central Hallway Stairs": 0x60,
    "Buried Chamber: Right Shade Hall": 0x61,
    "City of Haze: Right Corner Room": 0x64,
    "City of Haze: Left Plaza": 0x65,
    "Great Stairway: Underground Hidden Room": 0x66,
    "Sandy Grave: Lower Big Underground Room Top": 0x67,
    "Nation of Fools: Upper Upside Down": 0x68,
    "Forgotten City: Lower Boulder Room Tunnel Alcove": 0x69,
    "Dark Academy: Main Building Secret Ceiling": 0x6B,
    "Forest of Doom: Secret Cave Room": 0x6C,
    "Nest of Evil: Doppelganger Reward": 0x6D,
    "City of Haze: Center Room Lower": 0x6E,
    "Sandy Grave: On Statue": 0x6F,
    "Tower of Death: Third Gears Room": 0x70,
    "Entrance: Above Metal Block Room": 0x71,
    "Dark Academy: Main Building Entrance": 0x72,
    "Burnt Paradise: Bottom Corner": 0x73,
    "Forest of Doom: Left Atrium Top": 0x75,
    "Great Stairway: Before Keremet Room": 0x76,
    "Forgotten City: Lower Boulder Room Upper Alcove": 0x77,
    "Entrance: First Passage Upper Item": 0x78,
    "Great Stairway: Upper Grand Staircase Corner Nook": 0x79,
    "Burnt Paradise: Bottom Right Big Room": 0x7A,
    "Entrance: Right Hidden Room": 0x7B,
    "Entrance: First Passage Lower Item": 0x7C,
    "City of Haze: Left Dance Hall Right Item": 0x7E,
    "City of Haze: Tunnel Room Left": 0x7F,
    "Burnt Paradise: Upper Left Big Room Middle Building": 0x82,
    "City of Haze: Chunky Room": 0x84,
    "Entrance: Pre-Behemoth Boss Room": 0x88,
    "Great Stairway: After Keremet Upper": 0x89,
    "Tower of Death: Gear Belt Room": 0x8A,
    "City of Haze: Dance Halls Basement": 0x8B,
    "City of Haze: Central Hallway Lower": 0x8C,
    "Burnt Paradise: Upper Right Big Room Right Side": 0x8F,
    "Buried Chamber: Central Hall": 0x92,
    "Great Stairway: Central Nook": 0x93,
    "Sandy Grave: Eastmost Item": 0x94,
    "Sandy Grave: Behind Bricks": 0x95,
    "City of Haze: Underground Square Left": 0xA0,
    "Great Stairway: Upper Grand Staircase Upper Alcove": 0xA1,
    "City of Haze: Right Dance Hall Secret Room": 0xA7,
    "Nation of Fools: Bottom Left Medium Square On Wall": 0xA8,
    "City of Haze: First Big Room": 0xA9,
    "Buried Chamber: Final Shaft Item": 0xAA,
    "Great Stairway: Central Upper": 0xAB,
    "Forest of Doom: Right Atrium East Top Room": 0xAC,
    "Dark Academy: Right Building Top Floor": 0xAD,
    "Sandy Grave: Boulder Room Corner Alcove": 0xAE,
    "Forgotten City: Post-Boss Item": 0xAF,
    "City of Haze: Cart Secret Left": 0xB0,
    "City of Haze: Winding Rooms": 0xB3,
    "Great Stairway: Lower Grand Staircase Lower Alcove": 0xB4,
    "Forest of Doom: Right Atrium East Square Room Left": 0xB5,
    "Forgotten City: Bottom Chamber": 0xB9,
    "City of Haze: Meat Room": 0xBB,
    "Great Stairway: Big Underground Room Hidden Item": 0xBF,
    "Great Stairway: Right Loft": 0xC0,
    "Great Stairway: Left Loft": 0xC1,
    "Nation of Fools: Bottom-Right Room Left Building": 0xC2,
    "13th Street: Many Nyxes Room": 0xC4,
    "The Throne Room: Above Throne Right": 0xC5,
    "City of Haze: Tunnel Room Right": 0xC8,
    "Great Stairway: Lower Grand Staircase Upper Alcove": 0xCA,
    "Great Stairway: Underground East Room": 0xCB,
    "Tower of Death: Elevator Room Top": 0xCC,
    "Entrance: Hub Room": 0xCD,
    "Buried Chamber: Eastmost Room": 0xCE,
    "Tower of Death: Hidden Room": 0xD1,
    "Nation of Fools: Bottom-Right Room Middle Building": 0xD4,
    "Forgotten City: Pyramid 5F": 0xD5,
    "13th Street: Train Room Secret Right": 0xD6,
    "City of Haze: Left Dance Hall Left Item": 0xD8,
    "Great Stairway: Big Underground Room Lower": 0xDA,
    "Tower of Death: Elevator Room Middle": 0xDB,
    "Nation of Fools: Crevice Item": 0xDC,
    "City of Haze: First Passage": 0xDD,
    "Forgotten City: Gorgon Room": 0xDE,
    "City of Haze: Axe Armor Item": 0xE0,
    "Sandy Grave: Giant Shaft Upper Item": 0xE1,
    "City of Haze: Dance Halls Vertical Hallway": 0xE2,
    "Tower of Death: Above Motorcycles": 0xE3,
    "Nation of Fools: Top-Right Room Axe Item": 0xE4,
    "Dark Academy: Main Building Secret Malphas Room": 0xE5,
    "13th Street: Underground Secret Room": 0xE6,
    "Great Stairway: Big Underground Room Upper": 0xE7,
    "Forest of Doom: Right Atrium West Top Room": 0xE8,
    "Burnt Paradise: Upper Left Big Room Left Building": 0xE9,
    "13th Street: Underground Demon Room": 0xEA,
    "Sandy Grave: Mega Ghost Room Lower": 0xEB,
    "13th Street: Left Big Room": 0xEC,
    "City of Haze: Bread Shelf": 0xED,
    "Burnt Paradise: Upper Left Lower Corner Upright Building": 0xEE,
    "City of Haze: Underground Secret Room": 0xEF,
    "Sandy Grave: Mega Ghost Room Upper": 0xF0,
    "Burnt Paradise: Lower Left Big Room": 0xF1,
    "13th Street: Secret Floor Room": 0xF3,
    "City of Haze: Right Dance Hall Item": 0xF7,
    "Tower of Death: Top Gears Room": 0xF9,
    "13th Street: East Courtyard": 0xFA,
    "City of Haze: Corner Room": 0xFC,
    "Sandy Grave: Giant Shaft Middle Item": 0xFD,
    "Entrance: Lilith Room": 0x101,
    "Sandy Grave: Right Trap": 0x103,
    "Nation of Fools: Left Bottom Corner Room": 0x104,
    "Forgotten City: Lower Underground Square Upper Item": 0x105,
    "City of Haze: Center Room Top": 0x10E,
    "Great Stairway: Upper Grand Staircase Middle Alcove": 0x10F,
    "Buried Chamber: Right Shaft Top": 0x110,
    "Sandy Grave: Pyramid 3F Upper": 0x113,
    "Nation of Fools: Bottom Right Medium Square On Wall": 0x114,
    "Sandy Grave: Lonely Mimic Alcove": 0x116,
    "13th Street: Near Big Room": 0x118,
    "Forgotten City: Pyramid East 3F": 0x119,
    "Great Stairway: Upper Grand Staircase Lower Alcove": 0x11B,
    "Nation of Fools: Right Vertical Room": 0x11C,
    "Sandy Grave: Fleaman Pit": 0x11E,
    "Nation of Fools: Top-Right Room Bottom Item": 0x11F,
    "Forgotten City: Pyramid East 5F": 0x122,
    "Burnt Paradise: Lower Vertical Hall": 0x123,
    "Buried Chamber: West Shaft": 0x124,
    "Great Stairway: Lower Grand Staircase Middle Alcove": 0x127,
    "Entrance: Behemoth Chase Room": 0x12C,
    "Entrance: First Passage Hidden Wall": 0x12D,
    "Tower of Death: Lower Passage Hidden Item": 0x131,
    "Dark Academy: West Building Breakable Wall": 0x134,
    "Forgotten City: Armored Fleaman Pit": 0x137,
    "Nation of Fools: Top-Left Room Right Building": 0x13F,
    "Forest of Doom: Left Atrium Breakable Wall": 0x140,
    "Sandy Grave: Giant Shaft Low Item": 0x144,
    "The Throne Room: Great Stairs Hidden": 0x145,
    "Nation of Fools: Top-Right Room Breakable Wall": 0x146,
    "Burnt Paradise: Bottom Right Breakable Wall": 0x147,
    "Burnt Paradise: Right Upper Big Corner On Wall": 0x148,
    "Nation of Fools: Right Center Room": 0x149,
    "Burnt Paradise: Left Big Corner": 0x14A,
    "Buried Chamber: Hidden Wall Item": 0x014C,
    "13th Street: Bakery Middle": 0x14D,
    "City of Haze: Cart Secret Right": 0x14E,
    "13th Street: Right Dance Hall Top Right": 0x150,
    "13th Street: Bakery Left": 0x152,
    "13th Street: Train Room Secret Left": 0x153,
    "City of Haze: Bar Right": 0x154,
    "13th Street: Square Room": 0x155,
    "13th Street: Bakery Right": 0x156,
    "Burnt Paradise: Bottom Right Corner Room": 0x157,
    "Nation of Fools: Left Center Room": 0x15F,
    "Dark Academy: Main Building Square Room Breakable Wall": 0x160,
    "Nation of Fools: Upside Down Building": 0x161,
    "Dark Academy: Main Building Minotaur Room": 0x163,
    "Dark Academy: West Building Top Floor Right": 0x164,
    "Nation of Fools: Secret Room": 0x166,
    "Forest of Doom: Left Atrium Middle Room": 0x167,
    "Burnt Paradise: Upper Right Big Room": 0x16B,
    "Forest of Doom: Near Cave Save Breakable Wall": 0x16C,
    "Sandy Grave: Pyramid East 5F": 0x173,
    "Nest of Evil: First Item": 0x175,
    "Nest of Evil: Second Item": 0x176,
    "Forest of Doom: Left Atrium Upper Room": 0x177,
    "Great Stairway: Connector Pipe Left": 0x180,
    "Great Stairway: Connector Pipe Right": 0x181,
    "The Throne Room: Great Stairs Left": 0x182,
    "13th Street: Right Dance Hall Top Left": 0x183,
    "Dark Academy: West Building Top Floor Left": 0x184,
    "Forgotten City: Pyramid East 1F": 0x185,
    "Forgotten City: Lower Underground Square Lower Item": 0x186,
    "Tower of Death: Stella Item": 0x187,
    "Master's Keep: Whip Trial": 0x188,

    "Quest: Preparations": 0x0200,
    "Quest: Supersonic Punch": 0x0201,
    "Quest: Ghosts of the Desert": 0x0202,
    "Quest: Defender of the Stairs": 0x0203,
    "Quest: The Spinning Art": 0x0204,
    "Quest: Art of the Zephyr": 0x0205,
    "Quest: Find the King of Birds": 0x0206,
    "Quest: Overcome the Curse": 0x0207,
    "Quest: The Statue's Tear": 0x0208,
    "Quest: The Martial Art": 0x0209,
    "Quest: Holy Appearance": 0x020A,
    "Quest: Number of Fortune": 0x020B,
    "Quest: Mental Training 1": 0x020C,
    "Quest: Mental Training 2": 0x020D,
    "Quest: The Spear of Legend": 0x020E,
    "Quest: Mental Training 3": 0x020F,
    "Quest: Defeat the Ghoul King": 0x0211,
    "Quest: Abandon Greed": 0x0212,
    "Quest: A Rank Hunter": 0x0213,
    "Quest: Mental Training 4": 0x0214,
    "Quest: S Rank Hunter": 0x0215,
    "Quest: The Gambler": 0x0216,
    "Quest: Hands of the Clock": 0x0217,
    "Quest: Poison vs. Poison": 0x0218,
    "Quest: Build Your Strength 1": 0x0219,
    "Quest: Build Your Strength 2": 0x021A,
    "Quest: The Lonely Stage": 0x021B,
    "Quest: Build Your Strength 3": 0x021C,
    "Quest: Pray Before the Cross": 0x021D,
    "Quest: Build Your Strength 4": 0x021E,
    "Quest: Lost Page": 0x021F,
    "Quest: The Hundred Tasks": 0x0220,
    "Quest: Master the Holy Power": 0x0221,
    "Quest: Almighty": 0x0222,
    "Quest: The Great Sage": 0x0223,
    "Quest: Kill Gergoth": 0x0224
    }

location_data_table = {
    "Entrance: Drawbridge Pit Item": LocationInformation(0x022F9110, "overlay_78"),
    "Entrance: Drawbridge Switch Item": LocationInformation(0x022F911C, "overlay_78"),
    "City of Haze: Church Hallway": LocationInformation(0x022F6E7C, "overlay_94"),
    "Entrance: Statue Room Above Statue": LocationInformation(0x02304E64, "overlay_79"),
    "City of Haze: Post-Boss Room": LocationInformation(0x02302A18, "overlay_95"),
    "City of Haze: Heavy Cart Item": LocationInformation(0x022F6F3C, "overlay_94"),
    "Sandy Grave: Pyramid 5F Nook": LocationInformation(0x023071AC, "overlay_91"),
    "Great Stairway: After Keremet Lower": LocationInformation(0x022FAD60, "overlay_82"),
    "Forgotten City: Pyramid 1F Bricks": LocationInformation(0x02308924, "overlay_102"),
    "Nation of Fools: Central Top Shaft": LocationInformation(0x022F6948, "overlay_98"),
    "Entrance: Above Hub": LocationInformation(0x02304A8C, "overlay_79"),
    "Entrance: Double Room Upper": LocationInformation(0x02309140, "overlay_119"),
    "Nation of Fools: Legion Arena": LocationInformation(0x022F6A98, "overlay_98", True),
    "Forest of Doom: Post-Boss Room": LocationInformation(0x022FB1B0, "overlay_99"),
    "Dark Academy: Right Building Center Room": LocationInformation(0x022F2A5C, "overlay_112"),
    "The Throne Room: Above Throne Left": LocationInformation(0x022F19F8, "overlay_87"),
    "Sandy Grave: Boulder Room Tunnel": LocationInformation(0x023064EC, "overlay_92"),
    "City of Haze: Before Cart Room": LocationInformation(0x022F6D98, "overlay_94"),
    "City of Haze: Underground Square Right": LocationInformation(0x02302B68, "overlay_95"),
    "Sandy Grave: Upper Big Underground Top Right": LocationInformation(0x02306078, "overlay_92", True),
    "Nation of Fools: Bottom Corner Room": LocationInformation(0x023005F4, "overlay_96", True),
    "Nation of Fools: Mid-Right Corner Room": LocationInformation(0x02300438, "overlay_96", True),
    "Sandy Grave: Lower Big Underground Room Bottom": LocationInformation(0x02306354, "overlay_92", True),
    "Sandy Grave: Left Trap": LocationInformation(0x02306270, "overlay_92", True),
    "Buried Chamber: Central Secret": LocationInformation(0x022FEA00, "overlay_80"),
    "Sandy Grave: Sandworm Stomach": LocationInformation(0x02307674, "overlay_91"),
    "Tower of Death: Second Gears Room Left": LocationInformation(0x02306634, "overlay_85"),
    "Great Stairway: Lower Grand Staircase Corner Nook": LocationInformation(0x022FC944, "overlay_83"),
    "Master's Keep: Entrance": LocationInformation(0x022FBECC, "overlay_88"),
    "Forest of Doom: Left Atrium Big Room": LocationInformation(0x02302C50, "overlay_100"),
    "Forgotten City: Big Shaft Room Left": LocationInformation(0x02304648, "overlay_103", True),
    "Nation of Fools: Left Upper Corner Room": LocationInformation(0x02300840, "overlay_96", True),
    "Dark Academy: Main Building Ghoul Room": LocationInformation(0x022F84F8, "overlay_111", True),
    "13th Street: Triple Moth Room": LocationInformation(0x022FCC38, "overlay_105", True),
    "Tower of Death: Secret Room": LocationInformation(0x0230673C, "overlay_85", True),
    "Nation of Fools: Right Horizontal Room": LocationInformation(0x02300528, "overlay_96", True),
    "Burnt Paradise: Left Lower Isolated Room": LocationInformation(0x02303A94, "overlay_107", True),
    "Burnt Paradise: Right Lower Isolated Room": LocationInformation(0x02303D34, "overlay_107", True),
    "The Throne Room: Great Stairs Under Stairs": LocationInformation(0x022F1B54, "overlay_87", True),
    "13th Street: Behind Final Guard": LocationInformation(0x022FEE50, "overlay_105", True),
    "Buried Chamber: Right Secret": LocationInformation(0x022FEC34, "overlay_80"),
    "Sandy Grave: Bottom Right Room": LocationInformation(0x02306540, "overlay_92"),
    "Tower of Death: Passage Hidden Item": LocationInformation(0x0230661C, "overlay_85"),
    "Great Stairway: Left Loft Lower": LocationInformation(0x022F8798, "overlay_84", True),
    "Entrance: Center Hidden Room": LocationInformation(0x02304F0C, "overlay_79"),
    "Forgotten City: Big Shaft Room Right": LocationInformation(0x02304654, "overlay_103", True),
    "Nation of Fools: Right Bottom Corner Room": LocationInformation(0x02300510, "overlay_96", True),
    "Master's Keep: Hidden Room": LocationInformation(0x022FBC14, "overlay_88"),
    "13th Street: Three Amalaric Snipers": LocationInformation(0x022FF0F0, "overlay_105", True),
    "Dark Academy: Main Building Three Toads": LocationInformation(0x022F8060, "overlay_111"),
    "Nation of Fools: Top Corner Room": LocationInformation(0x02300258, "overlay_96", True),
    "Burnt Paradise: Left Upper Isolated Room": LocationInformation(0x02303908, "overlay_107", True),
    "Burnt Paradise: Right Upper Isolated Room": LocationInformation(0x02303E0C, "overlay_107", True),
    "The Throne Room: Great Stairs Center": LocationInformation(0x022F1B60, "overlay_87", True),
    "Forgotten City: Upper Underground Square": LocationInformation(0x023048A0, "overlay_103", True),
    "Entrance: Double Room Lower": LocationInformation(0x0230914C, "overlay_119"),
    "Buried Chamber: Westmost Room": LocationInformation(0x022FE700, "overlay_80"),
    "Sandy Grave: Pyramid East 1F": LocationInformation(0x02307500, "overlay_91"),
    "City of Haze: Register Room": LocationInformation(0x02301A3C, "overlay_93"),
    "City of Haze: Bar Left": LocationInformation(0x023019DC, "overlay_93"),
    "Nation of Fools: Bottom-Left Room Building": LocationInformation(0x02305ACC, "overlay_97"),
    "Sandy Grave: Pyramid 3F Lower": LocationInformation(0x0230711C, "overlay_91"),
    "Tower of Death: Rampart Room": LocationInformation(0x022FC224, "overlay_86"),
    "Entrance: Beyond Great Armor Hallway": LocationInformation(0x02305020, "overlay_79"),
    "Tower of Death: Elevator Room Lower": LocationInformation(0x02306130, "overlay_85"),
    "Forest of Doom: Right Atrium East Square Room Right": LocationInformation(0x022FDF10, "overlay_101"),
    "Forgotten City: Outside Left": LocationInformation(0x02308864, "overlay_102"),
    "Sandy Grave: Upper Big Underground Top Left": LocationInformation(0x02306084, "overlay_92"),
    "Burnt Paradise: Left Upper Big Corner": LocationInformation(0x02304D04, "overlay_108"),
    "Great Stairway: Upper Grand Staircase Top Left Item": LocationInformation(0x022FCB0C, "overlay_83"),
    "City of Haze: Axe Courtyard": LocationInformation(0x022F6F84, "overlay_94"),
    "Tower of Death: Top of the Tower": LocationInformation(0x023060DC, "overlay_85"),
    "Great Stairway: Upper Underground Room": LocationInformation(0x022FAB38, "overlay_82"),
    "Entrance: Drawbridge Upper Item": LocationInformation(0x022F9128, "overlay_78"),
    "Entrance: Statue Room Upper": LocationInformation(0x02304E70, "overlay_79"),
    "Tower of Death: Second Gears Room Right": LocationInformation(0x02306640, "overlay_85"),
    "Tower of Death: Lower Gears Room Spike Shaft": LocationInformation(0x023067B4, "overlay_85"),
    "Master's Keep: Right Square Room": LocationInformation(0x022FBCD4, "overlay_88"),
    "City of Haze: Central Hallway Stairs": LocationInformation(0x022F6EB8, "overlay_94"),
    "Buried Chamber: Right Shade Hall": LocationInformation(0x022FED6C, "overlay_80"),
    "City of Haze: Right Corner Room": LocationInformation(0x02301AA8, "overlay_93"),
    "City of Haze: Left Plaza": LocationInformation(0x02301DE4, "overlay_93"),
    "Great Stairway: Underground Hidden Room": LocationInformation(0x022FACF4, "overlay_82"),
    "Sandy Grave: Lower Big Underground Room Top": LocationInformation(0x02306348, "overlay_92"),
    "Nation of Fools: Upper Upside Down": LocationInformation(0x02300378, "overlay_96"),
    "Forgotten City: Lower Boulder Room Tunnel Alcove": LocationInformation(0x023049A8, "overlay_103"),
    "Dark Academy: Main Building Secret Ceiling": LocationInformation(0x022F8420, "overlay_111"),
    "Forest of Doom: Secret Cave Room": LocationInformation(0x022FDEB0, "overlay_101"),
    "Nest of Evil: Doppelganger Reward": LocationInformation(0x022EE9FC, "overlay_113"),
    "City of Haze: Center Room Lower": LocationInformation(0x02301C4C, "overlay_93"),
    "Sandy Grave: On Statue": LocationInformation(0x02307068, "overlay_91", True),
    "Tower of Death: Third Gears Room": LocationInformation(0x02306448, "overlay_85"),
    "Entrance: Above Metal Block Room": LocationInformation(0x02304F3C, "overlay_79", True),
    "Dark Academy: Main Building Entrance": LocationInformation(0x022F8660, "overlay_111", True),
    "Burnt Paradise: Bottom Corner": LocationInformation(0x02303698, "overlay_107", True),
    "Forest of Doom: Left Atrium Top": LocationInformation(0x023027C4, "overlay_100"),
    "Great Stairway: Before Keremet Room": LocationInformation(0x022FA864, "overlay_81", True),
    "Forgotten City: Lower Boulder Room Upper Alcove": LocationInformation(0x0230499C, "overlay_103", True),
    "Entrance: First Passage Upper Item": LocationInformation(0x02304AEC, "overlay_79"),
    "Great Stairway: Upper Grand Staircase Corner Nook": LocationInformation(0x022FCB3C, "overlay_83"),
    "Burnt Paradise: Bottom Right Big Room": LocationInformation(0x02305088, "overlay_108", True),
    "Entrance: Right Hidden Room": LocationInformation(0x022F92C0, "overlay_78"),
    "Entrance: First Passage Lower Item": LocationInformation(0x02304AE0, "overlay_79"),
    "City of Haze: Left Dance Hall Right Item": LocationInformation(0x02302784, "overlay_95"),
    "City of Haze: Tunnel Room Left": LocationInformation(0x02302928, "overlay_95", True),
    "Burnt Paradise: Upper Left Big Room Middle Building": LocationInformation(0x02304D88, "overlay_108", True),
    "City of Haze: Chunky Room": LocationInformation(0x023018BC, "overlay_93"),
    "Entrance: Pre-Behemoth Boss Room": LocationInformation(0x022F91E8, "overlay_78"),
    "Great Stairway: After Keremet Upper": LocationInformation(0x022FAD6C, "overlay_82", True),
    "Tower of Death: Gear Belt Room": LocationInformation(0x022FC2A8, "overlay_86"),
    "City of Haze: Dance Halls Basement": LocationInformation(0x023028C8, "overlay_95"),
    "City of Haze: Central Hallway Lower": LocationInformation(0x022F6EC4, "overlay_94"),
    "Burnt Paradise: Upper Right Big Room Right Side": LocationInformation(0x02304ECC, "overlay_108", True),
    "Buried Chamber: Central Hall": LocationInformation(0x022FE94C, "overlay_80"),
    "Great Stairway: Central Nook": LocationInformation(0x022F881C, "overlay_84", True),
    "Sandy Grave: Eastmost Item": LocationInformation(0x02307608, "overlay_91", True),
    "Sandy Grave: Behind Bricks": LocationInformation(0x02307074, "overlay_91"),
    "City of Haze: Underground Square Left": LocationInformation(0x02302C10, "overlay_95"),
    "Great Stairway: Upper Grand Staircase Upper Alcove": LocationInformation(0x022FCB30, "overlay_83"),
    "City of Haze: Right Dance Hall Secret Room": LocationInformation(0x023029E8, "overlay_95", True),
    "Nation of Fools: Bottom Left Medium Square On Wall": LocationInformation(0x02305B2C, "overlay_97"),
    "City of Haze: First Big Room": LocationInformation(0x023016C4, "overlay_93"),
    "Buried Chamber: Final Shaft Item": LocationInformation(0x022FEE5C, "overlay_80"),
    "Great Stairway: Central Upper": LocationInformation(0x022F8828, "overlay_84", True),
    "Forest of Doom: Right Atrium East Top Room": LocationInformation(0x022FDDF0, "overlay_101"),
    "Dark Academy: Right Building Top Floor": LocationInformation(0x022F29E4, "overlay_112", True),
    "Sandy Grave: Boulder Room Corner Alcove": LocationInformation(0x023064F8, "overlay_92"),
    "Forgotten City: Post-Boss Item": LocationInformation(0x023046B4, "overlay_103"),
    "City of Haze: Cart Secret Left": LocationInformation(0x022F7008, "overlay_94"),
    "City of Haze: Winding Rooms": LocationInformation(0x023017C0, "overlay_93"),
    "Great Stairway: Lower Grand Staircase Lower Alcove": LocationInformation(0x022FC950, "overlay_83", True),
    "Forest of Doom: Right Atrium East Square Room Left": LocationInformation(0x022FDF1C, "overlay_101"),
    "Forgotten City: Bottom Chamber": LocationInformation(0x02304D50, "overlay_103"),
    "City of Haze: Meat Room": LocationInformation(0x02301628, "overlay_93"),
    "Great Stairway: Big Underground Room Hidden Item": LocationInformation(0x022FAE38, "overlay_82"),
    "Great Stairway: Right Loft": LocationInformation(0x022F893C, "overlay_84", True),
    "Great Stairway: Left Loft": LocationInformation(0x022F878C, "overlay_84", True),
    "Nation of Fools: Bottom-Right Room Left Building": LocationInformation(0x023059A0, "overlay_97"),
    "13th Street: Many Nyxes Room": LocationInformation(0x022FEF7C, "overlay_105", True),
    "The Throne Room: Above Throne Right": LocationInformation(0x022F1A04, "overlay_87", True),
    "City of Haze: Tunnel Room Right": LocationInformation(0x02302934, "overlay_95", True),
    "Great Stairway: Lower Grand Staircase Upper Alcove": LocationInformation(0x022FC968, "overlay_83"),
    "Great Stairway: Underground East Room": LocationInformation(0x022FACA0, "overlay_82", True),
    "Tower of Death: Elevator Room Top": LocationInformation(0x02306118, "overlay_85"),
    "Entrance: Hub Room": LocationInformation(0x02304AB0, "overlay_79", True),
    "Buried Chamber: Eastmost Room": LocationInformation(0x022FEE38, "overlay_80"),
    "Tower of Death: Hidden Room": LocationInformation(0x022FC368, "overlay_86"),
    "Nation of Fools: Bottom-Right Room Middle Building": LocationInformation(0x02305994, "overlay_97", True),
    "Forgotten City: Pyramid 5F": LocationInformation(0x02308A2C, "overlay_102", True),
    "13th Street: Train Room Secret Right": LocationInformation(0x022F3B8C, "overlay_104"),
    "City of Haze: Left Dance Hall Left Item": LocationInformation(0x02302778, "overlay_95"),
    "Great Stairway: Big Underground Room Lower": LocationInformation(0x022FAE20, "overlay_82"),
    "Tower of Death: Elevator Room Middle": LocationInformation(0x02306124, "overlay_85"),
    "Nation of Fools: Crevice Item": LocationInformation(0x02305778, "overlay_97", True),
    "City of Haze: First Passage": LocationInformation(0x02301598, "overlay_93"),
    "Forgotten City: Gorgon Room": LocationInformation(0x02304858, "overlay_103", True),
    "City of Haze: Axe Armor Item": LocationInformation(0x02301AD8, "overlay_93"),
    "Sandy Grave: Giant Shaft Upper Item": LocationInformation(0x02305DFC, "overlay_92"),
    "City of Haze: Dance Halls Vertical Hallway": LocationInformation(0x0230288C, "overlay_95"),
    "Tower of Death: Above Motorcycles": LocationInformation(0x022FC440, "overlay_86", True),
    "Nation of Fools: Top-Right Room Axe Item": LocationInformation(0x02305808, "overlay_97", True),
    "Dark Academy: Main Building Secret Malphas Room": LocationInformation(0x022F83B4, "overlay_111", True),
    "13th Street: Underground Secret Room": LocationInformation(0x022FF2AC, "overlay_105", True),
    "Great Stairway: Big Underground Room Upper": LocationInformation(0x022FAE2C, "overlay_82"),
    "Forest of Doom: Right Atrium West Top Room": LocationInformation(0x022FDB44, "overlay_101"),
    "Burnt Paradise: Upper Left Big Room Left Building": LocationInformation(0x02304D94, "overlay_108", True),
    "13th Street: Underground Demon Room": LocationInformation(0x022FF264, "overlay_105", True),
    "Sandy Grave: Mega Ghost Room Lower": LocationInformation(0x02307434, "overlay_91", True),
    "13th Street: Left Big Room": LocationInformation(0x022FD058, "overlay_105", True),
    "City of Haze: Bread Shelf": LocationInformation(0x02301D78, "overlay_93", True),
    "Burnt Paradise: Upper Left Lower Corner Upright Building": LocationInformation(0x02304E0C, "overlay_108", True),
    "City of Haze: Underground Secret Room": LocationInformation(0x02302B50, "overlay_95", True),
    "Sandy Grave: Mega Ghost Room Upper": LocationInformation(0x0230741C, "overlay_91"),
    "Burnt Paradise: Lower Left Big Room": LocationInformation(0x02304C38, "overlay_108", True),
    "13th Street: Secret Floor Room": LocationInformation(0x022FF024, "overlay_105"),
    "City of Haze: Right Dance Hall Item": LocationInformation(0x02302964, "overlay_95"),
    "Tower of Death: Top Gears Room": LocationInformation(0x02306298, "overlay_85"),
    "13th Street: East Courtyard": LocationInformation(0x022FCA04, "overlay_105", True),
    "City of Haze: Corner Room": LocationInformation(0x0230176C, "overlay_93"),
    "Sandy Grave: Giant Shaft Middle Item": LocationInformation(0x02305DE4, "overlay_92", True),
    "Entrance: Lilith Room": LocationInformation(0x02304E28, "overlay_79"),
    "Sandy Grave: Right Trap": LocationInformation(0x0230627C, "overlay_92", True),
    "Nation of Fools: Left Bottom Corner Room": LocationInformation(0x02300750, "overlay_96", True),
    "Forgotten City: Lower Underground Square Upper Item": LocationInformation(0x02304A80, "overlay_103"),
    "City of Haze: Center Room Top": LocationInformation(0x02301C40, "overlay_93"),
    "Great Stairway: Upper Grand Staircase Middle Alcove": LocationInformation(0x022FCB24, "overlay_83", True),
    "Buried Chamber: Right Shaft Top": LocationInformation(0x022FEDA8, "overlay_80", True),
    "Sandy Grave: Pyramid 3F Upper": LocationInformation(0x02307128, "overlay_91"),
    "Nation of Fools: Bottom Right Medium Square On Wall": LocationInformation(0x023058F8, "overlay_97", True),
    "Sandy Grave: Lonely Mimic Alcove": LocationInformation(0x023064A4, "overlay_92", True),
    "13th Street: Near Big Room": LocationInformation(0x022FCE18, "overlay_105", True),
    "Forgotten City: Pyramid East 3F": LocationInformation(0x02308C9C, "overlay_102", True),
    "Great Stairway: Upper Grand Staircase Lower Alcove": LocationInformation(0x022FCB18, "overlay_83", True),
    "Nation of Fools: Right Vertical Room": LocationInformation(0x02300450, "overlay_96", True),
    "Sandy Grave: Fleaman Pit": LocationInformation(0x023073A4, "overlay_91"),
    "Nation of Fools: Top-Right Room Bottom Item": LocationInformation(0x023057F0, "overlay_97"),
    "Forgotten City: Pyramid East 5F": LocationInformation(0x02308BC4, "overlay_102", True),
    "Burnt Paradise: Lower Vertical Hall": LocationInformation(0x02304B60, "overlay_108", True),
    "Buried Chamber: West Shaft": LocationInformation(0x022FE748, "overlay_80", True),
    "Great Stairway: Lower Grand Staircase Middle Alcove": LocationInformation(0x022FC95C, "overlay_83", True),
    "Entrance: Behemoth Chase Room": LocationInformation(0x02304DA4, "overlay_79"),
    "Entrance: First Passage Hidden Wall": LocationInformation(0x02304B34, "overlay_79"),
    "Tower of Death: Lower Passage Hidden Item": LocationInformation(0x023068BC, "overlay_85"),
    "Dark Academy: West Building Breakable Wall": LocationInformation(0x022F6084, "overlay_109"),
    "Forgotten City: Armored Fleaman Pit": LocationInformation(0x02308C24, "overlay_102", True),
    "Nation of Fools: Top-Left Room Right Building": LocationInformation(0x02305BBC, "overlay_97", True),
    "Forest of Doom: Left Atrium Breakable Wall": LocationInformation(0x02302A40, "overlay_100"),
    "Sandy Grave: Giant Shaft Low Item": LocationInformation(0x02305DF0, "overlay_92", True),
    "The Throne Room: Great Stairs Hidden": LocationInformation(0x022F1B78, "overlay_87"),
    "Nation of Fools: Top-Right Room Breakable Wall": LocationInformation(0x023057FC, "overlay_97"),
    "Burnt Paradise: Bottom Right Breakable Wall": LocationInformation(0x02303848, "overlay_107"),
    "Burnt Paradise: Right Upper Big Corner On Wall": LocationInformation(0x02304F2C, "overlay_108", True),
    "Nation of Fools: Right Center Room": LocationInformation(0x022F6A5C, "overlay_98", True),
    "Burnt Paradise: Left Big Corner": LocationInformation(0x02304B90, "overlay_108"),
    "Buried Chamber: Hidden Wall Item": LocationInformation(0x022FECA0, "overlay_80"),
    "13th Street: Bakery Middle": LocationInformation(0x022FCB54, "overlay_105"),
    "City of Haze: Cart Secret Right": LocationInformation(0x022F7014, "overlay_94"),
    "13th Street: Right Dance Hall Top Right": LocationInformation(0x022FED84, "overlay_105", True),
    "13th Street: Bakery Left": LocationInformation(0x022FCB48, "overlay_105"),
    "13th Street: Train Room Secret Left": LocationInformation(0x022F3B80, "overlay_104"),
    "City of Haze: Bar Right": LocationInformation(0x023019E8, "overlay_93"),
    "13th Street: Square Room": LocationInformation(0x022FCA4C, "overlay_105", True),
    "13th Street: Bakery Right": LocationInformation(0x022FCB60, "overlay_105"),
    "Burnt Paradise: Bottom Right Corner Room": LocationInformation(0x023050A0, "overlay_108", True),
    "Nation of Fools: Left Center Room": LocationInformation(0x022F6A74, "overlay_98", True),
    "Dark Academy: Main Building Square Room Breakable Wall": LocationInformation(0x022F8198, "overlay_111"),
    "Nation of Fools: Upside Down Building": LocationInformation(0x02305C64, "overlay_97", True),
    "Dark Academy: Main Building Minotaur Room": LocationInformation(0x022F8564, "overlay_111", True),
    "Dark Academy: West Building Top Floor Right": LocationInformation(0x022F60F0, "overlay_109", True),
    "Nation of Fools: Secret Room": LocationInformation(0x023003D8, "overlay_96", True),
    "Forest of Doom: Left Atrium Middle Room": LocationInformation(0x023028D8, "overlay_100", True),
    "Burnt Paradise: Upper Right Big Room": LocationInformation(0x02304ED8, "overlay_108", True),
    "Forest of Doom: Near Cave Save Breakable Wall": LocationInformation(0x022FB120, "overlay_99"),
    "Sandy Grave: Pyramid East 5F": LocationInformation(0x02307344, "overlay_91"),
    "Nest of Evil: First Item": LocationInformation(0x022EE060, "overlay_113", True),
    "Nest of Evil: Second Item": LocationInformation(0x022EE864, "overlay_113", True),
    "Forest of Doom: Left Atrium Upper Room": LocationInformation(0x0230280C, "overlay_100"),
    "Great Stairway: Connector Pipe Left": LocationInformation(0x022F8A80, "overlay_84", True),
    "Great Stairway: Connector Pipe Right": LocationInformation(0x022F8A8C, "overlay_84", True),
    "The Throne Room: Great Stairs Left": LocationInformation(0x022F1B6C, "overlay_87", True),
    "13th Street: Right Dance Hall Top Left": LocationInformation(0x022FED78, "overlay_105", True),
    "Dark Academy: West Building Top Floor Left": LocationInformation(0x022F60E4, "overlay_109", True),
    "Forgotten City: Pyramid East 1F": LocationInformation(0x02308CF0, "overlay_102", True),
    "Forgotten City: Lower Underground Square Lower Item": LocationInformation(0x02304A8C, "overlay_103", True),
    "Tower of Death: Stella Item": LocationInformation(0x0230916B, "overlay_119", False, "Cutscene"),
    "Master's Keep: Whip Trial": LocationInformation(0x02309168, "overlay_119", False, "Cutscene"),

    "Quest: Preparations": LocationInformation(0x020DFD40, "arm9", False, "Quest")
}
