world_version = "3.0"

global_soul_table = [
    "Puppet Master Soul",
    "Zephyr Soul",
    "Paranoia Soul",
    "Imp Soul",
    "Skeleton Soul",
    "Zombie Soul",
    "Axe Armor Soul",
    "Student Witch Soul",
    "Warg Soul",
    "Bomber Armor Soul",
    "Amalaric Sniper Soul",
    "Cave Troll Soul",
    "Waiter Skeleton Soul",
    "Slime Soul",
    "Yorick Soul",
    "Une Soul",
    "Mandragora Soul",
    "Rycuda Soul",
    "Fleaman Soul",
    "Ripper Soul",
    "Guillotiner Soul",
    "Killer Clown Soul",
    "Malachi Soul",
    "Disc Armor Soul",
    "Great Axe Armor Soul",
    "Slaughterer Soul",
    "Hell Boar Soul",
    "Frozen Shade Soul",
    "Merman Soul",
    "Larva Soul",
    "Ukoback Soul",
    "Decarabia Soul",
    "Succubus Soul",
    "Slogra Soul",
    "Erinys Soul",
    "Homunculus Soul",
    "Witch Soul",
    "Fish Head Soul",
    "Mollusca Soul",
    "Dead Mate Soul",
    "Killer Fish Soul",
    "Malacoda Soul",
    "Flame Demon Soul",
    "Aguni Soul",
    "Abaddon Soul",
    "Hell Fire",
    "Alucard Bat",
    "Holy Flame",
    "Blue Splash",
    "Holy Lightning",
    "Cross",
    "Holy Water",
    "Grand Cross",
    "Flying Armor Soul",
    "Bat Company Soul",
    "Black Panther Soul",
    "Armor Knight Soul",
    "Spin Devil Soul",
    "Skull Archer Soul",
    "Ghost Soul",
    "Yeti Soul",
    "Buer Soul",
    "Manticore Soul",
    "Mushussu Soul",
    "White Dragon Soul",
    "Catoblepas Soul",
    "Gorgon Soul",
    "Persephone Soul",
    "Flying Humanoid Soul",
    "Devil Soul",
    "Medusa Head Soul",
    "Final Guard Soul",
    "Werewolf Soul",
    "Alura Une Soul",
    "Iron Golem Soul",
    "Bone Ark Soul",
    "Barbariccia Soul",
    "Valkyrie Soul",
    "Bat Soul",
    "Great Armor Soul",
    "Mini Devil Soul",
    "Harpy Soul",
    "Corpseweed Soul",
    "Quetzalcoatl Soul",
    "Needles Soul",
    "Alastor Soul",
    "Gaibon Soul",
    "Gergoth Soul",
    "Death Soul",
    "Golem Soul",
    "Bone Pillar Soul",
    "Lilith Soul",
    "Ghost Dancer Soul",
    "Tanjelly Soul",
    "Bugbear Soul",
    "Arc Demon Soul",
    "Giant Slug Soul",
    "Killer Doll Soul",
    "Tombstone Soul",
    "Treant Soul",
    "Ghoul Soul",
    "Skelerang Soul",
    "Skeleton Ape Soul",
    "Dead Warrior Soul",
    "Dead Pirate Soul",
    "Draghignazzo Soul",
    "Heart Eater Soul",
    "Peeping Eye Soul",
    "Skeleton Farmer Soul",
    "The Creature Soul",
    "Mimic Soul",
    "Mothman Soul",
    "Ouija Table Soul",
    "Dead Crusader Soul",
    "Stolas Soul",
    "Wakwak Tree Soul",
    "Balore Soul",
    "Malphas Soul",
    "Doppelganger Soul",
    "Rahab Soul",
    "Hippogryph Soul",
    "Procel Soul",
    "Mud Demon Soul"
]

global_weapon_table = [
    "Bare Knuckles",
    "Knife",
    "Combat Knife",
    "Baselard",
    "Cutall",
    "Cinquedia",
    "Rapier",
    "Fleuret",
    "Main Gauche",
    "Small Sword",
    "Estoc",
    "Whip Sword",
    "Garian Sword",
    "Kris Naga",
    "Nebula",
    "Short Sword",
    "Cutlass",
    "Long Sword",
    "Fragarach",
    "Hrunting",
    "Mystletain",
    "Joyeuse",
    "Milican's Sword",
    "Ice Brand",
    "Laevatain",
    "Burtgang",
    "Kaladbolg",
    "Valmanway",
    "Alucard Sword",
    "Claymore",
    "Falchion",
    "Great Sword",
    "Durandal",
    "Dainslef",
    "Ascalon",
    "Balmung",
    "Final Sword",
    "Claimh Solais",
    "Spear",
    "Partizan",
    "Halberd",
    "Lance",
    "Trident",
    "Brionac",
    "Geiborg",
    "Longinus",
    "Gungner",
    "Mace",
    "Morgenstern",
    "Mjollnjr",
    "Axe",
    "Battle Axe",
    "Bhuj",
    "Great Axe",
    "Golden Axe",
    "Death Scythe",
    "Blunt Sword",
    "Katana",
    "Kotetsu",
    "Masamune",
    "Osafune",
    "Kunitsuna",
    "Yasutsuna",
    "Muramasa",
    "Brass Knuckles",
    "Cestus",
    "Whip Knuckle",
    "Mach Punch",
    "Kaiser Knuckle",
    "Handgun",
    "Silver Gun",
    "Boomerang",
    "Chakram",
    "Tomahawk",
    "Throwing Sickle",
    "RPG",
    "Terror Bear",
    "Nunchakus",
    "Whip"
]

valid_random_starting_weapons = [
    "Knife",
    "Combat Knife",
    "Baselard",
    "Cutall",
    "Cinquedia",
    "Rapier",
    "Fleuret",
    "Main Gauche",
    "Small Sword",
    "Estoc",
    "Whip Sword",
    "Garian Sword",
    "Kris Naga",
    "Nebula",
    "Short Sword",
    "Cutlass",
    "Long Sword",
    "Fragarach",
    "Hrunting",
    "Mystletain",
    "Joyeuse",
    "Milican's Sword",
    "Ice Brand",
    "Laevatain",
    "Burtgang",
    "Kaladbolg",
    "Valmanway",
    "Claymore",
    "Falchion",
    "Great Sword",
    "Durandal",
    "Dainslef",
    "Ascalon",
    "Balmung",
    "Final Sword",
    "Claimh Solais",
    "Spear",
    "Partizan",
    "Halberd",
    "Lance",
    "Trident",
    "Brionac",
    "Geiborg",
    "Longinus",
    "Gungner",
    "Mace",
    "Morgenstern",
    "Mjollnjr",
    "Axe",
    "Battle Axe",
    "Bhuj",
    "Great Axe",
    "Golden Axe",
    "Death Scythe",
    "Blunt Sword",
    "Katana",
    "Kotetsu",
    "Masamune",
    "Osafune",
    "Kunitsuna",
    "Yasutsuna",
    "Muramasa",
    "Brass Knuckles",
    "Cestus",
    "Whip Knuckle",
    "Mach Punch",
    "Kaiser Knuckle",
    "Handgun",
    "Silver Gun",
    "RPG",
    "Terror Bear",
    "Nunchakus"
]

base_weapons = [
    "Knife",
    "Rapier",
    "Short Sword",
    "Claymore",
    "Mace",
    "Blunt Sword",
    "Axe",
    "Spear",
    "Handgun",
    "Brass Knuckles"
]

easter_egg_table = {
    "Dark Chapel: Bell Room In Bell": 0x222BE4C,
    "Demon Guest House: Central Main Chamber Bottom Room": 0x222BE40,
    "Cursed Clock Tower: Spike Room Secret": 0x222BE34
}

warp_room_table = [
    "Lost Village",
    "Wizardry Lab",
    "Garden of Madness",
    "Dark Chapel",
    "Demon Guest House",
    "Subterranean Hell",
    "Silenced Ruins",
    "Cursed Clock Tower",
    "Condemned Tower"
]

warp_room_regions = {
    "Lost Village": "Lost Village Lower",
    "Wizardry Lab": "Wizardry Lab Main",
    "Garden of Madness": "Garden of Madness Lower",
    "Dark Chapel": "Dark Chapel",
    "Demon Guest House": "Demon Guest House West Wing",
    "Subterranean Hell": "Subterranean Hell Central Upper",
    "Silenced Ruins": "Silenced Ruins",
    "Cursed Clock Tower": "Cursed Clock Tower Post-Boss",
    "Condemned Tower": "Condemned Tower Top"
}

warp_room_bits = {
    "Lost Village": 0x01,
    "Demon Guest House": 0x02,
    "Wizardry Lab": 0x04,
    "Garden of Madness": 0x08,
    "Dark Chapel": 0x10,
    "Condemned Tower": 0x20,
    # "Mine of Judgment": 0x40,
    "Subterranean Hell": 0x80,
    "Silenced Ruins": 0x0100,
    "Cursed Clock Tower": 0x0200,
    # "The Pinnacle": 0x0400,
    # "The Abyss": 0x0800
}

global_item_table = [
    "Potion",
    "High Potion",
    "Super Potion",
    "Mind Up",
    "High Mind Up",
    "Mana Prism",
    "Anti-Venom",
    "Uncurse Potion",
    "Meat Strip",
    "Tasty Meat",
    "Rice Ball",
    "Mushroom",
    "Corn Soup",
    "Beef Curry",
    "Noodles",
    "Cream Soda",
    "Cream Puff",
    "Milk",
    "Coffee",
    "Tea",
    "Pudding",
    "Strawberry",
    "Melon",
    "Grapes",
    "Hamburger",
    "Fried Chicken",
    "Hot Dog",
    "Pumpkin Pie",
    "Pancake",
    "Piroshki",
    "Tinned Spinach",
    "Foie Gras",
    "Caviar",
    "Truffle",
    "Paella",
    "Spaghetti",
    "Ice Cream",
    "Salmon Meuniere",
    "Boiled Starfish",
    "Amanita",
    "Rotten Meat",
    "Spoiled Milk",
    "Rusty Food Tin",
    "Return Gem",
    "CASTLE MAP 1",
    "CASTLE MAP 2",
    "UMA News 1-1",
    "UMA News 1-2",
    "UMA News 1-3",
    "UMA News 2-1",
    "UMA News 2-2",
    "UMA News 2-3",
    "UMA News 2-4",
    "UMA News 3-1",
    "UMA News 3-2",
    "UMA News 3-3",
    "UMA News 4",
    "Tower Key",
    "AP Item",
    "AP Item (prog)",
    "Soul Can",
    "Magic Seal 1",
    "Magic Seal 2",
    "Magic Seal 3",
    "Magic Seal 4",
    "Magic Seal 5",
    "Bare Knuckles",
    "Knife",
    "Combat Knife",
    "Baselard",
    "Cutall",
    "Cinquedia",
    "Rapier",
    "Fleuret",
    "Main Gauche",
    "Small Sword",
    "Estoc",
    "Whip Sword",
    "Garian Sword",
    "Kris Naga",
    "Nebula",
    "Short Sword",
    "Cutlass",
    "Long Sword",
    "Fragarach",
    "Hrunting",
    "Mystletain",
    "Joyeuse",
    "Milican's Sword",
    "Ice Brand",
    "Laevatain",
    "Burtgang",
    "Kaladbolg",
    "Valmanway",
    "Alucard Sword",
    "Claymore",
    "Falchion",
    "Great Sword",
    "Durandal",
    "Dainslef",
    "Ascalon",
    "Balmung",
    "Final Sword",
    "Claimh Solais",
    "Spear",
    "Partizan",
    "Halberd",
    "Lance",
    "Trident",
    "Brionac",
    "Geiborg",
    "Longinus",
    "Gungner",
    "Mace",
    "Morgenstern",
    "Mjollnjr",
    "Axe",
    "Battle Axe",
    "Bhuj",
    "Great Axe",
    "Golden Axe",
    "Death Scythe",
    "Blunt Sword",
    "Katana",
    "Kotetsu",
    "Masamune",
    "Osafune",
    "Kunitsuna",
    "Yasutsuna",
    "Muramasa",
    "Brass Knuckles",
    "Cestus",
    "Whip Knuckle",
    "Mach Punch",
    "Kaiser Knuckle",
    "Handgun",
    "Silver Gun",
    "Boomerang",
    "Chakram",
    "Tomahawk",
    "Throwing Sickle",
    "RPG",
    "Terror Bear",
    "Nunchakus",
    "Whip",
    "Casual Clothes",
    "Cloth Tunic",
    "Gym Clothes",
    "Kung Fu Suit",
    "Biker Jacket",
    "War Fatigues",
    "Ninja Suit",
    "Three 7s",
    "Justaucorps",
    "Army Jacket",
    "Pitch Black Suit",
    "Olrox's Suit",
    "Dracula's Tunic",
    "Leather Armor",
    "Breastplate",
    "Ring Mail",
    "Scale Mail",
    "Chain Mail",
    "Hauberk",
    "Cuirass",
    "Blocking Mail",
    "Eversing",
    "Demon's Mail",
    "Silk Robe",
    "Mage Robe",
    "Elfin Robe",
    "Wyrm Robe",
    "Aquarius",
    "Serenity Robe",
    "Death's Robe",
    "Cape",
    "Traveler Cape",
    "Crimson Cloak",
    "Black Cloak",
    "Pendant",
    "Heart Pendant",
    "Skull Necklace",
    "Flame Necklace",
    "Rosary",
    "Scarf",
    "Red Scarf",
    "Neck Warmer",
    "Power Belt",
    "Black Belt",
    "Megingiord",
    "Hoop Earring",
    "Turquoise Stud",
    "Silver Stud",
    "Gold Stud",
    "Bloody Stud",
    "Platinum Stud",
    "Tear Of Blood",
    "Lucky Charm",
    "Mina's Talisman",
    "Satan's Ring",
    "Rare Ring",
    "Soul Eater Ring",
    "Rune Ring",
    "Shaman Ring",
    "Gold Ring",
    "Chaos Ring"
]

common_filler_pool = [
    "Potion",
    "High Potion",
    "Super Potion",
    "Mind Up",
    "High Mind Up",
    "Mana Prism",
    "Anti-Venom",
    "Uncurse Potion",
    "Meat Strip",
    "Tasty Meat",
    "Rice Ball",
    "Mushroom",
    "Corn Soup",
    "Beef Curry",
    "Noodles",
    "Cream Soda",
    "Cream Puff",
    "Milk",
    "Coffee",
    "Tea",
    "Pudding",
    "Strawberry",
    "Melon",
    "Grapes",
    "Hamburger",
    "Fried Chicken",
    "Hot Dog",
    "Pumpkin Pie",
    "Pancake",
    "Piroshki",
    "Tinned Spinach",
    "Foie Gras",
    "Caviar",
    "Truffle",
    "Paella",
    "Spaghetti",
    "Ice Cream",
    "Salmon Meuniere",
    "Boiled Starfish",
    "Amanita",
    "Rotten Meat",
    "Spoiled Milk",
    "Rusty Food Tin",
    "CASTLE MAP 1",
    "CASTLE MAP 2",
    "UMA News 1-1",
    "UMA News 1-2",
    "UMA News 1-3",
    "UMA News 2-1",
    "UMA News 2-2",
    "UMA News 2-3",
    "UMA News 2-4",
    "UMA News 3-1",
    "UMA News 3-2",
    "UMA News 3-3",
    "UMA News 4",
    "Knife",
    "Combat Knife",
    "Baselard",
    "Cutall",
    "Cinquedia",
    "Rapier",
    "Fleuret",
    "Main Gauche",
    "Small Sword",
    "Estoc",
    "Whip Sword",
    "Garian Sword",
    "Kris Naga",
    "Nebula",
    "Short Sword",
    "Cutlass",
    "Long Sword",
    "Fragarach",
    "Hrunting",
    "Mystletain",
    "Joyeuse",
    "Milican's Sword",
    "Ice Brand",
    "Laevatain",
    "Burtgang",
    "Kaladbolg",
    "Valmanway",
    "Alucard Sword",
    "Claymore",
    "Falchion",
    "Great Sword",
    "Durandal",
    "Dainslef",
    "Ascalon",
    "Balmung",
    "Final Sword",
    "Claimh Solais",
    "Spear",
    "Partizan",
    "Halberd",
    "Lance",
    "Trident",
    "Brionac",
    "Geiborg",
    "Longinus",
    "Gungner",
    "Mace",
    "Morgenstern",
    "Mjollnjr",
    "Axe",
    "Battle Axe",
    "Bhuj",
    "Great Axe",
    "Golden Axe",
    "Death Scythe",
    "Blunt Sword",
    "Katana",
    "Kotetsu",
    "Masamune",
    "Osafune",
    "Kunitsuna",
    "Yasutsuna",
    "Muramasa",
    "Brass Knuckles",
    "Cestus",
    "Whip Knuckle",
    "Mach Punch",
    "Kaiser Knuckle",
    "Handgun",
    "Silver Gun",
    "Boomerang",
    "Chakram",
    "Tomahawk",
    "Throwing Sickle",
    "Cloth Tunic",
    "Gym Clothes",
    "Kung Fu Suit",
    "Biker Jacket",
    "War Fatigues",
    "Ninja Suit",
    "Three 7s",
    "Justaucorps",
    "Army Jacket",
    "Pitch Black Suit",
    "Olrox's Suit",
    "Dracula's Tunic",
    "Leather Armor",
    "Breastplate",
    "Ring Mail",
    "Scale Mail",
    "Chain Mail",
    "Hauberk",
    "Cuirass",
    "Blocking Mail",
    "Eversing",
    "Demon's Mail",
    "Silk Robe",
    "Mage Robe",
    "Elfin Robe",
    "Wyrm Robe",
    "Aquarius",
    "Serenity Robe",
    "Death's Robe",
    "Cape",
    "Traveler Cape",
    "Crimson Cloak",
    "Black Cloak",
    "Pendant",
    "Heart Pendant",
    "Skull Necklace",
    "Flame Necklace",
    "Rosary",
    "Scarf",
    "Red Scarf",
    "Neck Warmer",
    "Power Belt",
    "Black Belt",
    "Megingiord",
    "Hoop Earring",
    "Turquoise Stud",
    "Silver Stud",
    "Gold Stud",
    "Bloody Stud",
    "Platinum Stud",
    "Tear Of Blood",
    "Lucky Charm",
    "Satan's Ring",
    "Rare Ring",
    "Soul Eater Ring",
    "Rune Ring",
    "Shaman Ring",
    "Gold Ring"
]

enemy_table = [
    "Zombie",
    "Bat",
    "Ghost",
    "Skeleton",
    "Ouija Table",
    "Peeping Eye",
    "Axe Armor",
    "Skull Archer",
    "Warg",
    "Spin Devil",
    "Armor Knight",
    "Student Witch",
    "Slaughterer",
    "Bomber Armor",
    "Golem",
    "Slime",
    "Une",
    "Skeleton Ape",
    "Manticore",
    "Mollusca",
    "Rycuda",
    "Mandragora",
    "Yorick",
    "Skeleton Farmer",
    "The Creature",
    "Catoblepas",
    "Ghoul",
    "Corpseweed",
    "Yeti",
    "Tombstone",
    "Ghost Dancer",
    "Flying Humanoid",
    "Mini Devil",
    "Quetzalcoatl",
    "Treant",
    "Amalaric Sniper",
    "Valkyrie",
    "Great Armor",
    "Killer Doll",
    "Waiter Skeleton",
    "Persephone",
    "Witch",
    "Buer",
    "Lilith",
    "Killer Clown",
    "Skelerang",
    "Fleaman",
    "Devil",
    "Guillotiner",
    "Draghignazzo",
    "Needles",
    "Hell Boar",
    "Bone Pillar",
    "White Dragon",
    "Wakwak Tree",
    "Imp",
    "Harpy",
    "Barbariccia",
    "Malachi",
    "Cave Troll",
    "Larva",
    "Heart Eater",
    "Merman",
    "Fish Head",
    "Medusa Head",
    "Ukoback",
    "Killer Fish",
    "Mimic",
    "Dead Pirate",
    "Frozen Shade",
    "Homunculus",
    "Disc Armor",
    "Decarabia",
    "Dead Mate",
    "Bugbear",
    "Procel",
    "Bone Ark",
    "Gorgon",
    "Alura Une",
    "Great Axe Armor",
    "Mothman",
    "Mushussu",
    "Dead Crusader",
    "Dead Warrior",
    "Erinys",
    "Succubus",
    "Ripper",
    "Black Panther",
    "Mud Demon",
    "Giant Slug",
    "Werewolf",
    "Flame Demon",
    "Tanjelly",
    "Arc Demon",
    "Gaibon",
    "Slogra",
    "Stolas",
    "Final Guard",
    "Malacoda",
    "Alastor",
    "Iron Golem",
    "Flying Armor",
    "Balore",
    "Malphas",
    "Dimitrii",
    "Dario",
    "Puppet Master",
    "Rahab",
    "Gergoth",
    "Zephyr",
    "Bat Company",
    "Paranoia",
    "Aguni",
    "Death",
    "Abaddon",
    "Menace",
    "Soma",
    "Dracula"
]

boss_list = {
    "Flying Armor",
    "Balore",
    "Malphas",
    "Dimitrii",
    "Dario",
    "Puppet Master",
    "Rahab",
    "Gergoth",
    "Zephyr",
    "Bat Company",
    "Paranoia",
    "Aguni",
    "Death",
    "Abaddon",
    "Menace",
    "Soma",
    "Dracula"
}

unleveled_standard_souls = [
    "Imp Soul",
    "Yorick Soul",
    "Mandragora Soul",
    "Slaughterer Soul",
    "Hell Boar Soul",
    "Succubus Soul",
    "Erinys Soul",
    "Malacoda Soul",
    "Flame Demon Soul",
    "Black Panther Soul",
    "Ghost Soul",
    "Yeti Soul",
    "Flying Humanoid Soul",
    "Devil Soul",
    "Medusa Head Soul",
    "Final Guard Soul",
    "Werewolf Soul",
    "Iron Golem Soul",
    "Bone Ark Soul",
    "Barbariccia Soul",
    "Valkyrie Soul",
    "Great Armor Soul",
    "Tanjelly Soul",
    "Bugbear Soul",
    "Arc Demon Soul",
    "Giant Slug Soul",
    "Killer Doll Soul",
    "Tombstone Soul",
    "Treant Soul",
    "Ghoul Soul",
    "Skelerang Soul",
    "Skeleton Ape Soul",
    "Dead Warrior Soul",
    "Dead Pirate Soul",
    "Draghignazzo Soul",
    "Peeping Eye Soul",
    "Skeleton Farmer Soul",
    "The Creature Soul",
    "Mimic Soul",
    "Mothman Soul",
    "Ouija Table Soul",
    "Dead Crusader Soul",
    "Procel Soul",
    "Mud Demon Soul"
]
