from typing import NamedTuple

class LocationInformation(NamedTuple):  # In-game information used to define each Location in the ROM.
    pointer: int
    file: str
    location_type: str

location_ids = {
    "Demon Guest House: Antechamber": 0x01,
    "Garden of Madness: Lower Tree Hallway": 0x02,
    "Demon Guest House: West Wing Left": 0x03,
    "Cursed Clock Tower: Bugbear Hallway": 0x04,
    "The Pinnacle: Beyond Throne Room": 0x05,
    "Lost Village: Pre-Boss Room Lower": 0x06,
    "Lost Village: East Plaza": 0x07,
    "Dark Chapel: Main Room": 0x08,
    "Garden of Madness: Center Room": 0x09,
    "Lost Village: Upper Big Room Corner": 0x0B,
    "Demon Guest House: Doll Alcove": 0x0C,
    "Dark Chapel: Big Room Lower": 0x0D,
    "Silenced Ruins: Mirror World": 0x0F,
    "Wizardry Lab: Underwater Right": 0x10,
    "Condemned Tower: 1F East": 0x12,
    "Wizardry Lab: Main Entry Shaft": 0x13,
    "The Abyss: Sand Area": 0x14,
    "Demon Guest House: Puppet Hole": 0x15,
    "Dark Chapel: Bell Room Right": 0x16,
    "Subterranean Hell: Giant Underwater Room Center Left": 0x17,
    "Silenced Ruins: Mirror Room": 0x18,
    "The Pinnacle: Central Indoor Room": 0x19,
    "Dark Chapel: Bell Room Top Left": 0x1A,
    "Condemned Tower: Top of the Tower": 0x1E,
    "Lost Village: West Building Lower": 0x1F,
    "Lost Village: Central Building": 0x20,
    "Lost Village: Hidden Floor Room 1": 0x21,
    "Demon Guest House: Lower Main Chamber Bottom Room": 0x22,
    "Dark Chapel: Catacombs Top Left": 0x23,
    "Demon Guest House: Central Main Chamber Top Room": 0x25,
    "Subterranean Hell: Giant Underwater Room Center Right": 0x26,
    "Subterranean Hell: Central Upper Room": 0x27,
    "Wizardry Lab: Ceiling Secret Room": 0x28,
    "Lost Village: Axe Armor Hallway": 0x29,
    "The Pinnacle: Lower Hidden Room": 0x2A,
    "Lost Village: Hidden Floor Room 2": 0x2B,
    "Lost Village: Above Entrance": 0x2C,
    "Subterranean Hell: Waterfall Room Upper": 0x30,
    "Subterranean Hell: Waterfall Room Lower": 0x31,
    "Subterranean Hell: Central Lower Room": 0x32,
    "Subterranean Hell: Waterfall Room Middle": 0x33,
    "Subterranean Hell: Giant Underwater Room Bottom Right": 0x34,
    "Condemned Tower: 1F West": 0x35,
    "Demon Guest House: Paranoia Mirror": 0x36,
    "Demon Guest House: Central Main Chamber Middle Room": 0x37,
    "Subterranean Hell: Near Save Room": 0x38,
    "Demon Guest House: West Wing Right": 0x39,
    "Condemned Tower: 7F West": 0x3A,
    "Demon Guest House: Ice Block Room Right": 0x3B,
    "Dark Chapel: Big Room Central": 0x3C,
    "Cursed Clock Tower: East Gear Room": 0x3D,
    "Wizardry Lab: Behind West Gate": 0x3E,
    "Garden of Madness: West Big Room": 0x3F,
    "Demon Guest House: Mirror Room": 0x40,
    "Cursed Clock Tower: Mirror Room": 0x41,
    "Subterranean Hell: Giant Underwater Room Top Left": 0x42,
    "Subterranean Hell: Behind Waterfall": 0x43,
    "Garden of Madness: Hidden Room": 0x44,
    "Garden of Madness: Money Gate": 0x45,
    "Demon Guest House: Number 9 Room": 0x46,
    "Cursed Clock Tower: Lower Corner Room": 0x47,
    "Demon Guest House: Ice Block Room Left": 0x48,
    "Demon Guest House: Beyond Paranoia": 0x49,
    "Demon Guest House: Mirror World": 0x4A,
    "Garden of Madness: West Upper Room": 0x4B,
    "Wizardry Lab: East Gate": 0x4C,
    "Wizardry Lab: Above Water": 0x4D,
    "Lost Village: Mirror Room Left": 0x4F,
    "Dark Chapel: Catacombs Middle Room": 0x50,
    "Lost Village: Above Drawbridge": 0x51,
    "Lost Village: Above Guest House Entrance": 0x53,
    "Wizardry Lab: Mirror World": 0x54,
    "Wizardry Lab: West Gate": 0x55,
    "Dark Chapel: Catacombs Mirror Room": 0x56,
    "Lost Village: Underground Shaft": 0x57,
    "Dark Chapel: Big Square Room Alcove": 0x58,
    "Dark Chapel: Catacombs Mirror World": 0x59,
    "Dark Chapel: Post-Dimitrii Room": 0x5A,
    "Demon Guest House: Number 8 Room": 0x5B,
    "Condemned Tower: 2F East": 0x5C,
    "Lost Village: In Moat": 0x5D,
    "Wizardry Lab: Underwater Left": 0x5E,
    "Cursed Clock Tower: Mirror World": 0x5F,
    "Lost Village: Mirror Room Right": 0x60,
    "The Pinnacle: Before Throne Room Secret Left": 0x61,
    "Silenced Ruins: Ice Block Room": 0x62,
    "Demon Guest House: Secret Room": 0x63,
    "Cursed Clock Tower: Money Gate": 0x64,
    "Wizardry Lab: Money Gate": 0x65,
    "The Abyss: Ice Area": 0x66,
    "Lost Village: West Plaza": 0x67,
    "Demon Guest House: Number 1 Room": 0x68,
    "Lost Village: Pre-Boss Room Upper": 0x69,
    "Dark Chapel: Entrance Alcove": 0x6A,
    "The Pinnacle: Before Throne Room Secret Right": 0x6B,
    "Lost Village: Flying Armor Indoor Room": 0x6C,
    "Demon Guest House: Number 12 Room": 0x6D,
    "The Pinnacle: Under Big Staircase": 0x6E,
    "Lost Village: West Building Upper": 0x6F,
    "Wizardry Lab: Mirror Room": 0x70,
    "Demon Guest House: Number 5 Room": 0x71,
    "Garden of Madness: West Big Room Alcove": 0x72,
    "Garden of Madness: Underground Room": 0x73,
    "Condemned Tower: 5F West": 0x74,
    "Garden of Madness: East Alcove": 0x75,
    "Dark Chapel: Catacombs Soul Barrier": 0x76,
    "The Pinnacle: Central Outdoor Room": 0x77,
    "Wizardry Lab: Upper Big Room": 0x78,
    "Dark Chapel: Big Room Top Right": 0x79,




    #"Demon Guest House: Central Main Chamber Bottom Room": 0x, # TODO! Pickup flag for this
    #"Dark Chapel: Bell Room In Bell": 0x,
    #"Lost Village: Drawbridge Room": 0x00,  # TODO! THIS NEEDS A REAL FLAG NOW
    #     "Cursed Clock Tower: Spike Room Secret": 0x, # TODO! Pickup flag

    "Puppet Master Soul": 0x100,
    "Zephyr Soul": 0x101,
    "Paranoia Soul": 0x102,
    "Imp Soul": 0x103,
    "Skeleton Soul": 0x104,
    "Zombie Soul": 0x105,
    "Axe Armor Soul": 0x106,
    "Student Witch Soul": 0x107,
    "Warg Soul": 0x108,
    "Bomber Armor Soul": 0x109,
    "Amalaric Sniper Soul": 0x10A,
    "Cave Troll Soul": 0x10B,
    "Waiter Skeleton Soul": 0x10C,
    "Slime Soul": 0x10D,
    "Yorick Soul": 0x10E,
    "Une Soul": 0x10F,
    "Mandragora Soul": 0x110,
    "Rycuda Soul": 0x111,
    "Fleaman Soul": 0x112,
    "Ripper Soul": 0x113,
    "Guillotiner Soul": 0x114,
    "Killer Clown Soul": 0x115,
    "Malachi Soul": 0x116,
    "Disc Armor Soul": 0x117,
    "Great Axe Armor Soul": 0x118,
    "Slaughterer Soul": 0x119,
    "Hell Boar Soul": 0x11A,
    "Frozen Shade Soul": 0x11B,
    "Merman Soul": 0x11C,
    "Larva Soul": 0x11D,
    "Ukoback Soul": 0x11E,
    "Decarabia Soul": 0x11F,
    "Succubus Soul": 0x120,
    "Slogra Soul": 0x121,
    "Erinys Soul": 0x122,
    "Homunculus Soul": 0x123,
    "Witch Soul": 0x124,
    "Fish Head Soul": 0x125,
    "Mollusca Soul": 0x126,
    "Dead Mate Soul": 0x127,
    "Killer Fish Soul": 0x128,
    "Malacoda Soul": 0x129,
    "Flame Demon Soul": 0x12A,
    "Aguni Soul": 0x12B,
    "Abaddon Soul": 0x12C,

    "Flying Armor Soul": 0x135,
    "Bat Company Soul": 0x136,
    "Black Panther Soul": 0x137,
    "Armor Knight Soul": 0x138,
    "Spin Devil Soul": 0x139,
    "Skull Archer Soul": 0x13A,
    "Ghost Soul": 0x13B,
    "Yeti Soul": 0x13C,
    "Buer Soul": 0x13D,
    "Manticore Soul": 0x13E,
    "Mushussu Soul": 0x13F,
    "White Dragon Soul": 0x140,
    "Catoblepas Soul": 0x141,
    "Gorgon Soul": 0x142,
    "Persephone Soul": 0x143,
    "Flying Humanoid Soul": 0x144,
    "Devil Soul": 0x145,
    "Medusa Head Soul": 0x146,
    "Final Guard Soul": 0x147,
    "Werewolf Soul": 0x148,
    "Alura Une Soul": 0x149,
    "Iron Golem Soul": 0x14A,
    "Bone Ark Soul": 0x14B,
    "Barbariccia Soul": 0x14C,
    "Valkyrie Soul": 0x14D,
    "Bat Soul": 0x14E,
    "Great Armor Soul": 0x14F,
    "Mini Devil Soul": 0x150,
    "Harpy Soul": 0x151,
    "Corpseweed Soul": 0x152,
    "Quetzalcoatl Soul": 0x153,
    "Needles Soul": 0x154,
    "Alastor Soul": 0x155,
    "Gaibon Soul": 0x156,
    "Gergoth Soul": 0x157,
    "Death Soul": 0x158,
    "Golem Soul": 0x159,
    "Bone Pillar Soul": 0x15A,
    "Lilith Soul": 0x15B,
    "Ghost Dancer Soul": 0x15C,
    "Tanjelly Soul": 0x15D,
    "Bugbear Soul": 0x15E,
    "Arc Demon Soul": 0x15F,
    "Giant Slug Soul": 0x160,
    "Killer Doll Soul": 0x161,
    "Tombstone Soul": 0x162,
    "Treant Soul": 0x163,
    "Ghoul Soul": 0x164,
    "Skelerang Soul": 0x165,
    "Skeleton Ape Soul": 0x166,
    "Dead Warrior Soul": 0x167,
    "Dead Pirate Soul": 0x168,
    "Draghignazzo Soul": 0x169,
    "Heart Eater Soul": 0x16A,
    "Peeping Eye Soul": 0x16B,
    "Skeleton Farmer Soul": 0x16C,
    "The Creature Soul": 0x16D,
    "Mimic Soul": 0x16E,
    "Mothman Soul": 0x16F,
    "Ouija Table Soul": 0x170,
    "Dead Crusader Soul": 0x171,
    "Stolas Soul": 0x172,
    "Wakwak Tree Soul": 0x173,
    "Balore Soul": 0x174,
    "Malphas Soul": 0x175,
    "Rahab Soul": 0x177,
    "Procel Soul": 0x179,
    "Mud Demon Soul": 0x17A,

    "Wizardry Lab: West Gate Button": 0x200,
    "Wizardry Lab: East Gate Button": 0x201,
    "Garden of Madness: Gate Button": 0x202,
    "Subterranean Hell: Gate Button": 0x203
}

location_data_table = {
    "Ecclesia: Center Chest": LocationInformation(0x022D3094, "overlay_42", "Chest"),

}

def get_location_groups():
    location_groups = {
        "Lost Village": set(),
        "Demon Guest House": set(),
        "Wizardry Lab": set(),
        "Garden of Madness": set(),
        "Dark Chapel": set(),
        "Condemned Tower": set(),
        "Subterranean Hell": set(),
        "Silenced Ruins": set(),
        "Cursed Clock Tower": set(),
        "The Pinnacle": set(),
        "Mine of Judgment": set(),
        "The Abyss": set(),
    }
    for location in location_ids:
        group = location.split(":")[0]
        if group in location_groups:
            location_groups[group].add(location)  #TODO! Enemy groups, grouped to their source area

    return location_groups
