from typing import NamedTuple


class LocationInformation(NamedTuple):  # In-game information used to define each Location in the ROM.
    pointer: int
    location_type: str = "Normal"


location_ids = {
    "Demon Guest House: Antechamber": 0x01,
    "Garden of Madness: Lower Tree Hallway": 0x02,
    "Demon Guest House: West Wing Left": 0x03,
    "Cursed Clock Tower: Bugbear Hallway": 0x04,
    "The Pinnacle: Beyond Throne Room": 0x05,
    "Lost Village: Pre-Boss Room Lower": 0x06,
    "Lost Village: East Plaza": 0x07,
    "Dark Chapel: Main Room": 0x08,
    "Garden of Madness: Center Room": 0x09,
    # A is reserved for the bottom tier of the hammer thing
    "Lost Village: Upper Big Room Corner": 0x0B,
    "Demon Guest House: Doll Alcove": 0x0C,
    "Dark Chapel: Big Room Lower": 0x0D,
    # E is the second
    "Silenced Ruins: Mirror World": 0x0F,
    "Wizardry Lab: Underwater Right": 0x10,
    # 11 is the third
    "Condemned Tower: 1F East": 0x12,
    "Wizardry Lab: Main Entry Shaft": 0x13,
    "The Abyss: Sand Area": 0x14,
    "Demon Guest House: Puppet Hole": 0x15,
    "Dark Chapel: Bell Room Right": 0x16,
    "Subterranean Hell: Giant Underwater Room Center Left": 0x17,
    "Silenced Ruins: Mirror Room": 0x18,
    "The Pinnacle: Central Indoor Room": 0x19,
    "Dark Chapel: Bell Room Top Left": 0x1A,

    "Condemned Tower: Top of the Tower": 0x1E,
    "Lost Village: West Building Lower": 0x1F,
    "Lost Village: Central Building": 0x20,
    "Lost Village: Hidden Floor Room 1": 0x21,
    "Demon Guest House: Lower Main Chamber Bottom Room": 0x22,
    "Dark Chapel: Catacombs Top Left": 0x23,
    "Demon Guest House: Central Main Chamber Top Room": 0x25,
    "Subterranean Hell: Giant Underwater Room Center Right": 0x26,
    "Subterranean Hell: Central Upper Room": 0x27,
    "Wizardry Lab: Ceiling Secret Room": 0x28,
    "Lost Village: Axe Armor Hallway": 0x29,
    "The Pinnacle: Lower Hidden Room": 0x2A,
    "Lost Village: Hidden Floor Room 2": 0x2B,
    "Lost Village: Above Entrance": 0x2C,
    "Cursed Clock Tower: Spike Room Secret": 0x2D,
    "Demon Guest House: Central Main Chamber Bottom Room": 0x2E,
    "Dark Chapel: Bell Room In Bell": 0x2F,
    "Subterranean Hell: Waterfall Room Upper": 0x30,
    "Subterranean Hell: Waterfall Room Lower": 0x31,
    "Subterranean Hell: Central Lower Room": 0x32,
    "Subterranean Hell: Waterfall Room Middle": 0x33,
    "Subterranean Hell: Giant Underwater Room Bottom Right": 0x34,
    "Condemned Tower: 1F West": 0x35,
    "Demon Guest House: Paranoia Mirror": 0x36,
    "Demon Guest House: Central Main Chamber Middle Room": 0x37,
    "Subterranean Hell: Near Save Room": 0x38,
    "Demon Guest House: West Wing Right": 0x39,
    "Condemned Tower: 7F West": 0x3A,
    "Demon Guest House: Ice Block Room Right": 0x3B,
    "Dark Chapel: Big Room Central": 0x3C,
    "Cursed Clock Tower: East Gear Room": 0x3D,
    "Wizardry Lab: Behind West Gate": 0x3E,
    "Garden of Madness: West Big Room": 0x3F,
    "Demon Guest House: Mirror Room": 0x40,
    "Cursed Clock Tower: Mirror Room": 0x41,
    "Subterranean Hell: Giant Underwater Room Top Left": 0x42,
    "Subterranean Hell: Behind Waterfall": 0x43,
    "Garden of Madness: Hidden Room": 0x44,
    "Garden of Madness: Money Gate": 0x45,
    "Demon Guest House: Number 9 Room": 0x46,
    "Cursed Clock Tower: Lower Corner Room": 0x47,
    "Demon Guest House: Ice Block Room Left": 0x48,
    "Demon Guest House: Beyond Paranoia": 0x49,
    "Demon Guest House: Mirror World": 0x4A,
    "Garden of Madness: West Upper Room": 0x4B,
    "Wizardry Lab: East Gate": 0x4C,
    "Wizardry Lab: Above Water": 0x4D,
    "Lost Village: Drawbridge Room": 0x4E,  # TODO! Set this flag in game!
    "Lost Village: Mirror Room Left": 0x4F,
    "Dark Chapel: Catacombs Middle Room": 0x50,
    "Lost Village: Above Drawbridge": 0x51,
    "Lost Village: Above Guest House Entrance": 0x53,
    "Wizardry Lab: Mirror World": 0x54,
    "Wizardry Lab: West Gate": 0x55,
    "Dark Chapel: Catacombs Mirror Room": 0x56,
    "Lost Village: Underground Shaft": 0x57,
    "Dark Chapel: Big Square Room Alcove": 0x58,
    "Dark Chapel: Catacombs Mirror World": 0x59,
    "Dark Chapel: Post-Dimitrii Room": 0x5A,
    "Demon Guest House: Number 8 Room": 0x5B,
    "Condemned Tower: 2F East": 0x5C,
    "Lost Village: In Moat": 0x5D,
    "Wizardry Lab: Underwater Left": 0x5E,
    "Cursed Clock Tower: Mirror World": 0x5F,
    "Lost Village: Mirror Room Right": 0x60,
    "The Pinnacle: Before Throne Room Secret Left": 0x61,
    "Silenced Ruins: Ice Block Room": 0x62,
    "Demon Guest House: Secret Room": 0x63,
    "Cursed Clock Tower: Money Gate": 0x64,
    "Wizardry Lab: Money Gate": 0x65,
    "The Abyss: Ice Area": 0x66,
    "Lost Village: West Plaza": 0x67,
    "Demon Guest House: Number 1 Room": 0x68,
    "Lost Village: Pre-Boss Room Upper": 0x69,
    "Dark Chapel: Entrance Alcove": 0x6A,
    "The Pinnacle: Before Throne Room Secret Right": 0x6B,
    "Lost Village: Flying Armor Indoor Room": 0x6C,
    "Demon Guest House: Number 12 Room": 0x6D,
    "The Pinnacle: Under Big Staircase": 0x6E,
    "Lost Village: West Building Upper": 0x6F,
    "Wizardry Lab: Mirror Room": 0x70,
    "Demon Guest House: Number 5 Room": 0x71,
    "Garden of Madness: West Big Room Alcove": 0x72,
    "Garden of Madness: Underground Room": 0x73,
    "Condemned Tower: 5F West": 0x74,
    "Garden of Madness: East Alcove": 0x75,
    "Dark Chapel: Catacombs Soul Barrier": 0x76,
    "The Pinnacle: Central Outdoor Room": 0x77,
    "Wizardry Lab: Upper Big Room": 0x78,
    "Dark Chapel: Big Room Top Right": 0x79,

    "Puppet Master Soul": 0x100,
    "Zephyr Soul": 0x101,
    "Paranoia Soul": 0x102,
    "Imp Soul": 0x103,
    "Skeleton Soul": 0x104,
    "Zombie Soul": 0x105,
    "Axe Armor Soul": 0x106,
    "Student Witch Soul": 0x107,
    "Warg Soul": 0x108,
    "Bomber Armor Soul": 0x109,
    "Amalaric Sniper Soul": 0x10A,
    "Cave Troll Soul": 0x10B,
    "Waiter Skeleton Soul": 0x10C,
    "Slime Soul": 0x10D,
    "Yorick Soul": 0x10E,
    "Une Soul": 0x10F,
    "Mandragora Soul": 0x110,
    "Rycuda Soul": 0x111,
    "Fleaman Soul": 0x112,
    "Ripper Soul": 0x113,
    "Guillotiner Soul": 0x114,
    "Killer Clown Soul": 0x115,
    "Malachi Soul": 0x116,
    "Disc Armor Soul": 0x117,
    "Great Axe Armor Soul": 0x118,
    "Slaughterer Soul": 0x119,
    "Hell Boar Soul": 0x11A,
    "Frozen Shade Soul": 0x11B,
    "Merman Soul": 0x11C,
    "Larva Soul": 0x11D,
    "Ukoback Soul": 0x11E,
    "Decarabia Soul": 0x11F,
    "Succubus Soul": 0x120,
    "Slogra Soul": 0x121,
    "Erinys Soul": 0x122,
    "Homunculus Soul": 0x123,
    "Witch Soul": 0x124,
    "Fish Head Soul": 0x125,
    "Mollusca Soul": 0x126,
    "Dead Mate Soul": 0x127,
    "Killer Fish Soul": 0x128,
    "Malacoda Soul": 0x129,
    "Flame Demon Soul": 0x12A,
    "Aguni Soul": 0x12B,
    "Abaddon Soul": 0x12C,

    "Flying Armor Soul": 0x135,
    "Bat Company Soul": 0x136,
    "Black Panther Soul": 0x137,
    "Armor Knight Soul": 0x138,
    "Spin Devil Soul": 0x139,
    "Skull Archer Soul": 0x13A,
    "Ghost Soul": 0x13B,
    "Yeti Soul": 0x13C,
    "Buer Soul": 0x13D,
    "Manticore Soul": 0x13E,
    "Mushussu Soul": 0x13F,
    "White Dragon Soul": 0x140,
    "Catoblepas Soul": 0x141,
    "Gorgon Soul": 0x142,
    "Persephone Soul": 0x143,
    "Flying Humanoid Soul": 0x144,
    "Devil Soul": 0x145,
    "Medusa Head Soul": 0x146,
    "Final Guard Soul": 0x147,
    "Werewolf Soul": 0x148,
    "Alura Une Soul": 0x149,
    "Iron Golem Soul": 0x14A,
    "Bone Ark Soul": 0x14B,
    "Barbariccia Soul": 0x14C,
    "Valkyrie Soul": 0x14D,
    "Bat Soul": 0x14E,
    "Great Armor Soul": 0x14F,
    "Mini Devil Soul": 0x150,
    "Harpy Soul": 0x151,
    "Corpseweed Soul": 0x152,
    "Quetzalcoatl Soul": 0x153,
    "Needles Soul": 0x154,
    "Alastor Soul": 0x155,
    "Gaibon Soul": 0x156,
    "Gergoth Soul": 0x157,
    "Death Soul": 0x158,
    "Golem Soul": 0x159,
    "Bone Pillar Soul": 0x15A,
    "Lilith Soul": 0x15B,
    "Ghost Dancer Soul": 0x15C,
    "Tanjelly Soul": 0x15D,
    "Bugbear Soul": 0x15E,
    "Arc Demon Soul": 0x15F,
    "Giant Slug Soul": 0x160,
    "Killer Doll Soul": 0x161,
    "Tombstone Soul": 0x162,
    "Treant Soul": 0x163,
    "Ghoul Soul": 0x164,
    "Skelerang Soul": 0x165,
    "Skeleton Ape Soul": 0x166,
    "Dead Warrior Soul": 0x167,
    "Dead Pirate Soul": 0x168,
    "Draghignazzo Soul": 0x169,
    "Heart Eater Soul": 0x16A,
    "Peeping Eye Soul": 0x16B,
    "Skeleton Farmer Soul": 0x16C,
    "The Creature Soul": 0x16D,
    "Mimic Soul": 0x16E,
    "Mothman Soul": 0x16F,
    "Ouija Table Soul": 0x170,
    "Dead Crusader Soul": 0x171,
    "Stolas Soul": 0x172,
    "Wakwak Tree Soul": 0x173,
    "Balore Soul": 0x174,
    "Malphas Soul": 0x175,
    "Rahab Soul": 0x177,
    "Procel Soul": 0x179,
    "Mud Demon Soul": 0x17A,

    "Wizardry Lab: West Gate Button": 0x200,
    "Wizardry Lab: East Gate Button": 0x201,
    "Garden of Madness: Gate Button": 0x202,
    "Subterranean Hell: Gate Button": 0x203
}

location_data_table = {
    "Lost Village: Above Entrance": LocationInformation(0x020A0B6C),
    "Lost Village: Upper Big Room Corner": LocationInformation(0x020A0EC0),
    "Lost Village: Pre-Boss Room Upper": LocationInformation(0x020A12A4),
    "Lost Village: Pre-Boss Room Lower": LocationInformation(0x020A1298),
    "Lost Village: Drawbridge Room": LocationInformation(0x020A15EC),
    "Lost Village: Above Drawbridge": LocationInformation(0x020A1604),
    "Lost Village: In Moat": LocationInformation(0x020A15F8),
    "Lost Village: Above Guest House Entrance": LocationInformation(0x020A164C),
    "Lost Village: Flying Armor Indoor Room": LocationInformation(0x020A0FB0),
    "Lost Village: West Plaza": LocationInformation(0x020A1718),
    "Lost Village: West Building Upper": LocationInformation(0x020A0C8C),
    "Lost Village: West Building Lower": LocationInformation(0x020A0C98),
    "Lost Village: Central Building": LocationInformation(0x020A101C),
    "Lost Village: East Plaza": LocationInformation(0x020A1118),
    "Lost Village: Hidden Floor Room 1": LocationInformation(0x020A146C),
    "Lost Village: Hidden Floor Room 2": LocationInformation(0x020A1478),
    "Lost Village: Mirror Room Left": LocationInformation(0x020A1520),
    "Lost Village: Mirror Room Right": LocationInformation(0x020A152C),
    "Lost Village: Axe Armor Hallway": LocationInformation(0x020A0E3C),
    "Lost Village: Underground Shaft": LocationInformation(0x020A11F0),

    "Wizardry Lab: Mirror Room": LocationInformation(0x020A953C),
    "Wizardry Lab: Mirror World": LocationInformation(0x020A9548),
    "Wizardry Lab: Main Entry Shaft": LocationInformation(0x020A911C),
    "Wizardry Lab: Upper Big Room": LocationInformation(0x020A923C),
    "Wizardry Lab: West Gate": LocationInformation(0x020A8E34),
    "Wizardry Lab: Behind West Gate": LocationInformation(0x020A8E28),
    "Wizardry Lab: Ceiling Secret Room": LocationInformation(0x020A9584),
    "Wizardry Lab: East Gate": LocationInformation(0x020A9458),
    "Wizardry Lab: Money Gate": LocationInformation(0x020A95CC),
    "Wizardry Lab: Underwater Left": LocationInformation(0x020A99BC),
    "Wizardry Lab: Underwater Right": LocationInformation(0x020A99C8),
    "Wizardry Lab: Above Water": LocationInformation(0x020A9A4C),

    "Garden of Madness: Lower Tree Hallway": LocationInformation(0x020AC224),
    "Garden of Madness: West Big Room": LocationInformation(0x020AC014),
    "Garden of Madness: West Big Room Alcove": LocationInformation(0x020AC008),
    "Garden of Madness: West Upper Room": LocationInformation(0x020AC128),
    "Garden of Madness: Hidden Room": LocationInformation(0x020AC248),
    "Garden of Madness: Center Room": LocationInformation(0x020ACC14),
    "Garden of Madness: Money Gate": LocationInformation(0x020ACA64),
    "Garden of Madness: Underground Room": LocationInformation(0x020AC9E0),
    "Garden of Madness: East Alcove": LocationInformation(0x020AC8B4),

    "Demon Guest House: Secret Room": LocationInformation(0x020A6368),
    "Demon Guest House: Antechamber": LocationInformation(0x020A62FC),
    "Demon Guest House: Lower Main Chamber Bottom Room": LocationInformation(0x020A6338),
    "Demon Guest House: Puppet Hole": LocationInformation(0x020A608C),
    "Demon Guest House: Number 1 Room": LocationInformation(0x020A57A4),
    "Demon Guest House: Number 5 Room": LocationInformation(0x020A5810),
    "Demon Guest House: Number 8 Room": LocationInformation(0x020A5864),
    "Demon Guest House: Number 9 Room": LocationInformation(0x020A5888),
    "Demon Guest House: Number 12 Room": LocationInformation(0x020A58DC),
    "Demon Guest House: Mirror World": LocationInformation(0x020A5978),
    "Demon Guest House: Mirror Room": LocationInformation(0x020A596C),
    "Demon Guest House: Doll Alcove": LocationInformation(0x020A5C0C),
    "Demon Guest House: West Wing Left": LocationInformation(0x020A5708),
    "Demon Guest House: West Wing Right": LocationInformation(0x020A5B70),
    "Demon Guest House: Ice Block Room Left": LocationInformation(0x020A5564),
    "Demon Guest House: Ice Block Room Right": LocationInformation(0x020A5570),
    "Demon Guest House: Central Main Chamber Bottom Room": LocationInformation(0x020A62B4, "Easter Egg"),
    "Demon Guest House: Central Main Chamber Middle Room": LocationInformation(0x020A626C),
    "Demon Guest House: Central Main Chamber Top Room": LocationInformation(0x020A6224),
    "Demon Guest House: Beyond Paranoia": LocationInformation(0x020A56CC),
    "Demon Guest House: Paranoia Mirror": LocationInformation(0x020A5B10),

    "Dark Chapel: Entrance Alcove": LocationInformation(0x020AE714),
    "Dark Chapel: Catacombs Top Left": LocationInformation(0x020AE798),
    "Dark Chapel: Catacombs Middle Room": LocationInformation(0x020AE7C8),
    "Dark Chapel: Catacombs Soul Barrier": LocationInformation(0x020AE618),
    "Dark Chapel: Catacombs Mirror Room": LocationInformation(0x020AEBB8),
    "Dark Chapel: Catacombs Mirror World": LocationInformation(0x020AEBC4),
    "Dark Chapel: Big Square Room Alcove": LocationInformation(0x020AE660),
    "Dark Chapel: Main Room": LocationInformation(0x020AED08),
    "Dark Chapel: Bell Room In Bell": LocationInformation(0x020AEBDC, "Easter Egg"),
    "Dark Chapel: Bell Room Top Left": LocationInformation(0x020AEBF4),
    "Dark Chapel: Bell Room Right": LocationInformation(0x020AEBE8),
    "Dark Chapel: Post-Dimitrii Room": LocationInformation(0x020AEC9C),
    "Dark Chapel: Big Room Top Right": LocationInformation(0x020AEE10),
    "Dark Chapel: Big Room Central": LocationInformation(0x020AEE04),
    "Dark Chapel: Big Room Lower": LocationInformation(0x020AEE1C),

    "Condemned Tower: 1F West": LocationInformation(0x020B1BA4),
    "Condemned Tower: 1F East": LocationInformation(0x020B1F34),
    "Condemned Tower: 2F East": LocationInformation(0x020B1F28),
    "Condemned Tower: 5F West": LocationInformation(0x020B1AC0),
    "Condemned Tower: 7F West": LocationInformation(0x020B1A6C),
    "Condemned Tower: Top of the Tower": LocationInformation(0x020B1A48),

    "Cursed Clock Tower: Money Gate": LocationInformation(0x020B91CC),
    "Cursed Clock Tower: Lower Corner Room": LocationInformation(0x020B8728),
    "Cursed Clock Tower: Mirror Room": LocationInformation(0x020B8F80),
    "Cursed Clock Tower: Mirror World": LocationInformation(0x020B8F8C),
    "Cursed Clock Tower: Bugbear Hallway": LocationInformation(0x020B8F2C),
    "Cursed Clock Tower: East Gear Room": LocationInformation(0x020B9004),
    "Cursed Clock Tower: Spike Room Secret": LocationInformation(0x020B8ED8, "Easter Egg"),

    "Subterranean Hell: Giant Underwater Room Center Left": LocationInformation(0x020B4B4C),
    "Subterranean Hell: Giant Underwater Room Center Right": LocationInformation(0x020B4B40),
    "Subterranean Hell: Giant Underwater Room Top Left": LocationInformation(0x020B4B34),
    "Subterranean Hell: Giant Underwater Room Bottom Right": LocationInformation(0x020B4B58),
    "Subterranean Hell: Near Save Room": LocationInformation(0x020B4750),
    "Subterranean Hell: Central Lower Room": LocationInformation(0x020B4618),
    "Subterranean Hell: Central Upper Room": LocationInformation(0x020B46C0),
    "Subterranean Hell: Behind Waterfall": LocationInformation(0x020B43B4),
    "Subterranean Hell: Waterfall Room Lower": LocationInformation(0x020B4420),
    "Subterranean Hell: Waterfall Room Middle": LocationInformation(0x020B4414),
    "Subterranean Hell: Waterfall Room Upper": LocationInformation(0x020B4408),

    "Silenced Ruins: Ice Block Room": LocationInformation(0x020B6390),
    "Silenced Ruins: Mirror Room": LocationInformation(0x020B6024),
    "Silenced Ruins: Mirror World": LocationInformation(0x020B6030),

    "The Pinnacle: Lower Hidden Room": LocationInformation(0x020BB02C),
    "The Pinnacle: Under Big Staircase": LocationInformation(0x020BAE4C),
    "The Pinnacle: Central Indoor Room": LocationInformation(0x020BAE4C),
    "The Pinnacle: Central Outdoor Room": LocationInformation(0x020BB158),
    "The Pinnacle: Before Throne Room Secret Left": LocationInformation(0x020BADEC),
    "The Pinnacle: Before Throne Room Secret Right": LocationInformation(0x020BADF8),
    "The Pinnacle: Beyond Throne Room": LocationInformation(0x020BAD68),

    "The Abyss: Sand Area": LocationInformation(0x020BE020),
    "The Abyss: Ice Area": LocationInformation(0x020BE0F8),

    "Zombie Soul": LocationInformation(0x0, "Soul"),
    "Bat Soul": LocationInformation(0x0, "Soul"),
    "Ghost Soul": LocationInformation(0x0, "Soul"),
    "Skeleton Soul": LocationInformation(0x0, "Soul"),
    "Ouija Table Soul": LocationInformation(0x0, "Soul"),
    "Peeping Eye Soul": LocationInformation(0x0, "Soul"),
    "Axe Armor Soul": LocationInformation(0x0, "Soul"),
    "Skull Archer Soul": LocationInformation(0x0, "Soul"),
    "Warg Soul": LocationInformation(0x0, "Soul"),
    "Spin Devil Soul": LocationInformation(0x0, "Soul"),
    "Armor Knight Soul": LocationInformation(0x0, "Soul"),
    "Student Witch Soul": LocationInformation(0x0, "Soul"),
    "Slaughterer Soul": LocationInformation(0x0, "Soul"),
    "Bomber Armor Soul": LocationInformation(0x0, "Soul"),
    "Golem Soul": LocationInformation(0x0, "Soul"),
    "Slime Soul": LocationInformation(0x0, "Soul"),
    "Une Soul": LocationInformation(0x0, "Soul"),
    "Skeleton Ape Soul": LocationInformation(0x0, "Soul"),
    "Manticore Soul": LocationInformation(0x0, "Soul"),
    "Mollusca Soul": LocationInformation(0x0, "Soul"),
    "Rycuda Soul": LocationInformation(0x0, "Soul"),
    "Mandragora Soul": LocationInformation(0x0, "Soul"),
    "Yorick Soul": LocationInformation(0x0, "Soul"),
    "Skeleton Farmer Soul": LocationInformation(0x0, "Soul"),
    "The Creature Soul": LocationInformation(0x0, "Soul"),
    "Catoblepas Soul": LocationInformation(0x0, "Soul"),
    "Ghoul Soul": LocationInformation(0x0, "Soul"),
    "Corpseweed Soul": LocationInformation(0x0, "Soul"),
    "Yeti Soul": LocationInformation(0x0, "Soul"),
    "Tombstone Soul": LocationInformation(0x0, "Soul"),
    "Ghost Dancer Soul": LocationInformation(0x0, "Soul"),
    "Flying Humanoid Soul": LocationInformation(0x0, "Soul"),
    "Mini Devil Soul": LocationInformation(0x0, "Soul"),
    "Quetzalcoatl Soul": LocationInformation(0x0, "Soul"),
    "Treant Soul": LocationInformation(0x0, "Soul"),
    "Amalaric Sniper Soul": LocationInformation(0x0, "Soul"),
    "Valkyrie Soul": LocationInformation(0x0, "Soul"),
    "Great Armor Soul": LocationInformation(0x0, "Soul"),
    "Killer Doll Soul": LocationInformation(0x0, "Soul"),
    "Waiter Skeleton Soul": LocationInformation(0x0, "Soul"),
    "Persephone Soul": LocationInformation(0x0, "Soul"),
    "Witch Soul": LocationInformation(0x0, "Soul"),
    "Buer Soul": LocationInformation(0x0, "Soul"),
    "Lilith Soul": LocationInformation(0x0, "Soul"),
    "Killer Clown Soul": LocationInformation(0x0, "Soul"),
    "Skelerang Soul": LocationInformation(0x0, "Soul"),
    "Fleaman Soul": LocationInformation(0x0, "Soul"),
    "Devil Soul": LocationInformation(0x0, "Soul"),
    "Guillotiner Soul": LocationInformation(0x0, "Soul"),
    "Draghignazzo Soul": LocationInformation(0x0, "Soul"),
    "Needles Soul": LocationInformation(0x0, "Soul"),
    "Hell Boar Soul": LocationInformation(0x0, "Soul"),
    "Bone Pillar Soul": LocationInformation(0x0, "Soul"),
    "White Dragon Soul": LocationInformation(0x0, "Soul"),
    "Wakwak Tree Soul": LocationInformation(0x0, "Soul"),
    "Imp Soul": LocationInformation(0x0, "Soul"),
    "Harpy Soul": LocationInformation(0x0, "Soul"),
    "Barbariccia Soul": LocationInformation(0x0, "Soul"),
    "Malachi Soul": LocationInformation(0x0, "Soul"),
    "Cave Troll Soul": LocationInformation(0x0, "Soul"),
    "Larva Soul": LocationInformation(0x0, "Soul"),
    "Heart Eater Soul": LocationInformation(0x0, "Soul"),
    "Merman Soul": LocationInformation(0x0, "Soul"),
    "Fish Head Soul": LocationInformation(0x0, "Soul"),
    "Medusa Head Soul": LocationInformation(0x0, "Soul"),
    "Ukoback Soul": LocationInformation(0x0, "Soul"),
    "Killer Fish Soul": LocationInformation(0x0, "Soul"),
    "Mimic Soul": LocationInformation(0x0, "Soul"),
    "Dead Pirate Soul": LocationInformation(0x0, "Soul"),
    "Frozen Shade Soul": LocationInformation(0x0, "Soul"),
    "Homunculus Soul": LocationInformation(0x0, "Soul"),
    "Disc Armor Soul": LocationInformation(0x0, "Soul"),
    "Decarabia Soul": LocationInformation(0x0, "Soul"),
    "Dead Mate Soul": LocationInformation(0x0, "Soul"),
    "Bugbear Soul": LocationInformation(0x0, "Soul"),
    "Procel Soul": LocationInformation(0x0, "Soul"),
    "Bone Ark Soul": LocationInformation(0x0, "Soul"),
    "Gorgon Soul": LocationInformation(0x0, "Soul"),
    "Alura Une Soul": LocationInformation(0x0, "Soul"),
    "Great Axe Armor Soul": LocationInformation(0x0, "Soul"),
    "Mothman Soul": LocationInformation(0x0, "Soul"),
    "Mushussu Soul": LocationInformation(0x0, "Soul"),
    "Dead Crusader Soul": LocationInformation(0x0, "Soul"),
    "Dead Warrior Soul": LocationInformation(0x0, "Soul"),
    "Erinys Soul": LocationInformation(0x0, "Soul"),
    "Succubus Soul": LocationInformation(0x0, "Soul"),
    "Ripper Soul": LocationInformation(0x0, "Soul"),
    "Black Panther Soul": LocationInformation(0x0, "Soul"),
    "Mud Demon Soul": LocationInformation(0x0, "Soul"),
    "Giant Slug Soul": LocationInformation(0x0, "Soul"),
    "Werewolf Soul": LocationInformation(0x0, "Soul"),
    "Flame Demon Soul": LocationInformation(0x0, "Soul"),
    "Tanjelly Soul": LocationInformation(0x0, "Soul"),
    "Arc Demon Soul": LocationInformation(0x0, "Soul"),
    "Gaibon Soul": LocationInformation(0x0, "Soul"),
    "Slogra Soul": LocationInformation(0x0, "Soul"),
    "Stolas Soul": LocationInformation(0x0, "Soul"),
    "Final Guard Soul": LocationInformation(0x0, "Soul"),
    "Malacoda Soul": LocationInformation(0x0, "Soul"),
    "Alastor Soul": LocationInformation(0x0, "Soul"),
    "Iron Golem Soul": LocationInformation(0x0, "Soul"),
    "Flying Armor Soul": LocationInformation(0x0, "Soul"),
    "Balore Soul": LocationInformation(0x0, "Soul"),
    "Malphas Soul": LocationInformation(0x0, "Soul"),
    "Puppet Master Soul": LocationInformation(0x0, "Soul"),
    "Rahab Soul": LocationInformation(0x0, "Soul"),
    "Gergoth Soul": LocationInformation(0x0, "Soul"),
    "Zephyr Soul": LocationInformation(0x0, "Soul"),
    "Bat Company Soul": LocationInformation(0x0, "Soul"),
    "Paranoia Soul": LocationInformation(0x0, "Soul"),
    "Aguni Soul": LocationInformation(0x0, "Soul"),
    "Death Soul": LocationInformation(0x0, "Soul"),
    "Abaddon Soul": LocationInformation(0x0, "Soul"),

    "Wizardry Lab: West Gate Button": LocationInformation(0x0, "Button"),
    "Wizardry Lab: East Gate Button": LocationInformation(0x0, "Button"),
    "Garden of Madness: Gate Button": LocationInformation(0x0, "Button"),
    "Subterranean Hell: Gate Button": LocationInformation(0x0, "Button")

}

enemy_souls_per_area = {
    "Lost Village": ["Yeti Soul", "Axe Armor Soul", "Warg Soul", "Skeleton Soul", "Bat Soul", "Armor Knight Soul",
                     "Zombie Soul", "Peeping Eye Soul", "Skelerang Soul", "Spin Devil Soul", "Student Witch Soul",
                     "Flying Armor Soul", "Ouija Table Soul", "Hell Boar Soul", "Skeleton Ape Soul", "Merman Soul",
                     "Great Axe Armor Soul", "White Dragon Soul"],

    "Demon Guest House": ["Axe Armor Soul", "Skeleton Soul", "Peeping Eye Soul", "Skelerang Soul",
                          "Persephone Soul", "Devil Soul", "Lilith Soul", "Ghost Dancer Soul", "Killer Clown Soul",
                          "Waiter Skeleton Soul", "Valkyrie Soul", "Killer Doll Soul", "Bone Pillar Soul",
                          "Buer Soul", "Quetzalcoatl Soul", "Flame Demon Soul", "Malachi Soul", "Werewolf Soul",
                          "Student Witch Soul", "Witch Soul", "Succubus Soul", "Iron Golem Soul", "Mimic Soul",
                          "Puppet Master Soul", "Paranoia Soul"],

    "Wizardry Lab": ["Slime Soul", "Axe Armor Soul", "Bomber Armor Soul", "Student Witch Soul", "Skull Archer Soul",
                     "Skeleton Soul", "Slaughterer Soul", "Manticore Soul", "Armor Knight Soul", "Golem Soul",
                     "Ghost Soul", "The Creature Soul", "Great Axe Armor Soul", "Heart Eater Soul", "Cave Troll Soul",
                     "Mimic Soul", "Homunculus Soul", "Killer Fish Soul", "Larva Soul", "Iron Golem Soul",
                     "Balore Soul"],

    "Garden of Madness": ["Corpseweed Soul", "Une Soul", "Skelerang Soul", "Mandragora Soul", "Catoblepas Soul",
                          "Mollusca Soul", "Yorick Soul", "Rycuda Soul", "Treant Soul", "Skeleton Ape Soul",
                          "Skeleton Farmer Soul", "Mimic Soul", "Barbariccia Soul", "Ghoul Soul", "Wakwak Tree Soul"],

    "Dark Chapel": ["Guillotiner Soul", "Witch Soul", "Mini Devil Soul", "Amalaric Sniper Soul", "Ghost Dancer Soul",
                    "Hell Boar Soul", "White Dragon Soul", "Great Armor Soul", "Quetzalcoatl Soul", "Ghoul Soul",
                    "The Creature Soul", "Bone Pillar Soul", "Malphas Soul"],

    "Condemned Tower": ["Draghignazzo Soul", "Skeleton Ape Soul", "Great Axe Armor Soul",
                        "Buer Soul", "Disc Armor Soul", "Werewolf Soul", "Fleaman Soul"],

    "Subterranean Hell": ["Cave Troll Soul", "Decarabia Soul", "Une Soul", "Dead Pirate Soul", "Merman Soul",
                          "Fish Head Soul", "Needles Soul", "Frozen Shade Soul", "Killer Fish Soul",
                          "Mimic Soul", "Procel Soul", "Alura Une Soul", "Ukoback Soul", "Medusa Head Soul",
                          "Devil Soul", "Bone Ark Soul", "Rahab Soul"],

    "Silenced Ruins": ["Dead Mate Soul", "Skeleton Soul", "Bat Soul", "Skull Archer Soul", "Devil Soul",
                       "Larva Soul", "Skelerang Soul", "Ghoul Soul", "Dead Crusader Soul", "Bone Ark Soul",
                       "Waiter Skeleton Soul", "Bat Company Soul"],

    "Cursed Clock Tower": ["Harpy Soul", "Catoblepas Soul", "Imp Soul", "Malachi Soul", "Dead Pirate Soul",
                           "Medusa Head Soul", "Tanjelly Soul", "Slime Soul", "Bugbear Soul", "Flying Humanoid Soul",
                           "Devil Soul", "Zephyr Soul"],

    "The Pinnacle": ["Guillotiner Soul", "Mothman Soul", "Werewolf Soul", "Mushussu Soul", "Alastor Soul",
                     "Dead Crusader Soul", "Erinys Soul", "Final Guard Soul", "Succubus Soul",
                     "Malachi Soul", "Flame Demon Soul", "Bugbear Soul", "Dead Warrior Soul", "Aguni Soul"],

    "Mine of Judgment": ["Slogra Soul", "Ripper Soul", "Gaibon Soul", "Tanjelly Soul", "Giant Slug Soul",
                         "Bugbear Soul", "Death Soul"],

    "The Abyss": ["Alastor Soul", "Mud Demon Soul", "Frozen Shade Soul", "Malachi Soul", "White Dragon Soul",
                  "Malacoda Soul", "Arc Demon Soul", "Erinys Soul", "Heart Eater Soul", "Stolas Soul",
                  "Final Guard Soul", "Abaddon Soul", "Black Panther Soul", "Succubus Soul", "Iron Golem Soul"]
}


def get_location_groups():
    location_groups = {
        "Lost Village": set(),
        "Demon Guest House": set(),
        "Wizardry Lab": set(),
        "Garden of Madness": set(),
        "Dark Chapel": set(),
        "Condemned Tower": set(),
        "Subterranean Hell": set(),
        "Silenced Ruins": set(),
        "Cursed Clock Tower": set(),
        "The Pinnacle": set(),
        "Mine of Judgment": set(),
        "The Abyss": set(),
    }
    for location in location_ids:
        group = location.split(":")[0]
        if group in location_groups:
            location_groups[group].add(location)

    for area in enemy_souls_per_area:
        location_groups[area].update(enemy_souls_per_area[area])

    return location_groups
