map_palettes = {
    "Pyramid": 0,
    "Lost Underworld": 1,
    "Cave of the Past": 2,
    "Giygas's Lair": 3,
    "Onett": 4,
    # "Onett Nighttime": 5,
    # "Onett Flashback": 6,
    "Twoson": 7,
    "Happy-Happy Village": 8,
    "Happy-Happy Clear": 9,
    "Tunnel Outdoors": 10,
    "Threed": 11,
    "Threed Daytime": 12,
    "Fourside": 13,
    "Moonside": 14,
    "Magicant": 15,
    "Tunnels": 16,
    "Magicant Interiors": 17,
    "Tents": 18,
    "Peaceful Rest Valley": 19,
    "Grapefruit Falls": 20,
    "Saturn Valley": 21,
    "Deep Darkness": 22,
    "Lilliput Steps Sanctuary": 23,
    "Milky Well": 24,
    "Deep Darkness Darkness": 25,
    "Summers": 26,
    "Dusty Dunes Desert": 27,
    "The Sky": 28,
    "Dalaam": 29,
    "Dalaam Palace": 30,
    "Cave of the Present": 31,
    "Pink Cloud Sanctuary": 32,
    "The Sea": 33,
    "????": 34,
    "Monotoli Offices": 35,
    "Onett Hotel": 36,
    "Threed Red-Wall House": 37,
    "Electra's Room": 38, # 10 10 3
    "Threed Green-Wall House": 39,
    "Threed Blue-Wall House": 40,
    "Pokey's House": 41,
    "Moonside Hospital": 42,
    "Onett Green-Wall House": 43,
    "Onett Blue-Wall House": 44,
    "Onett Seafoam-Wall House": 45,
    "Onett Peach-Wall House": 46,
    "Onett Light Blue-Wall House": 47,
    "Onett Pink-Wall House": 48,
    "Onett White-Wall House": 49,
    # "Onett Flashback House": 50,
    "Twoson Hospital": 51,
    "Apple Kid's House": 52,
    "Tracy's Room": 53,
    "Orange Kid's House": 54,
    "Everdred's House": 55,
    "Twoson Green-Wall House": 56,
    "Ness's Room": 57,
    "Police Station Backroom": 58,
    "Winters": 59,
    "Rainy Circle Sanctuary": 60,
    # "Winters Nighttime": 61,
    #"????": 62,
    "Hospital Rooms": 63,
    "Twoson Peach-Wall House": 64,
    "Twoson Pink-Wall House": 65,
    "Twoson Gray-Wall House": 66,
    "Gold Office": 67,
    "Happy-Happy Guardhouse": 68,
    "Happy-Happy Hospital": 69,
    "Happy-Happy Hospital Clear": 70,
    "Onett Town Hall": 71,
    "Onett Hotel Bedrooms": 72,
    "Fourside Hotel Bedrooms": 73,
    "Happy-Happy Saturn House": 74,
    "Happy-Happy Hotel": 75,
    "Twoson Hotel Bedrooms": 76,
    "Threed Hotel Bedrooms": 77,
    "Happy-Happy Hotel Clear": 78,
    "Monotoli Building": 79,
    "Paula's House": 80,
    "Paula's Room": 81,
    "Ness's House": 82,
    "Twoson Hotel": 83,
    "Threed Hotel": 84,
    "Fourside Hotel": 85,
    "Monotoli Elevators": 86,
    "Fourside Dept. Store Office": 87,
    "Onett Library": 88,
    "Paula's House Rooms": 89,
    "Onett Police Station": 90,
    "Scaraba": 91,
    "Dalaam House": 92,
    "Scaraba House": 93,
    "Happy-Happy HQ": 94,
    "Fourside Cafe": 95,
    "Moonside Building": 96,
    "Scaraba Hospital": 97,
    "Scaraba Shop": 98,
    "Twoson Dept. Store": 99,
    "Fourside Dept. Store": 100,
    "Bakery": 101,
    "Mach Pizza": 102,
    "Burger Shop": 103,
    "Drugstore": 104,
    "Threed Drugstore": 105,
    "Winters Drugstore": 106,
    "Chaos Theater": 107,
    "Fourside Museum": 108,
    "Summers Hotel": 109,
    "Summers Shop": 110,
    # "Topolla Theater Stage": 111,

    "Snow Wood Boarding School": 112,
    "Chaos Theater Stage": 113,
    "Summers Harbor House": 114,
    "Summers Restaurant": 115,
    "Moonside Museum": 116,


    "Lumine Hall": 134,
    
    "Tenda Village": 159
}


nice_palettes = {
    'Onett': [
        4,
        5,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        19,
        21,
        22,
        42,
        105,
        106,
        107,
        109,
        116,
    ],
}

ugly_palettes = {
    'Onett': [
        0,
        1,
        2,
        6,
	    8,
        26,
        27,
        38,
        41,
        43,
        51,
        53,
        59,
        61,
        62,
        63,
        70,
        82,
        83,
        91,
        92,
        93,
        99,
        104,
        108,
        112,
        120,
        126,
        130,
        132,
        133,
    ]
}

nonsense_palettes = {
    'Onett': [
        34,
        39,
        47,
        57,
        58,
        65,
        67,
        68,
        69,
        74,
        75,
        111,
        114,
        117,
        118,
        121,
        129,
        131,
        160,
        161,
        162,
        164,
    ]
}
