region_text = {
    "Northern Onett": "Onett",
    "Onett": "Onett",
    "Giant Step": "Giant Step",
    "Twoson": "Twoson",
    "Peaceful Rest Valley": "Peaceful Rest Valley",
    "Happy-Happy Village": "Happy-Happy Village",
    "Lilliput Steps": "Lilliput Steps",
    "Threed": "Threed",
    "Belch's Factory": "Belch's factory",
    "Saturn Valley": "Saturn Valley",
    "Upper Saturn Valley": "Saturn Valley",
    "Milky Well": "Milky Well",
    "Dusty Dunes Desert": "the Dusty Dunes Desert",
    "Gold Mine": "the gold mine",
    "Monkey Caves": "the monkey caves",
    "Fourside": "Fourside",
    "Magnet Hill": "Fourside's sewers",
    "Monotoli Building": "the Monotoli Building",
    "Winters": "Winters",
    "Snow Wood Boarding School": "the Snow Wood Boarding School",
    "Southern Winters": "Winters",
    "Rainy Circle": "Rainy Circle",
    "Stonehenge Base": "Stonehenge",
    "Summers": "Summers",
    "Dalaam": "Dalaam",
    "Pink Cloud": "Pink Cloud",
    "Scaraba": "Scaraba",
    "Pyramid": "the Pyramid",
    "Southern Scaraba": "Scaraba",
    "Dungeon Man": "Dungeon Man",
    "Deep Darkness": "the Deep Darkness",
    "Tenda Village": "Tenda Village",
    "Lumine Hall": "Lumine Hall",
    "Lost Underworld": "the Lost Underworld",
    "Fire Spring": "Fire Spring",
    "Magicant": "Magicant",
    "Cave of the Present": "Cave of the Past",
    "Cave of the Past": "Cave of the Past"
}

barf_text = {
    "Paula": [0x10, 0xF8, 0xD6, 0xED, 0xF8, 0xD6],
    "Jeff": [0x10, 0xF8, 0xD6, 0xED, 0xF8, 0xD6],
    "Poo": [0x10, 0xF8, 0xD6, 0xED, 0xF8, 0xD6],
    "Flying Man": [0x10, 0xF8, 0xD6, 0xED, 0xF8, 0xD6]
}

eb_text_table = {" ": ([0x50]), "!": ([0x51]), '"': ([0x52]), "■": ([0x53]), "$": ([0x54]), "%": ([0x55]),
                "°": ([0x56]), "'": ([0x57]), '(': ([0x58]), ")": ([0x59]), "*": ([0x5A]), "+": ([0x5B]),
                "]),": ([0x5C]), "-": ([0x5D]), '.': ([0x5E]), "/": ([0x5F]), "0": ([0x60]), "1": ([0x61]),
                "2": ([0x62]), "3": ([0x63]), '4': ([0x64]), "5": ([0x65]), "6": ([0x66]), "7": ([0x67]),
                "8": ([0x68]), "9": ([0x69]), ':': ([0x6A]), ";": ([0x6B]), '“': ([0x6C]), "=": ([0x6D]),
                "”": ([0x6E]), "?": ([0x6F]), '@': ([0x70]), "A": ([0x71]), 'B': ([0x72]), "C": ([0x73]),
                "D": ([0x74]), "E": ([0x75]), 'F': ([0x76]), "G": ([0x77]), 'H': ([0x78]), "I": ([0x79]),
                "J": ([0x7A]), "K": ([0x7B]), 'L': ([0x7C]), "M": ([0x7D]), 'N': ([0x7E]), "O": ([0x7F]),
                "P": ([0x80]), "Q": ([0x81]), 'R': ([0x82]), "S": ([0x83]), 'T': ([0x84]), "U": ([0x85]),
                "V": ([0x86]), "W": ([0x87]), 'X': ([0x88]), "Y": ([0x89]), 'Z': ([0x8A]), "α": ([0x8B]),
                "β": ([0x8C]), "γ": ([0x8D]), 'Σ': ([0x8E]), "Ω": ([0x8F]), 'a': ([0x91]), "b": ([0x92]),
                "c": ([0x93]), "d": ([0x94]), 'e': ([0x95]), "f": ([0x96]), 'g': ([0x97]), "h": ([0x98]),
                "i": ([0x99]), "j": ([0x9A]), 'k': ([0x9B]), "l": ([0x9C]), 'm': ([0x9D]), "n": ([0x9E]),
                "o": ([0x9F]), "p": ([0xA0]), 'q': ([0xA1]), "r": ([0xA2]), 's': ([0xA3]), "t": ([0xA4]),
                "u": ([0xA5]), "v": ([0xA6]), 'w': ([0xA7]), "x": ([0xA8]), 'y': ([0xA9]), "z": ([0xAA]),
                "([": ([0xAB]), "♪": ([0xAC]), '])': ([0xAD]), "~": ([0xAE]), '◯': ([0xAF])}