def create_default_trait(trait: str):
    return Trait(trait, 1.0, 1.0)

banned_items = [
    0x01, # Franklin Badge
    0x68, # Pak of Bubble Gum
    0x69, # Jar of Fly Honey
    0x7D, # Backstage Pass
    0x8B, # Yogurt Dispenser
    0x9E, # UFO Engine
    0xA2, # Piggy Nose
    0xA4, # Shyness Book
    0xA6, # King Banana
    0xA7, # Letter for Tony
    0xAA, # Key to the Shack
    0xAB, # Key to the Cabin
    0xAC, # Bad Key Machine
    0xAD, # Archipelago Item
    0xAE, # Zombie Paper
    0xAF, # Hawk Eye
    0xB1, # ATM Card
    0xB2, # Show ticket MAYBE GOOD, THINK ON THIS
    0xB4, # Wad of Bills
    0xB6, # Diamond
    0xB7, # Signed Banana
    0xB8, # Pencil Eraser
    0xB9, # Hieroglyph Copy
    0xBB, # Contact Lens
    0xC0, # Key to the Tower
    0xC1, # Meteorite Piece
    0xCA, # Police Badge
    0xCB, # Mining Permit
    0xCC, # Suporma
    0xCD, # Key to the Locker
    0xCE, # Insig. Item
    0xD0, # Tiny Ruby
    0xD2, # Eraser Eraser
    0xD3, # Tendakraut
    0xFD # Carrot Key
]

id_item_table = {
    0x2: "Teddy Bear",
    0x3: "Super Plush Bear",
    0x4: "Broken Machine",
    0x5: "Broken Gadget",
    0x6: "Broken Air Gun",
    0x7: "Broken Spray Can",
    0x8: "Broken Laser",
    0x9: "Broken Iron",
    0xa: "Broken Pipe",
    0xb: "Broken Cannon",
    0xc: "Broken Tube",
    0xd: "Broken Bazooka",
    0xe: "Broken Trumpet",
    0xf: "Broken Harmonica",
    0x10: "Broken Antenna",
    0x11: "Cracked Bat",
    0x12: "Tee Ball Bat",
    0x13: "Sand Lot Bat",
    0x14: "Minor League Bat",
    0x15: "Mr. Baseball Bat",
    0xd5: "Big League Bat",
    0x17: "Hall of Fame Bat",
    0x18: "Magicant Bat",
    0x19: "Legendary Bat",
    0x1a: "Gutsy Bat",
    0x1b: "Casey Bat",
    0x1c: "Fry Pan",
    0x1d: "Thick Fry Pan",
    0x1e: "Deluxe Fry Pan",
    0x1f: "Chef's Fry Pan",
    0x20: "French Fry Pan",
    0x21: "Magic Fry Pan",
    0x22: "Holy Fry Pan",
    0x23: "Sword of Kings",
    0x24: "Pop Gun",
    0x25: "Stun Gun",
    0x26: "Toy Air Gun",
    0x27: "Magnum Air Gun",
    0x28: "Zip Gun",
    0x29: "Laser Gun",
    0x2a: "Hyper Beam",
    0x2b: "Crusher Beam",
    0x2c: "Spectrum Beam",
    0x2d: "Death Ray",
    0x2e: "Baddest Beam",
    0x2f: "Moon Beam Gun",
    0x30: "Gaia Beam",
    0x31: "Yo-yo",
    0x32: "Slingshot",
    0x33: "Bionic Slingshot",
    0x34: "Trick Yo-yo",
    0x35: "Combat Yo-yo",
    0x36: "Travel Charm",
    0x37: "Great Charm",
    0x38: "Crystal Charm",
    0x39: "Rabbit's Foot",
    0x3a: "Flame Pendant",
    0x3b: "Rain Pendant",
    0x3c: "Night Pendant",
    0x3d: "Sea Pendant",
    0x3e: "Star Pendant",
    0x3f: "Cloak of Kings",
    0x40: "Cheap Bracelet",
    0x41: "Copper Bracelet",
    0x42: "Silver Bracelet",
    0x43: "Gold Bracelet",
    0xd8: "Platinum Band",
    0xd9: "Diamond Band",
    0x46: "Pixie's Bracelet",
    0x47: "Cherub's Band",
    0x48: "Goddess Band",
    0x49: "Bracer of Kings",
    0x4a: "Baseball Cap",
    0x4b: "Holmes Hat",
    0x4c: "Mr. Baseball Cap",
    0x4d: "Hard Hat",
    0x4e: "Ribbon",
    0x4f: "Red Ribbon",
    0x50: "Goddess Ribbon",
    0x51: "Coin of Slumber",
    0x52: "Coin of Defense",
    0x53: "Lucky Coin",
    0x54: "Talisman Coin",
    0x55: "Shiny Coin",
    0x56: "Souvenir Coin",
    0x57: "Diadem of Kings",
    0x58: "Cookie",
    0x59: "Bag of Fries",
    0x5a: "Hamburger",
    0x5b: "Boiled Egg",
    0x5c: "Fresh Egg",
    0x5d: "Picnic Lunch",
    0x5e: "Pasta di Summers",
    0x5f: "Pizza",
    0x60: "Chef's Special",
    0x61: "Large Pizza",
    0x62: "PSI Caramel",
    0x63: "Magic Truffle",
    0x64: "Brain Food Lunch",
    0x65: "Rock Candy",
    0x66: "Croissant",
    0x67: "Bread Roll",
    0x6a: "Can of Fruit Juice",
    0x6b: "Royal Iced Tea",
    0x6c: "Protein Drink",
    0x6d: "Kraken Soup",
    0x6e: "Bottle of Water",
    0x6f: "Cold Remedy",
    0x70: "Vial of Serum",
    0x71: "IQ Capsule",
    0x72: "Guts Capsule",
    0x73: "Speed Capsule",
    0x74: "Vital Capsule",
    0x75: "Luck Capsule",
    0x76: "Ketchup Packet",
    0x77: "Sugar Packet",
    0x78: "Tin of Cocoa",
    0x79: "Carton of Cream",
    0x7a: "Sprig of Parsley",
    0x7b: "Jar of Hot Sauce",
    0x7c: "Salt Packet",
    0x7e: "Jar of Delisauce",
    0x7f: "Wet Towel",
    0x80: "Refreshing Herb",
    0x81: "Secret Herb",
    0x82: "Horn of Life",
    0x83: "Counter-PSI Unit",
    0x84: "Shield Killer",
    0x85: "Bazooka",
    0x86: "Heavy Bazooka",
    0x87: "HP-Sucker",
    0x88: "Hungry HP-Sucker",
    0x89: "Xterminator Spray",
    0x8a: "Slime Generator",
    0x8c: "Ruler",
    0x8d: "Snake Bag",
    0x8e: "Mummy Wrap",
    0x8f: "Protractor",
    0x90: "Bottle Rocket",
    0x91: "Big Bottle Rocket",
    0x92: "Multi Bottle Rocket",
    0x93: "Bomb",
    0x94: "Super Bomb",
    0x95: "Insecticide Spray",
    0x96: "Rust Promoter",
    0x97: "Rust Promoter DX",
    0x98: "Pair of Dirty Socks",
    0x99: "Stag Beetle",
    0x9a: "Toothbrush",
    0x9b: "Handbag Strap",
    0x9c: "Pharaoh's Curse",
    0x9d: "Defense Shower",
    0x9f: "Sudden Guts Pill",
    0xa0: "Bag of Dragonite",
    0xa1: "Defense Spray",
    0xa3: "For Sale Sign",
    0xa5: "Picture Postcard",
    0xa8: "Chick",
    0xa9: "Chicken",
    0xb0: "Bicycle",
    0xb2: "Show Ticket",
    0xb3: "Letter from Kids",
    0xb5: "Receiver Phone",
    0xba: "Meteotite",
    0xbb: "Contact Lens",
    0xbc: "Hand-Aid",
    0xbd: "Trout Yogurt",
    0xbe: "Banana",
    0xbf: "Calorie Stick",
    0xc2: "Earth Pendant",
    0xc3: "Neutralizer",
    0xc4: "Sound Stone",
    0xc5: "Exit Mouse",
    0xc6: "Gelato de Resort",
    0xc7: "Snake",
    0xc8: "Viper",
    0xc9: "Brain Stone",
    0xcf: "Magic Tart",
    0xd1: "Monkey's Love",
    0xd4: "T-Rex's Bat",
    0xd6: "Ultimate Bat",
    0xd7: "Double Beam",
    0xda: "Defense Ribbon",
    0xdb: "Talisman Ribbon",
    0xdc: "Saturn Ribbon",
    0xdd: "Coin of Silence",
    0xde: "Charm Coin",
    0xdf: "Cup of Noodles",
    0xe0: "Repel Sandwich",
    0xe1: "Repel Superwich",
    0xe2: "Lucky Sandwich",
    0xe3: "Progressive Bat",
    0xe4: "Progressive Fry Pan",
    0xe5: "Progressive Gun",
    0xe6: "Progressive Bracelet",
    0xe7: "Progressive Other",
    0xe8: "Cup of Coffee",
    0xe9: "Double Burger",
    0xea: "Peanut Cheese Bar",
    0xeb: "Piggy Jelly",
    0xec: "Bowl of Rice Gruel",
    0xed: "Bean Croquette",
    0xee: "Molokheiya Soup",
    0xef: "Plain Roll",
    0xf0: "Kabob",
    0xf1: "Plain Yogurt",
    0xf2: "Beef Jerky",
    0xf3: "Mammoth Burger",
    0xf4: "Spicy Jerky",
    0xf5: "Luxury Jerky",
    0xf6: "Bottle of DXwater",
    0xf7: "Magic Pudding",
    0xf8: "Non-Stick Frypan",
    0xf9: "Mr. Saturn Coin",
    0xfa: "Meteornium",
    0xfb: "Popsicle",
    0xfc: "Cup of Lifenoodles"
}

traits_list = {
    "Teddy Bear": ["Bear", "Toy", "Stuffed", "Fluffy", "Brown", "MeatShield", "Animal"],
    "Super Plush Bear": ["Bear", "Toy", "Stuffed", "Fluffy", "Brown", "MeatShield", "Animal"],
    "Boiled Egg": ["Boiled", "Cooked", "Heal", "Consumable", "Egg", "White", "Food", "AnimalProduct"],
}