from ..Items import item_table
import struct

subweapon_table = [
    "Knife Subweapon",
    "Axe Subweapon",
    "Bwaka Knife",
    "Paper Airplane",
    "Cream Pie",
    "Grenade",
    "Steel Ball",
    "Stonewall",
    "Offensive Form",
    "Taunt",
    "Knee Strike",
    "Aura Blast",
    "Javelin",
    "Ricochet Rock",
    "Boomerang",
    "Shuriken",
    "Yagyu Shuriken",
    "Discus",
    "Kunimitsu",
    "Kunai",
    "Crossbow",
    "Dart",
    "Defensive Form",
    "Wrecking Ball",
    "Rampage",
    "Berserker",
    "Cure Curse",
    "Rock Riot",
    "Spirit of Light",
    "Dark Rift",
    "Stone Circle",
    "Ice Needle",
    "Explosion",
    "Chain Lightning",
    "Nightmare",
    "Summon Medusa",
    "Acidic Bubbles",
    "Hex",
    "Salamander",
    "Thor's Bellow",
    "Summon Crow",
    "Summon Skeleton",
    "Summon Ghost",
    "Summon Gunman",
    "Summon Frog",
    "Eye for an Eye",
    "Clear Skies",
    "Cure Poison",
    "STR Boost",
    "CON Boost",
    "INT Boost",
    "MIND Boost",
    "ALL Boost",
    "Gale Force",
    "Raging Fire",
    "Ice Fang",
    "Thunderbolt",
    "Tempest",
    "Piercing Beam"
]


weapon_table = [
    "Encyclopedia",
    "Leather Whip",
    "Steel Whip",
    "Rose Stem Whip",
    "Blank Book",
    "Knife",
    "Combat Knife",
    "Baselard",
    "Short Sword",
    "Cutlass",
    "Gladius",
    "Rahab's Frost",
    "Agni's Flame",
    "Claymore",
    "Falchion",
    "Great Sword",
    "Zweihander",
    "Spear",
    "Partisan",
    "Lance",
    "Trident",
    "Long Spear",
    "Couse",
    "Axe",
    "Mace",
    "Battle Axe",
    "Morning Star",
    "Bhuj",
    "Brass Knuckles",
    "Cestus",
    "Halberd",
    "Tome of Arms 1",
    "Tome of Arms 2",
    "Long Sword",
    "Bakatwa",
    "Don Quixote",
    "Tristan&Isolde",
    "Bahg Nahk",
    "Whip Knuckles",
    "Milican's Sword"]

good_weapon_table = [
    "Medusa Whip",
    "Katar",
    "Cinquedea",
    "Heaven's Sword",
    "Jagdplaute",
    "Damascus Sword",
    "Dragon Slayer",
    "Final Sword",
    "Holy Claymore",
    "Sarissa",
    "Voulge",
    "Bullova",
    "Golden Axe",
    "Illusion Fist",
    "Tome of Arms 3",
    "Nebula",
    "Flame Whip",
    "Jet Black Whip",
    "Royal Sword",
    "Kaiser Knuckles",
    "Great Axe",
    "Book of Death"]

armor_table = [
    "Casual Clothes",
    "Hobo's Clothes",
    "Houppelande",
    "Poncho",
    "Combat Fatigues",
    "Adrenaline Gear",
    "Kalasiris",
    "Tailcoat",
    "Biker's Jacket",
    "Justaucorps",
    "Tuxedo Coat",
    "Battle Jacket",
    "Surcoat",
    "Leather Cuirass",
    "Copper Plate",
    "Iron Plate",
    "Silver Plate",
    "Gold Plate",
    "Holy Mail",
    "Mirror Cuirass",
    "Spiked Mail",
    "Leather Corset",
    "Jade Corset",
    "Amethyst Corset",
    "Emerald Corset",
    "Ruby Corset",
    "Sapphire Corset",
    "Lilith Corset",
    "Diamond Corset",
    "Kirtle",
    "Cotton Apron",
    "Silk Negligee",
    "Bathrobe",
    "Frilly Camisole",
    "Sequined Dress",
    "Clown Shirt",
    "Cocktail Dress",
    "Dancer's Blouse",
    "Cotehardie",
    "Eye for Decay",
    "Sunglasses",
    "Thick Glasses",
    "Glasses",
    "Monocle",
    "Goggles",
    "Uraeus",
    "Royal Crown",
    "Head Guard",
    "Iron Helmet",
    "Stone Mask",
    "Viking Helmet",
    "Ballroom Masque",
    "Fedora",
    "Porkpie Hat",
    "Silk Hat",
    "Traveler's Hat",
    "Skull Mask",
    "Witch's Hat",
    "Pearl Tiara",
    "Diamond Tiara",
    "Midnight Tiara",
    "Sandals",
    "Engineer Boots",
    "Royal Sandals",
    "Combat Boots",
    "Slick Boots",
    "Hiking Boots",
    "Oxfords",
    "Wingtips",
    "Iron Leggings",
    "Silver Leggings",
    "Enamel Pinheels",
    "Inuit Boots",
    "Glass Shoes",
    "Diamond Shoes",
    "Nun's Robes",
    "Combat Beret",
    "Bandana",
    "Velvet Ribbon",
    "Nun's Habit",
    "Clover Tiara",
    "Nun's Shoes"


]

good_armor_table = [
    "Feather Gear",
    "Lorica",
    "Platinum Plate",
    "Samurai Plate",
    "Berserker Mail",
    "Ancient Armor",
    "Scout Armor",
    "Heavy Armor",
    "Impervious Mail",
    "Diamond Corset",
    "Miko Dress",
    "Europa's Dress",
    "Dalmatica",
    "Princess Coat",
    "Wedding Dress",
    "Samurai Helmet",
    "Mourning Veil",
    "Open Veil",
    "Holy Veil",
    "Arachne Hennin",
    "Muse's Tiara",
    "Gold Leggings",
    "Platinum Lggngs",
    "Succubus Boots",
    "Prima Shoes",
    "Silent Sandals",
    "Robe Decollete",
    "Healing Mail",
    "Platinum Corset",
    "Attica Helmet",
    "Shogun Helmet",
    "Princess Tiara",
    "Moonwalkers",
    "Winged Boots",
    "Mercury Boots",
    "Spiked Boots",
    "Steel Greaves",
    "Samurai Leggngs",
    "Glamorous Pumps",
    "Artemis Shoes"


]

accessory_table = [
    "Studded Choker",
    "Charm Necklace",
    "Astral Ring",
    "Engagement Ring",
    "Gold Ring",
    "Shaman Ring",
    "Miser Ring",
    "Sage Ring",
    "Thief Ring",
    "Immunity Ring",
    "Blessed Ring",
    "Cape",
    "Blue Cape",
    "Pearl Ring",
    "Tough Ring",
    "Master Ring",
    "Skull Ring",
    "Hercules Ring",
    "Hero's Cape",
    "Elven Cape",
    "Invisible Cape",
    "Assassin's Cape",
    "Holy Mantle",
    "Paludamentum",
    "Blessed Ankh",
    "White Corsage",
    "Orchid Corsage",
    "Rose Corsage",
    "Sorceress Crest",
    "Forget-Me-Not",
    "Crystal Necklet",
    "Platinum Chain",
    "Heart Brooch",
    "Astral Brooch",
    "Laurel Brooch",
    "Abalone Brooch",
    "Diamond Brooch",
    "Moon Brooch",
    "Venus Brooch"]

consumable_table = [
    "Potion",
    "High Potion",
    "Tonic",
    "High Tonic",
    "Anti-Venom",
    "Uncurse Potion",
    "Beef Jerky",
    "Rice Ball",
    "Mushroom",
    "Corn Soup",
    "Mint Sundae",
    "Cream Puff",
    "Milk",
    "Coffee",
    "Tea",
    "Pudding",
    "Strawberry",
    "Grapes",
    "Hamburger",
    "Fried Chicken",
    "Hot Dog",
    "Pumpkin Pie",
    "Pancake",
    "Tinned Spinach",
    "Paella",
    "Spaghetti",
    "Ice Cream",
    "Meuniere",
    "Boiled Starfish",
    "Wheat Roll",
    "Sachertorte",
    "NY Cheesecake",
    "Mille-feuille",
    "Tarte au Poire",
    "Gateau Fraise",
    "Kugelhopf",
    "Green Tea Cake",
    "Gateau Marron",
    "Langues de Chat",
    "Financier",
    "Tropical Sundae",
    "Pudding Bucket",
    "Piyoko",
    "1000 Year Egg",
    "Jamon Iberico",
    "Spicy Shrimp",
    "Pasta Carbonara",
    "Penne Arrabiata",
    "Powdered Milk",
    "Rotten Durian",
    "Ground Meat",
    "Noodle Bun",
    "Touch & Pop",
    "Moldy Bread",
    "Penters Natural",
    "Beehive",
    "Amanita",
    "Rotten Meat",
    "Spoiled Milk",
    "Rusty Food Tin",
    "Spade",
    "Diamond",
    "Heart",
    "Club",
    "Joker",
    "Record 1",
    "Record 2",
    "Record 3",
    "Record 4",
    "Record 5"
]

good_food_table = [
    "Super Potion",
    "Super Tonic",
    "Tasty Meat",
    "New York Steak",
    "Curry",
    "Ramen Noodles",
    "Melon",
    "Foie Gras",
    "Caviar",
    "Truffle",
    "Peking Duck",
    "Birthday Cake"
]

global_item_ids = {
    "Potion": 0x1,
    "High Potion": 0x2,
    "Super Potion": 0x3,
    "Tonic": 0x4,
    "High Tonic": 0x5,
    "Super Tonic": 0x6,
    "Anti-Venom": 0x7,
    "Uncurse Potion": 0x8,
    "HP Max up": 0x9,
    "MP Max up": 0xa,
    "Beef Jerky": 0xb,
    "Tasty Meat": 0xc,
    "New York Steak": 0xd,
    "Rice Ball": 0xe,
    "Mushroom": 0xf,
    "Corn Soup": 0x10,
    "Curry": 0x11,
    "Ramen Noodles": 0x12,
    "Mint Sundae": 0x13,
    "Cream Puff": 0x14,
    "Milk": 0x15,
    "Coffee": 0x16,
    "Tea": 0x17,
    "Pudding": 0x18,
    "Strawberry": 0x19,
    "Melon": 0x1a,
    "Grapes": 0x1b,
    "Hamburger": 0x1c,
    "Fried Chicken": 0x1d,
    "Hot Dog": 0x1e,
    "Pumpkin Pie": 0x1f,
    "Pancake": 0x20,
    "Tinned Spinach": 0x21,
    "Foie Gras": 0x22,
    "Caviar": 0x23,
    "Truffle": 0x24,
    "Paella": 0x25,
    "Spaghetti": 0x26,
    "Ice Cream": 0x27,
    "Meuniere": 0x28,
    "Boiled Starfish": 0x29,
    "Wheat Roll": 0x2a,
    "Sachertorte": 0x2b,
    "NY Cheesecake": 0x2c,
    "Mille-feuille": 0x2d,
    "Tarte au Poire": 0x2e,
    "Gateau Fraise": 0x2f,
    "Kugelhopf": 0x30,
    "Green Tea Cake": 0x31,
    "Gateau Marron": 0x32,
    "Langues de Chat": 0x33,
    "Financier": 0x34,
    "Tropical Sundae": 0x35,
    "Pudding Bucket": 0x36,
    "Piyoko": 0x37,
    "1000 Year Egg": 0x38,
    "Jamon Iberico": 0x39,
    "Spicy Shrimp": 0x3a,
    "Peking Duck": 0x3b,
    "Pasta Carbonara": 0x3c,
    "Penne Arrabiata": 0x3d,
    "Powdered Milk": 0x3e,
    "Rotten Durian": 0x3f,
    "Ground Meat": 0x40,
    "Noodle Bun": 0x41,
    "Touch & Pop": 0x42,
    "Moldy Bread": 0x43,
    "Penters Natural": 0x44,
    "Birthday Cake": 0x45,
    "Magical Ticket": 0x46,
    "Beehive": 0x47,
    "Amanita": 0x48,
    "Rotten Meat": 0x49,
    "Spoiled Milk": 0x4a,
    "Rusty Food Tin": 0x4b,
    "CASTLE MAP 1": 0x4c,
    "CASTLE MAP 2": 0x4d,
    "CASTLE MAP 3": 0x4e,
    "Cog": 0x4f,
    "Tome of Arms p1": 0x53,
    "Tome of Arms p2": 0x54,
    "Spade": 0x55,
    "Diamond": 0x56,
    "Heart": 0x57,
    "Club": 0x58,
    "Joker": 0x59,
    "Statue's Tear": 0x5a,
    "Record Player": 0x5b,
    "Record 1": 0x5c,
    "Record 2": 0x5d,
    "Record 3": 0x5e,
    "Record 4": 0x5f,
    "Record 5": 0x60,
    "Vampire Killer": 0x62,
    "Leather Whip": 0x63,
    "Steel Whip": 0x64,
    "Rose Stem Whip": 0x65,
    "Medusa Whip": 0x66,
    "Nebula": 0x67,
    "Flame Whip": 0x68,
    "Jet Black Whip": 0x69,
    "Undead Killer": 0x6a,
    "True Vampire Killer": 0x6b,
    "Richter Vampire Killer": 0x6c,
    "Encyclopedia": 0x6d,
    "Blank Book": 0x6e,
    "Tristan&Isolde": 0x6f,
    "Don Quixote": 0x70,
    "Book of Death": 0x71,
    "Tome of Arms 1": 0x72,
    "Tome of Arms 2": 0x73,
    "Tome of Arms 3": 0x74,
    "Tome of Arms X": 0x75,
    "Knife": 0x76,
    "Combat Knife": 0x77,
    "Baselard": 0x78,
    "Katar": 0x79,
    "Cinquedea": 0x7a,
    "Short Sword": 0x7b,
    "Cutlass": 0x7c,
    "Long Sword": 0x7d,
    "Gladius": 0x7e,
    "Milican's Sword": 0x7f,
    "Rahab's Frost": 0x80,
    "Agni's Flame": 0x81,
    "Assassin Blade": 0x82,
    "Heaven's Sword": 0x83,
    "Bakatwa": 0x84,
    "Jagdplaute": 0x85,
    "Stellar Sword": 0x86,
    "Damascus Sword": 0x87,
    "Claymore": 0x88,
    "Falchion": 0x89,
    "Great Sword": 0x8a,
    "Zweihander": 0x8b,
    "Royal Sword": 0x8c,
    "Dragon Slayer": 0x8d,
    "Final Sword": 0x8e,
    "Holy Claymore": 0x8f,
    "Spear": 0x90,
    "Partisan": 0x91,
    "Halberd": 0x92,
    "Lance": 0x93,
    "Trident": 0x94,
    "Long Spear": 0x95,
    "Couse": 0x96,
    "Sarissa": 0x97,
    "Alucard's Spear": 0x98,
    "Axe": 0x99,
    "Mace": 0x9a,
    "Battle Axe": 0x9b,
    "Morning Star": 0x9c,
    "Bhuj": 0x9d,
    "Great Axe": 0x9e,
    "Voulge": 0x9f,
    "Bullova": 0xa0,
    "Golden Axe": 0xa1,
    "Brass Knuckles": 0xa2,
    "Cestus": 0xa3,
    "Whip Knuckles": 0xa4,
    "Bahg Nahk": 0xa5,
    "Bullet Punch": 0xa6,
    "Illusion Fist": 0xa7,
    "Kaiser Knuckles": 0xa8,
    "Tori": 0xa9,
    "Casual Clothes": 0xab,
    "Hobo's Clothes": 0xac,
    "Houppelande": 0xad,
    "Poncho": 0xae,
    "Combat Fatigues": 0xaf,
    "Adrenaline Gear": 0xb0,
    "Kalasiris": 0xb1,
    "Feather Gear": 0xb2,
    "Tailcoat": 0xb3,
    "Biker's Jacket": 0xb4,
    "Justaucorps": 0xb5,
    "Tuxedo Coat": 0xb6,
    "Battle Jacket": 0xb7,
    "Surcoat": 0xb8,
    "Leather Cuirass": 0xb9,
    "Copper Plate": 0xba,
    "Iron Plate": 0xbb,
    "Silver Plate": 0xbc,
    "Gold Plate": 0xbd,
    "Lorica": 0xbe,
    "Platinum Plate": 0xbf,
    "Samurai Plate": 0xc0,
    "Holy Mail": 0xc1,
    "Berserker Mail": 0xc2,
    "Ancient Armor": 0xc3,
    "Healing Mail": 0xc4,
    "Mirror Cuirass": 0xc5,
    "Spiked Mail": 0xc6,
    "Scout Armor": 0xc7,
    "Heavy Armor": 0xc8,
    "Impervious Mail": 0xc9,
    "Leather Corset": 0xca,
    "Jade Corset": 0xcb,
    "Amethyst Corset": 0xcc,
    "Emerald Corset": 0xcd,
    "Ruby Corset": 0xce,
    "Sapphire Corset": 0xcf,
    "Lilith Corset": 0xd0,
    "Platinum Corset": 0xd1,
    "Diamond Corset": 0xd2,
    "Kirtle": 0xd3,
    "Miko Dress": 0xd4,
    "Cotton Apron": 0xd5,
    "Silk Negligee": 0xd6,
    "Bathrobe": 0xd7,
    "Frilly Camisole": 0xd8,
    "Sequined Dress": 0xd9,
    "Clown Shirt": 0xda,
    "Nun's Robes": 0xdb,
    "Cocktail Dress": 0xdc,
    "Dancer's Blouse": 0xdd,
    "Cotehardie": 0xde,
    "Wedding Dress": 0xdf,
    "Europa's Dress": 0xe0,
    "Dalmatica": 0xe1,
    "Princess Coat": 0xe2,
    "Robe Decollete": 0xe3,
    "Eye for Decay": 0xe5,
    "Gambler Glasses": 0xe6,
    "Sunglasses": 0xe7,
    "Thick Glasses": 0xe8,
    "Glasses": 0xe9,
    "Monocle": 0xea,
    "Goggles": 0xeb,
    "Combat Beret": 0xec,
    "Uraeus": 0xed,
    "Royal Crown": 0xee,
    "Head Guard": 0xef,
    "Bandana": 0xf0,
    "Iron Helmet": 0xf1,
    "Stone Mask": 0xf2,
    "Viking Helmet": 0xf3,
    "Ballroom Masque": 0xf4,
    "Fedora": 0xf5,
    "Porkpie Hat": 0xf6,
    "Silk Hat": 0xf7,
    "Traveler's Hat": 0xf8,
    "Attica Helmet": 0xf9,
    "Samurai Helmet": 0xfa,
    "Shogun Helmet": 0xfb,
    "Skull Mask": 0xfc,
    "Velvet Ribbon": 0xfd,
    "Witch's Hat": 0xfe,
    "Mourning Veil": 0xff,
    "Nun's Habit": 0x100,
    "Open Veil": 0x101,
    "Holy Veil": 0x102,
    "Clover Tiara": 0x103,
    "Pearl Tiara": 0x104,
    "Diamond Tiara": 0x105,
    "Princess Tiara": 0x106,
    "Muse's Tiara": 0x107,
    "Midnight Tiara": 0x108,
    "Arachne Hennin": 0x109,
    "Sandals": 0x10b,
    "Engineer Boots": 0x10c,
    "Royal Sandals": 0x10d,
    "Combat Boots": 0x10e,
    "Moonwalkers": 0x10f,
    "Slick Boots": 0x110,
    "Spiked Boots": 0x111,
    "Mercury Boots": 0x112,
    "Winged Boots": 0x113,
    "Hiking Boots": 0x114,
    "Oxfords": 0x115,
    "Wingtips": 0x116,
    "Iron Leggings": 0x117,
    "Silver Leggings": 0x118,
    "Gold Leggings": 0x119,
    "Steel Greaves": 0x11a,
    "Platinum Lggngs": 0x11b,
    "Samurai Leggngs": 0x11c,
    "Enamel Pinheels": 0x11d,
    "Inuit Boots": 0x11e,
    "Succubus Boots": 0x11f,
    "Glamorous Pumps": 0x120,
    "Silent Sandals": 0x121,
    "Artemis Shoes": 0x122,
    "Nun's Shoes": 0x123,
    "Glass Shoes": 0x124,
    "Prima Shoes": 0x125,
    "Diamond Shoes": 0x126,
    "Studded Choker": 0x128,
    "Charm Necklace": 0x129,
    "Stella's Locket": 0x12a,
    "Astral Ring": 0x12b,
    "Engagement Ring": 0x12c,
    "Magus Ring": 0x12d,
    "Gold Ring": 0x12e,
    "Shaman Ring": 0x12f,
    "Miser Ring": 0x130,
    "Sage Ring": 0x131,
    "Thief Ring": 0x132,
    "Pearl Ring": 0x133,
    "Tough Ring": 0x134,
    "Master Ring": 0x135,
    "Skull Ring": 0x136,
    "Immunity Ring": 0x137,
    "Blessed Ring": 0x138,
    "Hercules Ring": 0x139,
    "Cape": 0x13a,
    "Hero's Cape": 0x13b,
    "Blue Cape": 0x13c,
    "Elven Cape": 0x13d,
    "Assassin's Cape": 0x13e,
    "Invisible Cape": 0x13f,
    "Holy Mantle": 0x140,
    "Paludamentum": 0x141,
    "Blessed Ankh": 0x142,
    "White Corsage": 0x143,
    "Orchid Corsage": 0x144,
    "Rose Corsage": 0x145,
    "Sorceress Crest": 0x146,
    "Forget-Me-Not": 0x147,
    "Crystal Necklet": 0x148,
    "Platinum Chain": 0x149,
    "Heart Brooch": 0x14a,
    "Astral Brooch": 0x14b,
    "Laurel Brooch": 0x14c,
    "Abalone Brooch": 0x14d,
    "Diamond Brooch": 0x14e,
    "Moon Brooch": 0x14f,
    "Venus Brooch": 0x150,
    "Puppet Master": 0x152,
    "R. Axe": 0x153,
    "R. Cross": 0x154,
    "R. Holy Water": 0x155,
    "Julius Cross": 0x156,
    "Seiryu": 0x157,
    "Suzaku": 0x158,
    "Byakko": 0x159,
    "Gnebu": 0x15a,
    "Knife Subweapon": 0x15b,
    "Axe Subweapon": 0x15c,
    "Cross": 0x15d,
    "Holy Water": 0x15e,
    "Bible": 0x15f,
    "Javelin": 0x160,
    "Ricochet Rock": 0x161,
    "Boomerang": 0x162,
    "Bwaka Knife": 0x163,
    "Shuriken": 0x164,
    "Yagyu Shuriken": 0x165,
    "Discus": 0x166,
    "Kunimitsu": 0x167,
    "Kunai": 0x168,
    "Paper Airplane": 0x169,
    "Cream Pie": 0x16a,
    "Crossbow": 0x16b,
    "Dart": 0x16c,
    "Grenade": 0x16d,
    "Steel Ball": 0x16e,
    "Stonewall": 0x16f,
    "Offensive Form": 0x170,
    "Defensive Form": 0x171,
    "Taunt": 0x172,
    "Wrecking Ball": 0x173,
    "Rampage": 0x174,
    "Knee Strike": 0x175,
    "Aura Blast": 0x176,
    "Rocket Slash": 0x177,
    "Toad Morph": 0x178,
    "Owl Morph": 0x179,
    "Sanctuary": 0x17a,
    "Speed Up": 0x17b,
    "Berserker": 0x17c,
    "Eye for an Eye": 0x17d,
    "Clear Skies": 0x17e,
    "Time Stop": 0x17f,
    "Heal": 0x180,
    "Cure Poison": 0x181,
    "Cure Curse": 0x182,
    "STR Boost": 0x183,
    "CON Boost": 0x184,
    "INT Boost": 0x185,
    "MIND Boost": 0x186,
    "LUCK Boost": 0x187,
    "ALL Boost": 0x188,
    "Gale Force": 0x189,
    "Rock Riot": 0x18a,
    "Raging Fire": 0x18b,
    "Ice Fang": 0x18c,
    "Thunderbolt": 0x18d,
    "Spirit of Light": 0x18e,
    "Dark Rift": 0x18f,
    "Tempest": 0x190,
    "Stone Circle": 0x191,
    "Ice Needle": 0x192,
    "Explosion": 0x193,
    "Chain Lightning": 0x194,
    "Piercing Beam": 0x195,
    "Nightmare": 0x196,
    "Summon Medusa": 0x197,
    "Acidic Bubbles": 0x198,
    "Hex": 0x199,
    "Salamander": 0x19a,
    "Cocytus": 0x19b,
    "Thor's Bellow": 0x19c,
    "Summon Crow": 0x19d,
    "Summon Skeleton": 0x19e,
    "Summon Ghost": 0x19f,
    "Summon Gunman": 0x1a0,
    "Summon Frog": 0x1a1,
    "Rush": 0x1a3,
    "Holy Lightning": 0x1a4,
    "Axe Bomber": 0x1a5,
    "1,000 Blades": 0x1a6,
    "Volcano": 0x1a7,
    "Meteor": 0x1a8,
    "Grand Cruz": 0x1a9,
    "Divine Storm": 0x1aa,
    "Dark Gate": 0x1ab,
    "Greatest Five": 0x1ac,
    "Change Cube": 0x1ad,
    "Call Cube": 0x1ae,
    "Skill Ccube": 0x1af,
    "Wait Cube": 0x1b0,
    "Acrobat Cube": 0x1b1,
    "Push Cube": 0x1b2,
    "Lizard Tail": 0x1b3,
    "Stone of Flight": 0x1b4,
    "Griffon Wing": 0x1b5,
    "Strength Glove": 0x1b6,
    "Spinning Art": 0x1b7,
    "Martial Art": 0x1b8,
    "Critical Art": 0x1b9,
    "Whip Skill 1": 0x1ba,
    "Whip Skill 2": 0x1bb,
    "Book of Spirits": 0x1bc
}

shop_pools = {
    0x020E0080: 13,
    0x020E003E: 12,
    0x020E00C6: 22,
    0x020E005A: 12,
    0x020E001A: 5
}


def generate_local_filler(world, return_as_id = False):
    weights = {"subweapon": 20, "good_weapon": 15, "accessory": 8, "good_food": 10,
               "good_armor": 15, "weapon": 30, "armor": 40, "consumable": 60}

    weight_table = {
        "subweapon": subweapon_table,
        "good_weapon": good_weapon_table,
        "weapon": weapon_table,
        "armor": armor_table,
        "good_armor": good_armor_table,
        "consumable": consumable_table,
        "good_food": good_food_table,
        "accessory": accessory_table
    }

    filler_type = world.random.choices(list(weights), weights=list(weights.values()), k=1)[0]
    filler_item = world.random.choice(weight_table[filler_type])
    item_id = global_item_ids[filler_item]
    if return_as_id:
        return item_id
    else:
        return filler_item

def generate_shop_items(world, rom):
    first_subweapon = world.random.choice(subweapon_table)
    shop_pool = ["Potion", "Tonic", "Claymore", "CASTLE MAP 1", first_subweapon]
    for pool in shop_pools:
        for i in range(shop_pools[pool]):
            item = "Potion"
            while item in shop_pool:
                item = generate_local_filler(world)
            shop_pool.append(item)
            if global_item_ids[item] > 0x150:
                price = world.random.randint(1, 0x10)
                skill_id = item_table[item].code - 0x800
                rom.write_to_file(0x020E3B14 + (skill_id * 6) + 4, "arm9", struct.pack("H", price))
            rom.write_to_file(pool + (i * 2), "arm9", struct.pack("H", global_item_ids[item]))
